### ISSUE TITLE
Looking forward to revel 0.13!

### ISSUE THREAD

**Issue by xpbliss** [revel/revel#1000]
I am looking forward to revel 0.13!  because it support pluginable template!  
 I want to use the pongo2 in  revel.  other go web frameworks support the pongo2,such as beego,gin,macaron,Tango.  but no Revel.
When do you dear release the revel 0.13?

**Comment by runner-mei** [comment]
there are patch in the here.
https://github.com/runner-mei/revel/tree/plugin_template_loader

It is incompleted, but soon will be create pull request.

Tasks that are not completed：
1. move pongo2 to revel/modules
2. add template pluging for revel/cmd

**Comment by xpbliss** [comment]
Dear revelers :
It has not been update  for a long time.
Some thing  should be  done!

**Comment by DavidHunter** [comment]
Does anyone use Revel in production?

**Comment by xpbliss** [comment]
Yes. Just for an inner using.

**Comment by alkchr** [comment]
@DavidHunter https://github.com/revel/revel/wiki/Apps-in-the-Wild

**Comment by xpbliss** [comment]
In the go web framework ,the revel's stars are near 6,000.  It is more any other go web framework.
But it is too slow to update.

**Comment by DavidHunter** [comment]
@alkchr I meant use it in a high traffic website

**Comment by DavidHunter** [comment]
You will need to ask brendensoares. If it was up to me I would delete that roadmap and pushback support for pongo2

**Comment by pedromorgan** [comment]
Maybe we need a "release candidate"..

**Comment by xpbliss** [comment]
why not update to revel 0.13?  @brendensoares

**Comment by alkchr** [comment]
@brendensoares Let me know when you find a void that Revel can fill and help is needed.

**Comment by brendensoares** [comment]
All, we're going to have to rework the roadmap as there isn't enough regular development on Revel to achieve the roadmap in reality.

I'll likely break it down into a list of priorities without specific release commitments.

I'll be dedicating a few days later in December to getting Revel reorganized. Any help is appreciated. I'm in IRC most days now.

**Comment by pedromorgan** [comment]
@alkchr >> Let me know when you find a void that Revel can fill and help is needed.

There are a few, can u help.. simple help would be helpful.. I go some time at last ...

**Comment by pedromorgan** [comment]
And u  first, U need to send me the prorities.. so I can crete stats, and decide plan and update docs et all..

So cunning plan is to actually create a 
"hacker.revelframework.com" control panel..

And the idea is to create there a "hot list" of bugs and issues..
that we want done to release and share and have more fun..

There are some strange showstoppers, such
as configs, subdomain, templates, jobs et all..

I am also emphasising the "hacker" part..
as normal documentation for an "end user developer"
would be at "dev.revelframework.com".. 

maybe.....

**Comment by alkchr** [comment]
> There are a few, can u help.. simple help would be helpful.. I go some time at last ... 

@pedromorgan Anything specific?

**Comment by brendensoares** [comment]
@xpbliss @jeevatkm has joined @revel/core and a sponsor has come forward to help get Revel moving again.

We'll have to push back template plugin support due to limited dev resources and the need to release the current `develop` branch.

**Comment by alkchr** [comment]
> and a sponsor has come forward to help get Revel moving again.

@brendensoares I wonder, who's that?

**Comment by brendensoares** [comment]
A IS software company from Prague. I'll share more soon.
