### ISSUE TITLE
Revel view - using short class names from google closure-stylesheets.jar

### ISSUE THREAD

**Issue by goors** [revel/revel#1001]
Hi, this is not issue but feature/improvement suggestion if you like. 

I really like google/facebook style short class names. 1 byte is better then 8 :) I know that closure library has that, but only for their .soy templates and bunch of javascript files and it is all messed up and as far as i am concern complicated to use. For last couple of hours I was trying to implement that in Revel. I end up with this solution with revel custom view functions.

1. You have to create renaming_map.json with
    <pre>
    java -jar closure-stylesheets.jar \
    --output-file output_short_names.css \
    --output-renaming-map renaming_map.json \
    --output-renaming-map-format JSON --rename CLOSURE my_regular_css_with_long_names.css
    </pre>
    This will create file called my_style_short_with_short_names.css

2. On you view(s)
    <pre>
    < div class="{{short_class_name "long_class_name"}}" > < /div> for single class name
   < div class="{{short_class_name "long_class_name1 long_class_name2 long_class_name3"}}"> for multiple class names - for example btn default red
   </pre>
3. Register short_class_name func in your view functions (app/controllers/init.go)
    
    <pre>
    package controllers
    import (
	"github.com/revel/revel"
	"github.com/antonholmquist/jason"
	"io/ioutil"
	"strings"
    )

    func init() {

	  revel.TemplateFuncs["short_class_name"] = func(a string) string {
          
        if revel.DevMode == true{
			return a
		}
		sp := strings.Split(a, " ")
		json_path := revel.BasePath+"/app/renaming_map.json"
		file, _ := ioutil.ReadFile(json_path)
		jason,_ := jason.NewObjectFromBytes(file)
		if len(sp) == 1 {
			class_name, _ := jason.GetString(a)
			return class_name
		} else{
			classes := ""
			for _, b := range sp{
				class_name, _ := jason.GetString(b)
				classes += " "+class_name
			}
			return classes[1:len(classes)]
		}
		return ""
	  }
}
</pre>

4. Of course you need to use your long class names fro debug in development and short in production and if you like vice versa, so on your view you can (header.html):

<pre>
    {{if eq .RunMode "dev"}}
    < link rel="stylesheet" type="text/css" href="/public/css/my_long_class_names.css" >
    {{else}}
    < link rel="stylesheet" type="text/css" href="/public/css/my_short_class_names.css" >
    {{end}}
</pre>

This is sort of solution for html but not for javascript. What if you have some javascript functions and dom elements with class names? I will try to figure that out as well and post answer here as well.

**Comment by brendensoares** [comment]
With HTTP compression, I don't see a benefit to shortening names. Descriptive names are good for humans, compression is good for load time/latency.

I'm closing for lack of action items. Feel free to prove the value of this idea.

Thanks!

**Comment by goors** [comment]
What about intellectual property or author rights? As far as I can see that is a big deal!

**Comment by brendensoares** [comment]
I've never heard of class names being an issue for copyright. At the very least, you can use your template function in your app.

If it is a common need for most of our devs, then we could add it.

Thanks for taking the time to discuss ideas to improve Revel.
