### ISSUE TITLE
TOML config

### ISSUE THREAD

**Issue by dre1080** [revel/revel#1005]
Is it possible to use TOML for config files? I think revel should really switch to TOML instead of INI files. TOML is just better :smile:

**Comment by pedromorgan** [comment]
NO i totally disagree.. All configs are really anstractions of xml, so we might as well use that for safety net and its x platform, human readable,.... haha ;-))))))))))))))))

But a plan in future is to use toml, yaml, json, ini, even aham xml.. with idea being to chare configs among apps etc.. 

Checkout the  issues tagged as config ..https://github.com/revel/revel/labels/%23config

**Comment by littlexiang** [comment]
maybe could write an app level config module by myself instead, that would be easy and flexiable

**Comment by notzippy** [comment]
Closing in Master tracking issue is #680
