### ISSUE TITLE
question: failed to find controller App

### ISSUE THREAD

**Issue by xinzhangcmu** [revel/revel#1006]
I've been using revel just fine, until I ran into this error: (not sure which of my recent changes caused it)

```
ERROR 2015/11/13 15:53:04 router.go:431: Route validation error (in /Users/xinzhang/Desktop/code/go/src/github.com/caicloud/app-provisioner/conf/routes:8): revel/controller: failed to find controller App
panic: Route validation error (in /Users/xinzhang/Desktop/code/go/src/github.com/caicloud/app-provisioner/conf/routes:8): revel/controller: failed to find controller App


goroutine 1 [running]:
log.(*Logger).Panicln(0xc20802df40, 0xc20816dbc0, 0x1, 0x1)
    /usr/local/go/src/log/log.go:207 +0xb7
github.com/revel/revel.func·045()
    /Users/xinzhang/Desktop/code/go/src/github.com/revel/revel/router.go:431 +0x37b
github.com/revel/revel.runStartupHooks()
    /Users/xinzhang/Desktop/code/go/src/github.com/revel/revel/server.go:135 +0x62
github.com/revel/revel.Run(0xd969)
    /Users/xinzhang/Desktop/code/go/src/github.com/revel/revel/server.go:92 +0x237
```

My routes file looks like this:

```
# Routes
# This file defines all application routes (Higher priority routes first)
# ~~~~

module:testrunner
module:jobs

GET /                                       App.Index
```

and I can see the controller App is defined under `app/controllers/app.go`:

```
package controllers

import (
    "github.com/caicloud/app-provisioner/Godeps/_workspace/src/github.com/revel/revel"
    "net/http"
)

type App struct {
    *revel.Controller
}

func (c App) Index() revel.Result {
    return c.Render()
}

// Handles the preflight OPTIONS request that comes before a CORS request. Always allow by
// returning an OK status.
func (c App) Options() revel.Result {
    c.Response.Status = http.StatusOK
    return nil
}
```

The major change I have done recently was using `godep save -r` in my revel project (didn't use `-r` before). Any insights would be greatly appreciated!

**Comment by alkchr** [comment]
> The major change I have done recently was using `godep save -r` in my revel project (didn't use -r before).

@xinzhangcmu I think that's it. Revel is not compatible with dependency managers that override import paths.
You may want to use Go's [`GO15VENDOREXPERIMENT`](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo).

**Comment by pedromorgan** [comment]
Inst this new Vendoring ??

**Comment by alkchr** [comment]
@pedromorgan Yes it is. https://tip.golang.org/cmd/go/#hdr-Vendor_Directories
> In Go 1.5, as an experiment, setting the environment variable GO15VENDOREXPERIMENT=1 enabled these features. As of Go 1.6 they are on by default. To turn them off, set GO15VENDOREXPERIMENT=0. In Go 1.7, the environment variable will stop having any effect.

**Comment by jeevatkm** [comment]
@xinzhangcmu did you sort out this via vendoring?

**Comment by notzippy** [comment]
Closing due to lack of response
