### ISSUE TITLE
GO 1.5.1 - does not compile: undefined: revel.TestSuites

### ISSUE THREAD

**Issue by UmeshVeerasingam** [revel/revel#1008]
I still get this error:    
Using GO 1.5.1
```
The Go code bittrove-api/app/tmp/main.go does not compile: undefined: revel.TestSuites  
```
My conf file does contain:  
```
module.static=github.com/revel/modules/static
and 
module.testrunner = github.com/revel/modules/testrunner
```

My test file looks like this:
```
package tests

import "github.com/revel/revel/testing"

type AppTest struct {
	testing.TestSuite
}

func (t *AppTest) Before() {
	println("Set up")
}
```

**Comment by alkchr** [comment]
Cannot reproduce, everything works as expected for me with go 1.5.1. Make sure you are using the latest version of Revel:
```bash
go get -u github.com/revel/cmd/revel
```
Then recompile your app:
```bash
revel run path/to/bittrove-api
```

**Comment by UmeshVeerasingam** [comment]
I tried: 
```
go get -u github.com/revel/cmd/revel
```
I still get error on my  src/bittrove-api/app/tmp/main.go  
here -> ``` revel.TestSuites ``` not defined   
```
	}
	revel.TestSuites = []interface{}{ 
	}
	revel.Run(*port)
}

**Comment by alkchr** [comment]
@UmeshVeerasingam Looks like `tmp/main.go` was generated by outdated version of Revel. `revel.TestSuites` is indeed undefined as it is now a part of `revel/testing` package and should look like `testing.TestSuites`.
Have you tried to remove the `tmp` directory and run the app?

**Comment by UmeshVeerasingam** [comment]
@alkchr 
You are right, for some reason it using the outdated version of Revel. On my Mac OS, it seems fine. I am only having this issue on my CentOS 7 box. I am going to give a try tomorrow. I'll let you know the outcome.

**Comment by pedromorgan** [comment]
Please repopen if this is still a problem.. ta ;-)
