### ISSUE TITLE
How do i redirect the urls  in the Filter?

### ISSUE THREAD

**Issue by xpbliss** [revel/revel#1009]
what are the differents  of the two  following?
1 
```
       func LoginFilter(c *revel.Controller, fc []revel.Filter) {
        // .. do some pre-processing ..
        if c.Session["userEmail"] == "" {
            c.Redirect("/App/Mytest")   // the Redirect do nothing,  why?
            return
        }
    fc[0](c, fc[1:]) // Execute the next filter stage.
    // .. do some post-processing ..
    }
```    

2 
 ```   
     func LoginFilter(c *revel.Controller, fc []revel.Filter) {
        // .. do some pre-processing ..
        if c.Session["userEmail"] == "" {
               c.Response.Out.Header().Set("Location", "/App/Mytest")
           c.Response.WriteHeader(http.StatusFound, "")  //it does. but the error is:"server.go:1934: http: multiple response.WriteHeader calls", why?
            return
        }

     fc[0](c, fc[1:]) // Execute the next filter stage.
    // .. do some post-processing ..
    }
   ``` 
How do i   redirect the urls in the Filter?

**Comment by notzippy** [comment]
You need to set c.Result with your redirect

     c.Result = c.Redirect("/App/Mytest")  
            return

The filter is run in server.go with the following code 

	var (
		req  = NewRequest(r)
		resp = NewResponse(w)
		c    = NewController(req, resp)
	)
	req.Websocket = ws

	Filters[0](c, Filters[1:])
	if c.Result != nil {
		c.Result.Apply(req, resp)
	} else if c.Response.Status != 0 {
		c.Response.Out.WriteHeader(c.Response.Status)
	}
	// Close the Writer if we can
	if w, ok := resp.Out.(io.Closer); ok {
		w.Close()
	}

So as you can see the result will be applied if it is not nill.

**Comment by xpbliss** [comment]
Thanks!
