### ISSUE TITLE
Empty Controller.Request.Body when send POST request

### ISSUE THREAD

**Issue by arhitiron** [revel/revel#1011]
When send raw body, can't read data from controller

func (c MyController) Action() revel.Result {
	revel.TRACE.Println(c.Request.Body)  // <-- empty
	return q.RenderJson(c.Request.Request.Body) // <-- empty
}

URL: /MyController
METHOD: POST
Request example: {"testKey":"testVal"}

**Comment by alkchr** [comment]
Gday, @arhitiron. Revel automatically calls `ParseForm`, `ParseMultipartForm` or whatever function is needed for a request, so `req.Body` is parsed and all valuable information is stored to `controller.Params.`(`Fixed`, `Route`, `Query`, `Form`, `Files`).

Though, if you still need the value of `c.Request.Body`, you should define the maximum request size to parse in your `app.conf` as follows:
```ini
http.maxrequestsize = 100500
```
Related commit: https://github.com/revel/revel/commit/fcf88855b6ec0bb3393a641f84a45610c70edb29
Related PR: #877

**Comment by brendensoares** [comment]
Please consider asking future questions on stackoverflow.com with the `revel` tag. Thanks!
