### ISSUE TITLE
proposal : advanced routing with additional controller result method Next()

### ISSUE THREAD

**Issue by fereidani** [revel/revel#1012]
Hi i recently start using revel ,  and thanks to its community , it's amazing .

i have a idea to share to maybe make it better . i have some experiences in security and nodejs web development .

in expressjs ( nodejs ) , in controllers developer receive a function that named `next`  which can tell the router i don't handle this request and pass it to next possibly available controller .

what is use of it ?

many things but for example i have a session authentication controller

```
if auth()
 next()
else
  return error you are not authorized
```

i know it also can implemented by filters in revel but imagine multi layer authentication .
it will be hard to handle more layers with filters and will have more overhead on application.

My idea is to add a `Next()` function/result to `Controller` which provide same action in revel framework .

syntax will be like:

```
func (c App) Authenticate() revel.Result {
        if isAuthenticated(c){
             return c.Next()// you are good to go
        }else{
             return c.renderTemplate("notAuthorized.html")// stop here , you are not authorized yet 
        }
}
```

router config example:

```
*     /admin/*     App.Authenticate
*     /admin/addPost     App.AddPost
...
...
...

```

it can also be useful for other kind of error handling .

**Comment by alkchr** [comment]
Good day, @fereidani. Can this be implemented with [interceptors](https://revel.github.io/manual/interceptors.html)?

```go
func (c App) Authenticate() revel.Result {
	if c.notAuthenticated {
		return c.RenderTemplate("notAuthenticated.html") // Stop here.
	}
	return nil // You're good to go.
}

func init() {
	revel.InterceptMethod(App.Authenticate, revel.BEFORE)
}
```

**Comment by fereidani** [comment]
@alkchr  , good day ,
yes , it can be but it raise human error factor in large programs with large set of controllers and routes,
for example developer accidently forgot to add this to one controller ,
and other problem remains in multilayer authentication ,
the `Next()` method need to be coded once for a route subpath and there is no need to more coding and direct attention to security layer in next Controller level .
it kinda give neat architecture to program and avoid repeating one action multiple times.

**Comment by alkchr** [comment]
@fereidani It is possible to create a separate auth module once and use it for any number of Controllers. For demonstration:

```go
// Auth is a controller that provides logics for user authentication.
type Auth struct {
	*revel.Controller
}

// Authenticate checks whether user is already authenticated.
// If not, an auth form is rendered.
func (c Auth) Authenticate() revel.Result {
	if c.notAuthenticated {
		return c.RenderTemplate("notAuthenticated.html") // Stop here.
	}
	return nil // You're good to go.
}

func init() {
	// Make sure the Authenticate action will be called before any
	// other action of Auth controller.
	revel.InterceptMethod(Auth.Authenticate, revel.BEFORE)
}
```
Now we can use the `Auth` controller as follows:
```go
// App is a sample controller.
type App struct {
	// We replaced "*revel.Controller" by our manual "Auth" controller here.
	Auth
}

// Index either shows an auth form or prints
// "You're authenticated" message.
func (c Controller) Index() revel.Result {
	return c.RenderText("You're authenticated.")
}
```
We can create hierarchies with any level of nesting using this approach.

Am I missing something (I'm not familiar with `expressjs`'s `Next` method)?

**Comment by fereidani** [comment]
thank you it seems nice approach  ,
but i still think `Next()` provide more flexible request flow control and human error prevented solution to application ,
it can even handle static file accesses base on route ,
many other route base ideas can be implemented easily ( logging , security , complicate request flow control )
maybe i have wrong idea in revel application design , is any way in revel to intercept a route instead of controller ?

you can check expressjs documentation http://expressjs.com/4x/api.html#app.METHOD .
i'm not trying to make revel like express , i know they have very different design philosophy , but i think when some approach seems more stable , it worth to check it at least .
i don't think it's be to hard to implement , i can help , if community accept this proposal .

**Comment by alkchr** [comment]
@fereidani My opinion is the idea you propose is interesting. There are already proposals to improve [filters](https://github.com/revel/revel/issues/600) and [replace interceptors](https://github.com/revel/revel/issues/420). I think #1012 should be discussed, too as an alternative approach. Let's see what core team [members](https://github.com/revel/revel/wiki/Core-Team#active-contributors) think.

**Comment by fereidani** [comment]
@alkchr thank you .

**Comment by notzippy** [comment]
Closed - dormant issue
