### ISSUE TITLE
Jobs, Controllers and InterceptMethod

### ISSUE THREAD

**Issue by janekolszak** [revel/revel#1013]
Hi,
Is there a reason why Jobs aren't Controllers?

I have a library revmgo that connects to MongoDB, but id does it's magic with InterceptMethod available only for Controllers...
1. Could Jobs be treated as Controllers?
2. Or at least could InterceptMethod/Function work with Jobs?

Cheers,
Jan

**Comment by notzippy** [comment]
Sorry for the late reply to this, I see that you have stopped work on the module. Your thoughts on adding the intercept capability to jobs is an interesting proposal. Currently the jobs implementation is using a package outside of Revel, but we have forked it so we could add something like this in the future. If you are interested in helping out let us know. Closing for now though until we have more interest in it.
