### ISSUE TITLE
new route module replacement request

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [revel/revel#1015]
hi, here is a high performanced route module, github url is https://github.com/julienschmidt/httprouter
there is a web framework which use this module make quite better performace

here is the discription url
https://github.com/gin-gonic

```
Gin is a HTTP web framework written in Go (Golang). 
It features a Martini-like API with much better performance -- up to 40 times faster. 
If you need smashing performance, get yourself some Gin.
```

routes config in file seems not not be convinient……
if revel can supply a option to use httproute, that will be much better

thanks very much!

**Comment by whidbey** [comment]
no,route config in file is more convinence I think.

**Comment by ziyouchutuwenwu** [comment]
ok, thank you
