### ISSUE TITLE
Local and Remote Caching behavior is different

### ISSUE THREAD

**Issue by bejayoharen** [revel/revel#1018]
The in-memory implementation does not conform to the "serialization" description given here: https://revel.github.io/manual/cache.html

Those docs state: `The Cache getters and setters automatically serialize values for callers, to and from any type` This is not the case for the in-memory cache, which does not serialize the values at all. When writing to the in-memory cache, the cache acts like a map; however when redis or memcached is used, the values are serialized. This can create subtle differences in behavior, and hard to diagnose bugs.

e.g. code such as this will act differently depending on which cache is used:

```
type Value struct { V *string }
v := Value{ V: "a" }
cache.Store( "key", V,  cache.DEFAULT)
v.V = "b"

// later
v := Value{ V }
cache.Get( "key", &v )
```

It would not be unreasonable to simply update the docs to clarify; however, I believe it would be much better make the implementations the same, so that the behavior is consistent. It would not be unreasonable for users to switch between local caching and memcached when they are testing vs in production. (Or, in my case, I came across this issue because I use BOTH the built-in cache and my own implementation of a Redis Cache.)

Note: the in-memory cache uses https://godoc.org/github.com/robfig/go-cache which is designed and documented to behave like a map.

**Comment by pedromorgan** [comment]
So I maintain some of the docs.. and have not got opporunnity to test,,,

Are u saying that revel serielises to redis+memcache ok and revel not??
As I understand in my limited usage.. redis or memcache need data serialised to json or alike for storage, when primitives are not used ??

**Comment by bejayoharen** [comment]
Correct: it serializes to memcache and redis (I *believe* using gob, not json), but it does not serialize when using the in-memory store. Rather it just keeps the objects around.

I'm not really sure how to write a test case for this, but I've seen it in live code, and I've traced it back through the source to determine the difference in serialization.

**Comment by notzippy** [comment]
Correct, inmemory stores the value in a map without serialization, when retrieved the pointer is set to the one stored in the map. So an update to the object will modify the version in cache. I have updated the document to reflect this
