### ISSUE TITLE
How can I get the url for a certain action

### ISSUE THREAD

**Issue by fduxiao** [revel/revel#1019]
I write a reusable form and I should specific the action each time. How can I get the url for an action of a controller which may have some params but I do not need to give it because I just want a url to post. I think the way to giving the name of the action and use 'url' in template is not efficiently.

**Comment by xpbliss** [comment]
requestUrl := c.Request.URL.Path
c.RenderArgs["yourUrl"] =requestUrl

maybe c.Action?

**Comment by fduxiao** [comment]
@xpbliss My current solution is writing {{set . "action" (url "Users.Create")}} in the template, but I think it should be decided when the app is compiled. c.Action has to take arguments but I can't give them because those data is post from another page so is there a good solution?

**Comment by pedromorgan** [comment]
Revel gives u permission to set these vars to your delight... ..

The logic needs to be in your code etc.. and do not think this is a revel problem.. are u php and want root url ???
