### ISSUE TITLE
by default, support favicon requests

### ISSUE THREAD

**Issue by wheelcomplex** [revel/revel#102]
add follow line to default routes file(create favicon.ico from favicon.png):

#--------------
GET     /favicon.ico                            Static.Serve("public/images/favicon.ico")
#-----------

**Comment by anonx** [comment]
@brendensoares I don't see any reason to complicate things.  Those who need it will add one line to their `routes` file.

**Comment by brendensoares** [comment]
Closing since it's an easy addition and since Revel doesn't use `ico` files currently. Thanks!
