### ISSUE TITLE
Separated response to normal requests and json ones

### ISSUE THREAD

**Issue by fduxiao** [revel/revel#1020]
Just like rails can post some/path/controller/action and some/path/controller/action.json which will be handle in one action (since they have the same responding logic so that pattern makes sense) but it will give different responses only in format corresponding to the incoming. It can save a lot of work

**Comment by pedromorgan** [comment]
Please explain more and an example please... Do not understand problem .. unfortunately..;-(

**Comment by brendensoares** [comment]
#659 #963
