### ISSUE TITLE
Turn off serving schema when no URL matches in dev mode

### ISSUE THREAD

**Issue by tejainece** [revel/revel#1024]
Is there a way to turn off serving in-built schema page when no URL matches in dev mode?

**Comment by pedromorgan** [comment]
Dont understand explain more please... ?

**Comment by tejainece** [comment]
In dev mode, when you access a route that doesn't exist, revel automatically servers a page with existing schema. Can this is be turned off?

**Comment by alkchr** [comment]
@tejainece Do you mean wildcard route? If so, remove [the last line](https://github.com/revel/revel/blob/master/skeleton/conf/routes#L16) of your `conf/routes` file:
```
15:  # Catch all
16:  *       /:controller/:action                    :controller.:action
```

**Comment by tejainece** [comment]
No.

I meant this page that is displayed: http://oi65.tinypic.com/33f99hv.jpg

When there is no matching route.

**Comment by runner-mei** [comment]
404.html

**Comment by alkchr** [comment]
Yeah, right as @runner-mei is pointing out, edit your [`app/views/errors/404.html` template](https://github.com/revel/revel/blob/master/skeleton/app/views/errors/404.html#L7-L9), the fragment of interest is:
```html
{{if eq .RunMode "dev"}}
{{template "errors/404-dev.html" .}}
{{else}}
```
Or create your custom `app/views/errors/404-dev.html` file ([The default one](https://github.com/revel/revel/blob/master/templates/errors/404-dev.html) for reference).

**Comment by pedromorgan** [comment]
config issue man.. ;-))

**Comment by tejainece** [comment]
Hey,

Thanks. Fixed it. Somehow forgot to inform you guys.

**Comment by brendensoares** [comment]
Thanks for sharing your outcome. Please consider using stackoverflow.com with the `revel` tag for future questions.
