### ISSUE TITLE
Hot-reload doesn't work on Linux

### ISSUE THREAD

**Issue by dreadiscool** [revel/revel#1026]
Revel doesn't seem to notice any changes to the filesystem - a restart of the web app is required. The folder it is watching is a symbolic link to a VirtualBox shared directory, which may cause the issue. Files are being saved with Sublime Text

**Comment by pedromorgan** [comment]
its in the `app/` directory right ?

http://revel.github.io/manual/appconf.html#watchers

**Comment by alkchr** [comment]
In theory symlinks should work OK since v0.10 (see #555 for details).

**Comment by dreadiscool** [comment]
Yes, it's in the app directory. The host OS is Windows 10, and the guest OS is Linux. I have /home/notroot/go/src/panel symlinked to /media/sf_Development/panel. I'm editing on Windows via Sublime Text. The shared directory appears to be working, but Revel isn't able to notice the changes

**Comment by alkchr** [comment]
@dreadiscool Is the version of Revel Framework >0.10 and version of Go >=1.4?

**Comment by dreadiscool** [comment]
It's the latest version of Revel as of 2 days ago, and it's Go 1.5

**Comment by pedromorgan** [comment]
Ok we need to work out if symlinks are "watched".. and this leads to another isse I want to watching "paths".. as not in the while of GOPATH, but externals such as a specific lib... 

Will try and test this when I get some time... this weekend..

**Comment by mattbaird** [comment]
@dreadiscool this is an issue with fsnotify, there isn't really a work around last time I checked. I ran into this when trying to run my dev env inside Docker hosted on linux.

**Comment by dreadiscool** [comment]
@mattbaird Revel with symlinks and mounted directories appear to create all kinds of problems for the app lol

**Comment by brendensoares** [comment]
Like @mattbaird said, it isn't a Revel issue. It's been discussed before here and elsewhere.

Closing this thread unless there is actionable changes in Revel's code. Thanks!
