### ISSUE TITLE
Incorrect caching of static files

### ISSUE THREAD

**Issue by dreadiscool** [revel/revel#1027]
Revel seems to be incorrectly reading documents. A file that looks like this (tested in Sublime and nano)

http://i.imgur.com/LReZbw6.png

Is returned like this by the internal server for Static.Serve (non-static files, i.e. ones put through the template engine, don't seem to suffer this problem)

http://i.imgur.com/GU26G8x.png

I've tried saving the file with different encodings - first UTF-8, then Western (ISO 8859-1). Is this an issue on my end?

**Comment by dreadiscool** [comment]
It looks like my original diagnosis was incorrect - it appears that Revel is somehow caching the old version of the document, and serving that instead. 

Basically, let's say I have a file "file.js" of length 10 bytes. If I update it, and append something - the file length becomes 12 bytes. Revel will display the first 10 bytes correctly, but the last 2 characters will be question marks in a black diamond.

Conversely, let's say that file.js was
123456789

Then, I replaced the document, and instead put in "hello", Revel serves me...
12345 - as many characters as there are in "hello".

For some reason, this seems to survive a restart of the app as well (I am porting an application from Laravel to Revel, so a lot of these files pre-existed, which is why the problem did not crop up until now)

**Comment by dreadiscool** [comment]
I found out the cause of the problem, and how to reliably reproduce it.

Revel does not seem to symlinks - there is no "old caching error" when the Revel app is not symlinked. However, if you run a symlink (such was my setup, with $GOPATH/src/panel symlinked to /media/sf_Development) Revel seems to load the wrong file, causing what looks like poor caching. 

Deleting the symlink, and working in that directory itself fixes the problem.

**Comment by dreadiscool** [comment]
After looking further, the problem also occurs for mounted directories the same way it occurs for symlinked files.

**Comment by pedromorgan** [comment]
Is there a quick way to create a test case for this so I can check here ??

**Comment by pedromorgan** [comment]
Am not sure what u doing.. is it a symlink in static directory ?? served by revel ??

**Comment by dreadiscool** [comment]
@pedromorgan 

My GOPATH is /home/notroot/documents/go

I have a Virtualbox shared directory mounted to $GOPATH/panel

The name of the revel app is `panel`. Any time I run via `revel run panel`, Revel appears to use the contents of the _old_ file, but the _length_ of the new file, for any files served with Static.Serve in the routes

**Comment by dreadiscool** [comment]
Here's a video showcasing the problem, in case I didn't explain it clearly enough (it'd kind of hard to explain via words)

https://shotr.io/BaiZq.mp4

**Comment by pedromorgan** [comment]
WHAW !!!!! fir time ever on screen play..

 Can u show it on windows-8 as well pelase.. ;-)))))))))

**Comment by dreadiscool** [comment]
I'm using Windows 10, with the guest os as Debian (Crunchbang)

**Comment by brendensoares** [comment]
@dreadiscool thanks for all the digging and rich details. The video is definitely helpful.

[Symlinks are a frequent issue](https://github.com/revel/revel/search?q=symlink&type=Issues&utf8=%E2%9C%93) we're having now.

I'm 99% sure Revel doesn't do any sort of caching.

What I would do is start in the [static module serve code](https://github.com/revel/modules/blob/master/static/app/controllers/static.go#L79) and follow the path through it. I'd be curious to [see what data is being returned](https://github.com/revel/revel/blob/8d01a054f6bca9430b3e497fe7b4f20ec8f054ce/controller.go#L209).

I would try another browser and try serving the file with another HTTPd (e.g. nginx). I ran a test on my side by creating a soft symlink (`ln -s ...`) inside my public folder and I created a `test.js` which I accessed in Chrome. I then proceeded to change it and refresh the browser each time. I could not reproduce your issue.

Let me know if you find more details.

**Comment by notzippy** [comment]
Revel doesnt cache files, however it does comply with http standards regarding sending header information about the file - so the browser can decide if to use its local cache or not. Symlinks may be the issue depending on the version of Go, if this is still an issue please reopen
