### ISSUE TITLE
Passing Variable Through Controller.Redirect()

### ISSUE THREAD

**Issue by yosualb** [revel/revel#1030]
How to pass variable through Contoller.Redirect()? Thank you.

**Comment by alkchr** [comment]
Pass them as parameters. If you're using reverse routing, you may want to do the following:
```go
import (
	...
	"github.com/ yosualb/yourproject/app/routes"
)

func (c *App) SomePage() revel.Result {
	return c.Redirect(routes.App.Greet("James", 16))
}

func (c *App) Greet(name string, age int) revel.Result {
	return c.RenderText(
		"Hello, %s. You're %d years old.",
		name, age,
	)
}
```
If you want to pass something user should not be able to modify, use session or cache.

**Comment by pedromorgan** [comment]
Is this a docs or patterns issue ??

**Comment by brendensoares** [comment]
Seems like your question is answered @yosualb. Consider asking questions on stackoverflow.com with the `revel` tag. Also, share your answers if you find a good solution.

Thanks!
