### ISSUE TITLE
{{ }} inserting newlines into generated template

### ISSUE THREAD

**Issue by dreadiscool** [revel/revel#1031]
Not sure if this counts as an issue, but here we go...

When using the templating engine, if you have something such as
{{ set . "title" "test" }}

The rendered output has an extra newline for every template "command", even if it's on the same line
{{if ... }} <something> {{end}}
Would produce two extra newlines.

It's definitely not high-priority, but it's something that annoys me when I view-source to see what's wrong with the generated HTML.

**Comment by alkchr** [comment]
Go 1.6 supports space trimming out of the box: https://tip.golang.org/pkg/text/template/#hdr-Text_and_spaces. Older versions don't. So, if you don't need a support of older versions of Go, make an upgrade and use the new `{{- ` and ` -}}` syntax.

**Comment by dreadiscool** [comment]
Nice, thanks!
