### ISSUE TITLE
Translations only work if I put into my on app before currentLocale

### ISSUE THREAD

**Issue by goors** [revel/revel#1032]
From revel docs for i18n it is perfectly clean who to define messages files and what to put into them
but when I change (and restart) <pre>i18n.default_language = sr</pre> I still get english by default.

When I log <pre>log.Println(c.Request.Locale)</pre> I got en-US.

I also tried to catch for example my language with <pre>?lang=sr</pre> and in controller <pre>c.Request.Locale = c.Request.FormValue("lang") </pre> but that is not changing language as well.

And one more thing, who to crete i18n cookie?

Maybe you should update docs with this. If it is hard for me with all this experience and 5-6 revel projects behind me some beginner will strugle for sure.

**Comment by goors** [comment]
When I do c.Request.Locale = c.Request.FormValue("lang")  for example [sr-RS] I got in log correct value from translation but view is the same. It keeps default value fro en.

**Comment by goors** [comment]
Translations only work if I put into my on app before:

<pre>c.RenderArgs["currentLocale"] = c.Request.Locale</pre>

So I am not sure that this is normal behaviour.

**Comment by notzippy** [comment]
Sorry for the long delay in replying to this.
The locale set in the RenderArgs comes from the request itself (or from a cookie). So if the browsers default locale is english then it will be set to english. We recently added the ability to set the locale via a request parameter `lang`.
