### ISSUE TITLE
TLS handshake error letsencrypt

### ISSUE THREAD

**Issue by ColinChartier** [revel/revel#1035]
I'm messing around with revel and [Lets Encrypt](https://letsencrypt.org/) and when I try to connect my app over ssl I get this error:

"server.go:2161: http: TLS handshake error from 209.171.88.125:12995: tls: first record does not look like a TLS handshake"

I'd appreciate any feedback.  If this is on the LetsEncrypt side, I'll bother them instead.

**Comment by ColinChartier** [comment]
I didn't realize enabling ssl completely disabled http serving from revel; properly redirecting http traffic to https and then routing everything to 443 did the trick.

**Comment by brendensoares** [comment]
Thanks for sharing your solution!
