### ISSUE TITLE
testrunner.go:223: json: unsupported type: <-chan struct {}

### ISSUE THREAD

**Issue by flaviamissi** [revel/revel#1037]
This error is thrown when running tests and one of the assertion fails. (go 1.6 on OS X El Capitan)

Steps to reproduce:
 1. From the revel samples, choose an app (I used the chat app)
 1. in the tests file, change an assertion to make it fail
 1. run the tests from the terminal, here's the output I get:

```
2016/03/20 11:16:44 test.go:108: Testing chat (github.com/revel/samples/chat) in dev mode

1 test suite to run.

ApplicationTest       Set up
Tear down
2016/03/20 11:16:44 testrunner.go:223: json: unsupported type: <-chan struct {}
  FAILED  !     0s

Failures:
ApplicationTest.TestThatIndexPageWorks
    Status: Header Content-Type: (expected) text/json; charset=utf-8 != text/html; charset=utf-8 (actual)
    In /tests/apptest.go (around line 18): 	t.AssertContentType("text/json; charset=utf-8")

```

This is not a big problem, but the error mentioned appears in red while the assertion failure doesn't, so it's a bit confusing/misleading.

**Comment by alkchr** [comment]
Can confirm. Revel's testrunner [serializes](https://github.com/revel/modules/blob/master/testrunner/app/controllers/testrunner.go#L220-L224) `Response` to show it to user in the browser for debugging purposes.
In Go 1.6, however, [`Cancel <- chan struct {}`](https://github.com/golang/go/blame/master/src/net/http/request.go#L245-L250) has been added to `Request` (and `Response` [embeds](https://github.com/golang/go/blob/master/src/net/http/response.go#L89-L92) `Request`).
As `chan struct{}` type is not supported by JSON `Marshal` methods (that are used for serialization), the change to the standard library broke Revel's testrunner module.

Now `Headers` tab of failing tests is empty.
![Empty Headers tab](https://cloud.githubusercontent.com/assets/6612636/13904399/90127840-eec9-11e5-8bed-a13fc51083bf.png)
And there is a `json: unsupported type: <-chan struct {}` console error.
![Console Error Message](https://cloud.githubusercontent.com/assets/6612636/13904400/96dfdc3a-eec9-11e5-8074-4fcd15b38212.png)

**Comment by jeevatkm** [comment]
Even though issue is with [golang core](https://play.golang.org/p/qEKc1nMFP9)

Test runner updated accordingly to prevent this `json: unsupported type: <-chan struct {}`
