### ISSUE TITLE
go 1.6 template block

### ISSUE THREAD

**Issue by lujiacn** [revel/revel#1040]
Hi,

Any one know how to use template block feature in revel? I hope base.html define the layout with {{ block "content" . }} {{ end}} defined. 
In other templates, just {{define "content" }} Content {{end}}.
I tried, but seems block will be overridden by another template which is not linked to the controller function. 

Thanks!
Regards,
Jia

**Comment by brendensoares** [comment]
@lujiacn I haven't tried this new feature, maybe you can share your findings with the rest of the community? Also, consider seeking answers on stackoverflow.com and tagging it as `revel`.

Thanks!
