### ISSUE TITLE
Template path priority

### ISSUE THREAD

**Issue by mrLSD** [revel/revel#1041]
There are some priority for templates bug.

I have controller:
**myapp/app/controllers/controller1.go**

and action for it: index
I have view:
**myapp/app/views/controller1/index.html**

I have module. And (for example):
**mymodule/app/controllers/controller1.go**
action: index
**mymodule/app/views/controller1/index.html**

and at my config:

`*       /myurl     module:mymodule`

and for URL: **/myurl/controller1/index**
I sow correct behavior for controller, **BUT** template got from:
**myapp/app/views/controller1/index.html**

It's wrong priority path.

More over. 
If I have view:
**mymodule/app/views/controller1/index1.html**

If at template I including other template:

> {{template "controller1/index.html" .}}

included template:
**myapp/app/views/controller1/index.html**
same results for layout.

How to fix it?

**Comment by notzippy** [comment]
I understand the expectation of a controller in a module to have its own view namespace, but that is not the way Revel works. The best practice is to create your own namespace for your module in your view. Rather then having `{{template "controller1/index.html" .}}` You should create a namespace within your views like `{{template "module1/controller1/index.html" .}}`. So your path structure will look like

```
module1/app
       -> controllers
       -> views/module1/controller1
            -> index.html
```

Within the template engine the index.html template will `module1/controller1/index.html`

We are continuing to work on documentation for best practices when writing modules. Thanks for your input.
