### ISSUE TITLE
import cycle not allowed when go get github.com/revel/revel

### ISSUE THREAD

**Issue by harryge00** [revel/revel#1044]
I am a newbie and want to install revel by `go get github.com/revel/revel`

Then I got 
```
import cycle not allowed
package github.com/revel/revel
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
```
My go version go1.5.4 linux/amd6

**Comment by harryge00** [comment]
eh...it is because I installed two version of golang into the same directory...

**Comment by alkchr** [comment]
You actually have to install it as `go get github.com/revel/cmd/revel`.
