### ISSUE TITLE
output url with format / extension

### ISSUE THREAD

**Issue by u007** [revel/revel#1045]
hi,

ive this route:
POST    /signup.:format                         App.SignUp

How do i use this in template?
this doesn't work:
{{url "App.SignUp", format: 'json'}}
output:
/signup.:format

thanks

**Comment by u007** [comment]
Im suggesting a .format support in http.go

**Comment by pedromorgan** [comment]
Are us suggesting a .ext ?? in controller input ??

**Comment by u007** [comment]
Hi Pete,

Yes, . ext is the plan
