### ISSUE TITLE
Ignore and exclude files from revel build/package

### ISSUE THREAD

**Issue by cavaliercoder** [revel/revel#1047]
In my current application, we make use of asset build tools such as Gulp or Bower to install packages or parse SCSS and Javascript files, etc.. The `revel build` command currently copies the entire application path, including the source and temporary files for these tools to `src/`, without exception.

It would be really convenient to include a `.gitignore` style file so that desired glob patterns could be excluded from the build and package processes to reduce the size and noise of deployment packages.

**Comment by pedromorgan** [comment]
any ideas how to impelment in "indistry wide way ??".

Am tagging issues so feedback respected..

**Comment by cavaliercoder** [comment]
My recommendation with limited research into alternatives would be:
* Allow users to create a `.revelignore` in the root of their revel project. This file contains one path glob pattern per line (e.g. `node_modules/` or `*.tmp`)
* When `revel build` is run (somewhere around [revel/cmd/revel/build.go:L70](https://github.com/revel/cmd/blob/master/revel/build.go#L70)), it will:
  - check for the existence of the ignore file
  - read each pattern by line
  - instead of calling `mustCopyDir`, it would recursively iterate through each file path in the project root and test each glob pattern against each path. If none of the patterns match, the file is copied into the destination package
  - child directories which match a pattern are not drilled into

**Comment by jeevatkm** [comment]
In-favour of revel/cmd#44, I'm closing this one.
