### ISSUE TITLE
prod crash after long idle

### ISSUE THREAD

**Issue by u007** [revel/revel#1049]
initially, i thought it was logging issue.
later i found out csrf plugin may cause the issue.

but after 1 hour away, 
the instance is still running,
but on my first attempt to visit the site,
the server crash with error:
Error running: signal: broken pipe

im not sure how i could replicate this immediately..
anyone have any idea? or any way to fix this?

**Comment by u007** [comment]
i found the issue comes from csrf plugin i was using.
but is there a way to log error when it crashes?

**Comment by u007** [comment]
im suspecting my crash was due to gorp sql connection idle timed out.
im currently testing it by setting
db.SetMaxIdleConns(0)
db.SetConnMaxLifetime(time.Minute) //1minute

but what is the recommended way to debug this type of issues on production?
the error seems very generic and does not show any crash?
but previous ive had similar issue with csrf plugin, with similar error.
anyway to log the full stack errors by revel?

**Comment by notzippy** [comment]
It does sound like you are missing some part of the error. Are you seeing this message in the log file? Is there anything printed to stderr? If a template function panics you will get a misleading error I think, do you have any custom template functions?

**Comment by u007** [comment]
Hi,
I found the crash was due to gorp using db/mysql connection idle issue. No
custom template function yet.

**Comment by notzippy** [comment]
So did this cause a panic? Do you get a clear error when in development mode?

**Comment by u007** [comment]
it did not happen on my machine cox im using it within 1 user,
but on production, it crashes with 
Error running: signal: broken pipe

does this count as panic?
i dont have any panic handler

**Comment by u007** [comment]
maybe u can duplicate the issue if u initialize gorp mysql driver
and then refresh the page, then shutdown mysql, and then refresh the page again
makesure the page has mysql queries

**Comment by pedromorgan** [comment]
am closing this for now.. If bug persists please repoen
