### ISSUE TITLE
code.google.com/p/go.net/websocket can not import

### ISSUE THREAD

**Issue by zllc** [revel/revel#1050]
hi, when I run go get github.com/revel  . I will get an error implies that  websocket package cannot import.
when I google it. I find that the package has been moved to  golang.org/x/net/websocket  . Can you fix that so we can run go get

**Comment by jeevatkm** [comment]
@zllc - thanks for reporting it.

[v0.12](https://github.com/revel/revel/blob/a9a2ff45fae4330ef4116b257bcf9c82e53350c2/server.go#L12) Revel is already pointed to `golang.org/x/net/websocket`.

Can you please try follow commands confirm?
```
$ go get -u github.com/revel/cmd/revel

$ revel new github.com/myaccount/my-app

$ revel run github.com/myaccount/my-app
```

Now sample application is running at [http://localhost:9000](http://localhost:9000)

**Comment by zllc** [comment]
thanks! It can run well now.

**Comment by jeevatkm** [comment]
You're welcome.
