### ISSUE TITLE
Create communication channel like slack 

### ISSUE THREAD

**Issue by sivakumar07** [revel/revel#1051]
@robfig @JackDanger @seanmac02 anyone create communication channel like slack

**Comment by jeevatkm** [comment]
@sivakumar07 thanks for your suggestion. Team is busy with preparing v0.13 release. After release we may circle back and see what is suitable for @revel/core team and revel community.

I'm closing this one.

**Comment by kumarsiva07** [comment]
What will be the expected release date?

**Comment by brendensoares** [comment]
Created revelframework.slack.com

**Comment by kumarsiva07** [comment]
Could you please add me in that channel?
kumarsiva07@live.com
