### ISSUE TITLE
[develop branch] Build issue in Go 1.3

### ISSUE THREAD

**Issue by jeevatkm** [revel/revel#1053]
Today, started analyzing the Go 1.3 build issue after few hours I have found the root cause.

`gopkg.in/fsnotify.v1` is switched to `golang.org/x/sys/...` package as on [Apr 19, 2016](https://github.com/fsnotify/fsnotify/releases/tag/v1.3.0) to bring support for linux/arm64. `revel/watcher.go` is using this library. This dependent library pushes Revel to start with Go 1.4

As long as we use this library, revel build won’t start at all for Go v1.3 it will fail at prep work itself.

```bash
The command "go get -v github.com/revel/revel/..." failed and exited with 2 during .
```
This build failure issue was discussed here #1025. For now I will be removing 1.3 from travis build file and adding 1.6 & tip also enabling verbose mode for test cases on `develop` branch.

@revel/core thoughts?

**Comment by jeevatkm** [comment]
Randomly cache test cases (memcached and redis) is failing. Which is impacting PR submission and dev work.

**Comment by alkchr** [comment]
There are no alternatives for `fsnotify` that could be used for Revel.
Revel has already had this in the README:
> As of Revel 0.11.0, Go 1.3+ is required.

How about just replacing it by 1.4?

P.S.: As for the commenting things out. I don't think that should be done.
Moreover, IMO both master and develop branch must be protected.
![Branch Protection](https://cloud.githubusercontent.com/assets/6612636/15452919/19bc54ac-2021-11e6-8316-4cee220e73a3.png)
All changes should be in a form of PRs: they are created, tests are started, if they pass PR gets merged. Otherwise, git history will be a mess.

**Comment by ottob** [comment]
The go project patches security issues in latest major release and previous (1.5). So I would drop support for anything older than that.

**Comment by jeevatkm** [comment]
@alkchr thanks for your suggestions. Yesterday I have updated the `develop` branch to Go 1.4, [build](https://travis-ci.org/revel/revel/builds/132013326) back to normal also I have nailed down the problem which was around cache test cases, will be looking into it one by one.

@ottob would you like to mention any particular security issue you think of?

**Comment by alkchr** [comment]
@jeevatkm I think what @ottob implies is that Go Team officially supports only Go 1.6 and 1.5. And thus Revel doesn't have to work on something older than 1.5.

**Comment by ottob** [comment]
@alkchr exactly!

**Comment by jeevatkm** [comment]
@alkchr @ottob - I understand your view point and suggesting to follow Go Lang [release policy](https://golang.org/doc/devel/release.html#policy).

I would like to share my thoughts here. Revel can be lenient about version support, which expands the usage of Revel Framework (In reality organizations/users gradually does the version upgrades). Yes, I agree we have push minimum version when our critical dependent library pushes us; like fsnotify made us to Go 1.4

@revel/core thoughts?

**Comment by ptman** [comment]
1.4 is the last "fast" compiler written in C, right? Until 1.7 is out, it is significantly faster than newer releases.

**Comment by brendensoares** [comment]
Good conversation everyone!

### TODO
- [ ] update `readme.md` to require Go 1.4
- [ ] update docs to reflect Go 1.4 minimum

**Comment by jeevatkm** [comment]
Taken care!
