### ISSUE TITLE
Error walking templates.

### ISSUE THREAD

**Issue by RobertChristopher** [revel/revel#1058]
Hey,

I am building a REST JSON API using the Revel framework. Because of this, I have no need for a views or public directory. After deleting them and running Revel in development, I get the following error.

> ERROR 2016/05/25 17:11:40 template.go:230: error walking templates: lstat /Users/rob/golang/src/github.com/FriendlyApp/Friendly-API/app/views: no such file or directory

I have made sure to set "watch.templates" equal to false inside of my configuration file. Does anyone know the cause of this? Any help would be appreciated. Thank you.

**Comment by jeevatkm** [comment]
Please have empty `views` directory. Will have fix in v0.13 release.

**Comment by jeevatkm** [comment]
Fix applied in v0.13 `develop` branch.
