### ISSUE TITLE
Compile revel project without revel command-cli

### ISSUE THREAD

**Issue by mageddo** [revel/revel#1065]
Is possible build and package revel project only with the go command?

**Comment by jeevatkm** [comment]
No, please use `revel build` or `revel package`.

**Comment by mageddo** [comment]
@jeevatkm  Ok, the problem is that this build generate some files that are not compiled, is there anyway of compile everything inside the binary file?

**Comment by jeevatkm** [comment]
I couldn't understand.

> build generate some files that are not compiled

Can you please explain in detail, what is the issue you're facing?

**Comment by mageddo** [comment]
Of course, for example the `chat`

When I run 

	$ revel build github.com/revel/samples/chat /tmp/chat-build prod

It generates the folow tree. This way my source code is exposed to the final user, I want that all files be compiled to the binary and no one source file be exposed, do you understand?

	.
	├── chat
	├── run.bat
	├── run.sh
	└── src
		└── github.com
		    └── revel
		        ├── modules
		        │   ├── static
		        │   │   └── app
		        │   │       └── controllers
		        │   │           └── static.go
		        │   └── testrunner
		        │       ├── app
		        │       │   ├── controllers
		        │       │   │   └── testrunner.go
		        │       │   ├── plugin.go
		        │       │   └── views
		        │       │       └── TestRunner
		        │       │           ├── FailureDetail.html
		        │       │           ├── Index.html
		        │       │           └── SuiteResult.html
		        │       ├── conf
		        │       │   └── routes
		        │       └── public
		        │           ├── css
		        │           │   ├── bootstrap.min.css
		        │           │   └── github.css
		        │           ├── images
		        │           │   └── favicon.png
		        │           └── js
		        │               ├── bootstrap.min.js
		        │               ├── highlight.pack.js
		        │               └── jquery-1.9.1.min.js
		        ├── revel
		        │   ├── conf
		        │   │   └── mime-types.conf
		        │   └── templates
		        │       └── errors
		        │           ├── 403.html
		        │           ├── 403.json
		        │           ├── 403.txt
		        │           ├── 403.xml
		        │           ├── 404-dev.html
		        │           ├── 404.html
		        │           ├── 404.json
		        │           ├── 404.txt
		        │           ├── 404.xml
		        │           ├── 405.html
		        │           ├── 405.json
		        │           ├── 405.txt
		        │           ├── 405.xml
		        │           ├── 500-dev.html
		        │           ├── 500.html
		        │           ├── 500.json
		        │           ├── 500.txt
		        │           └── 500.xml
		        └── samples
		            └── chat
		                ├── app
		                │   ├── chatroom
		                │   │   └── chatroom.go
		                │   ├── controllers
		                │   │   ├── app.go
		                │   │   ├── longpolling.go
		                │   │   ├── refresh.go
		                │   │   └── websocket.go
		                │   ├── routes
		                │   │   └── routes.go
		                │   ├── tmp
		                │   │   └── main.go
		                │   └── views
		                │       ├── Application
		                │       │   └── Index.html
		                │       ├── footer.html
		                │       ├── header.html
		                │       ├── LongPolling
		                │       │   └── Room.html
		                │       ├── Refresh
		                │       │   └── Room.html
		                │       └── WebSocket
		                │           └── Room.html
		                ├── conf
		                │   ├── app.conf
		                │   └── routes
		                ├── public
		                │   ├── images
		                │   │   └── favicon.png
		                │   ├── javascripts
		                │   │   ├── jquery-1.5.min.js
		                │   │   ├── jquery.scrollTo-min.js
		                │   │   └── templating.js
		                │   └── stylesheets
		                │       └── main.css
		                └── tests
		                    └── apptest.go

**Comment by jeevatkm** [comment]
okay, I get it. So you want to exclude the `src` from archive correct?

**Comment by mageddo** [comment]
yes.. but I can't because it causes error  for today

**Comment by mageddo** [comment]
The static files like `.css`, `.html` and `.json` can be on the `src` directory, not matter, the problem are only with the `.go` files, I can not leave they there

**Comment by jeevatkm** [comment]
I understand. Actually, exclude feature is currently not exists. 

Can you please create an issue [here](https://github.com/revel/cmd/issues) with feature description for `revel package` command?

**Comment by mageddo** [comment]
Of course @jeevatkm, thanks

**Comment by ptman** [comment]
In the meantime, I do something like this to filter the files I don't want out from my archives:

    gunzip < project.tar.gz | tar --wildcards --delete '*.go' src/$package/tests src/$package/doc | gzip > project-small.tar.gz

**Comment by jeevatkm** [comment]
@mageddo please create an issue at [revel/cmd](https://github.com/revel/cmd/issues) with detailed description for `package` command.

I'm closing this one.

**Comment by mageddo** [comment]
I've created [the issue](https://github.com/revel/cmd/issues/49)

**Comment by mageddo** [comment]
Many thanks @ptman, so the `.go`  are not  really needed on this folder? They are generated only by convection?

**Comment by ptman** [comment]
@mageddo well, we've had a production service running for almost a year running in a docker container without those .go files so I'm fairly confident that it works. They are just used when compiling the binary. I assume the archive contains the files because  all of app/ is just copied there.

**Comment by mageddo** [comment]
@ptman Good, your command will be useful while the feature request is not developed.

**Comment by brendensoares** [comment]
Just a note, you can delete most of what is included in archives (as alluded to here). The only files that are needed are used at runtime.

**Comment by mageddo** [comment]
@brendensoares Good pointer. Later I understood it, at principle I think that the are used
