### ISSUE TITLE
Fork third party library into revel org and map it in the codebase

### ISSUE THREAD

**Issue by jeevatkm** [revel/revel#1067]
- https://github.com/fsnotify/fsnotify
- https://github.com/robfig/pathtree
- https://github.com/robfig/go-cache
- https://github.com/bradfitz/gomemcache
- https://github.com/garyburd/redigo
- https://github.com/agtorre/gocolorize
- https://github.com/klauspost/compress

Refresh upstream repo into revel org, periodically/before each release.
- [x] Fork into revel org
- [ ] Map it in the revel codebase

**Comment by brendensoares** [comment]
Any news here?

**Comment by notzippy** [comment]
Moving this to backlog, I am not sure how important it is to have every module version available.

**Comment by notzippy** [comment]
Moved critical components
