### ISSUE TITLE
Debugging with IntelliJ

### ISSUE THREAD

**Issue by mrichman** [revel/revel#1072]
How can we configure IntelliJ to debug revel apps?

**Comment by jeevatkm** [comment]
Did you get a chance to see this [IntelliJ plugin wiki](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Documentation#debugging-a-go-project)? Please give it try.

**Comment by mrichman** [comment]
@jeevatkm It's not helpful because revel apps don't have a main entry point. They are invoked by the `revel` command. What command line would I pass to the plugin?

**Comment by jeevatkm** [comment]
Revel does have main entry point, `$GOPATH/src/<import-path>/app/tmp/main.go` gets generated during a build. 

Can you please try revel run command or output from run command?
```
revel run <import-path>
```

When you run `revel run`, it builds a revel app and creates a binary here `$GOPATH/bin/revel.d/<import-path>/<app-name>`.

That binary takes following params to run the application.
```
$GOPATH/bin/revel.d/<import-path>/<app-name> -importPath <importPath-value> -srcPath <sourcePath-value> -runMode <runMode-value>
```

If you turn on the trace logging in revel (app.conf - `log.trace.output = stderr`), you can relate my description from logging output.

**Comment by mrichman** [comment]
@jeevatkm Thanks! That worked perfectly. I had no idea about `tmp/main.go`.

**Comment by jeevatkm** [comment]
@mrichman I'm glad it worked.

I would like to ask a favor from you. Whenever you get a chance; can you please document (How to debug revel with IntelliJ Go plugin) your [steps here](https://github.com/revel/revel.github.io/edit/develop/manual/debug.md), it would be great. 

Community will get benefit from your effort and findings :)

**Comment by SirGordon** [comment]
Just for other people with the same question.
1. Create your project, for this example i will be using canonical "revel new github.com/myaccount/my-app"
2. "revel run github.com/myaccount/my-app" to generate tmp/main.go - this file is needed by intellij
3. Shutdown the running server
4. Create project in intellij from existing sources
5. Create run configuration and in "Program arguments" add "-importPath github.com\myaccount\my-app -srcPath <your gopath>\src -runMode dev"
6. In "before launch" add "Run external tool". There:
   Program: <your gopath>\bin\revel.exe
   Paramerets: build github.com/myaccount/my-app
Thats all, it works for me!

**Comment by notzippy** [comment]
Re-opening so this can be added to the documents @pedromorgan

**Comment by SirGordon** [comment]
Edited my post to be more clear

**Comment by notzippy** [comment]
Moved to webpage
