### ISSUE TITLE
Fsnotify problem

### ISSUE THREAD

**Issue by Venommmm** [revel/revel#1073]
When i start app in dev mode i get error messages like watcher.go:124: Failed to watch %filename like /gocode/src/my_app/app/controllers%- no space left on device. I think its problem with fsnotify. I have a lot of files in public folder. So how can i ignore this folder to run things smoothly?

**Comment by jeevatkm** [comment]
Can you please share project file structure and complete error log line?

Also, what is it mean `I have a lot of files in public folder`, error showing controller path tree and you're mentioning about public directory. I couldn't understand. Please clarify.

**Comment by Venommmm** [comment]
When revel runs in dev mode and i change revel files in /gocode/src/myapp/app/controllers, revel doesnt see changes and doesnt reload itself. I guess it happens because i have a lot of files in /gocode/src/myapp/public, so the fsnotify runs out max possible number of files it can track for changes. Error log when i start in dev mode:

ERROR 2016/06/26 03:55:55 watcher.go:124: Failed to watch /home/ve/gocode/src/my_app/app : no space left on device
ERROR 2016/06/26 03:55:55 watcher.go:124: Failed to watch /home/ve/gocode/src/my_app/app/controllers : no space left on device
ERROR 2016/06/26 03:55:55 watcher.go:124: Failed to watch /home/ve/gocode/src/my_app/app/helpers : no space left on device
ERROR 2016/06/26 03:55:55 watcher.go:124: Failed to watch /home/ve/gocode/src/my_app/app/models : no space left on device
ERROR 2016/06/26 03:55:55 watcher.go:124: Failed to watch /home/ve/gocode/src/github.com/revel/modules/static/app : no space left on device
ERROR 2016/06/26 03:55:55 watcher.go:124: Failed to watch /home/ve/gocode/src/github.com/revel/modules/static/app/controllers : no space left on device
ERROR 2016/06/26 03:55:55 watcher.go:124: Failed to watch /home/ve/gocode/src/github.com/revel/modules/testrunner/app : no space left on device
ERROR 2016/06/26 03:55:55 watcher.go:124: Failed to watch /home/ve/gocode/src/github.com/revel/modules/testrunner/app/controllers : no space left on device
ERROR 2016/06/26 03:55:55 watcher.go:124: Failed to watch /home/ve/gocode/src/my_app/tests : no space left on device

**Comment by jeevatkm** [comment]
I hope you have enough hard disk space :)  What is `ulimit` size for hard and soft? please increase it might solve your issue.

**Comment by Venommmm** [comment]
ulimit -Hn 65536; ulimit -Sn 1024
I found the command **sudo sysctl -w fs.inotify.max_user_watches=100000** is the solution for me. So can large /gocode/src/myapp/public be the problem?

**Comment by jeevatkm** [comment]
May be, if you exceed total of `100000`. One important thing, when you increased `fs.inotify.max_user_watches` value then increase max limit file descriptor too.

```bash
# vi /etc/sysctl.conf
fs.file-max = 200000

# Applying changes
sysctl -p
```

**Comment by Venommmm** [comment]
thank you, also used your code to implent tdewolf/minify, you're doing great work!

**Comment by jeevatkm** [comment]
Thank you.
