### ISSUE TITLE
GoDoc exported methods, variables & constants

### ISSUE THREAD

**Issue by jeevatkm** [revel/revel#1074]
This task is extract from #1057 as an separate issue -
- [ ] Document Exported variables, constants, structs, methods, etc. #419

**Comment by pedromorgan** [comment]
Here's a list, omitting some stuff which don't need docs and self explanitory

- [ ] https://godoc.org/github.com/revel/revel#ActionInvoker
- [ ] https://godoc.org/github.com/revel/revel#BindValue
- [ ] https://godoc.org/github.com/revel/revel#CheckInit
- [ ] https://godoc.org/github.com/revel/revel#CompressFilter
- [ ] https://godoc.org/github.com/revel/revel#ContainsString
- [ ] https://godoc.org/github.com/revel/revel#InterceptorFilter
- [ ] https://godoc.org/github.com/revel/revel#ParamsFilter
- [ ] https://godoc.org/github.com/revel/revel#RouterFilter
- [ ] https://godoc.org/github.com/revel/revel#Slug
- [ ] https://godoc.org/github.com/revel/revel#Unbind
- [ ] https://godoc.org/github.com/revel/revel#Controller.RenderError
- [ ] https://godoc.org/github.com/revel/revel#GoTemplate.Content
- [ ] https://godoc.org/github.com/revel/revel#InterceptorMethod
- [ ] https://godoc.org/github.com/revel/revel#ValidMatch
- [ ] https://godoc.org/github.com/revel/revel#Validation.Match
