### ISSUE TITLE
new project can't run on windows 7

### ISSUE THREAD

**Issue by sh8ker** [revel/revel#1078]
error message as follow:

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>cd e:\gopath

C:\Users\Administrator>e:

e:\gopath>revel new reveltest
~
~ revel! http://revel.github.io
~
Your application is ready:
   E:\gopath\src\reveltest

You can run it with:
   revel run reveltest

e:\gopath>revel run reveltest
~
~ revel! http://revel.github.io
~
INFO  2016/07/02 11:03:52 revel.go:365: Loaded module testrunner
INFO  2016/07/02 11:03:52 revel.go:365: Loaded module static
INFO  2016/07/02 11:03:52 revel.go:230: Initialized Revel v0.13.1 (2016-06-06) f
or >= go1.4
INFO  2016/07/02 11:03:52 run.go:57: Running reveltest (reveltest) in dev mode
INFO  2016/07/02 11:03:52 harness.go:170: Listening on :9000
INFO  2016/07/02 11:03:56 build.go:173: Cleaning dir tmp
INFO  2016/07/02 11:03:56 build.go:173: Cleaning dir routes
INFO  2016/07/02 11:03:56 build.go:173: Cleaning dir tmp
INFO  2016/07/02 11:03:56 build.go:173: Cleaning dir routes
ERROR 2016/07/02 11:03:57 build.go:102: # reveltest/app/tmp
C:\Go\pkg\tool\windows_386\link.exe: -X flag requires argument of the form impor
tpath.name=value

**## ERROR 2016/07/02 11:03:57 build.go:302: Failed to parse build errors:
 # reveltest/app/tmp
C:\Go\pkg\tool\windows_386\link.exe: -X flag requires argument of the form impor
tpath.name=value**

**Comment by jeevatkm** [comment]
This is not a windows issue please refer revel/cmd#51. What is your Go version (1.7 beta or devel)?

**Comment by sh8ker** [comment]
thanks.my Go version is 1.7 beta1

**Comment by jeevatkm** [comment]
Thanks for confirm, till that revel/cmd#51 get release. Please use Go v1.6.2.
