### ISSUE TITLE
Why are there still references to code.google.com?

### ISSUE THREAD

**Issue by acpower7** [revel/revel#1084]
Google has shut down code.google.com a while ago yet there are still many import references to that URL. I see many instances of "code.google.com/p/go.net/websocket" being imported. This is causing issues as I get errors such as 

`package code.google.com/p/go.net/websocket: unable to detect version control system for code.google.com/ path`

when doing `go get code.google.com/p/go.net/websocket`

**Comment by jeevatkm** [comment]
Please refer #1050

**Comment by acpower7** [comment]
Thanks. One final issue.

I'm trying to run the app from an executable.

`revel build vagrant-revel-react /tmp/myapp`

Then when I go to the app/tmp file I hit:` go run main.go`

I get the error: 

`revel.go:312: Failed to import  with error: import "": invalid import path`

Any help with this?

**Comment by jeevatkm** [comment]
After the build; target directory will have `run.sh` & `run.bat` and other files. Use the run file.

**Comment by acpower7** [comment]
sorry but I can't find the run.sh & run.bat file....they don't exist in the tmp directory.

**Comment by jeevatkm** [comment]
Let's say this is revel app `vagrant-revel-react` reside in `$GOPATH/src/vagrant-revel-react`

* when you `revel build vagrant-revel-react /tmp/myapp`
* `/tmp/myapp` gets created with build artifacts
* `cd /tmp/myapp` and this directory will have files I have mentioned about.

**Comment by acpower7** [comment]
Very strange. `myapp` directory isn't created when I run that command, just the tmp.

Anyway I was just experimenting, i'll probably move on. 

thanks

**Comment by brendensoares** [comment]
Seems this issue is finished.
