### ISSUE TITLE
Auto redirect to the requesting URL after successful login (db base)

### ISSUE THREAD

**Issue by arixion** [revel/revel#1089]
I have a golang web application made with revel framework. I am facing issue in redirecting to the previous page after login. I have few pages where users should login to view the content. I have successfully redirected to login page if the users is not logged in. Here is my code snippet below - 

``` go
    func checkUser(c *revel.Controller) revel.Result {
    if _, ok := c.Session["user"]; ok {
        return nil
    }
      var cont = c.Request.RequestURI
      fmt.Printf("Requesting URL : ", cont)
      return c.Redirect(LoginApp.Login, cont)
    }

    func init() {
      revel.InterceptFunc(checkUser, revel.BEFORE, &App{})
    }
```

And here is my app.go

``` go
    type App struct {
      *revel.Controller
    }

    func (c App) Application() revel.Result {
      var app = make(map[string]string)
      app["appTitle"] = "Hourglass"
      app["ngApp"] = "app"
      app["theme"] = "dark"
      app["ngController"] = "ApplicationController"
      return c.Render(app)
    }

    func (c App) Test() revel.Result {
      var app = make(map[string]string)
      app["appTitle"] = "Hourglass"
      app["ngApp"] = "app"
      app["theme"] = "dark"
      app["ngController"] = "ApplicationController"
      return c.Render(app)
    }
```

Now I have a login.go file which contains a **ServiceLogin** method

``` go
    func (c LoginApp) ServiceLogin(user models.User) revel.Result {

      username := user.UserName
      password := user.Password
      fmt.Printf("", username)
      fmt.Printf("", password)
      sess := service.GetSession()
      usercoll := sess.DB("hourglass_dev").C("user")
      var result models.User
      var err = usercoll.Find(bson.M{"UserName": username, "Password":   password}).One(&result)
      fmt.Printf("", result)
      fmt.Printf("", c.Request.RequestURI)
      if err != nil {
        fmt.Printf("", err)
      }
      //var app := make(map[string]string)
      //return c.Render(app)
      c.Session["user"] = username
      return c.Redirect(App.Application)
    }
```

Now in the last line of the method I have to hard coded the **App.Application** instead of which I want the requesting URL to be used so that when the user logged in successfully it automatically redirects to the page they are requesting for.

I am new to revel and please let me know if I am doing things wrong

Thanks
Arpan

**Comment by jeevatkm** [comment]
@arixion Multiple ways to achieve this behavior. One suggestion from my end.

```go
return c.Redirect(LoginApp.Login, cont)
```
Above line gives continue URL to the login page. Post `continue URL` you have on login page along with credentials. Then you will have login credentials and continue url as part of login submission.

Once login is success, use continue URL to redirect user to that page.

**Comment by notzippy** [comment]
No response, closing
