### ISSUE TITLE
Support OpenShift

### ISSUE THREAD

**Issue by molikto** [revel/revel#109]
I compiled and deployed Revel on OpenShift, but always get an error about load module failed. I think in the generated main.go, reading app.conf's module settings is unnecessary and causing the bug. Sorry for my broken English, hope you can understand what I mean.

**Comment by pedromorgan** [comment]
Is this still active ??

is there an openshift a docker etc ?

**Comment by brendensoares** [comment]
@pedromorgan let's close this one down. If someone can contribute to getting Revel running on OpenShift, then we can [start a RFC](https://github.com/revel/rfcs).
