### ISSUE TITLE
revel build fails when vendoring revel binary

### ISSUE THREAD

**Issue by Warashi** [revel/revel#1092]
when I vendored revel binary and `github.com/revel/revel` in project `vendor` folder, `revel build` fails and output this error.

```
ERROR 2016/08/26 06:05:38 revel.go:317: Failed to find Revel with error: cannot find package "github.com/revel/revel" in any of:
        /usr/local/go/src/github.com/revel/revel (from $GOROOT)
        / ... /src/github.com/revel/revel (from $GOPATH)
```

This comes from calling build.Import with second arg being empty string.

**Comment by notzippy** [comment]
looking at the code, this should now work, please reopen if it is still an issue
