### ISSUE TITLE
Can't use Session on Production mode

### ISSUE THREAD

**Issue by stargt** [revel/revel#1097]
The following is a simple controller for setting a session and a cookie.

``` go
func (c App) Index() revel.Result {
  c.Session["foo"] == "bar"
  c.SetCookie(&http.Cookie{Name: "foo2", Value: "Bar2"})
  return c.Render()
}
```

When I run this revel application with `$ revel run myapp dev`, It works fine. I can see the values on the browser's devtools
But, with `$ revel run myapp prod`, there is no related session and cookie values I can see on the devtools, and also some features are not working I have expected. ([Revel's Flash](https://revel.github.io/manual/sessionflash.html) is also unavailable.)

Finally, I figured out that after changing `mode.dev` value from `false`(default) to `true` under `[prod]` section in revel's `app.conf`, It started to work fine.

I couldn't find more details about this problem on [the official manual](https://revel.github.io/manual/index.html).
Is it a bug? Or is there anything I need to check about in this situation before using revel on Production mode?

**Comment by lujiacn** [comment]
I met the same issue today. Everything works fine in dev mode, but in prod mode, flash not work, csrf not work (due to cannot read session).
My previous revel projects no same issue, any thing updated recently?
@jeevatkm

**Comment by lujiacn** [comment]
issue due to revel.go, line 207
```
	CookieSecure = Config.BoolDefault("cookie.secure", !DevMode)
```
The !DevMode should be value false.

**Comment by jeevatkm** [comment]
Implementation was part of [v0.13.0 release](https://github.com/revel/revel/releases/tag/v0.13.0). 
* Defaults to HttpOnly and always secure cookies for non-dev mode #942, PR #943

**Comment by lujiacn** [comment]
go back to this issue.
since "cookie.secure  = false" is defined in app.conf. In revel, should respect config default value.
```
   CookieSecure = Config.BoolDefault("cookie.secure", !DevMode)
```
to
```
   CookieSecure = Config.BoolDefault("cookie.secure", false)
```

**Comment by shawncatz** [comment]
wouldn't we want the default to be true in production? Isn't that the intent of the change?
Disabling this in prod works around the problem, but exposes those apps to potential issues (as mentioned in the referenced issues / prs)

**Comment by lujiacn** [comment]
"A secure cookie has the secure attribute enabled and is only used via HTTPS".
I did not setup https in revel, but run revel behind nginx (SSL) in production mode. cookie.secure = !DevMode will introduce a issue.

**Comment by shawncatz** [comment]
Makes sense

-- 
Shawn Catanzarite
408-605-7744
http://shawncatz.com/
http://linkedin.com/in/shawncatanzarite

On February 28, 2017 at 12:16:00 AM, Jia Lu (notifications@github.com)
wrote:

"A secure cookie has the secure attribute enabled and is only used via
HTTPS".
I did not setup https in revel, but run revel behind nginx (SSL) in
production mode. cookie.secure = !DevMode will introduce a issue.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/revel/revel/issues/1097#issuecomment-282972193>, or mute
the thread

**Comment by lujiacn** [comment]
PR#1102  to resolve this issue

**Comment by brendensoares** [comment]
We've added a solution that will only enable secure cookies if the config declares HTTPS as enabled. Closing this issue now in favor of the PR.
