### ISSUE TITLE
Error in file syscall_linux_386.go while installing revel command tool 

### ISSUE THREAD

**Issue by yogesh-bitsbridge** [revel/revel#1099]
While running the command go get github.com/revel/cmd/revel I encounted the errors of undefined references in file src/golang.org/x/sys/unix/syscall_linux_386.go.

I changed the line 217 & 219 in func socketcall and func rawsocketcall. Add return statement in both functions
previously it was 
func socketcall(call int, a0, a1, a2, a3, a4, a5 uintptr) (n int, err syscall.Errno)
func rawsocketcall(call int, a0, a1, a2, a3, a4, a5 uintptr) (n int, err syscall.Errno)
after :
func socketcall(call int, a0, a1, a2, a3, a4, a5 uintptr) (n int, err syscall.Errno) { return }
func rawsocketcall(call int, a0, a1, a2, a3, a4, a5 uintptr) (n int, err syscall.Errno) {return }
@shaban @JackDanger @JackDanger @tmc @nathany @thequux

**Comment by pedromorgan** [comment]
Does not look like a revel issue, Please reopen with more into. TIA
