### ISSUE TITLE
Automatically bind POSTs of type application/json

### ISSUE THREAD

**Issue by purohit** [revel/revel#110]
I'm using Backbone.js for an app built with Revel, and one of the things it does is make ajax requests with `Content-Type: application/json`, whose parameters Revel doesn't auto-parse like it does with `application/x-www-form-urlencoded`. I can use http://backbonejs.org/#Sync-emulateJSON to have Backbone.js send a form-encoded request, but it does some weird things like namespace the payload into a parameter called "model", which in Revel I then have to unmarshal:

``` go
func (c MyController) Post(model string) revel.Result {
    type PostPayload struct {
        Text    string
        ObjectId int
    }
    // Gotta unmarshal this by hand
    var payload PostPayload
    err := json.Unmarshal([]byte(model), &payload)
        ...
}
```

Is a more generic auto-unmarshalling/binding of `application/json` ajax requests something I could contribute to Revel, or something you might have plans for already?

**Comment by arslantopcu** [comment]
err := json.Unmarshal([]byte(c.Request.Body), &payload)

error go file
cannot convert c.Controller.Request.Request.Body (type io.ReadCloser) to type []byte

**Comment by arslantopcu** [comment]
resolved 

https://github.com/revel/revel/issues/488 smothers commented on Mar 21, 2014
