### ISSUE TITLE
revel Template 

### ISSUE THREAD

**Issue by hishamwaleed** [revel/revel#1100]
controller render another page when i am trying to define the same template in the multiple pages 
parent.html:
```
<!DOCTYPE html>
<html>

<head>
    {{ template "head.html" . }}
</head>

<body>
    {{template "navbar.html" .}}
    {{template "content" .}}
    {{template "footer.html" . }}
</body>

</html>
```
home.html:
```
{{template "parent.html"}}
{{define "content"}}
<!--home HTML TAGS-->
{{end}}
```
signup.html
```
{{template "parent.html"}}
{{define "content"}}
<!-- sign up page HTML TAGS-->
{{end}}
```
home controller:
```
func (c App) Home() revel.Result {
	return c.RenderTemplate("App/home.html")
}
```
routing : 
```
GET     /                                       App.Home
GET     /signup                                 App.Signup
```
when i request home with 
`http://127.0.0.1:9000/`
render signup page instead of home
 :smile:

**Comment by lujiacn** [comment]
no solution now, only way is include different template. I also struggled for some time on using "define" in template to render different content.

**Comment by hishamwaleed** [comment]
thank you for replying. i will use manual templates
