### ISSUE TITLE
Can't compiler my revel app

### ISSUE THREAD

**Issue by yogesh-bitsbridge** [revel/revel#1101]
I installed revel framework and revel command tool. Afterwards I created an app using `revel new app` revel successfully created that but I am not able to run, build, test my app. encountering the same error every time 
`ERROR 2016/09/16 12:23:16 build.go:108: flag provided but not defined: -i`
`Error building: Go Compilation Error: See console for build error.`
Does anyone know the solution

**Comment by brendensoares** [comment]
Can you list the versions of Revel andGo you are using? Can you reproduce this issue on another machine?

**Comment by yogesh-bitsbridge** [comment]
thanx @brendensoares. I resolved the issue. Previously I installed Go with Gccgo compiler . Now I installed it with default Go compiler i.e. gc. It's working fine. 
by the way, I am using latest go version 1.7 and revel 0.13.1
