### ISSUE TITLE
how to handle preflight request

### ISSUE THREAD

**Issue by rishirajdev** [revel/revel#1104]
Hi,

I have api developed in revel framework .My front end send preflight request with options as a method.I have added CORS policy in my HeaderFilter in response,however still it return 404 not found.

For an example Below is the route configured in my revel code :
`GET  /users  APP.ACTION`
And the preflight request  details below
`Method: options`
`URL: http://www.example.com/users`

Therefore it is returning 404 not found

Below is the headerFilter code in the init.go file : [https://github.com/rishirajdev/searchApp.git](url) 

What I need to do in order to handle preflight request

**Comment by brendensoares** [comment]
[CORS requires](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) that you respond to the OPTIONS request with the needed headers.

I've not attempted this in Revel, so I can't provide more info. If you find a good solution, please share here.

I'll close this issue for now until there are actions items.
