### ISSUE TITLE
0.13.1 does not reload template code in watch.mode = "normal"

### ISSUE THREAD

**Issue by jmhodges** [revel/revel#1105]
I have a template in `app/views/App/Index.html` and when I make changes to it, the file is not being reliably reloaded and used even if I wait a few seconds.

I'm not super sure how to debug this further.

**Comment by jmhodges** [comment]
Oh! This is on macOS 10.12 Sierra

**Comment by torden** [comment]
Which one version? my test env below
- OS : 10.12 Sierra
- Go : 1.7.4 drawin/amd64
- Revel : v0.13.1

![2017-01-05 5 16 34](https://cloud.githubusercontent.com/assets/3272513/21673176/c5662c0e-d36a-11e6-86bb-3f3c59ffaa61.png)
work fine

**Comment by pedromorgan** [comment]
If this is still a problem then please reopen
