### ISSUE TITLE
Force write header

### ISSUE THREAD

**Issue by rbferreyra** [revel/revel#1106]
I am creating an api. But I have simulate a consuming to 404 route and getting error in HTML. But I put header in Postman `Accept: application/json`, it is returning in JSON.

I want to consume the resource and response all error in JSON without putting header `Accept: application/json` in Postman.

So I have an idea the force header directly in app and found a method called HeaderFilter in init.go. I put the code `c.Response.Out.Header().Add("Content-Type", "application/json")`

But, I getting still the header `text/html; charset=utf-8`

PS: Sorry about my english

**Comment by torden** [comment]
Hi,Do you want to "application/json" print out in every response header(including renderError).?

**Comment by notzippy** [comment]
The `Add` command adds that header to the existing one. What you need to do is use the `Set` command.
