### ISSUE TITLE
Flash a struct

### ISSUE THREAD

**Issue by audathuynh** [revel/revel#1108]
Dear all,
Could you please let me know how to flash an object automatically in Revel?
I would like to allow users to edit an object on a page and below is my controller.

```
func (c MyController) EditObject(id int) revel.Result {
    obj := loadObjectById(id)
    c.Flash.Data["obj.ID"] = strconv.Itoa(obj.ID)
    c.Flash.Data["obj.Name"] = obj.Name
    // there are a lot of fields in the struct of the object obj and I have to flash all of them manually
    c.Flash.Data["obj.Notes"] =obj.Notes
    return c.Render(obj)
}
```
Thank you very much.
D.

**Comment by pedromorgan** [comment]
Flash is a ```map[string]string```

At present it does not flash structs

Check the guide here on how to use flash
http://revel.github.io/manual/sessionflash.html#flash

**Comment by audathuynh** [comment]
Thank you very much for your answer.
Sincerely,
D.
