### ISSUE TITLE
DevMode not being setup before init()

### ISSUE THREAD

**Issue by Fyb3roptik** [revel/revel#1110]
I was trying to check DevMode in my app/init.go init() and it was false. Check this PR

https://github.com/revel/cmd/pull/68

Not sure if this is intended or if this is a bug, but could only access it inside of OnAppStart

**Comment by brendensoares** [comment]
According to [the manual](http://revel.github.io/manual/appconf.html#run-modes) DevMode is set at runtime. However, [the `revel.go` source code](https://github.com/revel/revel/blob/8d01a054f6bca9430b3e497fe7b4f20ec8f054ce/revel.go#L188) sets it based on an undefined `app.conf` setting called `mode.dev` and yet [the same source file](https://github.com/revel/revel/blob/8d01a054f6bca9430b3e497fe7b4f20ec8f054ce/revel.go#L43) has a comment that contradicts this `DevMode bool   // if true, RunMode is a development mode.`.

It seems this is a bug. `DevMode` needs to be set to `true` if `RunMode == "dev"` and `false` if not.

@revel/core correct?

**Comment by Fyb3roptik** [comment]
Glad I found this one! For now the workaround is my PR in the CMD repo

**Comment by jeevatkm** [comment]
Currently `DevMode` uses the app config `mode.dev` value. As you have described, it is safe to set `DevMode` to `true/false` value based on `RunMode`.  Safe to remove `mode.dev` from config.

**Comment by Fyb3roptik** [comment]
Right but that was not getting through. It is blank

**Comment by Fyb3roptik** [comment]
Please see my PR in the CMD repo to see what I am trying to say

**Comment by shawncatz** [comment]
as per comments above, the solution is to add an OnAppStart function to have access to RunMode and DevMode
