### ISSUE TITLE
Vagrant with SSL

### ISSUE THREAD

**Issue by Fyb3roptik** [revel/revel#1112]
Trying to get Revel to run in Vagrant using HTTPS and SSL. I am unable to bind to port 443 and wanted to know if I have any other options for this? I am currently stuck as HTTPS is required =(

**Comment by Steve-hyas** [comment]
You can proxy it through apache and mod_proxy

**Comment by Fyb3roptik** [comment]
Tried that already. Nothing seems to work. I can forward port 80 to 9000 and http works fine. When I use https its as if it isnt even getting there.

**Comment by Steve-hyas** [comment]
Is your vhost like ?:

    <VirtualHost *:443>
    ...

**Comment by Fyb3roptik** [comment]
With http I do not even need Apache though, so you're saying I will need apache? That seems a little counter-intuitive

**Comment by Steve-hyas** [comment]
Generally for most sites you want to use a server to serve the static content of the site. Also with apache you will need to enable ssl using `a2enmod ssl`

**Comment by Fyb3roptik** [comment]
I do not want to use Apache. Also this is for a dev environment only and I would like to be able to specify an https port like I can with http. Is this not possible with Revel? If not is there a specific reason? I would very much like to never install apache or Nginx if I can help it.

**Comment by Fyb3roptik** [comment]
I should reiterate I am on MacOS using Vagrant running Debian. It seems like 443 is not being forwarded properly or at all. I have to forward 443 to a DIFFERENT port other than 443 because Vagrant wont forward a port < 1024

**Comment by Fyb3roptik** [comment]
ok nevermind I was able to get this dev oauth server working without https. it is fine since it is just my dev env
