### ISSUE TITLE
init.go init function executes only after http request

### ISSUE THREAD

**Issue by leshax** [revel/revel#1113]
Hello guys,

Could you please explain why init function in init.go does not fire after command "revel run"

Here is the code snippet and the fmt.Println("init.go init()...") executes only after request to a web page not after the "revel run" command.

If it is expected behavior could you please explain how can I initialize the DB connection exactly after revel run command.
```

func init() {
	fmt.Println("init.go init()...")
	// Filters is the default set of global filters.
	revel.Filters = []revel.Filter{
		revel.PanicFilter,             // Recover from panics and display an error page instead.
		revel.RouterFilter,            // Use the routing table to select the right Action
		revel.FilterConfiguringFilter, // A hook for adding or removing per-Action filters.
		revel.ParamsFilter,            // Parse parameters into Controller.Params.
		revel.SessionFilter,           // Restore and write the session cookie.
		revel.FlashFilter,             // Restore and write the flash cookie.
		revel.ValidationFilter,        // Restore kept validation errors and save new ones from cookie.
		revel.I18nFilter,              // Resolve the requested language
		HeaderFilter,                  // Add some security based headers
		revel.InterceptorFilter,       // Run interceptors around the action.
		revel.CompressFilter,          // Compress the result.
		revel.ActionInvoker,           // Invoke the action.
	}

	// register startup functions with OnAppStart
	// ( order dependent )
	revel.OnAppStart(models.InitDB)
	// revel.OnAppStart(FillCache)
}
```

**Comment by ehenry2172** [comment]
Hi Leshax,

I'm new to using this project, so I can't speak to the details, but I just got my db connection up and running according to their well documented example [here](https://revel.github.io/manual/database.html). If you are still having trouble, could you post your InitDB function? The problem I had initially was that I used the dynamic typing " := " operator to initialize my DB pointer, so it wasn't exporting globally. Here is an example of my working code: https://gist.github.com/ehenry2172/d8e7e5bb5f85ed3e966bcceb2c56783f

**Comment by pedromorgan** [comment]
revel run launched the "harness", so its correct behaviour, eg with "watch" enabled
