### ISSUE TITLE
Unable to download revel

### ISSUE THREAD

**Issue by subbu05** [revel/revel#1120]
`go get -u github.com/revel/cmd/revel

# cd .; git clone https://gopkg.in/fsnotify.v1 /Users/sumalepa/go/src/gopkg.in/fsnotify.v1
Cloning into '/Users/sumalepa/go/src/gopkg.in/fsnotify.v1'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/fsnotify.v1: exit status 128
`

**Comment by Steve-hyas** [comment]
It could be your country is blocking the url https://gopkg.in/fsnotify.v1 , can you navigate to that address ?

**Comment by notzippy** [comment]
It could be your country is blocking the url https://gopkg.in/fsnotify.v1 , can you navigate to that address ?

**Comment by torden** [comment]
it could be your ISP(or network security guy) or Company is blocking the that url, please open a URI your browser.
