### ISSUE TITLE
SSE server

### ISSUE THREAD

**Issue by skitoo** [revel/revel#1121]
Hello,

Thanks for your work.

I want to use [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) system with Revel but I don't see SSE feature in documentation.

How can I use it ? 

Thank you.

**Comment by notzippy** [comment]
There is no internal package that supports eventsource, however there are some libraries available for go which you can use to implement it like this [one](https://github.com/antage/eventsource). I havent used this one but I think you can call the  `EventSource.ServeHTTP(resp http.ResponseWriter, req *http.Request) ` from the revel controller.

**Comment by dudochkin-victor** [comment]
here some details to SSE
https://gist.github.com/dudochkin-victor/ae59ac05efef78f1a0250de69ca08300
