### ISSUE TITLE
"revel new" does not work on my Windows 8.0

### ISSUE THREAD

**Issue by SirGordon** [revel/revel#1131]
Hello!
I'm new to go and revel, I tried the command
`revel new github.com/myaccount/my-app`
as [the main page](https://github.com/revel/revel) advises

> Error Abort: "could not create a Revel application outside of gopath"

What does this mean and how can I fix it?
Thank you!

**Comment by SirGordon** [comment]
Ah, i just needed to change my path to something inside gopath

**Comment by victorcastro** [comment]
How did you fix it? 

Details please

**Comment by notzippy** [comment]
Assuming your GOPATH is `c:\GOPATH` then you need to 
```
cd c:\GOPATH
revel new mycompany.com/myapp
```
