### ISSUE TITLE
undefined: config.DefaultSection in the develop branch

### ISSUE THREAD

**Issue by funyug** [revel/revel#1132]
While running the example project chat with the develop branch of revel, I am getting this error

undefined: config.DefaultSection

which means a change that has been merged is breaking old projects.

Chat project works fine with the master branch.

**Comment by notzippy** [comment]
This means you have not checked out the revel/config project on the develop branch

**Comment by funyug** [comment]
Oh sorry. My mistake. Is there a doc where i can know which all repos should be checked out for this to work? I ran into another undefined variable error after checking out config

**Comment by notzippy** [comment]
What I do is look at my gopath and anything under `src/github.com/revel` I switch to develop
