### ISSUE TITLE
New Relic Support

### ISSUE THREAD

**Issue by Fyb3roptik** [revel/revel#1134]
New Relic has finally brought a Go APM to market. Can we please get a library or some way of integrating it with revel?

https://github.com/newrelic/go-agent/blob/master/GUIDE.md

**Comment by notzippy** [comment]
Sounds like a good idea, using a module with a filter would be a good way of creating a generic implementation.

**Comment by notzippy** [comment]
So basically you would like to see an [application](https://github.com/newrelic/go-agent/blob/master/application.go) exposed through the revel API ?

**Comment by Fyb3roptik** [comment]
Right. I would like a way for all transactions through revel (http, database, etc) to be passed to NewRelic via their go agent if I add the api key to config. Not sure if that is doable but would be the best solution.

**Comment by notzippy** [comment]
Should be doable, we are looking at making the webengine pluggable so a module could be written with this intent. I will update this thread when I have more specifics

**Comment by notzippy** [comment]
Just an update, I have it working.

**Comment by notzippy** [comment]
![image](https://cloud.githubusercontent.com/assets/1387526/24561261/f2a58cb4-15fa-11e7-9d1b-74aa7a39a75f.png)

**Comment by Fyb3roptik** [comment]
Yes please!!! Thanks!

**Comment by notzippy** [comment]
Sample code to implement with current version of revel.
```
func init() {
config = newrelic.NewConfig("Unknown Application", " Unknown Key ")
app = 	app, err := newrelic.NewApplication(*config)
     RelicFilter = func(c *revel.Controller, fc []revel.Filter) {
     txn := app.StartTransaction(c.Action, c.Response.Out, c.Request)
     defer txn.End()
     fc[0](c, fc[1:]) // Execute the next filter stage.
}

	revel.Filters = []revel.Filter{
                RelicFilter,
		revel.PanicFilter,             // Recover from panics and display an error page instead.
		revel.RouterFilter,            // Use the routing table to select the right Action
		revel.FilterConfiguringFilter, // A hook for adding or removing per-Action filters.
		revel.ParamsFilter,            // Parse parameters into Controller.Params.
		revel.SessionFilter,           // Restore and write the session cookie.
		revel.FlashFilter,             // Restore and write the flash cookie.
		revel.ValidationFilter,        // Restore kept validation errors and save new ones from cookie.
		revel.I18nFilter,              // Resolve the requested language
		revel.InterceptorFilter,       // Run interceptors around the action.
		revel.CompressFilter,          // Compress the result.
		revel.ActionInvoker,           // Invoke the action.
	}
}

```

This is some rough (untested) code based on the server engine implmentation [here](https://github.com/notzippy/revel-modules/blob/server-engine/server-engine/newrelic/server-newrelic.go)

**Comment by Fyb3roptik** [comment]
Here is the tested working code!
`
func init() {

	config := newrelic.NewConfig(os.Getenv("NEWRELIC_APP_NAME"), os.Getenv("NEWRELIC_LICENSE"))
	app, _ := newrelic.NewApplication(config) // TODO Error check !!!
	RelicFilter := func(c *revel.Controller, fc []revel.Filter) {
	  txn := app.StartTransaction(c.Action, c.Response.Out, c.Request.Request)
	  defer txn.End()
	  fc[0](c, fc[1:]) // Execute the next filter stage.
	}

	// Filters is the default set of global filters.
	revel.Filters = []revel.Filter{
		RelicFilter,
		OptionsFilter,
		filters.FilterForApiDoc,
		revel.PanicFilter,             // Recover from panics and display an error page instead.
		revel.RouterFilter,            // Use the routing table to select the right Action
		revel.FilterConfiguringFilter, // A hook for adding or removing per-Action filters.
		revel.ParamsFilter,            // Parse parameters into Controller.Params.
		revel.SessionFilter,           // Restore and write the session cookie.
		revel.FlashFilter,             // Restore and write the flash cookie.
		revel.ValidationFilter,        // Restore kept validation errors and save new ones from cookie.
		revel.I18nFilter,              // Resolve the requested language
		HeaderFilter,                  // Add some security based headers
		CacheControlFilter,            // Add cache control headers
		revel.InterceptorFilter,       // Run interceptors around the action.
		revel.CompressFilter,          // Compress the result.
		revel.ActionInvoker,           // Invoke the action.
	}



	revel.OnAppStart(startupFunctions)
}
`

**Comment by notzippy** [comment]
Nice ! Good to see this is working for you now

**Comment by ismaelvacco** [comment]
Here to show the Action did that:

func init() {
	config := newrelic.NewConfig(os.Getenv("NEWRELIC_APP_NAME"), os.Getenv("NEWRELIC_LICENSE"))
	app, _ := newrelic.NewApplication(config) // TODO Error check !!!
	RelicFilter := func(c *revel.Controller, fc []revel.Filter) {
		txn := app.StartTransaction(c.Action, c.Response.Out, c.Request.Request)
		defer txn.End()
		fc[0](c, fc[1:]) // Execute the next filter stage.
	}

	// Filters is the default set of global filters.
	revel.Filters = []revel.Filter{
		revel.PanicFilter,  // Recover from panics and display an error page instead.
		revel.RouterFilter, // Use the routing table to select the right Action
		RelicFilter,
		revel.FilterConfiguringFilter, // A hook for adding or removing per-Action filters.
		revel.ParamsFilter,            // Parse parameters into Controller.Params.
		// revel.SessionFilter,           // Restore and write the session cookie.
		// revel.FlashFilter,             // Restore and write the flash cookie.
		revel.ValidationFilter, // Restore kept validation errors and save new ones from cookie.
		// revel.I18nFilter,        // Resolve the requested language
		HeaderFilter,            // Add some security based headers
		revel.InterceptorFilter, // Run interceptors around the action.
		revel.CompressFilter,    // Compress the result.
		revel.ActionInvoker,     // Invoke the action.
	}

	// register startup functions with OnAppStart
	// revel.DevMode and revel.RunMode only work inside of OnAppStart. See Example Startup Script
	// ( order dependent )
	// revel.OnAppStart(ExampleStartupScript)
	revel.OnAppStart(InitDB)
	// revel.OnAppStart(FillCache)
}

**Comment by jonathanbrenman** [comment]
Hey! Is not working the solution "": 
Go Compilation Error (in app/init.go:59): cannot use c.Response.Out (type revel.OutResponse) as type http.ResponseWriter in argument to app.StartTransaction:"

**Comment by notzippy** [comment]
You should use the newrelic http engine
http://revel.github.io/modules/server-engine-newrelic.html

**Comment by jonathanbrenman** [comment]
Hi notzippy, do you have more info?
This is not enough to setup newrelic in revel.

I'm trying to add newrelic apm to revel and record the transactions.
When I add the lines on the documentation that you wrote me I receive:

> 
> Revel executing: run a Revel application
> INFO  13:31:48    app     run.go:26: Running revel server                      
> CRIT  13:31:48  revel  panic.go:522: Recovered error in startup                error="Server Engine newrelic Not found" 
> panic: Server Engine newrelic Not found [recovered]
> 	panic: Fatal error in startup
>

**Comment by notzippy** [comment]
What version of Revel are you using ? does you app.conf contain the following ?

    module.newrelic = github.com/revel/modules/server-engine/newrelic
    server.engine=newrelic

**Comment by jonathanbrenman** [comment]
Revel executing: displays the Revel Framework and Go version
Revel Framework	:	0.21.0	(0.21.0 remote master branch)
Revel Cmd	:	0.21.1	(0.21.1 remote master branch)
Revel Modules	:	0.21.0	(0.21.0 remote master branch)
