### ISSUE TITLE
Auto route method to controller action

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#1139]
I'd like to be able to define a route that translates all HTTP methods to controller actions based on convention like:
```
* /api/sessions Sessions
```

instead of having to list out GET, POST, PUT, DELETE, etc.

**Comment by notzippy** [comment]
It should be working that way, see manual here http://revel.github.io/manual/routing.html
Can you confirm this does not work ?

**Comment by notzippy** [comment]
Closing due to no response from reported
