### ISSUE TITLE
Templating engine strips HTML comments, even in dev mode

### ISSUE THREAD

**Issue by noway** [revel/revel#1144]
1. `revel new bug`
2. Copypaste this in views/App/Index.html:
```
<!--
    <span>Test</span>
-->
```
3. `revel run bug`
4. See `view-source:http://localhost:9000/`. The comment is not present in the rendered HTML.

I do understand that having comments in the rendered HTML is unfavored in production run cases. But it should be possible to set up this behaviour for development runs.

There seems to be no option corresponding to tweaking this behaviour in `app.conf`. 
```
# Pretty print JSON/XML when calling RenderJson/RenderXml
results.pretty = false
```
was the closest one, but it doesn't affect this.

**Comment by notzippy** [comment]
The GO Template engine uses html/template to render the content on the page. That parser strips html comments from the content. [see here](https://github.com/golang/go/blob/master/src/html/template/html.go#L258) The reasoning behind this is [here](https://groups.google.com/forum/#!msg/golang-nuts/8y6by6SERyU/XQRnbw3aBhwJ) you can use a custom function to protect your inline comment to resolve this

**Comment by Steve-hyas** [comment]
Example https://play.golang.org/p/7l7UywD20B

**Comment by notzippy** [comment]
Revel provides the `raw` tag to do this, see this for an example : https://play.golang.org/p/7l7UywD20B

**Comment by Steve-hyas** [comment]
This is a better example https://play.golang.org/p/GOm-Myv3z5

**Comment by noway** [comment]
Okay, this makes sense, thanks!
