### ISSUE TITLE
Validator Ideas

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#1148]
I am looking 
- at the manual https://revel.github.io/manual/validation.html
- and the godocs https://godoc.org/github.com/revel/revel#Validation

And also at Qt (yes gui but same idea)
- http://doc.qt.io/qt-4.8/qvalidator.htm

So Maybe implementing FixUp() and a Validate() method would be simpler..

**Comment by pedromorgan** [comment]
Cross ref https://github.com/revel/revel/pull/1114

**Comment by pedromorgan** [comment]
https://github.com/revel/revel/pull/998

**Comment by notzippy** [comment]
Implemented
