### ISSUE TITLE
Error after updating to go 1.8 "-X flag requires argument of the form importpath.name=value"

### ISSUE THREAD

**Issue by kekeoki** [revel/revel#1149]
```
ERROR 2017/03/22 17:13:03 build.go:102: # pdd-go/app/tmp
/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64/link: -X flag requires argument of the form importpath.name=value

ERROR 2017/03/22 17:13:03 build.go:302: Failed to parse build errors:
 # pdd-go/app/tmp
/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64/link: -X flag requires argument of the form importpath.name=value
```

**Comment by xiaozi0lei** [comment]
@kekeoki Hi, kekeoki. Could you check the version of `revel-cmd`?
In my experience, I met this error message when I use the revel command version is less than `0.14.0`.
I guess the reason maybe go1.8 build command `-X` option is changed the format.

```bash
# revel v0.13.0 revel/cmd/harness/build.go #80
versionLinkerFlags := fmt.Sprintf("-X %s/app.APP_VERSION \"%s\"", revel.ImportPath, appVersi    on)

# revel v0.14.1 revel/cmd/harness/build.go #87
versionLinkerFlags := fmt.Sprintf("-X %s/app.AppVersion=%s -X %s/app.BuildTime=%s",
revel.ImportPath, appVersion, revel.ImportPath, buildTime)
```
revel v0.13.0 revel/cmd/harness/build.go [Github link](https://github.com/revel/cmd/blob/v0.13.0/harness/build.go#L80)

revel v0.14.1 revel/cmd/harness/build.go [Github link](https://github.com/revel/cmd/blob/v0.14.1/harness/build.go#L87)

The difference is that there is `=` character between `app.AppVersion=%s` in `v0.14.1`. This is satisfied go1.8 format. I guess. You can try it. This is solve my problem, but I recommand you to update the revel cmd version to `v0.14.1`.

Any question, please feel free to contact me.

**Comment by notzippy** [comment]
Think this fixes the issue https://github.com/revel/cmd/pull/86
