### ISSUE TITLE
Error in installing revel: undefined: config.DEFAULT_SECTION

### ISSUE THREAD

**Issue by paritosh90** [revel/revel#1152]
Hi,
I am installing revel using <a href="https://github.com/dkulchenko/bunch.git">Bunch </a>.
I am getting below error:

> installing github.com/revel/revel ... 2017/03/27 13:49:41 failed installing packages: failed building package github.com/revel/revel, error: # github.com/revel/revel
> ./revel.go:180: undefined: config.DEFAULT_SECTION
> , output: %!s(MISSING): exit status 2 [exit status 2 github.com/dkulchenko/bunch/packages.go:234: failed building package github.com/revel/revel, error: # github.com/revel/revel
> ./revel.go:180: undefined: config.DEFAULT_SECTION
> , output: %!s(MISSING) github.com/dkulchenko/bunch/packages.go:643: ]

Please help me with this and let me know how to resolve this problem.

Below is how my BunchFile look:
> github.com/dkulchenko/bunch !self
> 
> github.com/robfig/config
> github.com/revel/revel v0.13.0
> github.com/revel/cmd/revel v0.13.0
> github.com/janekolszak/revmgo
> github.com/afex/hystrix-go/hystrix
> github.com/remind101/newrelic

**Comment by dandee** [comment]
I've got the same error while using Glide and performing update after bumping up revel's version number. I fixed it by manually removing revel directories and letting Glide download them again fresh.

**Comment by notzippy** [comment]
Yes, there was a new release, which means that all packages under github.com/revel needs to be updated. This was a breaking release (some code changes may be required), you can read about the changes here https://github.com/revel/revel/releases
