### ISSUE TITLE
has no field or method Url

### ISSUE THREAD

**Issue by yazamiko** [revel/revel#1159]
I run my code with no error in my localhost, but when I try to run on docker container I get this error:

INFO  2017/04/05 11:23:50 revel.go:365: Loaded module static
INFO  2017/04/05 11:23:50 revel.go:365: Loaded module testrunner
INFO  2017/04/05 11:23:50 revel.go:230: Initialized Revel v0.13.1 (2016-06-06) for >= go1.4
INFO  2017/04/05 11:23:50 run.go:57: Running atendimento-go (atendimento-go) in dev mode
INFO  2017/04/05 11:23:51 harness.go:170: Listening on :9000
INFO  2017/04/05 11:24:02 build.go:179: Cleaning dir tmp
INFO  2017/04/05 11:24:02 build.go:179: Cleaning dir routes
INFO  2017/04/05 11:24:05 build.go:179: Cleaning dir tmp
INFO  2017/04/05 11:24:05 build.go:179: Cleaning dir routes
ERROR 2017/04/05 11:24:25 build.go:108: # atendimento-go/app/routes
app/routes/routes.go:15: revel.MainRouter.Reverse("App.NotFound", args).Url undefined (type *revel.ActionDefinition has no field or method Url, but does have URL)
app/routes/routes.go:22: revel.MainRouter.Reverse("App.ResetExpirationTime", args).Url undefined (type *revel.ActionDefinition has no field or method Url, but does have URL)
app/routes/routes.go:29: revel.MainRouter.Reverse("App.ServiceExpirationTime", args).Url undefined (type *revel.ActionDefinition has no field or method Url, but does have URL)
app/routes/routes.go:36: revel.MainRouter.Reverse("App.Authenticate", args).Url undefined (type *revel.ActionDefinition has no field or method Url, but does have URL)
app/routes/routes.go:43: revel.MainRouter.Reverse("App.Login", args).Url undefined (type *revel.ActionDefinition has no field or method Url, but does have URL)
app/routes/routes.go:50: revel.MainRouter.Reverse("App.Logout", args).Url undefined (type *revel.ActionDefinition has no field or method Url, but does have URL)
app/routes/routes.go:57: revel.MainRouter.Reverse("App.Denied", args).Url undefined (type *revel.ActionDefinition has no field or method Url, but does have URL)
app/routes/routes.go:64: revel.MainRouter.Reverse("App.ForgottenPass", args).Url undefined (type *revel.ActionDefinition has no field or method Url, but does have URL)
app/routes/routes.go:71: revel.MainRouter.Reverse("App.ResetPassword", args).Url undefined (type *revel.ActionDefinition has no field or method Url, but does have URL)
app/routes/routes.go:78: revel.MainRouter.Reverse("App.SendResetLink", args).Url undefined (type *revel.ActionDefinition has no field or method Url, but does have URL)

I have no idea what it can be, because this code is auto generated.

**Comment by runner-mei** [comment]
update github.com/revel/cmd ?

**Comment by notzippy** [comment]
Yes, do a go get -u GitHub.com/revel/cmd

**Comment by xiaozi0lei** [comment]
As the before comments said, you should update the revel/cmd repo to v0.14.0.
I think the revel/revel version should be v0.14.0 in the official docker revel build.
This revel/revel version needs the same version with revel/cmd. 
In the mean time, you should update your project revel variables based on [v0.14.0 release note](https://github.com/revel/revel/releases/tag/v0.14.0).

Good luck!

**Comment by pault84** [comment]
I tried above solution, did nothing. i've actually blown away revel and repulled the repo.
still running into that error.

**Comment by yazamiko** [comment]
It works for me, guys. Thank you!
