### ISSUE TITLE
Controller has no field or method RenderJson

### ISSUE THREAD

**Issue by galasky** [revel/revel#1160]
My code works fine on my Windows 10, but when I try to run my revel project on a mac sierra 10.12.4 I got this error for all my controllers : 

a.RenderJson undefined (type *Analytics has no field or method RenderJson)

What's happen please ?

**Comment by runner-mei** [comment]
Changes since v0.13.0
Breaking Changes

    revel/revel:
        change RenderArgs to ViewArgs PR #1135
        change RenderJson to RenderJSON PR #1057
        change RenderHtml to RenderHTML PR #1057
        change RenderXml to RenderXML PR #1057

**Comment by galasky** [comment]
Ok thx !
