### ISSUE TITLE
Some methods and fields undefined on the compiling.

### ISSUE THREAD

**Issue by eloyucu** [revel/revel#1163]
Hello everyone.  

I am finding this stack of errors when I try to compile an app:

```
Counting objects: 25, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (25/25), done.
Writing objects: 100% (25/25), 16.64 KiB | 0 bytes/s, done.
Total 25 (delta 19), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Revel app detected
remote: -----> Using go1.4
remote: -----> Running: go get -tags heroku ./...
remote: # ndc-console-test/app/controllers
remote: app/controllers/app.go:160: c.RenderJson undefined (type App has no field or method RenderJson)
remote: app/controllers/app.go:170: c.RenderArgs undefined (type App has no field or method RenderArgs)
remote: app/controllers/app.go:171: c.RenderArgs undefined (type App has no field or method RenderArgs)
remote: app/controllers/app.go:172: c.RenderArgs undefined (type App has no field or method RenderArgs)
remote: app/controllers/app.go:173: c.RenderArgs undefined (type App has no field or method RenderArgs)
remote: app/controllers/app.go:191: c.RenderArgs undefined (type App has no field or method RenderArgs)
remote: app/controllers/app.go:192: c.RenderArgs undefined (type App has no field or method RenderArgs)
remote: app/controllers/app.go:193: c.RenderArgs undefined (type App has no field or method RenderArgs)
remote: app/controllers/app.go:194: c.RenderArgs undefined (type App has no field or method RenderArgs)
remote: app/controllers/app.go:195: c.RenderArgs undefined (type App has no field or method RenderArgs)
remote: app/controllers/app.go:195: too many errors
remote: # ndc-console-test/app/routes
remote: app/routes/routes.go:15: revel.MainRouter.Reverse("App.Index", args).Url undefined (type *revel.ActionDefinition has no field or method Url)
remote: app/routes/routes.go:22: revel.MainRouter.Reverse("App.Ndc", args).Url undefined (type *revel.ActionDefinition has no field or method Url)
remote: app/routes/routes.go:29: revel.MainRouter.Reverse("App.FlightPrice", args).Url undefined (type *revel.ActionDefinition has no field or method Url)
remote: app/routes/routes.go:36: revel.MainRouter.Reverse("App.SeatAvailability", args).Url undefined (type *revel.ActionDefinition has no field or method Url)
remote: app/routes/routes.go:43: revel.MainRouter.Reverse("App.OrderCreateRQ", args).Url undefined (type *revel.ActionDefinition has no field or method Url)
remote: app/routes/routes.go:50: revel.MainRouter.Reverse("App.ServicePrice", args).Url undefined (type *revel.ActionDefinition has no field or method Url)
remote: app/routes/routes.go:57: revel.MainRouter.Reverse("App.OrderRetrieve", args).Url undefined (type *revel.ActionDefinition has no field or method Url)
remote: app/routes/routes.go:64: revel.MainRouter.Reverse("App.OrderChange", args).Url undefined (type *revel.ActionDefinition has no field or method Url)
remote: app/routes/routes.go:71: revel.MainRouter.Reverse("App.OrderCancel", args).Url undefined (type *revel.ActionDefinition has no field or method Url)
remote: app/routes/routes.go:83: revel.MainRouter.Reverse("TestRunner.Index", args).Url undefined (type *revel.ActionDefinition has no field or method Url)
remote: app/routes/routes.go:83: too many errors
remote:  !     Push rejected, failed to compile Revel app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to ndc-console.
```
This compilation is not local... this is the output when I run `git push heroku master`. It was working two months ago on my last push. The code I change today has nothing to do with the files where the problems are found... in fact I never touch the `app/routes/routes.go` file. The code is working locally and the buildpack is added in the heroku project.

VERSIONS
-----------
One of the things I think is that maybe the differents revel version are causing these errors. I have installed 0.13.1V and the last release is 0.14.0 (just less than two months ago, when I did my last push)...
So my question is... is there any way to upload revel from the command line?? or do I need to remove and resinstall?? in this case... how to uninstall revel??

Thank you.

**Comment by notzippy** [comment]
Update is best

`go get -u github.com/revel/cmd/revel`

If you want to "uninstall" find `$GOPATH/src/github.com/revel` and delete it, 
But that update statement should do it for you.

**Comment by eloyucu** [comment]
OK!! no... thanks I want to update.

**Comment by notzippy** [comment]
Cool, that should do it for you then. We are trying to push out new releases on the first day of Tuesday of every month now.

**Comment by eloyucu** [comment]
Thanks. Finally I solved the problem.

**Comment by goors** [comment]
I have save problem:

`Failed to build app: Go Compilation Error (in ../immoreal/app/controllers/app.go:46): c.RenderArgs undefined (type App has no field or method RenderArgs)`

go 1.8 and latest revel on Linux server(on OSX it works ok).

**Comment by eloyucu** [comment]
Change the version. It is the solution. :)

**Comment by eloyucu** [comment]
http://stackoverflow.com/questions/43609169/revel-app-doesn%C2%B4t-compile-in-heroku

**Comment by notzippy** [comment]
Sorry, I should have seen that as well. The commenter is right though, those method signatures were changed... Sorry

**Comment by goors** [comment]
Hi, i do not know why would someone go on and change RenderArgs -> ViewArgs. Just stupid. Now i have like 10 projects, that need update. Just stupid. Can you please, keep old RenderArgs as well and do another release with that as well?

**Comment by pedromorgan** [comment]
Can we do a "HOT FIX" and make renderArgs() call ViewArgs() ??

**Comment by brendensoares** [comment]
@goors I understand your pain. However, you should be able to easily find and replace [all breaking changes](https://github.com/revel/revel/releases/tag/v0.14.0) in your app code. @shawncatz is working on a `sed` command that you can use...

As far as WHY we renamed it, it is not for nothing. revel/revel#622 shows where the thought began back in 2014. We're looking to add a `Controller.View` to contain template context variables. We're also going to release a new pluggable template engine very soon that has support for multiple template formats and will allow for adding more in the future with ease. See revel/revel#622.

I hope you see the value in the direction we're going. We're also refining our release process to avoid these jarring surprises. We plan to communicate deprecations caused by breaking API changes in advance.

The big picture is that's we're refining Revel's current design now so that we can reach v1.0.0. When we reach v1, we'll ensure that no minor updates have breaking changes.

Thanks for being part of our awesome community!

**Comment by shawncatz** [comment]
@goors quick sed command:

This should work on MacOS or Linux
```
for f in $(find . -type f -name "*.go" | grep -v \/vendor\/); do sed -i.bak 's/RenderArgs/ViewArgs/g' $f; done
```

This will leave .bak versions of every go file it finds, to remove them use the command below.
Guessing you have your code tracked in git, so just be sure it's backed up.
```
find . -type f -name "*.bak" | xargs rm
```
