### ISSUE TITLE
autoload .env environment variables into app.conf

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#1168]
Inject environment variables into the running app like ruby dotenv so that you can manage common environment variables outside of source control.

**Comment by notzippy** [comment]
This should be under the revel/cmd I think.
That said I have done this in the past by placing a config value in the [dev] or [prod] section, and using that as a path to load up the localconfig for server specific values... So for [dev] it would be `./server_config.conf` and for [prod] `../../../../server_config.conf` (one level up from the application install folder)

Personally not a big fan of environment variables..

**Comment by brendensoares** [comment]
The key is having local config that does not track sensitive information in version control. Whether you use env vars or other means is an implementation detail.

i would say env vars are an extremely common approach and it would be good to clearly support it in Revel, perhaps even listing multiple solutions (like your `*.conf` file).

**Comment by notzippy** [comment]
Are you thinking of changing the config so it would default to the https://golang.org/pkg/os/#Getenv if it was available ?
```
func (c *Config) Int(section string, option string) (value int, err error) {
         sv,err := os.Getenv(option), nil.(error)
	if sv=="" {
           sv, err = c.String(section, option)
        }
	if err == nil {
		value, err = strconv.Atoi(sv)
	}

	return value, err
}
```

**Comment by notzippy** [comment]
Reference https://github.com/revel/revel/issues/391

**Comment by notzippy** [comment]
What do you think of embedding the example above  @brendensoares ? Maybe that with an option to turn it on in the app.conf ?

**Comment by notzippy** [comment]
Closing due to no response

**Comment by brendensoares** [comment]
I think the core issue is getting the OS environment variables into our config through Revel instead of a 3rd party tool.

Environment variables are so widespread that it's poor form not to enable their easy use. For example, AWS allows config values for Elastic Beanstalk apps via env vars.

`.env` file is a common convention in other dev environments that we should support. It's not a must, but it would be nice.

**Comment by notzippy** [comment]
But we do enable their use, this will use the environments variable `CHAT_DB_DRIVER`

    db.driver = ${CHAT_DB_DRIVER}

**Comment by notzippy** [comment]
Already implemented, closing
