### ISSUE TITLE
init in filter is not executing

### ISSUE THREAD

**Issue by goors** [revel/revel#1169]
Hi

not sure that this is issue but my init function in filter is not executing at all:

```
package filter
func init(){
    log.Println("initialising ....")
}
func SomeFilter(c *revel.Controller, fc []revel.Filter) {
	fc[0](c, fc[1:])
       //some code here
}
```

and in init.go i have:

```
revel.Filters = []revel.Filter{
		....
		filter.SomeFilter,// Some filter
		
}
```
`initialising` is never printed.

**Comment by notzippy** [comment]
`init` functions are not run as part of revel, the are a golang command see [here](https://golang.org/doc/effective_go.html#init)
