### ISSUE TITLE
Use casbin as the authorization plugin for revel

### ISSUE THREAD

**Issue by hsluoyz** [revel/revel#1176]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

I saw revel has a modules project [here](https://github.com/revel/modules). So what do you think by adding casbin as an authorization module? Thanks!

**Comment by notzippy** [comment]
Thankyou for your suggestion, we will discuss this and have a look into it.

**Comment by hsluoyz** [comment]
Hi,

I already made an example plugin here: https://github.com/casbin/revel-authz. Hope it can help:)

**Comment by notzippy** [comment]
We would put it in the modules folder - i see there is already an open PR there for it. If you could integrate it to use the GORM module that would be good revel/modules#42 . I would thing it should be in the revel/modules/auth/casbin  thanks
Steve

**Comment by hsluoyz** [comment]
Hi @notzippy ,

I have used Gorm for the policy storage of the Casbin module. Please review the PR: https://github.com/revel/modules/pull/47
