### ISSUE TITLE
revel/harness: app died

### ISSUE THREAD

**Issue by kikanny** [revel/revel#1177]
Our server code was working fine and all of sudden all I'm getting is "App failed to start up
revel/harness: app died." I didn't make any change to the code. I've tried reinstalling revel but that didn't work. I've tried doing a fresh pull of our server code and that didn't work either. Any ideas would be greatly appreciated!

Just wanna add that the app dies as soon as I run "revel run github.com/myapp" and hit localhost:9000

**Comment by notzippy** [comment]
Any stack Trace in the console window or log files?

**Comment by kikanny** [comment]
Here's the trace
`~
~ revel! http://revel.github.io
~
INFO  2017/05/20 20:59:40 revel.go:365: Loaded module testrunner
INFO  2017/05/20 20:59:40 revel.go:365: Loaded module jobs
INFO  2017/05/20 20:59:40 revel.go:365: Loaded module static
INFO  2017/05/20 20:59:40 revel.go:230: Initialized Revel v0.15.0 (2017-05-11) for >= go1.7
INFO  2017/05/20 20:59:40 run.go:119: Running bookingapp (github.com/mycompany/go-bookingapp) in dev mode
TRACE 2017/05/20 20:59:40 run.go:120: Base path: /Users/admin/go/src/github.com/mycompany/go-bookingapp
TRACE 2017/05/20 20:59:40 run.go:124: Running in watched mode.
TRACE 2017/05/20 20:59:40 template.go:198: Refreshing templates from [/Users/admin/go/src/github.com/revel/revel/templates]
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/403.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/403.json
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/403.txt
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/403.xml
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/404-dev.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/404.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/404.json
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/404.txt
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/404.xml
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/405.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/405.json
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/405.txt
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/405.xml
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/500-dev.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/500.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/500.json
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/500.txt
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/500.xml
INFO  2017/05/20 20:59:40 harness.go:175: Listening on :9000
TRACE 2017/05/20 20:59:46 harness.go:132: Rebuild
INFO  2017/05/20 20:59:46 build.go:192: Cleaning dir tmp
INFO  2017/05/20 20:59:46 build.go:192: Cleaning dir routes
INFO  2017/05/20 20:59:46 build.go:192: Cleaning dir tmp
INFO  2017/05/20 20:59:46 build.go:192: Cleaning dir routes
TRACE 2017/05/20 20:59:46 build.go:171: Exec: [/usr/bin/git --git-dir=/Users/admin/go/src/github.com/mycompany/go-bookingapp/.git describe --always --dirty]
TRACE 2017/05/20 20:59:46 build.go:112: Exec: [/usr/local/bin/go build -i -ldflags -X github.com/mycompany/go-bookingapp/app.AppVersion=git-0fe4449-dirty -X github.com/mycompany/go-bookingapp/app.BuildTime=2017-05-21T00:59:46Z -tags gorp -o /Users/admin/go/bin/revel.d/github.com/mycompany/go-bookingapp/go-bookingapp github.com/mycompany/go-bookingapp/app/tmp]
TRACE 2017/05/20 20:59:48 app.go:63: Exec app: /Users/admin/go/bin/revel.d/github.com/mycompany/go-bookingapp/go-bookingapp [/Users/admin/go/bin/revel.d/github.com/mycompany/go-bookingapp/go-bookingapp -port=52175 -importPath=github.com/mycompany/go-bookingapp -runMode=dev]`

I ended up fixing it though....after reinstalling go 3-4 times.

**Comment by kikanny** [comment]
Here's the trace. I ended up fixing it though....after reinstalling go 3-4 times...
> ~
~ revel! http://revel.github.io
~
INFO  2017/05/20 20:59:40 revel.go:365: Loaded module testrunner
INFO  2017/05/20 20:59:40 revel.go:365: Loaded module jobs
INFO  2017/05/20 20:59:40 revel.go:365: Loaded module static
INFO  2017/05/20 20:59:40 revel.go:230: Initialized Revel v0.15.0 (2017-05-11) for >= go1.7
INFO  2017/05/20 20:59:40 run.go:119: Running bookingapp (github.com/mycompany/go-bookingapp) in dev mode
TRACE 2017/05/20 20:59:40 run.go:120: Base path: /Users/admin/go/src/github.com/mycompany/go-bookingapp
TRACE 2017/05/20 20:59:40 run.go:124: Running in watched mode.
TRACE 2017/05/20 20:59:40 template.go:198: Refreshing templates from [/Users/admin/go/src/github.com/revel/revel/templates]
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/403.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/403.json
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/403.txt
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/403.xml
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/404-dev.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/404.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/404.json
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/404.txt
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/404.xml
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/405.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/405.json
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/405.txt
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/405.xml
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/500-dev.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/500.html
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/500.json
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/500.txt
TRACE 2017/05/20 20:59:40 template.go:256: adding template:  errors/500.xml
INFO  2017/05/20 20:59:40 harness.go:175: Listening on :9000
TRACE 2017/05/20 20:59:46 harness.go:132: Rebuild
INFO  2017/05/20 20:59:46 build.go:192: Cleaning dir tmp
INFO  2017/05/20 20:59:46 build.go:192: Cleaning dir routes
INFO  2017/05/20 20:59:46 build.go:192: Cleaning dir tmp
INFO  2017/05/20 20:59:46 build.go:192: Cleaning dir routes
TRACE 2017/05/20 20:59:46 build.go:171: Exec: [/usr/bin/git --git-dir=/Users/admin/go/src/github.com/mycompany/go-bookingapp/.git describe --always --dirty]
TRACE 2017/05/20 20:59:46 build.go:112: Exec: [/usr/local/bin/go build -i -ldflags -X github.com/mycompany/go-bookingapp/app.AppVersion=git-0fe4449-dirty -X github.com/mycompany/go-bookingapp/app.BuildTime=2017-05-21T00:59:46Z -tags gorp -o /Users/admin/go/bin/revel.d/github.com/mycompany/go-bookingapp/go-bookingapp github.com/mycompany/go-bookingapp/app/tmp]
TRACE 2017/05/20 20:59:48 app.go:63: Exec app: /Users/admin/go/bin/revel.d/github.com/mycompany/go-bookingapp/go-bookingapp [/Users/admin/go/bin/revel.d/github.com/mycompany/go-bookingapp/go-bookingapp -port=52175 -importPath=github.com/mycompany/go-bookingapp -runMode=dev]

**Comment by notzippy** [comment]
Nothing relevant appears in the trace. Reinstalling go basically cleans the GOPATH/pkg GOPATH/bin folders. But it doesn't explain why it was working and then wasn't. 

However if you are running this in a non development environment you should always use the `revel build` command to create a runtime executable, and then copy that to the server and run the executable. This will eliminate the need for any dependencies and also give you a single executable to run. You should never use `revel run`, as (like you saw) will try to run the application through a proxy and not give you meaningful errors if the software is unable to start. See [here](http://revel.github.io/manual/tool.html) for more documentation on the revel command
