### ISSUE TITLE
Change revel.Session from map[string]string to map[string]interface{}?

### ISSUE THREAD

**Issue by Acidic9** [revel/revel#1181]
When using the in-build sessions with Revel, the session type is `map[string]string`.
Is it possible for this to be changed to `map[string]interface{}` to allow any kind of session type?

If this was changed to `map[string]interface{}`, methods could be written for retrieving the basic data types such as `func (s *Session) Int64() int64 { ... }`, etc. 

Maybe this would over complicate things but it's just an idea.
Any thoughts?

**Comment by notzippy** [comment]
The reason for this is that this session data is stored in the form of an
encrypted cookie which is text based. What I have done in the past is to
convert the object to JSON before storing. Of course you need to be mindful
of the size limit of a cookie. If your objects are too large to serialized
with JSON you could store the session data in a database and use the cookie
session to store a reference to the database data. I am looking at ways to
implement this as a module. Hope this helps

Nz

**Comment by pedromorgan** [comment]
So one way am using is to serialise an "interface/struct" to json and back..another used a csv row

Would be neat to look at this, and see if we can add "helper" functions for data, inclucing checking cookie length etc.

**Comment by pedromorgan** [comment]
```
Session.ToJSON("foo")
Session.FromCSV("var")

```

**Comment by Acidic9** [comment]
But I thought the whole point of a session, is that it is not stored as a cookie on the client right? Only one cookie with a session ID is stored correct? Then all the session information is stored on the server-side program.

If I'm right about this, then doesn't it mean there is no restriction to the session value type?

**Comment by notzippy** [comment]
@Acidic9 currently session information is stored in an encrypted cookie, I am working on a way to change this so you can store session data server side (with client cookie reference) or like it currently does.

**Comment by Acidic9** [comment]
Ah it's just en encrypted cookie? Good luck with making it stored server-side. You'd need the data to be written to a file so it can be remembered after server restarts right?

Also I'd be keen to spend some time working on revel if there are any features you'd like done.

**Comment by notzippy** [comment]
With PR #1216 you will be able to store any small object in the session using the [controller.SessionMarshel ](https://github.com/revel/revel/pull/1216/files#diff-e30be89bfd41a0c219178028b9971a32R478-R486) And with this PR you will also be able to make your own [session engine](https://github.com/revel/revel/pull/1216/files#diff-c5e7836d41e9c57707af73eeae48816dR8) by implementing that interface. The idea is that you can then expand upon a cookie based version to a larger version
