### ISSUE TITLE
can't go get revel

### ISSUE THREAD

**Issue by cyongxue** [revel/revel#1182]
➜  GoglandProjects go get github.com/revel/revel
# cd .; git clone https://go.googlesource.com/net /Users/yongxue/GoglandProjects/src/golang.org/x/net
Cloning into '/Users/yongxue/GoglandProjects/src/golang.org/x/net'...
fatal: unable to access 'https://go.googlesource.com/net/': Server aborted the SSL handshake
package golang.org/x/net/websocket: exit status 128
package gopkg.in/fsnotify.v1: unrecognized import path "gopkg.in/fsnotify.v1" (https fetch: Get https://gopkg.in/fsnotify.v1?go-get=1: read tcp 172.17.29.252:59215->45.33.37.13:443: read: operation timed out)
➜  GoglandProjects go get github.com/revel/revel
package golang.org/x/net/websocket: unrecognized import path "golang.org/x/net/websocket" (https fetch: Get https://golang.org/x/net/websocket?go-get=1: net/http: TLS handshake timeout)
package gopkg.in/fsnotify.v1: unrecognized import path "gopkg.in/fsnotify.v1" (https fetch: Get https://gopkg.in/fsnotify.v1?go-get=1: net/http: TLS handshake timeout)
➜  GoglandProjects go get golang.org/x/net/websocket
package golang.org/x/net/websocket: unrecognized import path "golang.org/x/net/websocket" (https fetch: Get https://golang.org/x/net/websocket?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by runner-mei** [comment]
中国人吧，知道防火墙吧，不知道就别做程序员了。

**Comment by notzippy** [comment]
This is a firewall issue, closing for the time being - thanks @runner-mei

**Comment by cyongxue** [comment]
但是，我特意将Shadowsocks的自动代理切换到全局模式了，还是这样：
➜  github.com go get github.com/revel/revel
package golang.org/x/net/websocket: unrecognized import path "golang.org/x/net/websocket" (https fetch: Get https://golang.org/x/net/websocket?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package gopkg.in/fsnotify.v1: unrecognized import path "gopkg.in/fsnotify.v1" (https fetch: Get https://gopkg.in/fsnotify.v1?go-get=1: net/http: TLS handshake timeout)
难道代理也没用？

**Comment by cyongxue** [comment]
但是，我特意将Shadowsocks的自动代理切换到全局模式了，还是这样：
➜ github.com go get github.com/revel/revel
package golang.org/x/net/websocket: unrecognized import path "golang.org/x/net/websocket" (https fetch: Gethttps://golang.org/x/net/websocket?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package gopkg.in/fsnotify.v1: unrecognized import path "gopkg.in/fsnotify.v1" (https fetch: Gethttps://gopkg.in/fsnotify.v1?go-get=1: net/http: TLS handshake timeout)
难道代理也没用？


原始邮件
发件人:runnernotifications@github.com
收件人:revel/revelrevel@noreply.github.com
抄送:小用cyongxue@163.com; Authorauthor@noreply.github.com
发送时间:2017年6月7日(周三) 20:50
主题:Re: [revel/revel] can't go get revel (#1182)


中国人吧，知道防火墙吧，不知道就别做程序员了。

**Comment by wenjoy** [comment]
@cyongxue just use privoxy to enable proxy for iterm/terminal. Shadowsocks doesn't support that.
ps: forget what @runner-mei said. It's GFW's fault not ur's.

**Comment by lujiacn** [comment]
@cyongxue, after set proxy, also need set .ssh/config to make git go through proxy. Check related document for ssh config with proxy.
