### ISSUE TITLE
Rename OnAppStart to OnAppReady

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#1184]
More clear on the purpose of the call.

`init()` functions run when the app starts, but we want to run certain code AFTER the app is ready, not after it starts.

**Comment by brendensoares** [comment]
@notzippy prefers the current naming because it's before the server starts. We need to clarify further.

**Comment by alxkchr** [comment]
With `Before` / `After` instead of interceptors would it make sense to replace `OnAppStart` mechanism by a special first class function that would be invoked automagically? Like:
```go
type Controller struct {
	...
}

func (c *Controller) Before() revel.Result {
	...
}

func (c *Controller) SomeAction() revel.Result {
	...
}

func (c *Controller) After() revel.Result {
	...
}

func Ready() {
	...
}
```

**Comment by brendensoares** [comment]
Sometimes your init code is not related to a particular controller @alxkchr

**Comment by alxkchr** [comment]
That's why it's a function, not a method. Or is you concern that you can have only 1 `Ready` function per package?

**Comment by notzippy** [comment]
What purpose would the `Ready` function perform ?

**Comment by notzippy** [comment]
That couldn't be done by 
```
func init() {
  revel.OnAppStart(Ready)
}
```

**Comment by alxkchr** [comment]
What purpose would the [`Before` / `After` actions](https://github.com/revel/revel/issues/420) perform that couldn't be done by interceptors? That's consistency.

**Comment by ptman** [comment]
revel.OnRevelReady() or revel.OnRevelStart() or revel.OnInit() or revel.OnStart()?

**Comment by notzippy** [comment]
I like `revel.OnReady(func(){})` or `revel.OnStart(func(){})` 

That said, not sure if this is a direly needed feature

**Comment by notzippy** [comment]
Closing this in favor of clearer documentation on the subject
