### ISSUE TITLE
my revel project has not app folder, it is not running

### ISSUE THREAD

**Issue by zondahuman** [revel/revel#1187]
there is revel project,    revel run revel-svr2,  i delete app folder,  tree is:

revel-svr2  
                ---conf
                ---controllers
                ---service
                ---dao

when i run it ,there is error 

$ revel run revel-svr2
~
~ revel! http://revel.github.io
~
Sorted keys module.static
Sorted keys module.testrunner
INFO  2017/06/18 01:32:15 revel.go:410: Loaded module static
INFO  2017/06/18 01:32:15 revel.go:410: Loaded module testrunner
INFO  2017/06/18 01:32:15 revel.go:415: Found testrunner module, adding `tests` path D:\SystemFile\GoWorkspace\src\revel-svr2\tests
INFO  2017/06/18 01:32:15 revel.go:240: Initialized Revel v0.16.0 (2017-06-06) for >= go1.7
INFO  2017/06/18 01:32:15 run.go:119: Running revel-svr2 (revel-svr2) in dev mode
INFO  2017/06/18 01:32:15 template_engine.go:65: init templates: go
ERROR 2017/06/18 01:32:15 watcher.go:77: Failed to stat watched path D:\SystemFile\GoWorkspace\src\revel-svr2\app : GetFileAttributesEx D:\SystemFile\GoWorkspace\src\revel-svr2\app: The system cannot find the file specified.
INFO  2017/06/18 01:32:15 harness.go:175: Listening on :9000
INFO  2017/06/18 01:32:18 build.go:192: Cleaning dir tmp
INFO  2017/06/18 01:32:18 build.go:192: Cleaning dir routes
INFO  2017/06/18 01:32:18 build.go:192: Cleaning dir tmp
ERROR 2017/06/18 01:32:18 build.go:240: Failed to make 'tmp' directory: mkdir D:\SystemFile\GoWorkspace\src\revel-svr2\app\tmp: The system cannot find the path specified.

if myproject revel-svr2 has not app folder,   it is not running ?

**Comment by notzippy** [comment]
Revel expects an app folder with the controllers folder inside it. See [here](http://revel.github.io/manual/organization.html) to see how the folder structure should be laid out.
