### ISSUE TITLE
Fatal error: concurrent map writes - goroutine

### ISSUE THREAD

**Issue by alexfromvl** [revel/revel#1188]
I use testing of the created site through WRK:

`wrk -t1 -c3 -d10S --latency "http://127.0.0.1/"`

And every time after a few seconds after starting the test I get an error:

```
fatal error: concurrent map read and map write

goroutine 27677 [running]:
runtime.throw(0x8a54ce, 0x21) 
...

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f48b9b00f00, 0x72, 0x0)
...

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
...

goroutine 28027 [IO wait]:
net.runtime_pollWait(0x7f48b9b00e40, 0x72, 0x7)
...

```

Is it possible to avoid this error during testing?

**Comment by notzippy** [comment]
Sorry, this had gotten buried in my email. Is this an app that you have written or are you using one of the example apps ?

**Comment by alexfromvl** [comment]
Hello. The problem arises when using the example [https://revel.github.io/tutorial/firstapp.html](https://revel.github.io/tutorial/firstapp.html) and when creating a simple site from one main page.

By this error I was able to find this discussion[https://stackoverflow.com/questions/36167200/how-safe-are-golang-maps-for-concurrent-read-write-operations](https://stackoverflow.com/questions/36167200/how-safe-are-golang-maps-for-concurrent-read-write-operations). But it's not entirely clear how to rewrite the code so that you do not come to this error?

**Comment by daxorid** [comment]
I have reproduced this, on a production site with normal traffic. 

The templateLoad() function in template.go:332 is extremely concurrency-unfriendly.

I have hacked up a workaround for this by wrapping all accesses of loader.TemplateMap inside Lock/Unlock blocks until such time as the revel people address this.

Hope this helps.

**Comment by notzippy** [comment]
Thanks, PR #1205 should resolve this issue

**Comment by runner-mei** [comment]
PR #1205 is not resolve this issue

**Comment by notzippy** [comment]
Thanks @runner-mei , I had thought that maps with multiple read access was OK and writes required synchronized access. It appears I would need to use a `sync.RWMutex` for reading and writing to the map. I will update this PR with that which should make it functionally the same as yours.

**Comment by notzippy** [comment]
@runner-mei I have created a new PR to address the issue further - I think there may have also been a basic flaw with the previous PR where the save map values were never used. Please checkout #1223

**Comment by runner-mei** [comment]
https://github.com/revel/revel/pull/1223 may have also been a little flaw.


engine.Lookup will concurrency issue while invoke TemplateLoader.Refresh(), but it is unimportance.
````go
				if tmpl = engine.Lookup(langName); tmpl != nil {
					found = true
					break
				}
				if tmpl = engine.Lookup(name); tmpl != nil {
					found = true
					break
				}
```

**Comment by notzippy** [comment]
Good point @runner-mei  How about I move the mutex locking to the beginning of the else clause [like this](https://github.com/revel/revel/pull/1223/files#diff-4779dc22f7a7835ae9d75daa70021ad8R346) ?

**Comment by runner-mei** [comment]
@notzippy #1223 may have also been a little flaw.  I has two patch.

version1: https://github.com/runner-mei/revel/commit/1e409652ef865b8227c660444f2abefd07ae809d it is changed base the #1223, but its performance is bad

version2: https://github.com/revel/revel/pull/1225

**Comment by notzippy** [comment]
PR has been merged into develop
