### ISSUE TITLE
Controller.RenderJSON throws error

### ISSUE THREAD

**Issue by Huholoman** [revel/revel#1190]
Hello,
i did some search in issues and in code, but I didnt find anythink what could help me.

This is my code
```
func (this *Foo) Boo() {

	data := map[string]interface{}{
		"yaya": "blabla",
		"blabla": "yaya",
	}

	return this.RenderJson(data)
}
```

I think, it should be ok.. I even found similar code in some issue here, but my code still throws me this error
```
ERROR 2017/07/03 22:31:56 build.go:119: # remembrall/app/controllers
app/controllers/app.go:19: too many arguments to return
	have (revel.Result)
	want ()

```

Can anyone help me, please?

Thanks,
Tobias

**Comment by notzippy** [comment]
The first line should be

func (this *Foo) Boo() *revel.Result {

**Comment by Huholoman** [comment]
Yay, of course.. Thanks. :D
