### ISSUE TITLE
Cache forever

### ISSUE THREAD

**Issue by DaniloPolani** [revel/revel#1192]
Following the docs, to set an item to forever (I'm using redis) we need to use `go cache.Set(key, value, cache.FOREVER)`, but it throws the error `undefined: "github.com/revel/revel/cache".FOREVER"`, I think it's useless to import go-cache only to get **cache.noExpiration**.

A question: why `go` is required in front of the command?

PS: With a fresh install, when I tried to use cache with redis, **go-cache** and **redigo/redis** were not present, I don't know if it's a bug or it's impossible to automatically get go packages when installing revel.

**Comment by notzippy** [comment]
Sorry you found another manual issue, the correct values for cache are 
* DefaultExpiryTime
* ForEverNeverExpiry

The reason the "go" command is used is to offload the work to another thread, so the current thread doesn't need to wait for the cache to be added.
