### ISSUE TITLE
Unsopported default language

### ISSUE THREAD

**Issue by DaniloPolani** [revel/revel#1196]
I'm trying to translate messages, but the string is never found. I specified as default language in app.conf "it", with `i18n.default_language = it`. This is my structure:

```
app/
    messages/
        user.it
```

And the content of user.it:

```
user_not_found=User not found.
wrong_credentials=Wrong credentials.
```

Then in my controller I try to retrieve the message with `c.Message("user_not_found")`, but the string is never found. Log (terminal) content:

```
2017/07/07 16:42:46 i18n.go:228: Unable to read locale cookie with name 'REVEL_LANG': http: named cookie not present
2017/07/07 16:42:46 i18n.go:193: Found Accept-Language header value: it-IT
2017/07/07 16:42:46 i18n.go:63: Unsupported language for locale 'it-IT' and message 'user_not_found', trying default language
2017/07/07 16:42:46 i18n.go:66: Using default language 'it'
2017/07/07 16:42:46 i18n.go:70: Unsupported default language for locale 'it' and message 'user_not_found'
```

**Comment by notzippy** [comment]
The messages folder needs to be at the same level as the app folder - see the i18n example app here 
https://github.com/revel/examples/tree/master/i18n

**Comment by DaniloPolani** [comment]
Oh, well thank you, maybe it's better to update the documentation, the structure is wrong: https://revel.github.io/manual/i18n-messages.html

**Comment by notzippy** [comment]
O wow it totally is, thanks for pointing that out .. Sorry about that..

BTW like the goatee

**Comment by DaniloPolani** [comment]
Ahah no problem, I updated the comment, BTW thank you, I like revel, so we are ok I suppose (?) 

Can you check the other issue about cache with no expiration? Thank you!
