### ISSUE TITLE
Dont`t recognize GOPATH if use soft-link

### ISSUE THREAD

**Issue by javasgl** [revel/revel#1197]
In my computer ,  i made a soft-link to my goptah dir like this:
```
ln -s  gopath  ~/the/real/gopath
```
then, when i run `revel new project-name` in `gopath`,
```
cd gopath
revel new project-name
```
it aborted,here is the message:
```
ERROR 2017/07/08 09:07:06 Abort: could not create a Revel application outside of GOPATH.
```
but , when i run this command in the real go path dir , it works~!
```
cd ~/the/real/gopath
revel new project-name
```

**Comment by javasgl** [comment]
@robfig

**Comment by notzippy** [comment]
Yup, I have the same issue - we are working on rewriting the cli and have logged that as an issue https://github.com/revel/cli/issues/1
