### ISSUE TITLE
new version 0.17 template.delimiters invalid

### ISSUE THREAD

**Issue by chengziqing** [revel/revel#1199]
new version 0.16，0.17 template.delimiters invalid
need examples！！！

**Comment by notzippy** [comment]
Do you mean that the template delimiters in the app.conf is not being used ? Can you provide an example ?

thanks

**Comment by notzippy** [comment]
The documentation looks to be wrong, the app.conf should be `template.go.delimiters` not `template.delimiters` , this was changed in v0.16. Closing for now, if this does no resolve your issue please reopen

**Comment by chengziqing** [comment]
func (engine *GoEngine) ParseAndAdd(baseTemplate *TemplateView) error {
--
  | // If alternate delimiters set for the project, change them for this set
  | if engine.splitDelims != nil && baseTemplate.Location() == ViewsPath {
  | engine.templateSet.Delims(engine.splitDelims[0], engine.splitDelims[1])
  | } else {
  | // Reset to default otherwise
  | engine.templateSet.Delims("", "")
  | }

I setting template.go.delimiters,but invalid.
int code "baseTemplate.Location() == ViewsPath" ,not ==.when i debug.  I do not know，What else is set?

**Comment by notzippy** [comment]
If you change that if statement to 
	if engine.splitDelims != nil && strings.Index(baseTemplate.Location(), ViewsPath)>-1 {
does it work ?

**Comment by swrap** [comment]
The delimiters are not being used in the templates.

The following is in my app.conf
~~~
template.delimiters=[[ ]]
template.go.delimiters=[[ ]]
~~~

When I run the application the templates are still is using "{{ }}" as the delimiters.

Version(s):
   Revel v0.17.1 (2017-07-14)
   go1.9.2 linux/amd64

**Comment by notzippy** [comment]
@swrap , these changes have not been merged yet to master - will be on Tuesday...
