### ISSUE TITLE
API skeleton for `revel new` cmd

### ISSUE THREAD

**Issue by hfeeki** [revel/revel#120]
I think a pure json rest api server will be needed by many user. 
And a fake api server also needed.

**Comment by jniltinho** [comment]
Gojsonschema

Description
An implementation of JSON Schema, based on IETF's draft v4 - Go language

https://github.com/xeipuuv/gojsonschema

**Comment by brendensoares** [comment]
@jniltinho that's a nice tool ,but we can't include that in the scope of Revel itself.

### TODO
- [ ] define requirements
- [ ] implement

### Requirements (WIP)
- [ ] create and run api app with no errors
- [ ] no template file watching

### Tests (WIP)
1. `revel new apitest skeleton=api`
2. `revel run apitest`
3. no errors
4. ...

**Comment by notzippy** [comment]
Should be re-assigned to revel/cmd enhancement

**Comment by pedromorgan** [comment]
Maybe RAMl fits in here also https://github.com/revel/revel/issues/968

**Comment by notzippy** [comment]
Closed and moved to revel/cmd https://github.com/revel/cmd/issues/73
