### ISSUE TITLE
0.17 DOA

### ISSUE THREAD

**Issue by mattbaird** [revel/revel#1200]
route path parsing is broken for previously working routes

error message in one project: 
ERROR 2017/07/12 15:54:52 router.go:140: Failed to find controller for route path action /:controller/:action?controller.:action 

and error message in another project is: 

ERROR 2017/07/12 15:51:26 router.go:800: Route validation error (in /home/matthew/code/go/src/github.com/AtScaleInc/modeler/conf/routes:9): revel/controller: failed to find action createpost

**Comment by notzippy** [comment]
There was a lot of work done in routing, one change that may have effected your project is that the wildcard routing cannot affect controllers in other modules. If you can PM the route paths on https://gitter.im/revel I can have a look at them and see if I can see any issues

**Comment by mattbaird** [comment]
I filed this in haste while I'm gathering more details.

It seems to be non-deterministic and timing based. Is there a chance you are searching through the map of routes before it is fully loaded? I ask because I can have it work, stop the server restart with no changes and it fails.

we have a large set of routes - about 300 lines of routes.

**Comment by notzippy** [comment]
The errors you listed would occur on app startup before any requests are made, there are no parallel processes running at this time.

**Comment by notzippy** [comment]
The error below looks legit
```
ERROR 2017/07/12 15:54:52 router.go:140: Failed to find controller for route path action /:controller/:action?controller.:action
```
It looks like there is an action path in the routes file defined like `controller.:action` and it should likely be `:controller.:action`

**Comment by notzippy** [comment]
The other route error is indicating that the route action `createpost` does not exist for the controller - unfourtunately it does not log the actual controller name as well. If you modify github.com/revel/revel/controller.go line 307 to the following it should tell you the controller name as well.

```
 	if c.MethodType = c.Type.Method(methodName); c.MethodType == nil {
-		return errors.New("revel/controller: failed to find action " + methodName)
+		return errors.New("revel/controller: failed to find controller.action " + controllerName + "." + methodName)
 	}
```

**Comment by mattbaird** [comment]
those paths work in < .17, and surprisingly they ALSO work *occassionally* when I start up under 0.17. I have logs and another developer to verify this.

This codebase works fine if I roll back the commit hash to 8b511737be1349346965fddaf7c107017c0c1b9a

"createpost" doesn't exist - it's CreatePost and that does exist and is part of our QA automation testing (func (p Project) CreatePost(....))

I ctrl-c the process, up arrow to execute the same start command and get

```
Done, without errors.
INFO  2017/07/12 17:27:30 module.go:117: Sorted keys module.jobs
INFO  2017/07/12 17:27:30 module.go:117: Sorted keys module.static
INFO  2017/07/12 17:27:30 module.go:117: Sorted keys module.staticcache
INFO  2017/07/12 17:27:30 module.go:117: Sorted keys module.testrunner
INFO  2017/07/12 17:27:30 module.go:152: Loaded module jobs
INFO  2017/07/12 17:27:30 module.go:152: Loaded module static
INFO  2017/07/12 17:27:30 module.go:152: Loaded module staticcachecontrol
INFO  2017/07/12 17:27:30 module.go:152: Loaded module testrunner
INFO  2017/07/12 17:27:30 module.go:157: Found testrunner module, adding `tests` path /home/matthew/code/go/src/github.com/AtScaleInc/modeler/tests
INFO  2017/07/12 17:27:30 revel.go:249: Initialized Revel v0.17 (2017-07-11) for >= go1.6
INFO  2017/07/12 17:27:30 main.go:34: Running revel server
ERROR 2017/07/12 17:27:30 router.go:800: Route validation error (in /home/matthew/code/go/src/github.com/AtScaleInc/modeler/conf/routes:49): revel/controller: failed to find action route
panic: Route validation error (in /home/matthew/code/go/src/github.com/AtScaleInc/modeler/conf/routes:49): revel/controller: failed to find action route
```

thoughts?

**Comment by notzippy** [comment]
The validation is tighter with 17 then the older versions, although the
occasionally successfully starting up is puzzling., Can you update the
router. Go code to the above so it will show the controller it is looking
for in the action?

Thanks

**Comment by mattbaird** [comment]
```
INFO  2017/07/12 18:05:02 revel.go:249: Initialized Revel v0.17 (2017-07-11) for >= go1.6
INFO  2017/07/12 18:05:02 main.go:34: Running revel server
ERROR 2017/07/12 18:05:02 router.go:800: Route validation error (in /home/matthew/code/go/src/github.com/AtScaleInc/modeler/conf/routes:49): revel/controller: failed to find controller.action App\publish.route
panic: Route validation error (in /home/matthew/code/go/src/github.com/AtScaleInc/modeler/conf/routes:49): revel/controller: failed to find controller.action App\publish.route
goroutine 1 [running]:
log.(*Logger).Panicln(0xc420278370, 0xc420191d00, 0x1, 0x1)
	/usr/local/go/src/log/log.go:222 +0xbe
github.com/AtScaleInc/modeler/vendor/github.com/revel/revel.init.6.func1()
	/home/matthew/code/go/src/github.com/AtScaleInc/modeler/vendor/github.com/revel/revel/router.go:800 +0x241
github.com/AtScaleInc/modeler/vendor/github.com/revel/revel.runStartupHooks()
	/home/matthew/code/go/src/github.com/AtScaleInc/modeler/vendor/github.com/revel/revel/server.go:178 +0x85
github.com/AtScaleInc/modeler/vendor/github.com/revel/revel.InitServer(0xd781a0)
	/home/matthew/code/go/src/github.com/AtScaleInc/modeler/vendor/github.com/revel/revel/server.go:97 +0x34
github.com/AtScaleInc/modeler/vendor/github.com/revel/revel.Run(0xb3cb)
	/home/matthew/code/go/src/github.com/AtScaleInc/modeler/vendor/github.com/revel/revel/server.go:151 +0x1e4
main.main()
	/home/matthew/code/go/src/github.com/AtScaleInc/modeler/app/tmp/main.go:2767 +0x2f598
```
this function exists and is regularly called successfully:
```
func (p Publish) Route(orgId, projectId string, currentStep string, encodedPublishWorkflowData string) revel.Result {
```

btw, thank you for digging in on this.

**Comment by notzippy** [comment]
(back) 
 Can you insert the following ERROR.Printf line like :

 	// Note method name is case insensitive search
 	if c.MethodType = c.Type.Method(methodName); c.MethodType == nil {
    -		return errors.New("revel/controller: failed to find action " + methodName)
    +		ERROR.Printf("revel/controller: failed to find action " + controllerName + "." + methodName,"Short name",c.Type.ShortName(), "%#v", c.Type)
    +		for _,m := range c.Type.Methods {
    +			ERROR.Printf("Method " + m.Name)
    +		}

    +		return errors.New("revel/controller: failed to find action " + controllerName + "." + methodName)
 	}

That should print out the ControllerType details so maybe it will help resolve what is going on

I appreciate your time identifying issues, I know it can be painful process when something upstream breaks your code.

**Comment by mattbaird** [comment]
First startup worked, restarted and got this:

```
INFO  2017/07/13 09:31:35 revel.go:249: Initialized Revel v0.17 (2017-07-11) for >= go1.6
INFO  2017/07/13 09:31:35 main.go:34: Running revel server
ERROR 2017/07/13 09:31:35 controller.go:308: revel/controller: failed to find action App\engine.create%!!(MISSING)(EXTRA string=Short name, string=enginewebhooks, string=%!v(MISSING), *revel.ControllerType=&{App\ 0x12c3b60 controllers.EngineWebhooks [0xc4202b0b80 0xc4202b0bc0 0xc4202b0c00] [[0 0]]})
ERROR 2017/07/13 09:31:35 controller.go:310: Method Index
ERROR 2017/07/13 09:31:35 controller.go:310: Method UpdateHook
ERROR 2017/07/13 09:31:35 controller.go:310: Method DeleteHook
ERROR 2017/07/13 09:31:35 router.go:800: Route validation error (in /home/matthew/code/go/src/github.com/AtScaleInc/modeler/conf/routes:91): revel/controller: failed to find action App\engine.create
panic: Route validation error (in /home/matthew/code/go/src/github.com/AtScaleInc/modeler/conf/routes:91): revel/controller: failed to find action App\engine.create
```

**Comment by mattbaird** [comment]
engine.create exists (Engine.Create) func (e Engine) Create(orgId string) revel.Result {

enginewebhooks is a different controller (next one alphabetically) and has Index, UpdateHook and DeleteHook methods.

is it looking for Engine.Create but on EngineWebhooks controller?

**Comment by mattbaird** [comment]
btw you are so polite, you must be Canadian.

**Comment by notzippy** [comment]
Lol take off ehh !

Yes it appears that it is trying to map `Engine.Create` action to the `EngineWebhooks` controller. Can you post what you have for the route definitions of `Engine.Create` and what is defined for `EngineWebhooks` ?

**Comment by mattbaird** [comment]
The Engine controller has 
# Engines
GET    /org/:orgId/engine                                                                                          Engine.Index
GET    /org/:orgId/engine/create                                                                                   Engine.Create
POST   /org/:orgId/engine/create                                                                                   Engine.CreatePost
GET    /org/:orgId/engine/:engineId/update                                                                         Engine.Update
POST   /org/:orgId/engine/:engineId/update                                                                         Engine.UpdatePost
GET    /org/:orgId/engine/:engineId/delete                                                                         Engine.Delete
POST   /org/:orgId/engine/:engineId/default                                                                        Engine.MakeDefault
GET    /org/:orgId/engine/:engineId/advancedsettings                                                               Engine.AdvancedSettings
GET    /org/:orgId/engine/:engineId/license                                                                        Engine.License
GET    /org/:orgId/engine/:engineId/upload                                                                         Engine.Upload


and enginewebhooks has:
GET    /org/:orgId/engine/:engineId/webhooks                                                EngineWebhooks.Index
POST   /org/:orgId/engine/:engineId/webhooks                                              EngineWebhooks.UpdateHook
POST   /org/:orgId/engine/:engineId/envId/:envId/webhook/:hookId              EngineWebhooks.DeleteHook

**Comment by notzippy** [comment]
Is that the order in the route file or is enginewebhooks first ?

**Comment by mattbaird** [comment]
engine first, and then engine webhooks.

**Comment by notzippy** [comment]
Created a small test project with those settings, no issues parsing the routes... 
Do you have anything in your code that calls `revel.RefreshRoutes` ?

**Comment by notzippy** [comment]
And are those controllers in a module or in the app ?

**Comment by mattbaird** [comment]
No calls to RefreshRoutes

they are in a app, not in a module.

I would share the entire routes with you in a more private setting. email me (my first name)@atscale.com and I'll shoot it to you.

**Comment by notzippy** [comment]
Sure, email will come from (my github name)@gmail.com

**Comment by mattbaird** [comment]
got a different start up error where the publish controller and the publishedproject controller got confused. Similar to engine/enginewebhooks they both have the same prefix of publish

```
INFO  2017/07/14 10:23:16 module.go:157: Found testrunner module, adding `tests` path /home/matthew/code/go/src/github.com/AtScaleInc/modeler/tests
INFO  2017/07/14 10:23:16 revel.go:249: Initialized Revel v0.17 (2017-07-11) for >= go1.6
INFO  2017/07/14 10:23:16 main.go:34: Running revel server
ERROR 2017/07/14 10:23:16 controller.go:308: revel/controller: failed to find action App\publish.route%!!(MISSING)(EXTRA string=Short name, string=publishedproject, string=%!v(MISSING), *revel.ControllerType=&{App\ 0x12c5b60 controllers.PublishedProject [0xc4202b41c0] [[0 0]]})
ERROR 2017/07/14 10:23:16 controller.go:310: Method Index
ERROR 2017/07/14 10:23:16 router.go:800: Route validation error (in /home/matthew/code/go/src/github.com/AtScaleInc/modeler/conf/routes:49): revel/controller: failed to find action App\publish.route
panic: Route validation error (in /home/matthew/code/go/src/github.com/AtScaleInc/modeler/conf/routes:49): revel/controller: failed to find action App\publish.route
```
