### ISSUE TITLE
How could I mock functions while testing?

### ISSUE THREAD

**Issue by yashsriv** [revel/revel#1203]
I have an application with a controller like this:

```golang
package controllers
type UserLogin struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type User struct {
	*revel.Controller
}

// Login Action for logging into app
func (c User) Login(login UserLogin) revel.Result {

	authenticated, err := checkAuth(login.Username, login.Password)
	if err != nil {
		c.Response.Status = http.StatusInternalServerError
		return c.RenderText(err.Error())
	}
	if !authenticated {
		c.Response.Status = http.StatusUnauthorized
		return c.Result
	}

	c.Session["user"] = user.Username
	c.Response.Status = http.StatusOK
	return c.Result
}
```

Now while testing this, I would like to override the `checkAuth` function to return true/false without me having to provide a correct login/password. Is there any way to achieve this? If the test file was in package controllers itself, I could have done something like this:
```golang
    oldCheckAuth := checkAuth
    defer func () { checkAuth = oldCheckAuth }()
    checkAuth = func (username, password string) (bool, error) {
        return false, nil
    }
```

**Comment by notzippy** [comment]
Typically you would mock the database that the checkAuth function is using. Something like https://github.com/DATA-DOG/go-sqlmock can help with this. Then you do not need to change the function. Closing for now, re-open if you have more questions or chat on https://gitter.im/revel/community
