### ISSUE TITLE
 “fatal error: concurrent map writes” during the performance testing

### ISSUE THREAD

**Issue by mobileharry** [revel/revel#1221]
Steps to reproduce the issue:
1. revel new myapp
2. revel run myapp
3. Start loadrunner with only 10 concurrent users to post the request to the myapp. 

From the beginning everything works fine. After few seconds, the error comes out. 
The error shows that the concurrent template writes failed in the templateLoad() function in template.go.
![image](https://user-images.githubusercontent.com/5743832/29073364-ff3343b0-7c7d-11e7-8fd2-d51c7abeee85.png)

BTW, the error is in dev mode. If I start myapp in prod mode with setting watch=false, the app crashes directly likes the following:
![image](https://user-images.githubusercontent.com/5743832/29073370-07c67f74-7c7e-11e7-9092-e0f2b68634ba.png)

**Comment by notzippy** [comment]
Thanks for the detail bug report, this is resolved in PR #1205 which is merged to the development branch only atm
