### ISSUE TITLE
some suggestions for improvement

### ISSUE THREAD

**Issue by zuoRambo** [revel/revel#1222]
1. graceful shutdown and reload; as `OnAppStart` could register a series functions to be run at app startup we also need `OnAppShut` to handle some background tasks that are not completed.
2. log rotate; That will be wonderful if we could set rotate options as the below config 
```ini
log.rotate = true
log.rotate.type = time | size
log.rotate.time.interval = 86400 (seconds)
log.rotate.size.interval = 1048576 (KB)
log.rotate.backup.max = 10
log.rotate.backup.suffix = %(format.date)s
```
3. rich request log; we want to record `user-agent`, `referer`, `domain`,`protocol` etc.
4. context support; so we could generate request_id and pass util return response.

**Comment by notzippy** [comment]
1) Server Event support We have added a number of meta events [here](https://github.com/revel/revel/blob/develop/revel.go#L27-L47) a listener can be added [here](https://github.com/revel/revel/blob/develop/revel.go#L271) . We haven't got an implementation on how graceful shutdown will work but it is on the horizon (and the event is there)
2) Log rotation #1213 
3) With the new logger there is a context logger placed on the controller.Log [here](https://github.com/revel/revel/pull/1213/files#diff-e30be89bfd41a0c219178028b9971a32R43)
4) Controllers do have a kind of context map called [Args](https://github.com/notzippy/revel/blob/b65288f2764f25e22e4cd742e1b15552b5e20373/controller.go#L40) whose life cycle lives the length of the request. It is not a true context object that you can abort a request or the likes, but you really shouldn't be populating context with real data [anyways](https://medium.com/@cep21/how-to-correctly-use-context-context-in-go-1-7-8f2c0fafdf39) .

**Comment by notzippy** [comment]
Also - thanks for the feedback - always great to here back from people using Revel

**Comment by notzippy** [comment]
All the new items are now implemented !

**Comment by zuoRambo** [comment]
@notzippy thanks and you have worked hard～ The  `Master branch` build failed in travis-ci.

**Comment by notzippy** [comment]
Thanks, that failure is annoying - it almost seems like there is a slight delay before memcache retains the data and the unit tests are going to quick for it. I can get it to occur once in a thousand runs on my machine, and it is purely random, if I put any delay in like logging it never occurs ! So I think maybe a slight delay is needed between writing and reading the data back.

**Comment by notzippy** [comment]
Passing now !
