### ISSUE TITLE
Revel installation failing

### ISSUE THREAD

**Issue by paritosh90** [revel/revel#1227]
I have started getting this issue from last 1 hour

> failed installing packages: failed cloning repo for package github.com/revel/revel: exit status 1 [exit status 1 github.com/dkulchenko/bunch/packages.go:90: failed cloning repo for package github.com/revel/revel github.com/dkulchenko/bunch/packages.go:593: ]

Please help

**Comment by zuoRambo** [comment]
@paritosh90 how do you install `revel`

**Comment by notzippy** [comment]
go get github.com/revel/cmd/revel

**Comment by paritosh90** [comment]
There was an issue in cloning of repository. Sorry for trouble.
I am using Bunch (https://github.com/dkulchenko/bunch) for dependency management.

**Comment by notzippy** [comment]
We use a similar one, see process here revel/meta#11
