### ISSUE TITLE
add github.com/inconshreveable/log15?

### ISSUE THREAD

**Issue by runner-mei** [revel/revel#1229]
github.com/inconshreveable/log15 is used in github.com/revel/log15

github.com/inconshreveable/log15/term in root.go
github.com/inconshreveable/log15 in ext/handler.go
github.com/inconshreveable/log15 in ext/ext_test.go

**Comment by notzippy** [comment]
We needed to modify the github.com/inconshreveable/log15/logger. Wasn't planning on making this a long term repository though. Is this an issue for you ?

**Comment by runner-mei** [comment]
no issue
