### ISSUE TITLE
ATM, no recursive search for *revel.Controller

### ISSUE THREAD

**Issue by xaionaro** [revel/revel#1239]
Getting error

```
ERROR 2017/09/18 18:03:32 router.go:140: Failed to find controller for route path action /?App.Index 
map[string]*revel.ActionPathData{"testrunner.index":(*revel.ActionPathData)(0xc42021d340), "testrunner.list":(*revel.ActionPathData)(0xc42021d570), "static.servemodule(testrunner,public)":(*revel.ActionPathData)(0xc42021d7a0), "testrunner.suite":(*revel.ActionPathData)(0xc42021d9d0), "testrunner.run":(*revel.ActionPathData)(0xc42021dc00)}
```

in case:

```
app/controllers/App.go:

import "myapp/app"
type App struct {
        app.Controller
}
```

```
app/init.go:

type Controller struct {
        *revel.Controller
}
```

This may be caused by this code: https://github.com/revel/cmd/blob/8dac9acf7744fa7818c265c13238dada88a503a5/harness/reflect.go#L670 (which seems to do not scan recursively).

So I cannot use common structure made by myself for all controllers, at the moment. And I have to reimplement the same thing for every controller.

**Comment by notzippy** [comment]
You can use a common structure, but your common controller code must be in a package called controllers. For example the booking application [App Controller](https://github.com/revel/examples/blob/master/booking/app/controllers/app.go) extends the GorpController.

If you want to make a common controller that is used by multiple projects you can create a *module* and place the controller inside a package there. 

If you have multiple shared controllers in a single project you want to extend you can place them in a package like /app/shared/controllers/your_controller.go

The key is the package name must be controllers.

**Comment by notzippy** [comment]
I am closing this for now, feel free to re-open if this didnt work

**Comment by xaionaro** [comment]
> I am closing this for now, feel free to re-open if this didnt work

Well, I haven't such privileges in this project :)

> You can use a common structure, but your common controller code must be in a package called controllers.

I see, thanks. If this requirement is a feature (not a bug) then it's required to print it if somebody tries to do the same thing as me, IMHO. Otherwise it looks like a bug and eats time.

**Comment by notzippy** [comment]
@xaionaro If you want to help with development that would be great :-D

how about revel/cmd#100 ?

I have added some code to detect and hide types that are unexported
```
DEBUG 13:14:00  revel reflect.go:704: Skipping adding spec for unexported type  type=test package=hyas.com/saltspring/web/app/controllers 
```
I have added some warnings to indicate if a type exists in the package but does not inherit from the expected package like
```
WARN  11:54:39  revel reflect.go:713: Type found in package: controllers, but did not inherit from: revel.Controller  name=EventUI path=hyas.com/saltspring/web/app/controllers                       
```
