### ISSUE TITLE
Example validation application, sample 4, Template Execution Error

### ISSUE THREAD

**Issue by jazd** [revel/revel#1242]
revel run github.com/revel/examples/validation
http://localhost:9000/Sample4/Index

Results in:
Template Execution Error
3: executing "Sample4/Index.html" at <$field.Id>: can't evaluate field Id in type *revel.Field
In Sample4/Index.html (around line 18)

master commit 417d285da1342bc4f5035cbfef31d85685b29297

**Comment by notzippy** [comment]
Thanks, those should say {{$field.ID}} in that example, will do a PR for develop on this
