### ISSUE TITLE
Repeated logs on start

### ISSUE THREAD

**Issue by ajaychk** [revel/revel#1244]
When I start revel I get following logs:
2017/09/26 08:55:59 log.go:157: INFO  module.go:117: Sorted keys module.static
2017/09/26 08:55:59 log.go:157: INFO  module.go:152: Loaded module static
2017/09/26 08:55:59 log.go:157: INFO  revel.go:249: Initialized Revel v0.17.1 (2017-07-14) for >= go1.6
2017/09/26 08:55:59 log.go:157: INFO  run.go:119: Running sc2 (github.com/sc2) in dev mode
2017/09/26 08:55:59 log.go:157: INFO  template_engine.go:65: init templates: go
2017/09/26 08:55:59 log.go:157: INFO  harness.go:175: Listening on :9000
2017/09/26 08:55:59 log.go:157: INFO  build.go:192: Cleaning dir tmp
2017/09/26 08:55:59 log.go:157: INFO  build.go:192: Cleaning dir routes
2017/09/26 08:55:59 log.go:157: INFO  build.go:192: Cleaning dir tmp
2017/09/26 08:55:59 log.go:157: INFO  build.go:192: Cleaning dir routes
2017/09/26 08:55:59 log.go:157: INFO  module.go:117: Sorted keys module.static
2017/09/26 08:55:59 log.go:157: INFO  module.go:152: Loaded module static
2017/09/26 08:55:59 log.go:157: INFO  revel.go:249: Initialized Revel v0.17.1 (2017-07-14) for >= go1.6
2017/09/26 08:55:59 log.go:157: INFO  main.go:29: Running revel server
2017/09/26 08:55:59 log.go:157: INFO  template_engine.go:65: init templates: go

**Comment by notzippy** [comment]
Logging has been rewritten (on develop branch), I don't see this on the developer branch I am closing this as I cannot duplicate it.

**Comment by ajaychk** [comment]
Thanks,
 When this change will merge into master?

Thanks and Regards,
Ajay
Chipmonk

**Comment by notzippy** [comment]
Soon ?!? Just when I think it is good, I seem to find something else that is off :-(

If you are proficient in Go you can try switching to the develop branch for all the revel repos in your gopath (src/github.com/revel/*) and see how it goes for you. But there may be some bumps...

**Comment by ajaychk** [comment]
Thanks,
I will try that.

Thanks and Regards,
Ajay
Chipmonk
