### ISSUE TITLE
Database integration

### ISSUE THREAD

**Issue by vikram-rawat** [revel/revel#1249]
I want to know if you are planning to integrate the database into your product. Most of the product that i and my friends create have a huge dependency on database. It just can't be build without a database.

We would appreciate if you could design and integrate something that would solve this problem.

And yes if you could please tell us how to create an HTML table with CRUD capabilities. In simple terms.

I just want to know say i have a test table in postgres. With 2 column one date and another string.i want to create an HTML table which can be updated and deleted by a click. 

Like 

Time| string 
X:xx| xyz     update delete 
X:xx| xyz     update delete 
X:xx| xyz     update delete 
X:xx| xyz     update delete 

Something like this i am not able to find out how to save the time data in a slice. Or should i use a struct or a slice of struct. Nothing works. 

Can you please guide me how to do it.don't write the code just the steps. I couldn't find it on net.

I love your framework i recommend it too people but please integrate a better database design in it. Use something like gorm or sqlx packages.

I would appreciate your reply. Please do reply

**Comment by notzippy** [comment]
Hi

I have struggled with the question of how best to integrate a CRUD design into Revel as well, I don't think re-inventing the wheel is necessary as there are a lot of good tables out there already. Which one to choose ? It really depends on your current architecture, and what you are familiar with. I am thinking of making a module using datatables, it is a bit large of a javascript library but it appears to be consistent performance regardless of the number of rows. I will describe my setup below

I am using https://datatables.net/ with Revel to display an editable table with millions of records. I have enabled the scroller ,serverside flags and set the ajax property to retrieve the data via a json call. I have a collapsable section above the table which a user can create a new record or edit an existing record. On edit I fetch the row contents from the datatable using the 

                referenceRow = eventDataTable.row( $(this).parents('tr') )
                var data = referenceRow.data();

Saving the data is a matter of collecting it back into a data object and then I use an ajax post like

            $.ajax({
                url: "{{url `Data.DataSave`}}",
                contentType: "application/json",
                type: "POST",
                dataType: "json",
                data:JSON.stringify(data),
                success: function(dataReturn) {

The endpoint for "DataSave" is a single struct object which makes it easy to validate and save

I was able to do up 4 editable tables pretty quickly using this technique. Only issues I had is that numerical values needed to be a number, (or removed if they were empty). On server side I used `gopkg.in/guregu/null.v3` to handle null numbers. 

*******************************************************
Your issue with the timestamp i am not completely clear on, but it sounds like you if you posted the data back as a JSON object (make sure you set the correct contentType) and had a target of a slice of dates it should work. When posting arrays back as form values the expected field names are `a[]=?&a[]=?` and so on. 

Hope this helps
Postback if you are still having problems or chat on [gitter](https://gitter.im/revel/community)

**Comment by vikram-rawat** [comment]
Thanks for replying. But why can't you just use a package like sqlx and integrate with revel. You don't have to reinvent the wheel you just have to collaborate.

And can you please give a sample app based on what you just wrote. I am a new bee and have a hard time understanding multiple languages. But if i can read the code i will get it. Have you created anything like that? Please share the code

**Comment by notzippy** [comment]
Oh I thought you were talking about the whole front UI..  If you are just talking about a ORM we do have a module called using [GORM](https://github.com/revel/modules/tree/develop/orm/gorm) and another using [GORP](https://github.com/revel/modules/tree/develop/orm/gorp) SQLx would make another fine addition as well. With Revel the preference is to expand the functionality using modules, that way you are not locked in.

[Revel/examples](https://github.com/revel/examples/tree/master/booking) is an excellent place to checkout some sample code the booking app runs out of the box. It uses GORP to do the orm layer.

**Comment by vikram-rawat** [comment]
Naa i was not talking about front end. I was talking about something like. Describing driver and connection in app.conf file and then using it directly anywhere we like without much trouble or for loops. can this be done in revel. That will help people like me who create a lot of database app.

I come from R background and starting golang for speed. I usually build dashbaords sort of things and  integrated Database functions would help me and people like me who interact a lot with database.

Kindly think about it. the M in MVC is equally important.

could you please implement something like this.

**Comment by notzippy** [comment]
This is done, see the booking app in examples.

**Comment by vikram-rawat** [comment]
Thanks for the Help buddy.
