### ISSUE TITLE
template load map panic

### ISSUE THREAD

**Issue by wkupaochuan** [revel/revel#1250]
i got an error like this:

fatal error: concurrent map writes

goroutine 15064094 [running]:
runtime.throw(0x91e99c, 0x15)
    /data/webserver/goserver/src/runtime/panic.go:596 +0x95 fp=0xc428e2c710 sp=0xc428e2c6f0
runtime.mapassign(0x88fb40, 0xc422921c20, 0xc428e2c808, 0xb36880)
    /data/webserver/goserver/src/runtime/hashmap.go:499 +0x667 fp=0xc428e2c7b0 sp=0xc428e2c710
github.com/revel/revel.(*TemplateLoader).templateLoad(0xc4248c4230, 0xc4268dd9e0, 0xf, 0x0, 0xc428e2c8a0)
    /home/wangchuanchuan/work/go_pro/src/github.com/revel/revel/template.go:339 +0x177 fp=0xc428e2c828 sp=0xc428e2c7b0
github.com/revel/revel.(*TemplateLoader).TemplateLang(0xc4248c4230, 0xc4268dd9e0, 0xf, 0x0, 0x0, 0xc4268dd9e0, 0xf, 0x98, 0xc429ed9860)
    /home/wangchuanchuan/work/go_pro/src/github.com/revel/revel/template.go:323 +0x162 fp=0xc428e2c8b0 sp=0xc428e2c828
github.com/revel/revel.ErrorResult.Apply(0xc42511c180, 0xb2f4c0, 0xc429ed9860, 0xc4265861e0, 0xc42511c120)
    /home/wangchuanchuan/work/go_pro/src/github.com/revel/revel/results.go:51 +0x285 fp=0xc428e2caf8 sp=0xc428e2c8b0
github.com/revel/revel.(*ErrorResult).Apply(0xc42b4529c0, 0xc4265861e0, 0xc42511c120)
    <autogenerated>:87 +0x73 fp=0xc428e2cb38 sp=0xc428e2caf8
github.com/revel/revel.handleInternal(0xb35dc0, 0xc424168700, 0xc428ee9900, 0x0)
    /home/wangchuanchuan/work/go_pro/src/github.com/revel/revel/server.go:69 +0x71e fp=0xc428e2cc78 sp=0xc428e2cb38
github.com/revel/revel.handle(0xb35dc0, 0xc424168700, 0xc428ee9900)
    /home/wangchuanchuan/work/go_pro/src/github.com/revel/revel/server.go:49 +0xda fp=0xc428e2cce8 sp=0xc428e2cc78
net/http.HandlerFunc.ServeHTTP(0x931530, 0xb35dc0, 0xc424168700, 0xc428ee9900)
    /data/webserver/goserver/src/net/http/server.go:1942 +0x44 fp=0xc428e2cd10 sp=0xc428e2cce8
net/http.serverHandler.ServeHTTP(0xc4200a5080, 0xb35dc0, 0xc424168700, 0xc428ee9900)
    /data/webserver/goserver/src/net/http/server.go:2568 +0x92 fp=0xc428e2cd58 sp=0xc428e2cd10
net/http.(*conn).serve(0xc429ed97c0, 0xb36600, 0xc426cfd540)
    /data/webserver/goserver/src/net/http/server.go:1825 +0x612 fp=0xc428e2cfc8 sp=0xc428e2cd58
runtime.goexit()
    /data/webserver/goserver/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc428e2cfd0 sp=0xc428e2cfc8
created by net/http.(*Server).Serve
    /data/webserver/goserver/src/net/http/server.go:2668 +0x2ce

**Comment by runner-mei** [comment]
https://github.com/revel/revel/issues/1221
