### ISSUE TITLE
rl.Logger.SetStackDepth undefined

### ISSUE THREAD

**Issue by matsch01** [revel/revel#1254]
Version: 0.18.0

Getting this error when running:

revel run

ERROR 14:33:58  revel  build.go:146: # gitlab.net/company/abc/vendor/github.com/revel/revel/logger
../src/gitlab.net/company/abc/vendor/github.com/revel/revel/logger/logger.go:160:11: rl.Logger.SetStackDepth undefined (type log15.Logger has no field or method SetStackDepth)

**Comment by notzippy** [comment]
Can you do the following commands 
```
go get -u github.com/xeonx/timeago
go get -u github.com/revel/log15
```

**Comment by matsch01** [comment]
Problem seems to be that dep is not pulling from master. It pulls the latest release. For revel/log15 that is v2.11 and for timeago it's v1.0.0-rc2.

**Comment by Steve-hyas** [comment]
In `deps` you can specify that it use the master branch - 
I can label the revel/log15 but not the other

**Comment by notzippy** [comment]
I had to do the following in `Gopkg.toml`
```
[[override]]
  branch = "master"
  name = "github.com/xeonx/timeago"
[[override]]
  branch = "master"
  name = "github.com/revel/log15"

```

**Comment by matsch01** [comment]
Thank you for this.
