### ISSUE TITLE
Error when compiling: revel.AppLog.Info in revel 1.8

### ISSUE THREAD

**Issue by sgreene570** [revel/revel#1255]
After upgrading to Revel 1.8, I am experiencing the following compilation error when running `revel build`

``
Abort: Failed to build: Go Compilation Error (in app/tmp/main.go:30): undefined: revel.AppLog in revel.AppLog.Info
``

This is not OS specific and has happened both on my local machine and on my docker images.
Output of `revel version`

``
DEBUG 17:22:21  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 
~
~ revel! http://revel.github.io
~
Version(s):
   Revel v0.18.0 (2017-10-30)
   go1.8.3 linux/amd64
``

**Comment by notzippy** [comment]
Are you using a `vendor` version of revel ? it looks like the github.com/revel/revel that Go is compiling against is not the correct version.

**Comment by sgreene570** [comment]
I have been using the official revel version.  I have only installed revel through
`go get -u github.com/revel/revel' and `go get -u github.com/revel/cmd/revel`.

**Comment by notzippy** [comment]
Can you verify that `$GOPATH/src/github.com/revel/revel/logger` folder exists ?

**Comment by sgreene570** [comment]
Folder certainly exists and contains these files:
`doc.go  format.go  handlers.go  logger.go  utils.go`

**Comment by notzippy** [comment]
And you are sure there are no vendor folders in your project ? If you check the file [$GOPATH/src/github.com/revel/logger.go](https://github.com/revel/revel/blob/master/logger.go#L18) The field is really there. So I am thinking maybe the go compiler is using another folder ?

**Comment by sgreene570** [comment]
Ah there it is, I should not have been using glide the way I was, my vendor folder was the culprit.   Thanks for the help!
