### ISSUE TITLE
Question: Does the version of github.com/revel/revel and github.com/revel/cmd/revel need to match?

### ISSUE THREAD

**Issue by matsch01** [revel/revel#1256]
I pulled the latest version of github.com/revel/cmd/revel, but my app uses vendoring and github.com/revel/revel is locked at version 0.17.0. Must github.com/revel/revel and github.com/revel/cmd/revel be on the same/corresponding versions in order for:

revel run app 

to work properly? I'm getting errors that seem to be due to github.com/revel/cmd/revel being at the latest version.

What is the solution if I want to stay on 0.17.0 github.com/revel/revel and don't have the corresponding github.com/revel/cmd/revel? Can I build github.com/revel/cmd/revel from source in order to get revel.exe?

Can you provide the build command I would use?

And how do you know what version of github.com/revel/cmd/revel to use with a specific version of github.com/revel/revel (i.e. 0.17.0)? They are versioned differently.

Or is there an easier way?

**Comment by notzippy** [comment]
If you want to stay with an older version of revel you can use the revel meta package. 
Steps 
```
$ go get github.com/sparrc/gdm
$ mkdir revel-checkout 
$ cd revel-checkout/ 
$ export GOPATH=$PWD 
$ go get github.com/revel/meta 
package github.com/revel/meta: no buildable Go source files in revel-checkout/src/github.com/revel/meta 
$ cd src/github.com/revel/meta/ 
$ gdm restore -f v0.17.0.godeps 
$ go install github.com/revel/cmd/revel/ 
$ ../../../../bin/revel version 
~ ~ revel! 
http://revel.github.io 
~ Version(s): 
Revel v0.17.0 (2017-06-06) 
go1.8.3 linux/amd64
```

**Comment by notzippy** [comment]
Currently the revel/cmd and revel/revel must be the same version. I haven't found an easy way to separate them :-( . But the above will work to checkout specific versions of Revel, I just havent found a nice way to document it yet

**Comment by notzippy** [comment]
The GDM package manager adjusts your GOPATH's repos checked out hash to match the "godeps" file (or if the repo isnt checked out it will do so then adjust the checked out branch). That is why I created a new GOPATH in my example

**Comment by matsch01** [comment]
Perfect. Thank you.
