### ISSUE TITLE
Problems with revel.Request (FormFile) after updating to 0.18

### ISSUE THREAD

**Issue by goors** [revel/revel#1257]
I am geting all sort of errors.
```
func UploadFile(r *revel.Request, id string, name string, file_field string) string {

	file, header, err := r.FormFile(file_field)
        //it says in log type *revel.Request has no field or method FormFile
```
Didi you rename it/remove it to something else or?

**Comment by notzippy** [comment]
That is a different approach of saving a file, ideally the files should be saved like this app https://github.com/revel/examples/tree/master/upload , so if you pass in the `controller.Params` object you should be good to go.
