### ISSUE TITLE
Problems with revel.Request (Request Body) after updating to 0.18

### ISSUE THREAD

**Issue by goors** [revel/revel#1258]
I really do not know what is wrong with you as a developer. Why would you go and change:

`c.Request.Body` to `c.Request.GetBody()`

I am speechless. Do you have any idea how much impact this will have on projects that I as a developer have and other in community?

**Comment by goors** [comment]
I mean look at this `c.Rquest.Request` -> this does not exists as well? How do you access Http request?

I mean mean, you took something good and break it!

**Comment by goors** [comment]
You really fuck up my all project!!! It will take me like weeks to change to your new methods and stuff. How can I download 0.17 and compile it from your 0.17 release?

**Comment by notzippy** [comment]
Its called abstraction, it was done so that the server engine can be abstracted to use other http.Server like Fasthttp.

**Comment by notzippy** [comment]
If you need to stay on an older version of revel here are the steps to do that. Sorry this has not made it to the documentation yet

https://github.com/revel/meta/pull/11

**Comment by brendensoares** [comment]
@goors What's your use case for directly accessing the [`http.Requests`](https://golang.org/pkg/net/http/#Request)? Doesn't Revel abstract access to all related fields (e.g. URL/route, params, etc)?

It may not be clear, but this change allows us to use more performant http engines, like  [FastHTTP](https://github.com/valyala/fasthttp).

Revel's purpose as a framework is to allow developers to focus on developing application logic without getting stuck in the lower level details. Has Revel failed to provide you with that functionality and, if so, can we improve Revel?

Thanks for being part of the conversation and contributing your time to the community.
