### ISSUE TITLE
Problems with revel.Request (http.Request) after updating to 0.18

### ISSUE THREAD

**Issue by goors** [revel/revel#1259]
How to get http.Request now? `c.Request.Request` is not workin anymore.
Another fuckup!

**Comment by notzippy** [comment]
You need to read the [change log](https://github.com/revel/revel/blob/master/CHANGELOG.md#breaking-changes) or the [release notes](https://github.com/revel/revel/releases)

**Comment by xaionaro** [comment]
Doesn't work

```golang
response := controller.Response.Out.Server.GetRaw().(*http.Response)
```

```
INFO  19:46:51    app server.go:2753: http: panic serving 127.0.0.1:34062: interface conversion: interface {} is *http.response, not *http.Response
```

**Comment by notzippy** [comment]
You need to cast it to ResponseWriter,
https://github.com/revel/revel/releases

"You can get the http.ResponseWriter from
revel.Controller.Response.Out.Server.GetRaw().(*http.ResponseWriter)`"
