### ISSUE TITLE
prod environment cannot render result

### ISSUE THREAD

**Issue by lujiacn** [revel/revel#1263]
I push code to server and run in prod mode, cannot return result,  only "return 0x0".
Seems a major change on the prod mode which perform inconsistent with dev mode.

**Comment by notzippy** [comment]
Are you returning `c.RenderTemplate` ? or something else ?

You can try change the logging in production to be the same as dev and see if that helps tracking things down. 

I would also try looking for something that you specified in the dev section that is not in the prod section of the configuration file.

**Comment by lujiacn** [comment]
Hi notzippy,
Thanks for the actively update. But encounter some unexpected issues below: 
1. in file server.go
line 80, address := HTTPAddr, added 
```go
if address == "" {
    address="localhost"
}
```
this update annoyed me for a while. Usually I did not fill in http.address in the conf file and make server listen to all request, but this changes make me must fill in ip or 0.0.0.0.

2. after do all modification for 0.18, I can run the server locally in prod and dev mode without issue. Via "revel run project dev|prod". But after compile and package the project via `GOOS=linux GOARCH=amd64 revel package xxxx prod`. The server cannot return result, only return "Return 0x0" in the console. Check with the source code, seems related to appModule. In line 471, results.go file, `println("Returned ", module)`. Not know any reason add appModule function?

**Comment by notzippy** [comment]
Hi @lujiacn 
Thanks for the detailed explanation - 

1) The default http.addr listening ip was to open, and as such could be a security issue in its default state. That is why it was changed, but that change should have been noted. I will add it.

2) Confirmed. This appears to be an issue with the way the package command works differently from the build command. For now please use the build command and *tar* that folder to the server.

**Comment by Fyb3roptik** [comment]
We need a solution for people who use a service like Elastic Beanstalk which uses a CNAME instead of an IP. The IP gets regenerated if you rebuild the environment.

**Comment by notzippy** [comment]
You can use an environmental variable in the configuration - see http://revel.github.io/manual/appconf.html

**Comment by lujiacn** [comment]
@notzippy Thank you. I will use build and package as temp solution :)

**Comment by lujiacn** [comment]
I close this issue, not related to revel, but my project code. revel will not point out the error code location if we use wrong c.Redrect format. (c.Redirect(Task.Index) --> trigger error but no project code location, should be c.Redirect(routes.Task.Index()).
Thanks you notzippy and sorry for the inconvenience caused.

**Comment by notzippy** [comment]
No problems, another way of doing the redirect is
```
c.Redirect((*Task).Index)
```
That way you do not need to import the route file
