### ISSUE TITLE
go get `no buildable Go source files`

### ISSUE THREAD

**Issue by raphaelvigee** [revel/revel#1265]
When running `go get github.com/revel/cmd/revel` or `go get github.com/revel/revel`, I get:

    go build github.com/go-stack/stack: no buildable Go source files in /home/raphael/gocode/src/github.com/go-stack/stack

`go get` works fine with other packages tho

Infos:

    go version go1.6.2 linux/amd64

    $ echo $GOPATH 
    /home/raphael/gocode

**Comment by lujiacn** [comment]
update go to 1.92 and try again.

**Comment by raphaelvigee** [comment]
I tried `go 1.9` as well and it didn't work...

**Comment by raphaelvigee** [comment]
I purged my `go` install and now it works. Closing.
