### ISSUE TITLE
0.18.0's new WebSocket get "interface conversion: interface is nil, not io.Writer" error

### ISSUE THREAD

**Issue by cytown** [revel/revel#1267]
In 0.15.0, the old 3rd party websocket works very well, and if upgrade to 0.18.0, the new websocket will get "interface conversion: interface is nil, not io.Writer" error if refresh the page.

I don't know why, but it really happens, even I just by pass all the WS protocol in routes file, it still the same result, and then all the system will get 502 error in all the pages.

Question 1: how it happens and how to fix?
Question 2: could it has a way to use the old websocket or 3rd party websocket???

Thanks.  And now I could only temporary revert to 0.15.0 and it works like a charm...

**Comment by cytown** [comment]
I read the source code, found the internal use is the same websocket with no change, but why it will get the difference result???

Really confuse me...

**Comment by notzippy** [comment]
It may be that the Websocket interface has been changed - if you look at the breaking [changes](https://github.com/revel/revel/blob/master/CHANGELOG.md#breaking-changes) you can see the new interface for a WebSocket is `ws revel.ServerWebSocket` . This simplified the access to a websocket to two methods `ws.MessageSendJSON(&event)` and `err := ws.MessageReceiveJSON(&msg)` 

Does this resolve your issue ?

**Comment by cytown** [comment]
Hi @notzippy, trust me, I won't make such mistake without modify the relative codes, I did modify them according to the new example/chat, and it will work, only when I refresh them, it will cause such system failure....

**Comment by notzippy** [comment]
Is the example application failing for you as well ? I don't understand `it will work, only when I refresh them` - Does this mean it works until you refresh the page ? 

Can you provide me with the steps to make the example/chat application fail in the manner you describe ?

**Comment by notzippy** [comment]
@cytown can you check to see if that patch resolves your issue ?

**Comment by cytown** [comment]
Yes, it works.

**Comment by cytown** [comment]
Thanks @notzippy
