### ISSUE TITLE
0.18.0's default value of http.addr changed to "localhost"?　

### ISSUE THREAD

**Issue by yuki2006** [revel/revel#1268]
(Sorry, my English is not good.)

0.18.0's default value of http.addr changed to "localhost"?　
And can I set a wildcard?

document
https://revel.github.io/manual/appconf.html
> On Linux, an empty string indicates a wildcard

source code(0.18.0)
https://github.com/revel/revel/blob/master/server.go#L82

**Comment by notzippy** [comment]
If you set the address to 0.0.0.0 it should listen on all ip addresses. I
will update the manual
