### ISSUE TITLE
Http Middleware v18.0

### ISSUE THREAD

**Issue by gourlaa** [revel/revel#1269]
Hi,

In the last release v18 you change the revel.Request and revel.Response.

For exemple, previously the Out parameter of a revel.Request was a http.ResponseWriter and now it's OutResponse.

However I was using this parameter to set up some middleware like with this package: github.com/crewjam/saml/samlsp.

```
type Saml struct {
	Options samlsp.Options
}

func (r Saml) Apply(req *revel.Request, resp *revel.Response) {
	samlSP, _ := samlsp.New(r.Options)
	samlSP.ServeHTTP(resp.Out, req.Request)
}
```

Is it still possible to access to the http parameter ?

I already check : https://github.com/revel/revel/releases However I need the http.ResponseWriter and not the http.Response for exemple.

Thanks,

**Comment by gourlaa** [comment]
Another problem with the revel abstraction, I always get "unexpected end of JSON input".

I just switch from u.Request.Body to u.Request.GetBody().

I'm doing this : 
        body, err := ioutil.ReadAll(u.Request.GetBody())
	var formEditEmailUser forms.FormEditEmailUser
	if err = json.Unmarshal(body, &formEditEmailUser); err != nil {
		u.Response.Status = 400
		log.Println(err)
		return u.RenderJSON(err.Error())
	}

**Comment by notzippy** [comment]
The Release notes were mistake about the http.Response - it is actually the http.ResponseWriter 


http.Response.Out Is not the http.ResponseWriter and is deprecated, you can get the output writer by doing http.Response.GetWriter(). You can get the http.ResponseWriter from revel.Controller.Response.Out.Server.GetRaw().(*http.ResponseWriter)`

Another (more generic) approach to do this is by extending the GoServerEngine . An example of this approach is the [NewRelic module](https://github.com/revel/modules/tree/master/server-engine/newrelic)

**Comment by gourlaa** [comment]
Ok perfect!

Thanks!
