### ISSUE TITLE
Revel Request GetBody Empty

### ISSUE THREAD

**Issue by gourlaa** [revel/revel#1270]
Hi,

Another problem with the v0.18, I always get "unexpected end of JSON input".

I just switch from u.Request.Body to u.Request.GetBody().

I'm doing this :
body, err := ioutil.ReadAll(u.Request.GetBody())
var formEditEmailUser forms.FormEditEmailUser
if err = json.Unmarshal(body, &formEditEmailUser); err != nil {
u.Response.Status = 400
log.Println(err)
return u.RenderJSON(err.Error())
}

When the request with post man has a content type text, the GetBody return the content of te body.
However when the content type is application/json, the GestBody is empty.

Next time could you just deprecated before to change every thing because there are a lot of problem, my team have already lost 1 day..

Thanks !

**Comment by notzippy** [comment]
Sorry, you are having issues - You are coming from version 0.15 correct ? Version 0.16 started automatically capturing request containing a json body (specified by the request header) and placed that into the c.Params.JSON object. Further if there is a structure parameter it would automatically bind. So for your code

```
func (u *Controller) Endpoint() revel.Result{
body, err := ioutil.ReadAll(u.Request.GetBody())
var formEditEmailUser forms.FormEditEmailUser
if err = json.Unmarshal(body, &formEditEmailUser); err != nil {
u.Response.Status = 400
log.Println(err)
return u.RenderJSON(err.Error())
}
// More code
```

You can simplify it to
```
func (u *Controller) Endpoint(userForm forms.FormEditEmailUser) revel.Result{
/// more code
}
```

**Comment by gourlaa** [comment]
Ok thanks !!
