### ISSUE TITLE
Failed to generate name for field is an Error and should be Warning

### ISSUE THREAD

**Issue by Fyb3roptik** [revel/revel#1272]
INFO  20:37:15  revel  build.go:235: Cleaning dir tmp
INFO  20:37:15  revel  build.go:235: Cleaning dir routes
ERROR 20:37:15  revel reflect.go:789: Failed to generate name for field. Make sure the field name is valid.
ERROR 20:37:17  revel reflect.go:789: Failed to generate name for field. Make sure the field name is valid.
ERROR 20:37:17  revel reflect.go:789: Failed to generate name for field. Make sure the field name is valid.

**Comment by vinniyo111** [comment]
No updates on this?

**Comment by Fyb3roptik** [comment]
@notzippy @brendensoares

**Comment by notzippy** [comment]
This is an indicator that a controller function has a field in which the the Revel cmd generator cannot automatically create as a unique identifier.  For example lets say your controller validates something like the following

    c.Validation.Required(user.Name)

In behind the scenes Revel looks at the source and captures the `user.Name`, so when this validation fails Revel knows in this file that the particular function that was being validated had the key of `user.Name` (it does this by calling the runtime.Caller() and getting the source code position)

You can override the key name by doing something like

    c.Validation.Required(user.Name).Key("application.user.name")

which will work just as well allowing you to explicitly to do this. I will check the code to see if I can make the error message more friendly

**Comment by notzippy** [comment]
New version will say 
```
ERROR 08:12:49 reflect.go:540: Error: Failed to generate key for field validation. Make sure the field name is valid. line=14 function=Index file=src/test/app/controllers/app.go 
```
