### ISSUE TITLE
Redirect appends nil to url

### ISSUE THREAD

**Issue by Zauberstuhl** [revel/revel#1273]
I am using the latest master-branch-version from revel.

```
return c.Redirect(Hotels.Settings)
```
If I use the redirect function like described in the documentation it will redirect me to:
```
/hotels/settings/<nil>
```

I have to change it to `return c.Redirect(Hotels.Settings, "")` then it works.

I believe the issue exists somewhere here https://github.com/revel/revel/blob/master/controller.go#L342 since `args` is still nil.

Let me know if this is only a problem on my end.

Thanks

//EDIT:

After some research the problem is probably this in my `conf/routes` file

```
GET     /stream                                 Stream.Index
GET     /stream/:page                           Stream.Index
```

**Comment by Zauberstuhl** [comment]
Ok I resolved it. For something like this

```
GET     /stream                                 Stream.Index
GET     /stream/:page                           Stream.Index
```

I changed my controller to:
```
func (s Stream) Index() revel.Result {
  return s.IndexPagination(0)
}

func (s Stream) IndexPagination(page int) revel.Result {
[...]
```

and my `conf/routes` to:
```
GET     /stream                                 Stream.Index
GET     /stream/:page                           Stream.IndexPagination
```

**Comment by notzippy** [comment]
I can see how it would get confused with that. Glad you were able to
resolve it.
