### ISSUE TITLE
imports runtime/internal/sys: cannot find package "runtime/internal/sys"

### ISSUE THREAD

**Issue by royburns** [revel/revel#1275]
OS: Centos 7
Go: go version go1.8.3 linux/amd64

[root@li1203-166 go]# go get -u github.com/revel/cmd/revel
package github.com/revel/cmd/revel
	imports archive/tar
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/sys: cannot find package "runtime/internal/sys" in any of:
	/usr/local/go/src/runtime/internal/sys (from $GOROOT)
	/root/go/src/runtime/internal/sys (from $GOPATH)

**Comment by notzippy** [comment]
I do not think this is a revel issue, it could be you have an older go installation that is causing issues.
See [here](https://github.com/golang/go/issues/14816)

**Comment by royburns** [comment]
got it，thanks
