### ISSUE TITLE
result.compressed not work in 0.18.0

### ISSUE THREAD

**Issue by lujiacn** [revel/revel#1276]
Before 0.18.0, I set "result.compressed = true" in app.conf and works fine to render result. In 0.18.0, the compressed function not work correctly. If set "result.compressed = true" all pages will be downloaded as actionName.gz file, instead of render html page.

Seems the render function did set html header as gzip format correctly.

**Comment by notzippy** [comment]
confirmed `results.compressed = true`

**Comment by notzippy** [comment]
[This should fix the issue](https://github.com/revel/revel/pull/1271/commits/f31f7a7f25a69f5f305b5085c4921f18704aa1e7)

**Comment by lujiacn** [comment]
Thanks for the prompt action 👍
