### ISSUE TITLE
Unknown template engine name - pongo2

### ISSUE THREAD

**Issue by megabait1212** [revel/revel#1278]
Hi, 
I am trying to load pongo2 but always getting this error "Template loader error                     error="Panic (Template Loader): Unknown template engine name - pongo2."
Revel v0.18.0 (2017-10-30)
   go1.9.2 linux/amd64

I have installed pongo2 like in the manual "go get -u github.com/flosch/pongo2", also tried with dep and glide, for existing project and for new, nothing help. 
Could you give advice what to do? How to fix such issue?
Thank you

**Comment by notzippy** [comment]
Did you specify the template engine to use go and pongo int the app.conf ?

**Comment by megabait1212** [comment]
Yes,
module.1.pongo2=github.com/revel/modules/template-engine/pongo2
module.2.static = github.com/revel/modules/static
template.engines=pongo2,go

**Comment by megabait1212** [comment]
Maybe full debug help you 
DEBUG 19:47:42  revel module.go:145: Sorted keys                               section=module keys=module.1.pongo2 
DEBUG 19:47:42  revel module.go:145: Sorted keys                               section=module keys=module.2.static 
DEBUG 19:47:42  revel module.go:190: Loaded module                             section=module  
DEBUG 19:47:42  revel module.go:190: Loaded module                             section=module  
INFO  19:47:42  revel  revel.go:204: Initialized Revel                         Version=0.18.0 BuildDate=2017-10-30 MinimumGoVersion=">= go1.6" 
INFO  19:47:42  revel    run.go:124: Running test (test) in dev mode
          
DEBUG 19:47:42  revel    run.go:125: Base path:                                path=/home/vasily/go/src/test 
DEBUG 19:47:42  revel    run.go:129: Running in watched mode.                  
DEBUG 19:47:42  revel template.go:116: Refresh: Refreshing templates from        section=template path=[/home/vasily/go/src/github.com/revel/revel/templates] 
registered factories map[string]func(*revel.TemplateLoader) (revel.TemplateEngine, error){"go":(func(*revel.TemplateLoader) (revel.TemplateEngine, error))(0x7d9550)}
 pongo2 
ERROR 19:47:42  revel harness.go:100: Template loader error                     error="Panic (Template Loader): Unknown template engine name - pongo2." 
DEBUG 19:47:42  revel harness.go:146: Rebuild Called                            
INFO  19:47:42  revel  build.go:235: Cleaning dir tmp                          
INFO  19:47:42  revel  build.go:235: Cleaning dir routes                       
INFO  19:47:42  revel  build.go:235: Cleaning dir tmp                          
INFO  19:47:42  revel  build.go:235: Cleaning dir routes                       
INFO  19:47:42  revel   build.go:96: No vendor folder detected, not using dependency manager to import files  
DEBUG 19:47:42  revel  build.go:139: Exec:                                     args="[/usr/lib/go-1.9/bin/go build -i -ldflags -X test/app.AppVersion= -X test/app.BuildTime=2017-12-09T17:47:42Z -tags  -o /home/vasily/go/bin/revel.d/test/test test/app/tmp]" 
DEBUG 19:47:43  revel     app.go:63: Exec app:                                 path=/home/vasily/go/bin/revel.d/test/test args="[/home/vasily/go/bin/revel.d/test/test -port=43837 -importPath=test -runMode=dev]" 
DEBUG 19:47:43  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 
DEBUG 19:47:43  revel module.go:145: Sorted keys                               section=module keys=module.1.pongo2 
DEBUG 19:47:43  revel module.go:145: Sorted keys                               section=module keys=module.2.static 
DEBUG 19:47:43  revel module.go:190: Loaded module                             section=module  
DEBUG 19:47:43  revel module.go:190: Loaded module                             section=module  
INFO  19:47:43  revel  revel.go:204: Initialized Revel                         Version=0.18.0 BuildDate=2017-10-30 MinimumGoVersion=">= go1.6" 
INFO  19:47:43    app    main.go:28: Running revel server                      
DEBUG 19:47:43  revel controller_type.go:64: Registered controller: App\app            section=controller 
DEBUG 19:47:43  revel controller.go:523: RegisterController:Registered controller  section=controller controller=App\\app 
DEBUG 19:47:43  revel controller_type.go:64: Registered controller: static\static      section=controller 
DEBUG 19:47:43  revel controller.go:523: RegisterController:Registered controller  section=controller controller=static\\static 
DEBUG 19:47:43  revel server.go:106: InitServerEngine: Found server engine and invoking  section=server name=go 
INFO  19:47:43    app  utils.go:134: Adding standard handler crit output stderr  section=system 
INFO  19:47:43    app  utils.go:113: Adding key map handler log.all.filter.module.app all output stdout  section=system 
INFO  19:47:43    app  utils.go:113: Adding key map handler log.error.nfilter.module.app error output stderr  section=system 
Listening on.. localhost:43837
INFO  19:47:43  revel harness.go:190: Listening on :9000                        
INFO  19:48:22    app server-engine.go:165: Request Stats                             ip=127.0.0.1 path=/ method=GET action=App.Index namespace=App\\ start=2017/12/09 19:48:22 status=200 duration_seconds=0.0074565 section=requestlog 
INFO  19:48:22    app server-engine.go:165: Request Stats                             ip=127.0.0.1 path=/favicon.ico method=GET start=2017/12/09 19:48:22 status=404 duration_seconds=0.0001366 section=requestlog 
INFO  19:49:05    app server-engine.go:165: Request Stats                             ip=127.0.0.1 path=/ method=GET action=App.Index namespace=App\\ start=2017/12/09 19:49:05 status=200 duration_seconds=0.0067503 section=requestlog

**Comment by notzippy** [comment]
It appears you can ignore this error. The "proxy" used in the `revel` command makes use of the revel server engine and it erroneously reports this error. But if you look further on it does compile the pongo2 templates successfully (at least for me) 

```
ERROR 10:24:05  revel harness.go:100: Template loader error                     error="Panic (Template Loader): Unknown template engine name - pongo2."                                               
DEBUG 10:24:05  revel harness.go:146: Rebuild Called                                                                                                                                                  
```
later on
```
DEBUG 10:24:09  revel template.go:116: Refresh: Refreshing templates from        section=template path="[/Work/builds/gopath-revel/srcgithub.com/revel/examples/booking2/app/views /Work/builds/gopath-revel/src/github.com/revel/revel/templates /Work/builds/gopath-revel/src/github.com/revel/modules/template-engine/pongo2/app/views /Work/builds/gopath-revel/src/github.com/revel/modules/template-engine/ace/app/views /Work/builds/gopath-revel/src/github.com/revel/modules/jobs/app/views /Work/builds/gopath-revel/src/github.com/revel/modules/testrunner/app/views]"
DEBUG 10:24:09  revel template_engine.go:66: CreateTemplateEngine: init templates      section=template name=pongo2
DEBUG 10:24:09  revel template_engine.go:66: CreateTemplateEngine: init templates      section=template name=ace
DEBUG 10:24:09  revel template_engine.go:66: CreateTemplateEngine: init templates      section=template name=go
DEBUG 10:24:09  revel template.go:144: Refresh: Refreshing templates from        section=template path="[/Work/builds/gopath-revel/src/github.com/revel/examples/booking2/app/views /Work/builds/gopath-revel/src/github.com/revel/modules/testrunner/app/views /Work/builds/gopath-revel/src/github.com/revel/modules/template-engine/pongo2/app/views /Work/builds/gopath-revel/src/github.com/revel/modules/template-engine/ace/app/views /Work/builds/gopath-revel/src/github.com/revel/modules/jobs/app/views /Work/build
s/gopath-revel/src/github.com/revel/revel/templates]"
DEBUG 10:24:09  revel template.go:330: loadIntoEngine:Engine 'ace' compiled /Work/builds/gopath-revel/src/github.com/revel/examples/booking2/app/views/Application/About.html  section=template
DEBUG 10:24:09  revel template.go:330: loadIntoEngine:Engine 'pongo2' compiled /Work/builds/gopath-revel/src/github.com/revel/examples/booking2/app/views/Application/Index.html  section=template
```
Can you verify this as well ?

**Comment by megabait1212** [comment]
![image](https://user-images.githubusercontent.com/5767396/33798455-02c5b04a-dd21-11e7-9952-b4766cf44e64.png)
If I use a filename like index.html it shows like on the image. But if I change filename to the index.pongo2.html then it shows errors
Server Error:
Template Compilation Error (in /home/vasily/go/src/test/app/views/App/Index.pongo2.html:5): [Error (where: parser) in header.html | Line 5 Col 14 near '.'] Expected either a number, string, keyword or identifier.

Additionally, an error occurred when rendering the error page:
Template Compilation Error (in /home/vasily/go/src/test/app/views/App/Index.pongo2.html:5): [Error (where: parser) in header.html | Line 5 Col 14 near '.'] Expected either a number, string, keyword or identifier. 
The same error with shebang

**Comment by notzippy** [comment]
Can you show me the full startup stack until it says 
```
Listening on.. localhost:
```

**Comment by megabait1212** [comment]
DEBUG 20:47:38  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 
~
~ revel! http://revel.github.io
~
DEBUG 20:47:38  revel module.go:145: Sorted keys                               section=module keys=module.1.pongo2 
DEBUG 20:47:38  revel module.go:145: Sorted keys                               section=module keys=module.2.static 
DEBUG 20:47:38  revel module.go:190: Loaded module                             section=module  
DEBUG 20:47:38  revel module.go:190: Loaded module                             section=module  
INFO  20:47:38  revel  revel.go:204: Initialized Revel                         Version=0.18.0 BuildDate=2017-10-30 MinimumGoVersion=">= go1.6" 
INFO  20:47:38  revel    run.go:124: Running test (test) in dev mode
          
DEBUG 20:47:38  revel    run.go:125: Base path:                                path=/home/vasily/go/src/test 
DEBUG 20:47:38  revel    run.go:129: Running in watched mode.                  
DEBUG 20:47:38  revel template.go:116: Refresh: Refreshing templates from        section=template path=[/home/vasily/go/src/github.com/revel/revel/templates] 
registered factories map[string]func(*revel.TemplateLoader) (revel.TemplateEngine, error){"go":(func(*revel.TemplateLoader) (revel.TemplateEngine, error))(0x7d9550)}
 pongo2 
ERROR 20:47:38  revel harness.go:100: Template loader error                     error="Panic (Template Loader): Unknown template engine name - pongo2." 
DEBUG 20:47:38  revel harness.go:146: Rebuild Called                            
INFO  20:47:38  revel  build.go:235: Cleaning dir tmp                          
INFO  20:47:38  revel  build.go:235: Cleaning dir routes                       
INFO  20:47:38  revel  build.go:235: Cleaning dir tmp                          
INFO  20:47:38  revel  build.go:235: Cleaning dir routes                       
INFO  20:47:38  revel   build.go:96: No vendor folder detected, not using dependency manager to import files  
DEBUG 20:47:38  revel  build.go:139: Exec:                                     args="[/usr/lib/go-1.9/bin/go build -i -ldflags -X test/app.AppVersion= -X test/app.BuildTime=2017-12-09T18:47:38Z -tags  -o /home/vasily/go/bin/revel.d/test/test test/app/tmp]" 
DEBUG 20:47:39  revel     app.go:63: Exec app:                                 path=/home/vasily/go/bin/revel.d/test/test args="[/home/vasily/go/bin/revel.d/test/test -port=36435 -importPath=test -runMode=dev]" 
DEBUG 20:47:39  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 
DEBUG 20:47:39  revel module.go:145: Sorted keys                               section=module keys=module.1.pongo2 
DEBUG 20:47:39  revel module.go:145: Sorted keys                               section=module keys=module.2.static 
DEBUG 20:47:39  revel module.go:190: Loaded module                             section=module  
DEBUG 20:47:39  revel module.go:190: Loaded module                             section=module  
INFO  20:47:39  revel  revel.go:204: Initialized Revel                         Version=0.18.0 BuildDate=2017-10-30 MinimumGoVersion=">= go1.6" 
INFO  20:47:39    app    main.go:28: Running revel server                      
DEBUG 20:47:39  revel controller_type.go:64: Registered controller: App\app            section=controller 
DEBUG 20:47:39  revel controller.go:523: RegisterController:Registered controller  section=controller controller=App\\app 
DEBUG 20:47:39  revel controller_type.go:64: Registered controller: static\static      section=controller 
DEBUG 20:47:39  revel controller.go:523: RegisterController:Registered controller  section=controller controller=static\\static 
DEBUG 20:47:39  revel server.go:106: InitServerEngine: Found server engine and invoking  section=server name=go 
INFO  20:47:39    app  utils.go:134: Adding standard handler crit output stderr  section=system 
INFO  20:47:39    app  utils.go:113: Adding key map handler log.all.filter.module.app all output stdout  section=system 
INFO  20:47:39    app  utils.go:113: Adding key map handler log.error.nfilter.module.app error output stderr  section=system

**Comment by notzippy** [comment]
That is the first part, there should be more yet

**Comment by megabait1212** [comment]
I don't have more, now copied everything from console
revel run
DEBUG 21:36:47  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 
~
~ revel! http://revel.github.io
~
DEBUG 21:36:47  revel module.go:145: Sorted keys                               section=module keys=module.1.pongo2 
DEBUG 21:36:47  revel module.go:145: Sorted keys                               section=module keys=module.2.static 
DEBUG 21:36:47  revel module.go:190: Loaded module                             section=module  
DEBUG 21:36:47  revel module.go:190: Loaded module                             section=module  
INFO  21:36:47  revel  revel.go:204: Initialized Revel                         Version=0.18.0 BuildDate=2017-10-30 MinimumGoVersion=">= go1.6" 
INFO  21:36:47  revel    run.go:124: Running test (test) in dev mode
          
DEBUG 21:36:47  revel    run.go:125: Base path:                                path=/home/vasily/go/src/test 
DEBUG 21:36:47  revel    run.go:129: Running in watched mode.                  
DEBUG 21:36:47  revel template.go:116: Refresh: Refreshing templates from        section=template path=[/home/vasily/go/src/github.com/revel/revel/templates] 
registered factories map[string]func(*revel.TemplateLoader) (revel.TemplateEngine, error){"go":(func(*revel.TemplateLoader) (revel.TemplateEngine, error))(0x7d9550)}
 pongo2 
ERROR 21:36:47  revel harness.go:100: Template loader error                     error="Panic (Template Loader): Unknown template engine name - pongo2." 
DEBUG 21:36:47  revel harness.go:146: Rebuild Called                            
INFO  21:36:47  revel  build.go:235: Cleaning dir tmp                          
INFO  21:36:47  revel  build.go:235: Cleaning dir routes                       
INFO  21:36:47  revel  build.go:235: Cleaning dir tmp                          
INFO  21:36:47  revel  build.go:235: Cleaning dir routes                       
INFO  21:36:47  revel   build.go:96: No vendor folder detected, not using dependency manager to import files  
DEBUG 21:36:47  revel  build.go:139: Exec:                                     args="[/usr/lib/go-1.9/bin/go build -i -ldflags -X test/app.AppVersion= -X test/app.BuildTime=2017-12-09T19:36:47Z -tags  -o /home/vasily/go/bin/revel.d/test/test test/app/tmp]" 
DEBUG 21:36:48  revel     app.go:63: Exec app:                                 path=/home/vasily/go/bin/revel.d/test/test args="[/home/vasily/go/bin/revel.d/test/test -port=38763 -importPath=test -runMode=dev]" 
DEBUG 21:36:48  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 
DEBUG 21:36:48  revel module.go:145: Sorted keys                               section=module keys=module.1.pongo2 
DEBUG 21:36:48  revel module.go:145: Sorted keys                               section=module keys=module.2.static 
DEBUG 21:36:48  revel module.go:190: Loaded module                             section=module  
DEBUG 21:36:48  revel module.go:190: Loaded module                             section=module  
INFO  21:36:48  revel  revel.go:204: Initialized Revel                         Version=0.18.0 BuildDate=2017-10-30 MinimumGoVersion=">= go1.6" 
INFO  21:36:48    app    main.go:28: Running revel server                      
DEBUG 21:36:48  revel controller_type.go:64: Registered controller: App\app            section=controller 
DEBUG 21:36:48  revel controller.go:523: RegisterController:Registered controller  section=controller controller=App\\app 
DEBUG 21:36:48  revel controller_type.go:64: Registered controller: static\static      section=controller 
DEBUG 21:36:48  revel controller.go:523: RegisterController:Registered controller  section=controller controller=static\\static 
DEBUG 21:36:48  revel server.go:106: InitServerEngine: Found server engine and invoking  section=server name=go 
INFO  21:36:48    app  utils.go:134: Adding standard handler crit output stderr  section=system 
INFO  21:36:48    app  utils.go:113: Adding key map handler log.all.filter.module.app all output stdout  section=system 
INFO  21:36:48    app  utils.go:113: Adding key map handler log.error.nfilter.module.app error output stderr  section=system 
Listening on.. localhost:38763
INFO  21:36:48  revel harness.go:190: Listening on :9000

**Comment by megabait1212** [comment]
if it helps, full app.conf
################################################################################
# Revel configuration file
# More info at http://revel.github.io/manual/appconf.html
################################################################################

# Sets `revel.AppName` for use in-app.
# Example:
#   `if revel.AppName {...}`
app.name = test

# A secret string which is passed to cryptographically sign the cookie to prevent
# (and detect) user modification.
# Keep this string secret or users will be able to inject arbitrary cookie values
# into your application
app.secret = mAXEpa8CzG9deFytrD7bJvXzSkAowebC1j97EmHl6XLeaMDFGQG2mIQKsBIVFj1D

# Revel running behind proxy like nginx, haproxy, etc.
app.behind.proxy = false


# The IP address on which to listen.
http.addr =

# The port on which to listen.
http.port = 9000

# Whether to use SSL or not.
http.ssl = false

# Path to an X509 certificate file, if using SSL.
#http.sslcert =

# Path to an X509 certificate key, if using SSL.
#http.sslkey =


# Timeout specifies a time limit for request (in seconds) made by a single client.
# A Timeout of zero means no timeout.
http.timeout.read = 90
http.timeout.write = 60


# For any cookies set by Revel (Session,Flash,Error) these properties will set
# the fields of:
# http://golang.org/pkg/net/http/#Cookie
#
# Each cookie set by Revel is prefixed with this string.
cookie.prefix = REVEL

# A secure cookie has the secure attribute enabled and is only used via HTTPS,
# ensuring that the cookie is always encrypted when transmitting from client to
# server. This makes the cookie less likely to be exposed to cookie theft via
# eavesdropping.
#
# Defaults to false. If 'http.ssl' is enabled, this will be defaulted to true.
# This should only be true when Revel is handling SSL connections. If you are
# using a proxy in front of revel (Nginx, Apache, etc), then this should be left
# as false.
# cookie.secure = false

# Limit cookie access to a given domain.
#cookie.domain =

# Define when your session cookie expires.
# Values:
# "720h"
#   A time duration (http://golang.org/pkg/time/#ParseDuration) after which
#   the cookie expires and the session is invalid.
# "session"
#   Sets a session cookie which invalidates the session when the user close
#   the browser.
session.expires = 720h


# The date format used by Revel. Possible formats defined by the Go `time`
# package (http://golang.org/pkg/time/#Parse)
format.date     = 2006-01-02
format.datetime = 2006-01-02 15:04


# Determines whether the template rendering should use chunked encoding.
# Chunked encoding can decrease the time to first byte on the client side by
# sending data before the entire template has been fully rendered.
results.chunked = false


# The default language of this application.
i18n.default_language = en

# The default format when message is missing.
# The original message shows in %s
#i18n.unknown_format = "??? %s ???"


module.1.pongo2 = github.com/revel/modules/template-engine/pongo2
# Module to serve static content such as CSS, JavaScript and Media files
# Allows Routes like this:
#  `Static.ServeModule("modulename","public")`
module.2.static = github.com/revel/modules/static
template.engines = pongo2,go



################################################################################

# Section: dev
# This section is evaluated when running Revel in dev mode. Like so:
#   `revel run path/to/myapp`
[dev]

# This sets `revel.DevMode` for use in-app.
# Example:
#   `if revel.DevMode {...}`
#   or in your templates with
#   `<no value>`
# Values:
# "true"
#   Sets `DevMode` to `true`.
# "false"
#   Sets `DevMode` to `false`.
mode.dev = true


# Pretty print JSON/XML when calling RenderJSON/RenderXML
# Values:
# "true"
#   Enables pretty printing.
# "false"
#   Disables pretty printing.
results.pretty = true


# Watch your applicaton files for changes and automatically rebuild
# Values:
# "true"
#   Enables auto rebuilding. 
# "false"
#   Disables auto rebuilding.
watch = true


# Define when to rebuild new changes.
# Values:
# "normal"
#   Rebuild when a new request is received and changes have been detected.
# "eager"
#   Rebuild as soon as changes are detected.
watch.mode = normal

# Watch the entire `$GOPATH` for changes.
# Values:
# "true"
#   Includes `$GOPATH` in watch path.
# "false"
#   Excludes `$GOPATH` from watch path. Default value.
#watch.gopath = true


# Module to run code tests in the browser
# See:
#   http://revel.github.io/manual/testing.html
#module.testrunner = github.com/revel/modules/testrunner


# Where to log the various Revel logs
# Values:
# "off"
#   Disable log output.
# "stdout"
#   Log to OS's standard output.
# "stderr"
#   Log to Os's standard error output. Default value.
# "relative/path/to/log"
#   Log to file.
log.all.filter.module.app = stdout    # Log all loggers for the application to the stdout
log.error.nfilter.module.app = stderr # Everything else that logs an error to stderr
log.crit.output = stderr              # Everything that logs something as critical goes to this

# Revel request access log
# Access log line format:
# INFO  21:53:55 static server-engine.go:169: Request Stats                             ip=127.0.0.1 path=/public/vendors/datatables.net-buttons/js/buttons.html5.min.js method=GET start=2017/08/31 21:53:55 status=200 duration_seconds=0.0002583 section=requestlog
log.request.output = stdout



################################################################################
# Section: prod
# This section is evaluated when running Revel in production mode. Like so:
#   `revel run path/to/myapp prod`
# See:
#  [dev] section for documentation of the various settings
[prod]

mode.dev = false

results.pretty = false

watch = false

module.testrunner =

log.warn.output  = log/%(app.name)-warn.json    # Log all warn messages to file
log.error.output = log/%(app.name)-error.json   # Log all errors to file
log.crit.output = log/%(app.name)-critical.json # Log all critical to file

# Revel request access log (json format)
# Example:
#   log.request.output = %(app.name)s-request.json
log.request.output = log/%(app.name)s-requests.json

**Comment by notzippy** [comment]
Hi

Can you change the config log to be 
```
log.all = stdout    # Log all loggers to the stdout

# log.all.filter.module.app = stdout    # Log all loggers for the application to the stdout
# log.error.nfilter.module.app = stderr # Everything else that logs an error to stderr
# log.crit.output = stderr              # Everything that logs something as critical goes to this

```
And capture what the output is until the `Listening on.. localhost:` again

**Comment by pedromorgan** [comment]
side question here @notzippy what u looking for, can try and runa quick test here..

**Comment by Steve-hyas** [comment]
@pedromorgan Create a new app add config `template.engines = pongo2,go` and try a pongo2 template file to see if it works

**Comment by megabait1212** [comment]
`DEBUG 19:06:06  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 
~
~ revel! http://revel.github.io
~
DEBUG 19:06:06  revel module.go:145: Sorted keys                               section=module keys=module.1.pongo2 
DEBUG 19:06:06  revel module.go:145: Sorted keys                               section=module keys=module.2.static 
DEBUG 19:06:06  revel module.go:190: Loaded module                             section=module  
DEBUG 19:06:06  revel module.go:190: Loaded module                             section=module  
INFO  19:06:06  revel  revel.go:204: Initialized Revel                         Version=0.18.0 BuildDate=2017-10-30 MinimumGoVersion=">= go1.6" 
INFO  19:06:06  revel    run.go:124: Running test (test) in dev mode
          
DEBUG 19:06:06  revel    run.go:125: Base path:                                path=/home/vasily/go/src/test 
DEBUG 19:06:06  revel    run.go:129: Running in watched mode.                  
DEBUG 19:06:06  revel template.go:116: Refresh: Refreshing templates from        section=template path=[/home/vasily/go/src/github.com/revel/revel/templates] 
registered factories map[string]func(*revel.TemplateLoader) (revel.TemplateEngine, error){"go":(func(*revel.TemplateLoader) (revel.TemplateEngine, error))(0x7d9550)}
 pongo2 
ERROR 19:06:06  revel harness.go:100: Template loader error                     error="Panic (Template Loader): Unknown template engine name - pongo2." 
DEBUG 19:06:06  revel harness.go:146: Rebuild Called                            
INFO  19:06:06  revel  build.go:235: Cleaning dir tmp                          
INFO  19:06:06  revel  build.go:235: Cleaning dir routes                       
INFO  19:06:06  revel  build.go:235: Cleaning dir tmp                          
INFO  19:06:06  revel  build.go:235: Cleaning dir routes                       
INFO  19:06:06  revel   build.go:96: No vendor folder detected, not using dependency manager to import files  
DEBUG 19:06:06  revel  build.go:139: Exec:                                     args="[/usr/lib/go-1.9/bin/go build -i -ldflags -X test/app.AppVersion= -X test/app.BuildTime=2017-12-11T17:06:06Z -tags  -o /home/vasily/go/bin/revel.d/test/test test/app/tmp]" 
DEBUG 19:06:07  revel     app.go:63: Exec app:                                 path=/home/vasily/go/bin/revel.d/test/test args="[/home/vasily/go/bin/revel.d/test/test -port=39291 -importPath=test -runMode=dev]" 
DEBUG 19:06:07  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go 
DEBUG 19:06:07  revel module.go:145: Sorted keys                               section=module keys=module.1.pongo2 
DEBUG 19:06:07  revel module.go:145: Sorted keys                               section=module keys=module.2.static 
DEBUG 19:06:07  revel module.go:190: Loaded module                             section=module  
DEBUG 19:06:07  revel module.go:190: Loaded module                             section=module  
INFO  19:06:07  revel  revel.go:204: Initialized Revel                         Version=0.18.0 BuildDate=2017-10-30 MinimumGoVersion=">= go1.6" 
INFO  19:06:07    app    main.go:28: Running revel server                      
DEBUG 19:06:07  revel controller_type.go:64: Registered controller: App\app            section=controller 
DEBUG 19:06:07  revel controller.go:523: RegisterController:Registered controller  section=controller controller=App\\app 
DEBUG 19:06:07  revel controller_type.go:64: Registered controller: static\static      section=controller 
DEBUG 19:06:07  revel controller.go:523: RegisterController:Registered controller  section=controller controller=static\\static 
DEBUG 19:06:07  revel server.go:106: InitServerEngine: Found server engine and invoking  section=server name=go `

**Comment by megabait1212** [comment]
I still waiting for any ideas how to fix it. Please advice.

**Comment by notzippy** [comment]
Hi - I wanted to thoroughly test the situation (thus the delay). 

First off i was wrong about the log command it should be `log.all.output=stdout` that will show all debug / info messages. Now I believe the issue may be that the included templates are not in pongo2 format, so what happens is the pongo2 engine compile fails for the primary template then the go engine picks up the template and renders what you see. The fix is to change the header.html and footer.html like

header.html
```
<!DOCTYPE html>

<html>
  <head>
    <title>{{title}}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/public/css/bootstrap-3.3.6.min.css">
    <link rel="shortcut icon" type="image/png" href="/public/img/favicon.png">
    <script src="/public/js/jquery-2.2.4.min.js"></script>
    <script src="/public/js/bootstrap-3.3.6.min.js"></script>
    {% for style in moreStyles %}
      <link rel="stylesheet" type="text/css" href="/public/{{style}}">
    {% endfor %}
    {% for script in moreScripts %}
      <script src="/public/{{script}}" type="text/javascript" charset="utf-8"></script>
    {% endfor %}
  </head>
  <body>
```
Footer.html
```
  </body>
</html>

```

Now if you do NOT want the automatic rollback you can add a shebang header to the Index.html like this
```
#! pongo2
{% set title = "Home" %}
{% include "header.html" %}

<header class="jumbotron" style="background-color:#A9F16C">
  <div class="container">
    <div class="row">
      <h1>It works!</h1>
      <p></p>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="span6">
      {% include "flash.html" %}
    </div>
  </div>
</div>

{% set title = "Home" %}
{% include "footer.html" %}

```

Then if the specified engine fails to compile the template you will get an error like
```
Server Error:
Template Compilation Error (in /home/notzippy/tmp/revel-test/src/testpongo/app/views/App/Index.html:1): [Error (where: parser) in footer.html | Line 1 Col 17 near '='] If-condition is malformed.

Additionally, an error occurred when rendering the error page:
Template Compilation Error (in /home/notzippy/tmp/revel-test/src/testpongo/app/views/App/Index.html:1): [Error (where: parser) in footer.html | Line 1 Col 17 near '='] If-condition is malformed.
```

**Comment by megabait1212** [comment]
Thank you now, it's working. And also, I knew a new log output. Thank you
