### ISSUE TITLE
Revel Log is not getting logged properly in file

### ISSUE THREAD

**Issue by pranay-1995** [revel/revel#1279]
Hi, 
I have created a Revel application. I am trying to log some app level logs in a file. The logs are getting logged to file, however, they are not getting logged in proper format.
1. I can see some extra characters that are not relevant.
2. Log messages are getting printed twice in file.

The **code** to log is as follows:
log := c.Log.New()
log.Debug("----------------------Login---------------------")
log.Error("----------------------Login---------------------")
log.Info("----------------------Login---------------------")
revel.AppLog.Debug("----APPLOG-----")

**app.conf** log part configurations are:
log.all.filter.module.app = logger    # Log all loggers for the application to the stdout
log.debug.filter.module.app = stdout
log.error.nfilter.module.app = stderr # Everything else that logs an error to stderr
log.crit.output = stderr              # Everything that logs something as critical goes to this
log.colorize = false

These logs are written to **logger** file as:
INFO  10:53:32    app   plugin.go:9: Go to /@tests to run the tests.         [INFO] [10:53:32] Go to /@tests to run the tests.  
WARN  10:53:41    app static.go:102: File not found                          [WARN] [10:53:41] File not found   [33mip[0m=127.0.0.1 [33mpath[0m=/public/img/bg_footer_main_form.gif [33mmethod[0m=GET [33maction[0m=Static.Serve [33mnamespace[0m=App\\ [33mfile[0m=C:\\Projects\\Go\\src\\abc\\public\\img\\bg_footer_main_form.gif [33merror[0m="CreateFile C:\\Projects\\Go\\src\\abc\\public\\img\\bg_footer_main_form.gif: The system cannot find the file specified." 
DEBUG 10:53:45    app     app.go:46: ----------------------Login---------------------[DBUG] [10:53:45] ----------------------Login---------------------  [36mip[0m=127.0.0.1 [36mpath[0m=/Login [36mmethod[0m=POST [36maction[0m=App.Login [36mnamespace[0m=App\\ 
ERROR 10:53:45    app     app.go:47: ----------------------Login---------------------[EROR] [10:53:45] ----------------------Login---------------------  [31mip[0m=127.0.0.1 [31mpath[0m=/Login [31mmethod[0m=POST [31maction[0m=App.Login [31mnamespace[0m=App\\ 
INFO  10:53:45    app     app.go:48: ----------------------Login---------------------[INFO] [10:53:45] ----------------------Login---------------------  [32mip[0m=127.0.0.1 [32mpath[0m=/Login [32mmethod[0m=POST [32maction[0m=App.Login [32mnamespace[0m=App\\ 
DEBUG 10:53:45    app     app.go:49: ----APPLOG-----                         [DBUG] [10:53:45] ----APPLOG-----  
WARN  10:53:46    app static.go:102: File not found                          [WARN] [10:53:46] File not found   [33mip[0m=127.0.0.1 [33mpath[0m=/public/img/bg_footer_main_form.gif [33mmethod[0m=GET [33maction[0m=Static.Serve [33mnamespace[0m=App\\ [33mfile[0m=C:\\Projects\\Go\\src\\abc\\public\\img\\bg_footer_main_form.gif [33merror[0m="CreateFile C:\\Projects\\Go\\src\\abc\\public\\img\\bg_footer_main_form.gif: The system cannot find the file specified." 

As one can see, [33m are the unrequired characters. Also, long and repeated message are getting logged. Can anyone comment on this as early as possible?

**Comment by notzippy** [comment]
Thanks, included the fix in pr #1271

**Comment by pranay-1995** [comment]
@notzippy I have already installed revel on my system. So, how do you update revel with this patch merged?

**Comment by notzippy** [comment]
You can do a

go get -u github.com/revel/cmd/revel
