### ISSUE TITLE
Can't bind a parameter to a data type

### ISSUE THREAD

**Issue by megabait1212** [revel/revel#1281]
Hi, 
After an update, I found that I can bind a parameter to a data type straight in the Revel. Early I used github.com/gorilla/schema. I am trying to parse post request. My field in the looks like
```
example of c.Params.Form
map[
DateTimeAttr[].Value:[2009-08-22] 
TextAttr[].Value:[Impedit totam voluptatibus magnam vitae perferendis] 
DecimalAttr[].AttrID:[5] 
BooleanAttr[].Value:[1] 
TextAttr[].AttrID:[2] 
Values[].ID:[          ] 
Values[].AttributeValuesID:[44 50 51 47] 
id:[0] 
BooleanAttr[].AttrID:[10] 
VarCharAttr[].AttrID:[1 3 4 6] 
DateTimeAttr[].AttrID:[11] 
VarCharAttr[].Value:[Zephania Lloyd 449840647275 9608969470475 Jocelyn Mccormick] Values[].EntityID:[          ] 
Values[].AttributesID:[1 2 3 4 5 6 7 8 9 10 11] 
barcode:[3453151238297] 
DecimalAttr[].Value:[4023]
]
```
I tried
```
	var varChar []models.ProductHasAttrVarchar
	//varChar := map[string]interface{}{}
	c.Params.Bind(&varChar, "VarCharAttr")
	fmt.Println(varChar)
```
But it's return 
`[{0 0 0 } {0 0 0 } {0 0 0 } {0 0 0 } {0 0 0 } {0 0 0 } {0 0 0 } {0 0 0 }]`
If I bind to the map of interfaces then I got Runtime panic "Bind: revel/params: non-pointer passed to Bind: VarCharAttr"
I tried to pass as parameters to the controller's method 
`func (c Product) Create(barcode string, varChar *models.ProductHasAttrVarchar) revel.Result {`
but got the same result
`[{0 0 0 } {0 0 0 } {0 0 0 } {0 0 0 } {0 0 0 } {0 0 0 } {0 0 0 } {0 0 0 }]`

How can I bind parameters to data type? Please give advice what I am doing wrong. Thank you

**Comment by notzippy** [comment]
When we test the binder we try them in various formats like [this](https://github.com/revel/revel/blob/master/binder_test.go#L33) Can you reduce your test to something a bit smaller ?

**Comment by megabait1212** [comment]
Ok, thank you I will check

**Comment by megabait1212** [comment]
Thank you for your help. I decide to stay with Gorilla Schema
