### ISSUE TITLE
Can use uber-go/zap to replace log15? if it is yes, I can provide a pull request

### ISSUE THREAD

**Issue by runner-mei** [revel/revel#1282]
log15 is  inactive for a long time.
Can use uber-go/zap to replace log15? if it is yes, I can provide a pull request.

**Comment by notzippy** [comment]
I wouldn't be opposed to improving performance as long as it can be done
without changing the current logger interface definition, and can provide a
similar non breaking configuration options.

Let me know if that is possible before starting any work. One of the issues
we had with log15 was being able to set the debit frame properly so it
would report the correct long numbers, this may be an issue in zap as well.

**Comment by runner-mei** [comment]
zap has a  https://godoc.org/go.uber.org/zap#AddCallerSkip Option, it is increases the number of callers skipped.

**Comment by notzippy** [comment]
Are you working on this @runner-mei ?

**Comment by runner-mei** [comment]
No, I waiting for your confirm

**Comment by runner-mei** [comment]
I will working it at this weekend

**Comment by notzippy** [comment]
Sounds good - like I said earlier all that I am concerned about is that the [Multilogger](https://github.com/revel/revel/blob/master/logger/logger.go#L15) interface remains unchanged and that the configuration settings for it remains the same.

**Comment by notzippy** [comment]
@runner-mei any updates on this ?

**Comment by runner-mei** [comment]
https://github.com/revel/revel/pull/1298

**Comment by notzippy** [comment]
Thanks for the PR, was there issues with the implementation @runner-mei ? Or did you run out of time working with it...

**Comment by runner-mei** [comment]
@notzippy 1. zap is suck at route LogRecord to output target.
2. I am busy before 2017-02-12,   I have Holidays to working with it after 2017-02-12,

**Comment by intel352** [comment]
@runner-mei any luck with this?

**Comment by notzippy** [comment]
I'm closing this issue for now, I want to make the current logger interface less reliant on log15 for the interfaces but for now zap logger is a heavier implementation - I created a start of a [gist](https://gist.github.com/notzippy/1acaf5869b7487ec6c4cb6a5fb3fa97c) but if you want to remain perfectly agnostic use the `logger.HandlerFunc` to perform your own logging.
