### ISSUE TITLE
Issue with Heroku deployments -- Web process failed to bind to $PORT within 60 seconds of launch

### ISSUE THREAD

**Issue by bityogi** [revel/revel#1283]
I was able to successfully create a sample app and deploy it to Heroku following the well documented instructions in the [manual](http://revel.github.io/manual/deployment.html) and [this link](http://collaboradev.com/2016/06/29/deploying-go-revel-apps-on-heroku/).

However, after deploying the app, heroku was not able to bind to the port that the app was running on.

```
Listening on.. localhost:57432
heroku[web.1]: State changed from starting to crashed
heroku[web.1]: Process exited with status 137
heroku[web.1]: **Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60** seconds of launch
heroku[web.1]: Stopping process with SIGKILL
```

[This thread on stack-exchange](https://stackoverflow.com/questions/32463004/heroku-go-app-crashing) was able to provide some more useful information.

In the file [server.go](https://github.com/revel/revel/blob/master/server.go), I changed the code to:

`localAddress = ":" + strconv.Itoa(port)`
from 
`localAddress = address + ":" + strconv.Itoa(port)`

and this fixed the issue for me. I don't want to make a PR for this just yet, as I'm still fairly new to golang and I see that there is a lot of logic going on with setting the localAddress variable. But you may want to address this for Heroku deployments.

**Comment by lujiacn** [comment]
Sithout changing the server.go file, just input ip address in app.conf, http.address = 0.0.0.0, default is localhost (only listen localhost) if no http.address defined in app.conf

**Comment by bityogi** [comment]
@lujiacn : That worked!
