### ISSUE TITLE
False errors in testing

### ISSUE THREAD

**Issue by ptman** [revel/revel#1292]
I have a POST route with a method that takes a file upload. It works fine when manually testing with revel 0.18, but fails during tests:

```
Post http://localhost:41703/: EOF 
github.com/revel/modules/testrunner/app/controllers/testrunner.go:113 +0x6d
panic(0xac1980, 0xc4205617d0)
	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
github.com/revel/revel/testing.(*TestRequest).MakeRequest(0xc420bde3b0)
	github.com/revel/revel/testing/testsuite.go:245 +0x39a
github.com/revel/revel/testing.(*TestRequest).Send(0xc420bde3b0)
	github.com/revel/revel/testing/testsuite.go:235 +0x52
github.com/revel/revel/testing.(*TestSuite).PostFile(0xc42084bfc0, 0xb680d3, 0xd, 0xc4207ae180, 0xc4207ae1b0)
	github.com/revel/revel/testing/testsuite.go:203 +0x116
```

So a panic here: https://github.com/revel/revel/blob/164f0cf561ac8046a994276fa417fc7f11863da5/testing/testsuite.go#L243

The revel run process also logs another error:

```
INFO  12:21:26    app server.go:2848: http: panic serving 127.0.0.1:42868: runtime error: invalid memory address or nil pointer dereference
goroutine 374 [running]:
net/http.(*conn).serve.func1(0xc4204e9400)
	/usr/lib/go-1.9/src/net/http/server.go:1697 +0xd0
panic(0xaafa20, 0xfc6f80)
	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
github.com/revel/revel.handleInvocationPanic(0xc42026d5f0, 0xaafa20, 0xfc6f80)
	github.com/revel/revel/panic.go:28 +0xda
github.com/revel/revel.PanicFilter.func1(0xc42026d5f0)
	github.com/revel/revel/panic.go:18 +0x4d
panic(0xaafa20, 0xfc6f80)
	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
github.com/revel/revel.ParseParams(0xc42014d1a0, 0xc42051a300)
	github.com/revel/revel/params.go:63 +0x779
github.com/revel/revel.ParamsFilter(0xc42026d5f0, 0xc4201c0258, 0x8, 0x9)
	github.com/revel/revel/params.go:170 +0x3f
github.com/revel/revel.FilterConfiguringFilter(0xc42026d5f0, 0xc4201c0250, 0x9, 0xa)
```
It seems that `mp == nil` in https://github.com/revel/revel/blob/master/params.go#L60

The tests worked fine in 0.17.1

**Comment by notzippy** [comment]
Thanks for finding this, I will see if I can write a test case for the test framework which simulates this.

**Comment by ptman** [comment]
Ran into this again. IE causes crash as it sends quite weird data on POST -> GET redirect.

https://stackoverflow.com/questions/39358954/ie-sending-wrong-content-type-on-redirect-using-xmlhttprequest

**Comment by ptman** [comment]
I just surrounded lines 60 & 61 with if mp != nil {}, but I doubt that's a full solution.

**Comment by notzippy** [comment]
I think the error is [here](https://github.com/revel/revel/blob/master/http.go#L183), rather then returning the error this function returns nil. If an error was returned then `params.go` would just log a warning. @ptman can you test this change ?

```
-		return nil, nil
+		return nil, err
```

**Comment by ptman** [comment]
@notzippy yes, works, seems to be the correct fix

**Comment by ptman** [comment]
and maybe https://github.com/revel/revel/blob/master/http.go#L142 as well

**Comment by notzippy** [comment]
Changes merged into develop
