### ISSUE TITLE
app server.go:2753: http: panic serving 127.0.0.1:58660: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by slimina** [revel/revel#1294]
os : window 7
go version : go1.8.4 windows/amd64
revel :Revel v0.18.0 (2017-10-30)

a simple demo, run success . request error!

Listening on.. 127.0.0.1:58637
[32mINFO [0m 17:35:01  revel harness.go:190: Listening on 127.0.0.1:9000
Returned  0x0
[32mINFO [0m 17:35:18    app server.go:2753: http: panic serving 127.0.0.1:58660: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc0423283c0)
        C:/Go/src/net/http/server.go:1721 +0xd7
panic(0x888480, 0xb42b40)
        C:/Go/src/runtime/panic.go:489 +0x2dd
github.com/revel/revel.getRedirectURL(0x870d20, 0x927058, 0x0, 0x0, 0x0, 0xc0422c6558, 0xa, 0xb, 0xc04238bad0)
        E:/gowork/src/github.com/revel/revel/results.go:472 +0x278
github.com/revel/revel.(*RedirectToActionResult).Apply(0xc04241dce0, 0xc0420598c0, 0xc0422030e0)
        E:/gowork/src/github.com/revel/revel/results.go:439 +0x63
github.com/revel/revel.handleInternal(0xb19720, 0xc042216160)
        E:/gowork/src/github.com/revel/revel/server-engine.go:147 +0x9d3
github.com/revel/revel.(*GoHttpServer).Handle(0xc04220a420, 0xb1c920, 0xc042332460, 0xc042001d00)
        E:/gowork/src/github.com/revel/revel/server_adapter_go.go:101 +0x240
github.com/revel/revel.(*GoHttpServer).Init.func3(0xb1c920, 0xc042332460, 0xc042001d00)
        E:/gowork/src/github.com/revel/revel/server_adapter_go.go:43 +0x4f
net/http.HandlerFunc.ServeHTTP(0xc042206bf0, 0xb1c920, 0xc042332460, 0xc042001d00)
        C:/Go/src/net/http/server.go:1942 +0x4b
net/http.serverHandler.ServeHTTP(0xc04208d600, 0xb1c920, 0xc042332460, 0xc042001d00)
        C:/Go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc0423283c0, 0xb1d120, 0xc0423447c0)
        C:/Go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2668 +0x2d5  [32msection[0m=system
[32mINFO [0m 17:35:18    app reverseproxy.go:316: http: proxy error: EOF                    [32msection[0m=system
[36mDEBUG[0m 17:37:05  revel     app.go:96: Killing revel server pid                  [36mpid[0m=18824

**Comment by notzippy** [comment]
Can you post your `redirect` ?

**Comment by slimina** [comment]
can not  post ， HTTP ERROR 502
