### ISSUE TITLE
Correctly handle Accept-Headers

### ISSUE THREAD

**Issue by Merovius** [revel/revel#130]
In my opinion the current handling of Accept-handlers is faulty.

If you send an "Accept: application/json“ or similar header and the controller uses Render(), you get special treatment from revel - specifically it will render a .json-template with content-type text/html, if such a template exists and return an Error 500 with content-type application/json, if not. This breaks with http-autonegotiation, because If I only accept application/json I would expect either a content-type of application/json or getting a return code of 406.

The current approach for developers to specify content-types for different routes by supplying seperate templates for them is in my opinion insufficient and cumbersome (first: revel uses html/template also for json etc. as far as I understand, second: You have to supply such a template and maintain it together with your code, which is not necessary with RenderJson).
There should be some way for the controller to tell, what content-types it can generate and what methods to use for it (for example by adding a ContentTypes-function to the Result-interface, which returns a list of content-types, or making a special-result-type, or adding options to the routes…) and then have revel employ the content-type autonegotiation to determine, what content-type to return.

This of course would also help in creation of RESTful json-apis.

I would be willing to try to implement one of these, but wanted to pick your thought on the matter first.

**Comment by notzippy** [comment]
looks to be implemented .. closing
