### ISSUE TITLE
source code of official document is very very hard to read!

### ISSUE THREAD

**Issue by KirisameMarisa** [revel/revel#1301]
hi.
source code of official document is very very hard to read!
Especially comment is hard to read!
⇒ http://revel.github.io/manual/sessionflash.html

can you replace to syntax highlight easy to read？

I changed to echo because I don't feel like reading :(

**Comment by notzippy** [comment]
Sorry - I tried to fix the XML source code and ended up breaking the go lang examples. I think both are legible now (but they need some more loving on the look side of things).

**Comment by KirisameMarisa** [comment]
Thank you！
It's easier to read than before:)
