### ISSUE TITLE
Revel 0.19 error link csss

### ISSUE THREAD

**Issue by phamthanhlam** [revel/revel#1309]
I am install Revel 0.19. I run http://localhost:9000 . It work but link css error.

![error](https://user-images.githubusercontent.com/25340581/35912193-70558996-0c2e-11e8-8ae6-badd66a0ff98.PNG)

**Comment by notzippy** [comment]
That is strange, can you pastbin the source code that was generated for the page ?
And can you tell us what OS you are using ?

thanks

**Comment by phamthanhlam** [comment]
I using Windown 10 and golang version 1.9.4. I have not written any code yet. I only use the following command:

> revel new github.com/lam/tmdt
> revel rung github.com/lam/tmdt
I run http://localhost:9000 . It work but link css error.

**Comment by hwsong** [comment]
i have same issue on windows 10 / golang 1.9.2 or 1.9.4

**Comment by notzippy** [comment]
This issue was moved to revel/modules#69
