### ISSUE TITLE
Variable disappears :(

### ISSUE THREAD

**Issue by tr0mb1r** [revel/revel#1311]
I have three templates (header.html, index.html and somestat.html)
on the index.html I have next basic form:
![image](https://user-images.githubusercontent.com/16959656/36156781-27f70372-10e9-11e8-92dd-67c7c98fcbe8.png)
In controller i have next thing:
```
func (c App) Katastat(ThatUsername string) revel.Result {
    c.Validation.Required(ThatUsername).Message("Username is required.")
    if c.Validation.HasErrors() {
		c.Validation.Keep()
		c.FlashParams()
		return c.Redirect(App.Index)
    }
    ...SOME CODE THERE...
    return c.Render(ThatUsername, somedata)
}
```
And on the header.html i have:
![image](https://user-images.githubusercontent.com/16959656/36156821-49d6cee6-10e9-11e8-8c4d-d61ec4a2eb91.png)
header.html is loaded for somestat.html unfortunately variable ThatUsername is not loaded on the page:
![image](https://user-images.githubusercontent.com/16959656/36157352-a1dfe7fc-10ea-11e8-8cf8-297342b44c7f.png)
BUT I see it in dev tools:
![image](https://user-images.githubusercontent.com/16959656/36157172-48c2a31c-10ea-11e8-9b6f-3a93e63fd639.png)

Same problem is in example with "title" variable

**Comment by notzippy** [comment]
You likely included the header `{{template "header.html"}}` the way you should have included it was `{{template "header.html" .}}` The extra period after the template name means pass the current pipeline  (which  is the ViewArgs in the revel.Controller) into the template as well. 

Let me know if this resolves the issue

**Comment by tr0mb1r** [comment]
Yes, `{{template "header.html" .}}` worked. Thank you.
