### ISSUE TITLE
Reverse route for extended controller.

### ISSUE THREAD

**Issue by ghost** [revel/revel#1317]
¿Can revel reverse route extended controllers?
I get an error when I try:

in admin.go:
`type Admin struct{
     *revel.Controller
}`
in api.go:
`type Api struct{
    Admin
}
func (c Api) Method() revel.Result{
   c.Render()
}
`
in index.html:
`<a href="{url "Api.Method"}>Api method</a>"`

in routes:
`POST     /admin/api/:method     Api.:method`

Then when I go to index.html I get this error:
_Failed to find controller for reverse route section=router action=Api.EditInvitacion_

¿Am I doing something wrong?

**Comment by mighty-pirate** [comment]
Have you tried the following?

`
type Api struct{
    *Admin
}
`

**Comment by notzippy** [comment]
@LuciferDev , that should work just fine. Are you still having this issue ?
