### ISSUE TITLE
can't connect mysql db

### ISSUE THREAD

**Issue by aloha1003** [revel/revel#1318]
I've write an initDb func in init.go , code is [here](https://gist.github.com/aloha1003/c95b138ebae20ad8210bf412c07707c8)

But I got error message :  `default addr for network '127.0.0.1' unknown Failed to establish database connection with root:password@127.0.0.1/dbname?charset=utf8&parseTime=True&loc=Local`
  In /github.com/revel/modules/orm/gorp/app/controllers/controller.go (around line 23)

**Comment by pedromorgan** [comment]
try  ...
```root:password@/dbname?etc```
or
```root:password@tcp(127.0.0.1)/dbname?etc```
