### ISSUE TITLE
gopkg.in/fsnotify.v1: unrecognized import path

### ISSUE THREAD

**Issue by gourlaa** [revel/revel#1323]
Hi,

When we get revel like this :
` go get github.com/revel/revel`

Since today, we have 
`package gopkg.in/fsnotify.v1: unrecognized import path "gopkg.in/fsnotify.v1" (parse https://gopkg.in/fsnotify.v1?go-get=1: no go-import meta tags ())`

Do you know why?

Thanks,

**Comment by gourlaa** [comment]
Apparently that repo no longer exists :/

**Comment by nikolawannabe** [comment]
https://github.com/fsnotify/fsnotify/issues/118 Author claims to have removed that a long time ago.  Proper url linked in attached commit.

**Comment by alika** [comment]
Related issue https://github.com/go-fsnotify/fsnotify/issues/1. Seems this repo was just created today https://github.com/go-fsnotify. Which also corresponds to when my build that references `gopkg.in/fsnotify` started breaking.

**Comment by gourlaa** [comment]
Ok there change the location of the repo : https://github.com/go-fsnotify/fsnotify/blob/master/README.md

**Change your dependencies from github.com/go-fsnotify/fsnotify to github.com/fsnotify/fsnotify**

**Comment by Liangzx** [comment]
I use "github.com/fsnotify/fsnotify" run well

**Comment by gourlaa** [comment]
I just did a pull request : https://github.com/revel/revel/pull/1324

As with Docker, we can't update anymore our application..

**Comment by ptman** [comment]
May I recommend [dep](https://github.com/golang/dep/) or something else that allows you to use your own copies of dependencies? That way you can also easily patch stuff

**Comment by notzippy** [comment]
Released version 0.19.1 to address this issue - thanks for the quick work guys

**Comment by HemanthKumarChinta** [comment]
Hi , Any idea on the error please ?

   gopkg.in/mgo.V2: cannot find module providing package gopkg.in/mgo.V2: unrecognized import path "gopkg.in": parse https://gopkg.in/?go-get=1: no go-import meta tags ()
