### ISSUE TITLE
Is it possible to use it with dep?

### ISSUE THREAD

**Issue by gyurobenjamin** [revel/revel#1326]
I got my vendor folder with all dependencies from my code.
But I need the revel cmd, so I install it separately with go get.

When I run it, I got this issue:

`revel watcher.go:78: Watcher: Failed to stat watched path      section=util path=/go/src/bitbucket.org/***/core-api/vendor/github.com/revel/revel/templates error="stat /go/src/bitbucket.org/***/core-api/vendor/github.com/revel/revel/templates: no such file or directory"`

It seems revel confused by multiple copies from revel.

**Comment by gyurobenjamin** [comment]
put this into Gokpg.toml

```toml
ignored = [
  "github.com/revel/cron",
  "github.com/revel/modules",
  "github.com/revel/modules/jobs/app/jobs",
  "github.com/revel/revel",
  "github.com/revel/revel/testing",
]
```

**Comment by notzippy** [comment]
My dependency file looks like 
```

# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
required = ["github.com/revel/cmd/revel"]

[[override]]
  branch = "develop"
  name = "github.com/revel/modules"

[[override]]
  branch = "develop"
  name = "github.com/revel/revel"

[[override]]
  branch = "develop"
  name = "github.com/revel/cmd"

[[override]]
  branch = "master"
  name = "github.com/revel/log15"

[[override]]
  branch = "develop"
  name = "github.com/revel/cron"

[[override]]
  branch = "master"
  name = "github.com/xeonx/timeago"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/Masterminds/squirrel.v1"

[[constraint]]
  name = "gopkg.in/guregu/null.v3"
  version = "3.2.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"
```

**Comment by luciomr** [comment]
Did you get revel to work with dep? If so, could you share it, please? The documentation on this is quite scarce.

**Comment by notzippy** [comment]
The command line launcher still has some issues but other then that you can use revel with dep. 
* Place the above Gopkg.toml file inside the project folder (the one up from the app folder), change the branch to be the one you want to follow.
* Make sure deps is installed, and is on the path
* Run deps
* Run `revel run yourapp` (command line ) 
Revel should use deps to pull out any additional packages based on what is needed in your application

**Comment by luciomr** [comment]
Hello. Thanks for the quick response. 

> - Run deps

I don't understand what you mean by running `deps`. I did the following:
- I created a `Gopkg.toml` file based on yours (attached at the bottom) in `$GOPATH/src/MYAPP`, but I removed those packages which I am not using.
- I ran `dep ensure` in `$GOPATH/src/MYAPP` to get my dependencies installed in `$GOPATH/src/MYAPP/vendor` .
- I tried running `revel run MYAPP` to no avail. The output I get is: `/bin/sh: revel: not found`.

I am not sure of what I am missing here. 

My Gopkg.toml looks like this (removed those packages in your example file which I am not using):
```
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
required = ["github.com/revel/cmd/revel"]

[[override]]
  version = "0.19.0"
  name = "github.com/revel/modules"

[[override]]
  version = "0.19.1"
  name = "github.com/revel/revel"

[[override]]
  version = "0.14.1"
  name = "github.com/revel/cmd"

[[override]]
  version = "0.19.1"
  name = "github.com/revel/cron"
```

**Comment by notzippy** [comment]
Sorry forgot to add you need to install the command line version of revel
as well

`go get -u github.com/revel/cmd/revel`

**Comment by gyurobenjamin** [comment]
@luciomr Yes I did. Check my last comment. Before I closed the issue.

**Comment by shaumux** [comment]
> CRIT  20:46:56  revel watcher.go:78: Watcher: Failed to stat watched path      section=util path=/home/shaumux/go/mercury/src/bitbucket.org/dataemo/mercury/vendor/github.com/revel/revel/templates error="stat /home/shaumux/go/mercury/src/bitbucket.org/dataemo/mercury/vendor/github.com/revel/revel/templates: no such file or directory" 

I get this error when I run in dev mode, but if I run in prod mode I don't get the error and works well.

My Gopkg.toml looks like this

```
required = ["github.com/revel/cmd/revel"]

[[constraint]]
  name = "github.com/revel/modules"
  version = "0.19.0"

[[constraint]]
  name = "github.com/revel/revel"
  version = "0.19.1"

[[override]]
  branch = "master"
  name = "github.com/xeonx/timeago"

[[override]]
  branch = "master"
  name = "github.com/revel/log15"

[[override]]
  version = "0.19.0"
  name = "github.com/revel/cmd"

[prune]
  go-tests = true
  unused-packages = true
```
I want to get this running without the ignore statements as I want to lock in versions, or is that not a good practice in Go? I'm new to go and revel.

**Comment by stuartkuentzel** [comment]
I'm having the same issue. Got it to work by adding the ignore array, but couldn't get it to work with the overrides.

**Comment by notzippy** [comment]
@stuartkuentzel  Not sure what you mean by `adding the ignore array`, can you post an example ?

**Comment by stuartkuentzel** [comment]
@notzippy like @gyurobenjamin recommended above, added this to Gokpg.toml

```
ignored = [
  "github.com/revel/cron",
  "github.com/revel/modules",
  "github.com/revel/modules/jobs/app/jobs",
  "github.com/revel/revel",
  "github.com/revel/revel/testing",
]
```

**Comment by notzippy** [comment]
OK, Version 0.20  should help with this as it separates revel/cmd from revel/revel so there should be no cross contanimation
