### ISSUE TITLE
Can't access on an external host

### ISSUE THREAD

**Issue by gyurobenjamin** [revel/revel#1327]
Trying to run a revel application in kubernetes.

`revel run appname prod 9000`

My http.addr is 0.0.0.0 also tried with empty string etc...

Is there a wild card value for this or I need to use an nginx inside that docker box?

**Comment by gyurobenjamin** [comment]
I can use directly the pod IP but not the service IP.

**Comment by notzippy** [comment]
If you are running inside of a docker box you need to setup specific networking to allow the docker to communicate outside of itself. Should be similar to an apache or nginx setup. `0.0.0.0` is the special address to use to listen on all interfaces. If you do figure out the issue then please post and close this.

thanks

**Comment by gyurobenjamin** [comment]
0.0.0.0 and proxy did the job
