### ISSUE TITLE
Troubles building in Travis CI a revel proyect with gorm.

### ISSUE THREAD

**Issue by nelsoncaastro** [revel/revel#1328]
I'm trying to use travis CI to test a project built with revel, which also uses `gorm`. This is how I set the  [.travis.yml](https://gist.github.com/nelsoncaastro/86e1738f2af596917c0c0518355aa499). It's built the same way as the one in the revel/revel repository and everything works ([Travis build](https://travis-ci.org/nelsoncaastro/amai/builds/361636157)) except for two things: 

* 1st. This go test, the exact same as the one in revel/revel.

[Line 756](https://travis-ci.org/nelsoncaastro/amai/jobs/361636160#L756)

```
$ go test -v github.com/revel/revel/...
```

[Line 837](https://travis-ci.org/nelsoncaastro/amai/jobs/361636160#L837)

``` 
The command "go test -v github.com/revel/revel/..." exited with 2.
```

* 2nd. The actual thing I'm trying to test with the revel cmd.

[Line 1061](https://travis-ci.org/nelsoncaastro/amai/jobs/361636160#L1061)

```
$ revel test    github.com/nelsoncaastro/amai dev
```

[Line 1121](https://travis-ci.org/nelsoncaastro/amai/jobs/361636160#L1121)

```
The command "revel test    github.com/nelsoncaastro/amai dev" exited with 1.
```

I think however that both of this errors are related. `revel test (...)` fails to find _app/modules_ as if [it didn't exist](https://travis-ci.org/nelsoncaastro/amai/jobs/361636160#L1099),  but the [Project](https://imgur.com/a/6Nk6p) is structured correctly and it's clearly there. Both of these commands work on local run in powershell, cmd or bash.  With the only difference that I have located the proyect directory as follows _$GOPATH/src/amai_ and elseways Travis clones it as _$GOPATH/src/github.com/nelsoncaastro/amai_.

Therefore I suspect it could highly be caused by the routes, something wrong with gorm or just me using wrongly the revel command. 

I would **deeply** appreciate if anyone could shed some light on this matter. Thanks in advance.

**Comment by notzippy** [comment]
I would highly recommend changing your go import path in your project to be the github one, I know it is annoying but it will cause grief if you keep going in this manner 
```
import (
	"github.com/nelsoncaastro/amai/app/models"
	"github.com/nelsoncaastro/amai/app/routes"

	"github.com/revel/revel"
)
```

That said you should be able to symlink the fetched folder so that travis is happy `ln -s $GOPATH/src/github.com/nelsoncaastro/amai $GOPATH/src/amai`

Let me know if this works for you

**Comment by nelsoncaastro** [comment]
First of all, thank you so much. It worked almost perfectly. I updated the [.travis.yml](https://github.com/nelsoncaastro/Amai/blob/master/.travis.yml) as you instructed, also included postgres as the [database](https://docs.travis-ci.com/user/database-setup/#PostgreSQ) service. I ran the build again and: 
```The command "go test -v github.com/revel/revel/..." exited with 2.```
```The command "revel test    github.com/nelsoncaastro/amai dev" exited with 0.``` 

Which is so relieving, The actual thing i was trying worked for the first time, but only on windows and linux. In the MacOS X Environment it failed creating the database in postgres, I did little research and found [this](https://stackoverflow.com/questions/36875239/travis-os-x-test-postgres) then modified the before_install of the [.travis.yml](https://github.com/nelsoncaastro/Amai/blob/master/.travis.yml) to: 

```
before_install:
  - ln -s $GOPATH/src/github.com/nelsoncaastro/amai $GOPATH/src/amai
  - echo $TRAVIS_OS_NAME
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update && brew install memcached redis && brew services start redis && brew services start memcached
      export PG_DATA=$(brew --prefix)/var/postgres
      pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}
      createuser -s postgres
      psql -c 'create database amai_development;' -U postgres
      cat postgres.log
    fi
  - redis-server --daemonize yes
  - redis-cli info
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      psql -c 'create database amai_development;' -U postgres
    fi 
```
I'm extremly grateful with your help so far, I've achieved more than enough with successfully doing `revel test    github.com/nelsoncaastro/amai dev` but out of pure curiosity I have two questions:

1. Why did the go test -v github.com/revel/revel/... fail?

[Line 740](https://travis-ci.org/nelsoncaastro/amai/jobs/361927645#L740)
``` 
The command "go test -v github.com/revel/revel/..." exited with 2.
```
1. This two errors who cause the buld to fail in the MacOS X Environment

[Line 2875](https://travis-ci.org/nelsoncaastro/amai/jobs/361951516#L2875)
``` 
ERROR 03:22:21  revel  build.go:157: ../../jinzhu/gorm/dialects/mysql/mysql.go:3:8: cannot find package "github.com/go-sql-driver/mysql" in any of:
	/Users/travis/.gimme/versions/go1.10.darwin.amd64/src/github.com/go-sql-driver/mysql (from $GOROOT)
	/Users/travis/gopath/src/github.com/go-sql-driver/mysql (from $GOPATH) (   .    .    .    )
```
[Line 2920](https://travis-ci.org/nelsoncaastro/amai/jobs/361951516#L2920)
``` 
ERROR 03:22:28    app    gorm.go:29: * LOG DEPRECATED * FATAL dial tcp [::1]:5432: connect: connection refused  section=deprecated 
panic: dial tcp [::1]:5432: connect: connection refused (   .    .    .    )
```

Thank you in advance!

**Comment by notzippy** [comment]
Sorry didnt mean to drop off the face of the earth - were you able to resolve this issue ? Im assuming you have but if you havent reopen
