### ISSUE TITLE
Adding controllers on REVEL_AFTER_MODULES_LOADED

### ISSUE THREAD

**Issue by mighty-pirate** [revel/revel#1331]
I would like to add controllers to a module on `REVEL_AFTER_MODULES_LOADED`. I am programatically adding modules to `revel.Config` on `REVEL_BEFORE_MODULES_LOADED` but this doesn't load the controllers as `main.go` has already been generated. This means I get an error such as the following on `> revel run`

```
CRIT  18:12:44  revel logger.go:139: NewRoute: Failed to find controller for route path action /@basemod?Basemod.List 
map[string]*revel.ActionPathData{"testrunner.index":(*revel.ActionPathData)(0xc4202f48c0), "testrunner.list":(*revel.ActionPathData)(0xc4202f4a80), "testrunner\\testrunner.list":(*revel.ActionPathData)(0xc4202f4a80), "static\\static.servemodule(testrunner,public)":(*revel.ActionPathData)(0xc4202f4c40), "testrunner\\testrunner.suite":(*revel.ActionPathData)(0xc4202f4e00), "testrunner.run":(*revel.ActionPathData)(0xc4202f4fc0), "testrunner\\testrunner.index":(*revel.ActionPathData)(0xc4202f48c0), "static.servemodule(testrunner,public)":(*revel.ActionPathData)(0xc4202f4c40), "testrunner.suite":(*revel.ActionPathData)(0xc4202f4e00), "testrunner\\testrunner.run":(*revel.ActionPathData)(0xc4202f4fc0)}
  section=router 
panic: NewRoute: Failed to find controller for route path action /@basemod?Basemod.List 
map[string]*revel.ActionPathData{"testrunner.index":(*revel.ActionPathData)(0xc4202f48c0), "testrunner.list":(*revel.ActionPathData)(0xc4202f4a80), "testrunner\\testrunner.list":(*revel.ActionPathData)(0xc4202f4a80), "static\\static.servemodule(testrunner,public)":(*revel.ActionPathData)(0xc4202f4c40), "testrunner\\testrunner.suite":(*revel.ActionPathData)(0xc4202f4e00), "testrunner.run":(*revel.ActionPathData)(0xc4202f4fc0), "testrunner\\testrunner.index":(*revel.ActionPathData)(0xc4202f48c0), "static.servemodule(testrunner,public)":(*revel.ActionPathData)(0xc4202f4c40), "testrunner.suite":(*revel.ActionPathData)(0xc4202f4e00), "testrunner\\testrunner.run":(*revel.ActionPathData)(0xc4202f4fc0)}
```

Is there a simple way to add the controllers to the loaded modules on the `REVEL_AFTER_MODULES_LOADED` event? Do I need to register the controller using `revel.RegisterController()` within `revel/revel/controller.go` and then add the controller to a module using `m.AddController()` in `revel/revel/module.go`?

The reason I want to do this is do be able to add modules with code, without adding them to the base project's `app.config` file.

**Comment by notzippy** [comment]
It feels like you are swimming against the current. When you define the module inside of app.conf Revel does all this nice stuff for you. So even if you never use that module in your routes there is no harm of having it defined. Go really doesn't allow you to include code programatically even the database implementations require that you import the needed modules in order to function. 

That all said I think you can do this all by performing the same process as the import module does, but just in a file with an init function defined in the module like this. But note the harder aspects like the "MODULE_FILESYSTEM_PATH" need to be hardcoded inside the source code because they cannot be determined at run time.
```
func init() {
	revel.AddInitEventHandler(func(typeOf int, value interface{}) (responseOf int) {
		if typeOf == revel.REVEL_BEFORE_MODULES_LOADED {
                        myModule := &Module{Name: "MODULE_NAME", Log: revel.RootLog.New("module","MODULE_NAME")}
			revel.Modules = append(revel.Modules, myModule)

			// If there are template files in this module we need to know the file path to import them
			myModule.Path = filepath.ToSlash("MODULE_FILESYSTEM_PATH")
                        revel.CodePaths = append(revel.CodePaths, filepath.Join(myModule.Path, "app"))
                        revel.TemplatePaths = append(revel.TemplatePaths, filepath.Join(myModule.Path, "app","views"))

			myModule.ImportPath = filepath.ToSlash("MODULE_GO_IMPORT_PATH")
			revel.RegisterController( // Add in necessary stuff
			)
			// Repeat for all controllers.
		}

		return
	})

}
```
This `init` code would need to be maintained in the module manually, but it would then make it unnecessary to do extra work in your app. All you would need to do in your app would be to `import _ "foo.bar/my/module"` in your code. I would also recommend, in your module, avoid using the `controller.Render` method, but instead use the `controller.RenderTemplate` instead. The reasoning for this is that the passing in values for `revel.RenderArgNames` is based on the source code line number and would (likely) be painful for you to maintain (although it is possible)

This should allow you to skip adding them to the `app.conf` file directly (untested though, let me know if it worked for you).

**Comment by mighty-pirate** [comment]
Thanks very much! I will give it a try and let you know soon :+1: 

If it was possible to modify the revel.Config just after the config has been read in to memory, and before the main.go file was generated, would revel then do all the work?

I was eventually going to fork Revel and add the module loading code into that, to allow submodules, along with a config module that I am going to build shortly, which would make this is a non-issue, but for now, I am keeping it as a separate module. I expect that before I fork and pull request, it would be better to talk to a maintainer of the codebase, such as yourself.

If submodule loading isn't suitable for the revel codebase, then I was thinking that perhaps allowing a CodePath inside apps and modules for the build stage (perhaps a `build` directory), that the harness imports, which could be triggered by AddBuildEventHandler with HARNESS_BEFORE_BUILD and HARNESS_AFTER_BUILD events. These events would be triggered before and after main.go is generated.

I expect this is probably very edge case stuff as most people who use Revel don't want to do anything until their app has started running, so maybe it is more work that it is worth.

**Comment by notzippy** [comment]
That is the direction that we want to take Revel, the functionality of the
Revel cmd package was going to be my next focus, basically I want to remove
all revel/revel dependencies from that project (that will help with
vendoring) and make me happily release a version 1.0. it would also be an
ideal time to try and implement the dynamic module support. We were just
discussing that the other week about how we could make adding modules more
dynamic, and easier to add. If you have some ideas on this I would be happy
to have a chat, find me on gitter.im/revel

**Comment by mighty-pirate** [comment]
The code for adding modules worked great, so thanks very much for that!

To register controllers, I generate a file similar to main.go, build it as a plugin, and then load the plugin into the app. This allows me to keep things pretty automated. The only annoyance is the duplicated code from revel/cmd/harness, but I can live with that :smile: 

Thanks very much for your help :+1:
