### ISSUE TITLE
How filter the result page?

### ISSUE THREAD

**Issue by xaionaro** [revel/revel#1334]
Hello.

I want to run some regexpressions to substitute some stuff on the resulting page in specific conditions. How can I do that?

**Comment by notzippy** [comment]
You can add a [filter](http://revel.github.io/manual/filters.html) to your process, on the way in set the writer `Controller.Response.SetWriter` with your own filtered version (if the specific condition exists).

For further details feel free to ask at https://gitter.im/revel/community
