### ISSUE TITLE
revel can get http.Response

### ISSUE THREAD

**Issue by zhaoming200808** [revel/revel#1335]
revel cant get http.Response

CHANGELOG.md 
* `http.Response.Out` Is not the http.Response and is deprecated, you can get the output writer by doing `http.Response.GetWriter()`. You can get the `http.Response` from revel.Controller.Response.Out.Server.GetRaw().(*http.Response)`

is not work

revel.Controller.Response.Out.Server.GetRaw()  type is *http.response not *http.Response

**Comment by notzippy** [comment]
Documentation updated
