### ISSUE TITLE
Logging configuration ignored before the startup hooks chain execution

### ISSUE THREAD

**Issue by vanni-giachin** [revel/revel#1337]
After the startup of my Revel application, some DEBUG logs are sent to the **standard error** channel with colors enabled, ever if the `runMode` is `prod` and regardless of the `app.config` configuration.
As example, this is the first log line after the app run. It is sent to the standard error:
`DEBUG 12:00:38  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go`

OS: Windows 10

app.config (only log settings):

log.debug.prefix = "DEBUG "
log.info.prefix  = "INFO  "
log.warn.prefix  = "WARN  "
log.error.prefix = "ERROR "

[dev]
mode.dev=true

log.debug.output = stdout
log.info.output  = stdout
log.warn.output  = stderr
log.error.output = stderr

log.request.output = stdout

[prod]
mode.dev=false

log.debug.output = off
log.info.output  = off
log.warn.output  = stderr
log.error.output = stderr

log.request.output = off

log.colorize = false

**Comment by intel352** [comment]
I see this as well, it seems that Revel is logging it's engine start prior to evaluating the app configuration, so it gets quite a bit of logging done re: startup prior to taking config into account.

**Comment by notzippy** [comment]
Yes, the proxy runner (when `revel run` is executed) is verbose with sending messages to the console. I will be adding code to the revel command to make this less verbose

**Comment by notzippy** [comment]
This is resolved in the new revel command tool
