### ISSUE TITLE
Defined template block scope 

### ISSUE THREAD

**Issue by mighty-pirate** [revel/revel#1338]
I have 2 templates (login.html and forgot.html) that share a master template (form.gohtml), which uses a master layout (master.gohtml). The idea is that I can use a single master template to store the base HTML page and then apply body to that page using defined blocks.

#### login.html
```html
{{ define "formbody }}
  <input type="text" name="email" value="{{ .Form.Email }}" placeholder="Email address" class="form__input">
  <input type="password" name="password" value="" placeholder="Password" class="form__input">
  <a href="/forgot-password" class="form__link">Forgot Password?</a>
  <button type="submit" name="submit" class="form__submit">OK</button>
{{ end }}
{{ template "Auth/templates/form.gohtml" . }}
```  

#### forgot.html
```html
{{ define "formbody }}
  <input type="text" name="email" value="{{ .Form.Email }}" placeholder="Email address" class="form__input">
  <a href="/login" class="form__link">Back to login</a>
  <button type="submit" name="submit" class="form__submit">OK</button>
{{ end }}
{{ template "Auth/templates/form.gohtml" . }}
```  

#### form.gohtml
```html
{{ define "form"}}
  <div class="form form--{{ .Form.Modifier }}">
    <div class="form__header">
      <h1 class="form__title">{{ .Form.Title }}</h1>
    </div>
    <form action="{{ .Form.Action }}" method="{{ .Form.Method }}" class="form__body form__body--{{ .Form.Modifier }}">
      {{ template "formbody" . }}
    </form>
  </div>
{{ end }}
{{ template "Auth/templates/master.gohtml" . }}
``` 

#### master.gohtml
```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>{{ .Master.Title }}</title>
  </head>
  <body class="background">
    <div class="wrapper">
      {{ template "form" . }}
    </div>
  </body>
</html>
```
The problem is, that when I call login.html using the following controller method, revel just uses formbody from forgot.html instead of login.html. I've not included the viewargs code as I don't think that it is relevant here. I am using the gorm module.

```go
type Auth struct {
	gormc.Controller
}

func (c Auth) ShowLogin() revel.Result {
	master := masterargs.NewMasterViewArgs()
	master.Title = "Login"
	master.Apply(&c.Controller) // Creates .Master 
	form := authargs.NewFormViewArgs(authargs.LoginForm)
	form.Apply(&c.Controller) // Creates .Form
 	return c.RenderTemplate("Auth/login.html")
}
```
Do defined template blocks have a global scope? I can create unique names for template blocks and use conditions to load the correct template, but allowing scoped template blocks allows for far more extensibility.

**Comment by notzippy** [comment]
Yes, on prelaunch all the templates are compiled at once and put into the master `template.Template` object. This allows the software to detect any errors before the application starts. I can see how this would cause issues for you. What I would do in this case is uniquely define your form bodies, [set](http://revel.github.io/manual/templates-go.html#set) the `formBodyTemplate` before you call the `template` function and use the [i18ntemplate function](http://revel.github.io/manual/templates-go.html#i18ntemplate) to render the results (since it allows you to pass in the name as a varaible where the `template` function doesn't)

roughly then
```
{{ define "form"}}
  <div class="form form--{{ .Form.Modifier }}">
    <div class="form__header">
      <h1 class="form__title">{{ .Form.Title }}</h1>
    </div>
    <form action="{{ .Form.Action }}" method="{{ .Form.Method }}" class="form__body form__body--{{ .Form.Modifier }}">
      {{ i18ntemplate .formBodyTemplate . }}
    </form>
  </div>
{{ end }}
{{ template "Auth/templates/master.gohtml" . }}
```
and login could look like
```
{{ define "form_login_body" }}
  <input type="text" name="email" value="{{ .Form.Email }}" placeholder="Email address" class="form__input">
  <input type="password" name="password" value="" placeholder="Password" class="form__input">
  <a href="/forgot-password" class="form__link">Forgot Password?</a>
  <button type="submit" name="submit" class="form__submit">OK</button>
{{ end }}
{{set . "formBodyTemplate" "form_login_body" }}
{{ template "Auth/templates/form.gohtml" . }}

```
Alternately the template names could be external files as well...

**untested**

But I have hope it should work in some form :-P

**Comment by notzippy** [comment]
Nix that , the file must be defined externally in order to do this so you need to have a third file, Ill update the original

**Comment by mighty-pirate** [comment]
Yes, that does the job, thanks very much for the help :smile:
