### ISSUE TITLE
undefined: revel.Server

### ISSUE THREAD

**Issue by sujeet03** [revel/revel#1339]
I am getting this error :
revel  build.go:157: # github.com/appName/app/controllers
github.com/appName/app/controllers/init.go:16:3: undefined: revel.Server
github.com/appName/app/controllers/init.go:17:3: undefined: revel.Server

init.go:

func init() {
	revel.OnAppStart(func() {
		revel.Server.ReadTimeout = 0
		revel.Server.WriteTimeout = 0
	})

**Comment by notzippy** [comment]
It doest appear you have any import statements in your code - did you set up your code using the `revel new` command ?
