### ISSUE TITLE
Reverse Proxy connection refused.

### ISSUE THREAD

**Issue by jyr** [revel/revel#1340]
Hi,

I'm running revel on docker container and I need to set reverse proxy port value, because I have the error:

> INFO  17:38:12    app reverseproxy.go:321: http: proxy error: dial tcp 127.0.0.1:37685: connect: connection refused  section=system
ERROR 17:38:21  revel harness.go:249: Error dialing websocket backend           host=localhost:37685 error="dial tcp 127.0.0.1:37685: connect: connection refused"

I don't understand if this issue is for docker or I need a tradeoff, Can I open and set custom websocket port?

**Comment by notzippy** [comment]
By default revel only listens on the localhost, I think if you want to run inside docker you need to change the IP to listen on to 0.0.0.0 see #1327 and [http.addr=0.0.0.0](http://revel.github.io/manual/appconf.html) in your app.conf
