### ISSUE TITLE
Log all output, but disable DEBUG - How?

### ISSUE THREAD

**Issue by intel352** [revel/revel#1341]
I've been trying different app configurations to log all output, but disable DEBUG level.
What is a valid config to make this work, and can the example be added to the wiki?  I see there's also a [stackoverflow question on this](https://stackoverflow.com/questions/48300230/how-to-disable-debug-logs-app-and-revel-both-in-app-conf-file-of-revel-framewo?rq=1), so at least I'm not the only one...

My ultimate goal is to have a result like so:
all, excluding debug, to stdout
-- and additionally
warn to warn.log
error to error.log
crit to crit.log
request to request.log

**Comment by notzippy** [comment]
Thanks for pointing out that message on SO, I have answered it. 

Currently the revel proxy application starts up (assuming you started it with `revel run` command) with the debug level at max. So until you see the output "Application has started" it will print a large amount of messages. Once the application has started the logger should be configured to what is set in the configuration. To avoid this you need to run a built version (`revel build myapp targetfolder`) then your application will be run without the proxy

There may be an assumption that `off` is an active handler, so it would discard the data, unfortunately the handlers are "or"ed logically together, not "and"ed so setting `all` outputs to one handler then turning one `off` does not affect the logger set to `all`

For your configuration the following should work
```
log.warn.output  = stdout
log.error.output  = stdout
log.crit.output  = stdout
log.warn = warn.log
log.error = error.log
log.crit = crit.log
log.request = request.log
```

**Comment by intel352** [comment]
@notzippy I've tried your recommendation, but I only see stdout logs, I don't see any log files created (aside from the request log, which I've not messed with as it works fine as-is).

```
# Log all loggers for the application to the stdout (except debug)
log.info.output = stdout
log.warn.output = stdout
log.error.output = stdout
log.crit.output = stdout

log.info = log/%(app.name)s-warn.json    # Log all warn messages to file
log.warn = log/%(app.name)s-warn.json    # Log all warn messages to file
log.error = log/%(app.name)s-error.json   # Log all errors to file
log.crit = log/%(app.name)s-critical.json # Log all critical to file
```

**Comment by notzippy** [comment]
Opps, I missed the output - try 
```
# Log all loggers for the application to the stdout (except debug)
log.info.output = stdout
log.warn.output = stdout
log.error.output = stdout
log.crit.output = stdout

log.info.output = log/%(app.name)s-warn.json    # Log all warn messages to file
log.warn.output = log/%(app.name)s-warn.json    # Log all warn messages to file
log.error.output = log/%(app.name)s-error.json   # Log all errors to file
log.crit.output = log/%(app.name)s-critical.json # Log all critical to file
```

**Comment by intel352** [comment]
@notzippy This is weird, the app is behaving differently in a local Docker run, than it does when deployed to Heroku (via Docker as well). On heroku, only requests log is created. In local Docker, I see at least the warn and requests logs (warn was also recording info level, error of mine in the config I'd pasted earlier).

Don't worry about it, I'll try to see if I can sort why this is behaving differently despite same app.conf and Docker CMD.

Thanks!

**Comment by notzippy** [comment]
I see these two loging to the same file is that correct ?
```
log.info.output = log/%(app.name)s-warn.json    # Log all warn messages to file
log.warn.output = log/%(app.name)s-warn.json    # Log all warn messages to file

```

**Comment by notzippy** [comment]
Also note that the log is section dependent, so if you have the log information in the "debug" section then you may have different results when in production

**Comment by intel352** [comment]
@notzippy both info and warn were going to the same file on my local Docker instance, I've corrected that. I have the configuration in the [prod] section, and I'm using same exact Dockerfile to deploy locally as well as on Heroku (meaning it has the same CMD even, with prod mode specified).

After digging further, I was using `heroku run` to check log files, but apparently that executes a one-off dyno. So quite likely files are logging, I need to set up heroku exec instead to be able to connect to an existing dyno.

Learning pains  :)
