### ISSUE TITLE
A clarification about RegisterTemplateLoader

### ISSUE THREAD

**Issue by golddranks** [revel/revel#1348]
On the page https://revel.github.io/manual/template-engine.html it says that

> To register a new engine in Revel :
> 
> - Define it as a module to be loaded in the app.conf.
> - In an init() function, which registers the engine in revel by calling:
> RegisterTemplateLoader(key string, loader func(loader *TemplateLoader) (TemplateEngine, error)) (err error)
> - Specify the template engines to be used by setting the template.engines configuration option to the names of the engine to be used (a comma delimited list).

I haven't been able to successfully get pongo2 working; it errors with:

    ERROR 00:24:13  revel harness.go:100: Template loader error                     error="Panic (Template Loader): Unknown template engine name - pongo2."

I suspect it's because I don't call `RegisterTemplateLoader` in the `init()` – but the documentation is really unclear that. Is `RegisterTemplateLoader` called by Revel or am I supposed to call it? The documentation shows the function signature but doesn't tell how it should be called. There isn't any code examples.

I didn't even manage to find a single example that uses revel and pongo2 with Google. Is pongo2 actually working with revel currently?

**Comment by notzippy** [comment]
That description is the process to create a new template engine, [This](https://revel.github.io/manual/templates.html) describes using an existing engine. The Pongo2 engine and the Ace engine are both existing template engines that work in Revel.

**Comment by golddranks** [comment]
Thanks. I send some clarifications to the documentation: https://github.com/revel/revel.github.io/pull/170
