### ISSUE TITLE
Controllers' member values in the previous access appear in the next access

### ISSUE THREAD

**Issue by KoichiWada** [revel/revel#1354]
Our revel app for v0.17 have many controllers containing member variables.
We have assumed those member variables are initially filled by zero values, and later, some are given new values by conditions.
But from v0.18, those member values used in the previous access are kept by the controller cache and appear in the next access.

Below is a sample code for explation. Suppose `App.Index` is bound to `localhost:9000/`
```
package controllers

import (
	"fmt"

	"github.com/revel/revel"
)

func init() {
	revel.InterceptMethod((*App).Before, revel.BEFORE)
}

type App struct {
	*revel.Controller
	Flag bool
}

func (c *App) Before() revel.Result {
	if c.Params.Query.Get("p") != "" {
		c.Flag = true
	}
	return nil
}

func (c *App) Index() revel.Result {
	return c.RenderText(fmt.Sprintf(
		"App\nFlag:%v\n",
		c.Flag,
	))
}
```

With this code, `localhost:9000/` prints this:
```
App
Flag:false
```

then after accessing `localhost:9000/?p=1`, `localhost:9000/` prints this:
```
App
Flag:true
```

Is this an expected behavior?
Or do we have to add more initialization code to our app for revel v0.18 or later?

**Comment by notzippy** [comment]
Sorry for the late response, Controllers instances are reused now. but you can turn that off by setting `revel.controller.reuse=false` in your app.conf
