### ISSUE TITLE
Auto decompress Request JSON body revel

### ISSUE THREAD

**Issue by vdharashive** [revel/revel#1355]
Hi All,

Is there any provision in golang to auto decompress gzip/DEFLATE Request body to JSON string.

Thanks
Vinod D

**Comment by notzippy** [comment]
If the response headers are set appropriate the body should be decompressed automatically

**Comment by vdharashive** [comment]
Hi ,

This is for the POST request. post is done using gzip/DEFLATE and server side i need unzip the stream to json.

Thanks
Vinod D

**Comment by notzippy** [comment]
So kind of like a pre-processor before the body is pulled out for binding. You can do that with a [filter](http://revel.github.io/manual/filters.html) like
```
realRequest := controller.Request.In.GetRaw().(*http.Request)
buf, _ := ioutil.ReadAll(realRequest.Body)
rdr1 := ioutil.NopCloser(bytes.NewBuffer(unpackBody(buf))) // note unpackBody would return the unziped body

realRequest.Body = rdr1 // OK since rdr2 implements the io.ReadCloser interface
```
Just make sure the filter is called before the actionfilter is invoked

**Comment by vdharashive** [comment]
thanks steve, Ill try this
