### ISSUE TITLE
Mocking services used by controller

### ISSUE THREAD

**Issue by mrgiaquino** [revel/revel#1356]
I have added an interface type on my controller struct

```go
type TransactionController struct {
  *revel.Controller
  TransactionService services.TransactionService
}

func (c TransactionController) Create() revel.Result {
  res, err := c.TransactionService.Process(id, data)
  ...
}
```

The function `c.TransactionService.Process()` involves API calls. I was able to mock the `TransactionService` and assigned it to `TransactionController` on unit test but I can't find on revel source code how to reinitialize the routes to use `TransactionController` with _mocked_ `TransactionService`. My unit test looks like 

```go
req := t.PostCustom(t.BaseUrl()+"/v2/transactions", "application/json", bytes.NewBuffer(byteData))
req.Send()
t.AssertOk()
```

where `/v2/transactions` is mapped to `TransactionController.Create()`

I hope you could help me.
Hope to hear from you soon. Thanks!

**Comment by notzippy** [comment]
Sorry for the late reply. What you could do is have a section in the app.conf specified just for running unit tests, and if this is the revel.Mode in your `init.go` you can check the `revel.Mode` and see if the mode is in test mode, if it is then set your controller to use the mock transaction
