### ISSUE TITLE
Support go modules in go 1.11

### ISSUE THREAD

**Issue by ptman** [revel/revel#1357]
Go 1.11 will come with (experimental?) go modules. Revel should probably support this official module versioning solution.

**Comment by gadelkareem** [comment]
Any updates on this one? initiating modules using `go mod app-name` disallows `revel run` to work anymore.

**Comment by LahiruSenevirathne** [comment]
Yah I'm stucked on that now  revel run doesnt work anymore

**Comment by ptman** [comment]
@notzippy do you remember why this was closed?

**Comment by davidrenne** [comment]
Can this be reopened?  I would like to find all the go get's that happen on a `revel new` so I can manually put it into my go.mod file if possible so I have a nice little package going on.

**Comment by notzippy** [comment]
It was just on the roadmap, i'm happy to reopen

**Comment by davidrenne** [comment]
Thank you!  Bye GOPATH go installs for revel new I suppose someday.

**Comment by SVilgelm** [comment]
Hi,
Do you have any dates when it will be done? Does any one work on it?

**Comment by Steve-hyas** [comment]
Work is started, getting on this.

**Comment by SVilgelm** [comment]
thanks

**Comment by davidrenne** [comment]
Free work by @SVilgelm. It's just amazing what awesome developers do for the open source communities.  Revel is such a cool project.  Can't wait to use it more using modules without things capping out.

I'm glad I reopened this item

**Comment by ptman** [comment]
https://github.com/revel/cmd/issues/177

**Comment by ztroop** [comment]
It's 2020-02, is there an ETA for supporting go modules?

**Comment by ptman** [comment]
https://github.com/revel/cmd/issues/180

**Comment by ptman** [comment]
seems done
