### ISSUE TITLE
go 1.11 supports SameSite for cookies

### ISSUE THREAD

**Issue by ptman** [revel/revel#1359]
But what versions of Go does revel want to support?

**Comment by notzippy** [comment]
Current thoughts are that the new Go module support will be supported by a
module (as they are currently implemented). This will allow the base
framework to remain compatible at a different level.

**Comment by ptman** [comment]
Sorry, I must have missed this reply somehow. My question wasn't about modules, but about samesite cookies. See https://scotthelme.co.uk/csrf-is-really-dead/

**Comment by ptman** [comment]
@notzippy Please take another look

SameSite issues will soon break sites with chrome: https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

https://www.chromestatus.com/feature/5088147346030592

https://caniuse.com/#feat=same-site-cookie-attribute

**Comment by brendensoares** [comment]
I've reopened this since there was likely a misunderstanding in the original comment and @ptman has clarified and requested we re-evaluate.

cc @notzippy

**Comment by brendensoares** [comment]
Additional Resources:

1. https://web.dev/samesite-cookies-explained/ is a nice technical overview.
2. https://golang.org/pkg/net/http/#Cookie the golang docs showing `SameSite` support
3  [relevant Go issue](https://github.com/golang/go/issues/15867)

I believe the relevant Revel code is the [default session cookie implementation](https://github.com/revel/revel/blob/a3d7a7c23ca885cc5036d3641ede49ce4a14ee2e/session_adapter_cookie.go) and the [flash variable implementation](https://github.com/revel/revel/blob/248166bf840eab87a88d1c18309f8e174e8327ff/flash.go#L57).

Am I correct in assuming the only usage of cookies in Revel is the Session cookie-based driver and the flash variables? Both of these are first-party cookie scenarios.

I'm not entirely sure what the consequences are of Chrome blocking unmarked cookies when requesting cross origin resources. What are the use cases for this? @ptman can you confirm any major concerns to help us determine the priority and scope of this change? 

A scenario I can imagine is if you have content that is intended to be shared by other domains (e.g. an embeddable widget) and you want the related cookies to be sent with the embedding request. This could negatively impact the user experience.

**Comment by brendensoares** [comment]
When we make this change, should Revel's default be `Lax`? I believe that would still cause the cookies to be blocked in CORS requests making no apparent difference to any change we might make.

It seems the safe default should be the `Default` or `Lax` mode. I don't believe Revel as it is now prevents app code from creating its own cookies with specific `SameSite` settings.

So this makes me question what changes, if any, we should make. @ptman thought? Suggestions? Insight?

**Comment by ptman** [comment]
SameSiteDefaultMode seems to leave the default up to the browser: https://github.com/golang/go/blob/a67c481f765c08b8a2e0432e3c94cd282ee4a6d6/src/net/http/cookiejar/jar.go#L423

Lax or Default is probably a better choice than strict. But SameSite protects from XSRF, so strict can is some cases make the csrf module unnecessary.

For us, samesite cookies are relevant when integrating with other sites where the browser is involved. Like SAML or OpenIDConnect.

**Comment by brendensoares** [comment]
@ptman I'm not experienced with SAML/OpenID and how cookies affect their flow. Do you think that Revel's session or flash code has an affect on that logic? Could you write your own session driver implementation or take any other app level approach?

**Comment by ptman** [comment]
SAML and OpenID Connect usually require a trip to another domain and returning to the same session when returning to the callback handler. So a way to manage that and a sensible default should be enough.

**Comment by ptman** [comment]
done
