### ISSUE TITLE
Route to view without controller?

### ISSUE THREAD

**Issue by vinniyo111** [revel/revel#1360]
Can you route to a view without the controller to render it?

Tried Eg: 
    # Routes Config
    GET	/Message2			Static.Serve("/app/views/App/Message2.html")

as opposed to a 2 line controller that renders the messages.html

**Comment by goors** [comment]
Sure you can. You just need to add this to touter:

GET     /app/views/App/*filepath                         Static.Serve("/app/views/App/")

And then in browser: http://localhost:9000/Message2.html

**Comment by notzippy** [comment]
Closing due to no further response
