### ISSUE TITLE
Dep fails to pull several revel folders.

### ISSUE THREAD

**Issue by matsch01** [revel/revel#1363]
When using dep a number of revel/revel folders are not pulled:

cache
conf
logger
templates
testdata

I was forced to copy revel/revel into my vendor folder in order to get it working properly.

What is the correct way to get revel working with dep?

**Comment by notzippy** [comment]
Thanks for the note, what does your toml file look like ?

**Comment by matsch01** [comment]
required = ["github.com/revel/cmd/revel"]

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  name = "github.com/revel/revel"
  version = "0.19.1"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  branch = "master"
  name = "github.com/revel/log15"

[[constraint]]
  name = "github.com/revel/modules"
  branch = "master"

[[override]]
  name = "github.com/revel/cmd"
  version = "0.19.1"

**Comment by notzippy** [comment]
I think the cause is the `prune`
have you tried commenting it out ?
or add into the prune section `non-go = false`
See [this](https://golang.github.io/dep/docs/Gopkg.toml.html#prune)

**Comment by matsch01** [comment]
Yes. Thanks.
