### ISSUE TITLE
Install Revel on Windows 10 error syscall.SIGUSR2

### ISSUE THREAD

**Issue by bukku-yuda** [revel/revel#1376]
i'm trying to install revel v0.20.0 on windows 10
$ go get github.com/revel/revel

return message:
# github.com/revel/revel
src\github.com\revel\revel\server_adapter_go.go:135:79: undefined: syscall.SIGUSR2

can help me? or how to install specific version to v0.19.1?

**Comment by rwese** [comment]
#747 same problem

**Comment by notzippy** [comment]
Yes there is a known bug in this release for windows. I am in the process of correcting a newer version

**Comment by MAF1N** [comment]
this one is still reproduced for Win 10

**Comment by michaellee8** [comment]
Same here, when will same release happen?

**Comment by EarlOatsDev** [comment]
Dido! Hopefully soon!

**Comment by keithnyc** [comment]
Is there any workaround?

**Comment by rwese** [comment]
Guys, you can apply the patch from this PR #1380

**Comment by bukku-yuda** [comment]
edit file server_adapter_go.go
https://github.com/revel/revel/pull/1380/files

please remove 
import syscall

change => signal.Notify(signalChan, syscall.SIGINT, syscall.SIGTERM, syscall.SIGKILL, syscall.SIGUSR2)
chnage to => signal.Notify(signalChan, os.Interrupt, os.Kill)
