### ISSUE TITLE
Creating New Application Fails

### ISSUE THREAD

**Issue by mkrain** [revel/revel#1379]
I attempted to create a new application using the latest revel command:

revel new -a $GOPATH/src/$VENDORPATH/newapp -s ""

1.  The documentation is incorrect, -s, --skeleton is required although I was allowed to pass ""
2.  I get an error because a skeleton cannot be found:

CRIT  09:01:40    new.go:248: Abort: could not clone the  Skeleton  source code:
Cloning into '/var/folders/w3/gpkz60lj19n53lyndxmz62ndhdytbw/T/revel/skeleton'...
fatal: read error: Operation timed out

git://github.com/revel/skeletons:basic/bootstrap4

This on on mac osx using go 1.11.1 (which I don't believe to be the problem).

As a workaround can I just copy a sample application and use that as the basis for a new application?

**Comment by notzippy** [comment]
There was an issue with revel/cmd where the skeleton repository used was retrieved via ssh - which would fail if behind a proxy or firewall. The next milestone release changed the retrevial to use https.
