### ISSUE TITLE
How To Construct A Controller Instance With Persistent Dependencies

### ISSUE THREAD

**Issue by mkrain** [revel/revel#1381]
I'm currently evaluating revel as a replacement for a homegrown REST API.  One thing that I can't figure out how to do is tell the revel framework to construct a controller that has dependencies.  It seems like the documentation only mentions the Before function but that would seem less than Ideal given that some of the dependencies I'm using need to be instantiated only once per application lifecycle, not on each request.  Is there some other documentation I'm missing?  The examples are too simplistic and don't match my use case.  For example:

I have a controller: Controller with dependencies, Repository (wrapper around persistence call), Statsd (client around statsd).  These dependencies should only be created once.  

Any help would be appreciated.

**Comment by notzippy** [comment]
Hi, https://gitter.im/revel/community is a good channel to ask this on. 
But basically if you have persistent entities that are shared among your controller you want to use the `revel.OnAppStart(func(){})`  place your code within the function. When Revel is initialized and before it starts the engine the function will be called
