### ISSUE TITLE
Docker execute project error 

### ISSUE THREAD

**Issue by neto-dev** [revel/revel#1384]
When running my project with docker-compose marks a strange error, the strangest thing is that I had more than 3 months working properly and days ago when I make a minimal change to the project I can no longer run the project, in my machine everything works properly. 

Error: 

> WARN  15:13:42     run.go:97: Unable to run using an import path, assuming import path is working directory %s %s Argument=8080 error="cannot find package \"8080\" in any of:\n\t/usr/local/go/src/8080 (from $GOROOT)\n\t/go/src/8080 (from $GOPATH)"
Revel executing: run a Revel application
WARN  15:13:42 harness.go:170: No http.addr specified in the app.conf listening on localhost interface only. This will not allow external access to your application
panic: interface conversion: interface {} is *ast.Ident, not string

> goroutine 1 [running]:
> github.com/revel/cmd/logger.findInContext(0x8c940c, 0x6, 0xc0006e4500, 0x4, 0x4, 0x40a565, 0xc64390)
> 	/go/src/github.com/revel/cmd/logger/format.go:99 +0x13d
> github.com/revel/cmd/logger.TerminalFormatHandler.func1(0xc00081c3f0, 0x77, 0xc00071a980, 0x7efff8b5c070)
> 	/go/src/github.com/revel/cmd/logger/format.go:56 +0xd4
> github.com/revel/log15.formatFunc.Format(0xc0000a8ee0, 0xc00081c3f0, 0xc000398bc0, 0xaaaaaaaaaaaaaaaa, 0x38)
> 	/go/src/github.com/revel/log15/format.go:34 +0x30
> github.com/revel/log15.StreamHandler.func1(0xc00081c3f0, 0x203000, 0xc0007ac470)
> 	/go/src/github.com/revel/log15/handler.go:43 +0x4f
> github.com/revel/log15.funcHandler.Log(0xc000150930, 0xc00081c3f0, 0xc00009a9d0, 0x40d4af)
> 	/go/src/github.com/revel/log15/handler.go:31 +0x30
> github.com/revel/log15.SyncHandler.func1(0xc00081c3f0, 0x0, 0x0)
> 	/go/src/github.com/revel/log15/handler.go:57 +0x91
> github.com/revel/log15.funcHandler.Log(0xc0000a8f00, 0xc00081c3f0, 0x7efff8bb8440, 0x0)
> 	/go/src/github.com/revel/log15/handler.go:31 +0x30
> github.com/revel/log15.LazyHandler.func1(0xc00081c3f0, 0xc0006e4500, 0xc000398bd0)
> 	/go/src/github.com/revel/log15/handler.go:295 +0x2e2
> github.com/revel/log15.funcHandler.Log(0xc0000a8f20, 0xc00081c3f0, 0x2, 0x2)
> 	/go/src/github.com/revel/log15/handler.go:31 +0x30
> github.com/revel/log15.CallerFileHandler.func1(0xc00081c3f0, 0xc00081c3f0, 0x0)
> 	/go/src/github.com/revel/log15/handler.go:101 +0x15b
> github.com/revel/log15.funcHandler.Log(0xc0000a8f40, 0xc00081c3f0, 0xc0007ac6a8, 0x5598af)
> 	/go/src/github.com/revel/log15/handler.go:31 +0x30
> github.com/revel/cmd/logger.(*CompositeMultiHandler).Log(0xc0000c6960, 0xc00081c3f0, 0x90, 0x8981c0)
> 	/go/src/github.com/revel/cmd/logger/handlers.go:224 +0x68
> github.com/revel/log15.(*swapHandler).Log(0xc00008e810, 0xc00081c3f0, 0x63dc99, 0xc000653ce0)
> 	/go/src/github.com/revel/log15/handler_go14.go:14 +0x77
> github.com/revel/log15.(*logger).write(0xc000092f00, 0x8e2cd3, 0x3d, 0x2, 0xc000653ce0, 0x2, 0x2)
> 	/go/src/github.com/revel/log15/logger.go:108 +0x214
> github.com/revel/log15.(*logger).Warn(0xc000092f00, 0x8e2cd3, 0x3d, 0xc000653ce0, 0x2, 0x2)
> 	/go/src/github.com/revel/log15/logger.go:154 +0x66
> github.com/revel/cmd/parser.appendAction(0xc0003c7d00, 0xc0007acae8, 0x94c5a0, 0xc00001e630, 0xc0003df170, 0x22, 0xc0003dd730, 0xb, 0xc0007acab8)
> 	/go/src/github.com/revel/cmd/parser/appends.go:137 +0x8fa
> github.com/revel/cmd/parser.processPackage(0xc0003c7d00, 0xc0003df170, 0x22, 0xc0003df140, 0x2a, 0xc000452a80, 0x0)
> 	/go/src/github.com/revel/cmd/parser/reflect.go:174 +0xac4
> github.com/revel/cmd/parser.(*processContainer).processPath(0xc000222060, 0xc0003df140, 0x2a, 0x94ec60, 0xc000434000, 0x0, 0x0, 0xc0003df140, 0x2a)
> 	/go/src/github.com/revel/cmd/parser/reflect.go:139 +0x4c2
> github.com/revel/cmd/parser.(*processContainer).processPath-fm(0xc0003df140, 0x2a, 0x94ec60, 0xc000434000, 0x0, 0x0, 0x0, 0x0)
> 	/go/src/github.com/revel/cmd/parser/reflect.go:48 +0x69
> github.com/revel/cmd/utils.fsWalk.func1(0xc0003df140, 0x2a, 0x94ec60, 0xc000434000, 0x0, 0x0, 0x0, 0xc000167178)
> 	/go/src/github.com/revel/cmd/utils/file.go:237 +0x1a5
> path/filepath.walk(0xc0003deff0, 0x2a, 0x94ec60, 0xc000434000, 0xc000222090, 0x0, 0x0)
> 	/usr/local/go/src/path/filepath/path.go:362 +0xf6
> path/filepath.walk(0xc0003dee40, 0x27, 0x94ec60, 0xc0003b5ba0, 0xc000222090, 0x0, 0x0)
> 	/usr/local/go/src/path/filepath/path.go:382 +0x2fe
> path/filepath.walk(0xc00032de90, 0x23, 0x94ec60, 0xc00032ed00, 0xc000222090, 0x0, 0x0)
> 	/usr/local/go/src/path/filepath/path.go:382 +0x2fe
> path/filepath.walk(0xc0000b4860, 0x17, 0x94ec60, 0xc000226000, 0xc000222090, 0x0, 0x30)
> 	/usr/local/go/src/path/filepath/path.go:382 +0x2fe
> path/filepath.Walk(0xc0000b4860, 0x17, 0xc000222090, 0x0, 0xc000026027)
> 	/usr/local/go/src/path/filepath/path.go:404 +0x105
> github.com/revel/cmd/utils.fsWalk(0xc0000b4860, 0x17, 0xc0000b4860, 0x17, 0xc00021e030, 0xc000167501, 0xc00021e030)
> 	/go/src/github.com/revel/cmd/utils/file.go:239 +0x96
> github.com/revel/cmd/utils.Walk(0xc0000b4860, 0x17, 0xc00021e030, 0xf, 0x0)
> 	/go/src/github.com/revel/cmd/utils/file.go:200 +0x49
> github.com/revel/cmd/parser.ProcessSource(0xc00012a780, 0xc0001678d0, 0x2, 0x2)
> 	/go/src/github.com/revel/cmd/parser/reflect.go:48 +0x167
> github.com/revel/cmd/harness.Build(0xc000136000, 0xc00012a780, 0xe, 0x0, 0x0)
> 	/go/src/github.com/revel/cmd/harness/build.go:43 +0xcc
> github.com/revel/cmd/harness.(*Harness).Refresh(0xc00009e8a0, 0x0)
> 	/go/src/github.com/revel/cmd/harness/harness.go:217 +0xd4
> github.com/revel/cmd/watcher.(*Watcher).notifyInProcess(0xc0000f2800, 0x947620, 0xc00009e8a0, 0x0)
> 	/go/src/github.com/revel/cmd/watcher/watcher.go:270 +0x10b
> github.com/revel/cmd/watcher.(*Watcher).Notify(0xc0000f2800, 0x0)
> 	/go/src/github.com/revel/cmd/watcher/watcher.go:214 +0x3c5
> github.com/revel/cmd/harness.(*Harness).Run(0xc00009e8a0)
> 	/go/src/github.com/revel/cmd/harness/harness.go:269 +0x199
> main.runApp(0xc000136000, 0x17, 0x2)
> 	/go/src/github.com/revel/cmd/revel/run.go:144 +0x798
> main.main()
> 	/go/src/github.com/revel/cmd/revel/revel.go:103 +0x20d

Dockerfile:
```
FROM golang:1.10.1

COPY . /go/src/dhq-central/
WORKDIR /go/src/dhq-central/

RUN go get github.com/revel/cmd/revel
RUN go get github.com/jinzhu/gorm
RUN go get github.com/kelseyhightower/envconfig
RUN go get gopkg.in/validator.v2
RUN go get github.com/go-sql-driver/mysql

ENV DHQ_USER root
ENV DHQ_PASS 4p1DHQdata.base

EXPOSE 9000 8080
CMD ["revel", "run", "9000"]
```

Docker-compose.yml:
```
database:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: 4p1DHQdata.base
web:
  build: .
  links:
    - database
  ports:
    - "9000:9000"
    - "81:8080"
  environment:
    DHQ_USER: "root"
    DHQ_PASS: "4p1DHQdata.base"
    DHQ_DB_HOST: "database:3306"
```

**Comment by lujiacn** [comment]
WARN 15:13:42 harness.go:170: No http.addr specified in the app.conf listening on localhost interface only. This will not allow external access to your application

try to define http.addr=0.0.0.0 ?

**Comment by usk83** [comment]
I suspect this issue might be something related to https://github.com/revel/cmd/issues/149.

**Comment by notzippy** [comment]
This is fixed in this milestone version
