### ISSUE TITLE
Impossible to access raw request body for application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by sinataghva** [revel/revel#1392]
Hello,

I'm receiving a POST body from Slack API which is not in JSON but in `application/x-www-form-urlencoded`.

While it's possible to get the values using
`value := c.Params.Form.Get("key")`
,I also need to get the whole raw body in order to validate the signature of the body that used a signing secret and a standard HMAC-SHA256 keyed hash as described here:
[](https://api.slack.com/docs/verifying-requests-from-slack)

The Slack API calculate the same value and put in the HTTP header. I need to do the same on the whole body and compare the values in order to be sure that the request is coming from Slack and not a third party.

When I use 
`body, _ := ioutil.ReadAll(s.Request.GetBody())`
, it's empty. As I read elsewhere, it's because the parser already read this buffer.

While I appreciate the work that the parser do to fill 
`controller.Params.(Fixed, Route, Query, Form, Files)`
we may still need to access to raw request body as they're legitimate way to do so. One example is verification of signature.

Can you please add a way to read raw request body in string or []byte? Or tell me if it's already possible which I doubt so because I already lost a day searching for that.

**Comment by notzippy** [comment]
Slack is interesting how it signs stuff
https://golang.org/pkg/net/http/#Request.ParseForm is what auto reads the body of the request into the Params, this calls [parsePostForm](https://golang.org/src/net/http/request.go?s=37937:37972#L1120). which reads the body and converts it (and by reading the body you lose access to it)

I have a couple of ideas of how to do the signature check.
1) Combine the controller.Params.Form object back into the bytes. I think this is likely the best since Revel can still parse your params for you automatically
2) Skip the `revel.ParamsFilter` by using [configuring filter](https://godoc.org/github.com/revel/revel#FilterConfigurator). This will stop parsing the form automatically

Let me know which one you choose

**Comment by notzippy** [comment]
Thought about it the first technic will not work, because revel juggles the map when you read it back. 

That leaves you the configuring filter, or making your own custom filter to do something like this 
```
realRequest := controller.Request.In.GetRaw().(*http.Request)
buf, _ := ioutil.ReadAll(realRequest.Body)
rdr1 := ioutil.NopCloser(bytes.NewBuffer(buf))
rdr2 := ioutil.NopCloser(bytes.NewBuffer(buf))

slackChecksumCheck(rdr1)
r.Body = rdr2 // OK since rdr2 implements the io.ReadCloser interface
```

**Comment by sinataghva** [comment]
Thanks, I'll try filters to see how it can be done.

**Comment by notzippy** [comment]
Closing since there was no further information added

**Comment by sinataghva** [comment]
Sorry for the delay, I was busy with other parts of the projet and had this issue on hold.

I followed your suggestion and it worked !

I copy the code here for future developers that might have the same issue.

I first defined a filter:

```
var SlackFilter = func(c *revel.Controller, fc []revel.Filter) {

	realRequest := c.Request.In.GetRaw().(*http.Request)
	buf, _ := ioutil.ReadAll(realRequest.Body)
	rdr1 := ioutil.NopCloser(bytes.NewBuffer(buf))
	rdr2 := ioutil.NopCloser(bytes.NewBuffer(buf))

	body, _ := ioutil.ReadAll(rdr1)
	c.Args["body"] = body

	realRequest.Body = rdr2

	fc[0](c, fc[1:])
}
```


Then in the `init()` function of my controller I wrote this:
```
revel.FilterController(Slack{}).Insert(SlackFilter,revel.BEFORE,revel.ParamsFilter)
```

This way I added my filter just before the `ParamsFilter` and I did this only for the controller that receives Slack requests.

I later acquire the body from `c.Args["body"]` to calculate the HMAC hash value and compare it with the value that is provided in the header.

**Comment by notzippy** [comment]
Fantastic @sinataghva , thanks for sharing your code, as a side note, I think you do not need `rdr1` at all but can set the args like `c.Args["body"] = buf`


As an additional note (for people looking at this in the far future) in the init of the main app the FilterConfiguringFilter needs to be enabled as well like
```
	// Filters is the default set of global filters.
	revel.Filters = []revel.Filter{
		revel.PanicFilter,             // Recover from panics and display an error page instead.
		revel.RouterFilter,            // Use the routing table to select the right Action
		revel.FilterConfiguringFilter, // A hook for adding or removing per-Action filters.
		revel.ParamsFilter,            // Parse parameters into Controller.Params.
```

**Comment by sinataghva** [comment]
You're right, my bad. I updated my code.
