### ISSUE TITLE
Possible to create a catch-all route that will reverse-proxy requests?

### ISSUE THREAD

**Issue by castrapel** [revel/revel#1402]
Hello,

I'm considering re-writing a Python Tornado web application in Go (Utilizing Revel). I'd like to have both services running concurrently and  basically like to have a catch-all route at the end of my revel routes file that will reverse proxy requests as-is to the Python service. That way I can write new routes / migrate existing routes on my own timeline, but keep both services operational with only one routes config.

I could also just have nginx/apache do the routing for me, but it would be nice to just have to maintain one simple routes file that would do it for me. I've read the routing section in the doc and this doesn't seem possible. Perhaps I could just have a catch all route that runs a Go function that will do it for me? 

Has anyone done anything like this before?

**Comment by notzippy** [comment]
Hi,

It certainly can be done. You need to write a filter that runs before the [RouterFilter] that checks if a route path could be found (similar to the [route filter code](https://github.com/revel/revel/blob/master/router.go#L749-L753)) If the MainRouter returns nil then do a proxy call to the python instance, and write the results into `controller.Response.GetWriter()`

In the next release (this week hopefully) I have added a catch all path function it operates first though (so it isnt a catchall). The man page is [here]( https://github.com/revel/revel.github.io/blob/develop/manual/custom-mux.md) 

If you have more questions feel free to chat on https://gitter.im/revel/community, 




```
