### ISSUE TITLE
Question: What is "workpermits" meaning   in JOB module 

### ISSUE THREAD

**Issue by OhBonsai** [revel/revel#1406]
I  am a newbie in golang .  When I saw JOB MODULE [source](https://github.com/revel/modules/blob/master/jobs/app/jobs/job.go#L58). 

```
	if workPermits != nil {
		workPermits <- struct{}{}
		defer func() { <-workPermits }()
	}
```

I wanna know what happen when workPermits is not nil . and why put a `struct{}{}` into workPermits

**Comment by OhBonsai** [comment]
I got it ...  workPermits  is the MAX RUNNING JOB NUMBER.
But why use `struct{}` type channel?

**Comment by notzippy** [comment]
Correct [workPermits](https://github.com/revel/modules/blob/master/jobs/app/jobs/plugin.go#L15) is the max number of concurrent jobs - it could have been a bool or anything really but that was the way it was done [6 years ago](https://github.com/revel/revel/blame/v0.8/modules/jobs/app/jobs/plugin.go)
