### ISSUE TITLE
close_wait issue in axis client

### ISSUE THREAD

**Issue by santha6693** [revel/revel#1408]
I am Using **org.apache.axis.client.Stub** for Stub Call but it causing many CLOSE_WAIT State.

Can any one please help me how to solve this Issue.

Thanks in advance.

**Comment by notzippy** [comment]
It sounds like the client is not closing the connection after the call you can specify read and write timeouts in the app.conf file `http.timeout.read` , `http.timeout.write` by default they are set to 0 so no timeout, by setting them the server should autoclose the connection. Timeout time is in seconds
