### ISSUE TITLE
Templating: impossible to *not* escape slashes inside <script>

### ISSUE THREAD

**Issue by daxorid** [revel/revel#1409]
If I have a type:

```
type FooBar struct {  
  Url string  
}
```

And in my controller:
```
foobar := FooBar { "https://www.example.com/foobar" }  
return c.Render(foobar)
```

And in my template:

```
<script type="text/javascript">
        var item = {
            Url: '{{.foobar.Url}}',
         }
</script>
```

The resulting template output is:

```
<script type="text/javascript">
        var item = {
            Url: 'https:\/\/www.example.com\/foobar',
         }
</script>
```

Nothing I do seems to fix the escaping of forward slashes. I have tried using template.URL, template.HTML, template.Js instead of string for the type. I have tried {{raw .foobar.Url}}. There appears to be no way to prevent Revel from doing this bizarre slash escaping.

If I change the `<script text="text/javascript">` element to `<script type="text/javazcript">` then the escaping stops, but of course I need to have the proper type attribute.

**Comment by notzippy** [comment]
Hi

THis has nothing to do with Revel, this is Go's html templating system being very secure aware. To prevent the escaping you can wrap certain fields in template types to prevent this - for [example](https://play.golang.org/p/fYg99G-aNVp) the [template.JSStr](https://golang.org/pkg/html/template/#JSStr) type will wrap prevent your issue with the script text being escaped.
