### ISSUE TITLE
revel log rotation is not working

### ISSUE THREAD

**Issue by johnwick03** [revel/revel#1414]
Following is my app.conf settings for logging into app.log file and log rotation:

log.trace.output = off 
log.info.output  = app.log
log.warn.output  = app.log
log.error.output = app.log
log.maxsize = 10         # The max file size before rotation in MB degault 10G

Ideally with these settings, app.log should rotate the logs once it hit 10MB size but instead it keeps growing beyond 10MB

**Comment by johnwick03** [comment]
log.trace.output = off
log.info.output  = stderr
log.warn.output  = stderr
log.error.output = stderr
log.maxsize = 1         # The max file size before rotation in MB degault 10G

**Comment by jameslai** [comment]
I have found this as well. It appears that Revel only checks the size of the logs during startup. If the existing log filesize exceeds the specified value during startup, the log will be rotated. However, if the service is in operation, it never periodically checks the size to rotate.

Therefore, in effect, the more successful your application is at living a long time, the more disastrously large the logfile can become.

If there is a decision to make action on this, I would also recommend that log rotation for time periods be considered as well in addition to filesystem. Rotating logs daily despite the filesize not being exceeded is a common requirement.

**Comment by mukeshjeengar** [comment]
I have submitted a fix for this bug.

Here the pull request
https://github.com/revel/revel/pull/1439
