### ISSUE TITLE
How to get http.ResponseWriter and http.Request

### ISSUE THREAD

**Issue by rps-repo** [revel/revel#1426]
I am trying to use a oauth2 server package with a revel project.  It needs http.ResponseWriter and http.Request for token requests.  How do I get this in a controller?

**Comment by notzippy** [comment]
Which package are you using ? Those can be extracted from the `controller.Request.In.GetRaw().(*http.Request)` and `controller.Response.Out.GetRaw().(*http.ResponseWriter)` . The reason they are abstracted is to allow for custom server engines.

**Comment by rps-repo** [comment]
Thanks for the quick reply.  `controller.Response.Out.GetRaw().(*http.ResponseWriter) ` does not work. 
` controller.Controller.Response.Out.GetRaw undefined (type revel.OutResponse has no field or method GetRaw)`
 I tried `controller.Response.Out.Server.GetRaw().(*http.Response)` that I found from change logs and get the error: 
`http.Response.Header is a field, not a method`

**Comment by rps-repo** [comment]
oh, and I am using this package; https://github.com/go-oauth2/oauth2

**Comment by notzippy** [comment]
Should be `controller.Response.Out.Server.GetRaw().(http.ResponseWriter)`
