### ISSUE TITLE
I don't use sqlite3, how to disable it

### ISSUE THREAD

**Issue by hinet** [revel/revel#1429]
I don't use sqlite3, how to disable it，I used MySQL in my project, but compiled SQLite3 incorrectly

`Failed to parse build errors             error="# github.com/mattn/go-sqlite3\nexec: \"gcc\": executable file not found in %PATH%\n"`

**Comment by hinet** [comment]
Why do I need sqlite3? I don't need it.

**Comment by pedromorgan** [comment]
just comment out the `import sqlite`

**Comment by notzippy** [comment]
There shouldnt be any packages that import this explicitly unless you added it to your app.conf [like this](https://github.com/revel/examples/blob/master/booking/conf/app.conf) it shouldn't be importing it.
