### ISSUE TITLE
revel support go mod build projects？

### ISSUE THREAD

**Issue by hinet** [revel/revel#1430]

**Comment by notzippy** [comment]
This is a feature that is being prepared for.

**Comment by hinet** [comment]
thanks. that's what I'm looking forward to. do you have a specific schedule?

**Comment by lealife** [comment]
+1  I'm looking forward to.

**Comment by cytown** [comment]
sure need support go mod!

**Comment by ptman** [comment]
https://github.com/revel/cmd/issues/177

**Comment by ptman** [comment]
Revel does support go mod now

**Comment by brendensoares** [comment]
If anyone has further questions or feedback, feel free to comment. Closing due to age and the fact that Revel does now support go modules.
