### ISSUE TITLE
Redirects are ignored in a BEFORE interceptor function

### ISSUE THREAD

**Issue by dmjones** [revel/revel#1433]
I'd like to be able to redirect to a URL from a `Before` interceptor. This doesn't appear to work:

```go
type BaseController struct {
	*revel.Controller
}

func (c *BaseController) Before() (revel.Result, *BaseController) {
	revel.AppLog.Info("Running before")
	return c.Redirect("http://www.google.com"), c
}
```

I get the log output, but the redirect is ignored. How can I redirect from an interceptor function? 

Minimal example application: https://github.com/dmjones/revel-interceptor-issue

**Comment by dmjones** [comment]
The [docs](https://revel.github.io/manual/interceptors.html#results) suggest:

> The effect of returning a non-nil revel.Result depends on When() the interceptor was invoked.
> 
> **1. BEFORE**
>   No further interceptors are invoked, and neither is the action.

This seems contrary to the code in github.com/revel/revel/before_after_filter.go, which looks like this:

```go
        // ...
	if resultValue := beforeAfterFilterInvoke(BEFORE, c); resultValue != nil && !resultValue.IsNil() {
		c.Result = resultValue.Interface().(Result).  // Here the value is indeed kept
	}
	fc[0](c, fc[1:]) // But here, the action is executed anyway
	if resultValue := beforeAfterFilterInvoke(AFTER, c); resultValue != nil && !resultValue.IsNil() {
		c.Result = resultValue.Interface().(Result)
	}
```

I'll submit a PR that fixes this.

**Comment by brendensoares** [comment]
@dmjones I've labeled this issue as best as I can. I'm grooming the backlog of open issues. Do you have any feedback for me on how to get this wrapped up?

**Comment by brendensoares** [comment]
It looks like we got this merged already. I'll close this for now assuming it has been delivered. Thanks!
