### ISSUE TITLE
Revel cannot create new application with command prompt

### ISSUE THREAD

**Issue by eikcalb** [revel/revel#1441]
Hello,

When creating a new application on my Windows machine using command prompt, I get the below error:

> CRIT  11:11:37 command_config.go:286: Abort: could not create a Revel application outside of GOPATH.

However, when using Bash for windows, the application builds successfully.

**Comment by notzippy** [comment]
What is your GOPATH environment variable set to in the windows environment ?

**Comment by eikcalb** [comment]
GOPATH is set to "c:/users/d.onaolap/go". This is the same as in my bash shell, but revel only works from bash not command prompt.

**Comment by Secret-Arya** [comment]
me too getting same error what to do now

**Comment by eikcalb** [comment]
Try running with powershell

**Comment by brendensoares** [comment]
@eikcalb I feel like I've seen this issue on Mac OS as well. Did you find a solution? I don't think this is a Revel issue as much as it is a Go env. config issue.

**Comment by eikcalb** [comment]
@brendensoares I could only get this to work using Powershell or git bash for Windows.

What's the experience when not using the default MacOS terminal?

**Comment by jhbelalc** [comment]
If you still have this problem, I fix it by adding a new line in command_config.go before the error, this is to be sure that **c.SrcRoot** has the same content of **c.GoPath** that is the path of our apps.
![change_in_Command_config_go](https://user-images.githubusercontent.com/5776255/79410873-1f32bf80-7f67-11ea-869e-af71f0a305a8.png)

`	
if len(c.SrcRoot) == 0 {
	c.SrcRoot = c.GoPath
}
`
after that you must recompile revel, i did it with the original go get command:
`go get github.com/revel/cmd/revel`
