### ISSUE TITLE
Hot reload not fully working

### ISSUE THREAD

**Issue by nikilase** [revel/revel#1446]
Hi, I'm very new to Revel so I first started with the Tutorial on their site. In their last chapter "Hello World App" they showcased adding a new view. After the step 
```GET     /App/Hello     App.Hello```
I waited a little bit and reloaded the Page. There the same error as the one mentioned at the start of the chapter still appeared. After I manually restarted revel and reloaded the Page it displayed the actual Page I was requesting. 
For me it appears, as though revel did not detect the change in `/conf/routes` or that it just didnt hot reload.
Did I not wait long enough?

**Comment by notzippy** [comment]
Hi and welcome - The routes path is not hot reloaded.
