### ISSUE TITLE
raw doesn't work in templates inside a tag

### ISSUE THREAD

**Issue by digininja** [revel/revel#1454]
I'm trying to use the [raw](https://revel.github.io/manual/templates-go.html#raw) function in a template to output an unencoded string. It works fine if I do it like this:

```
name = 'fred">x'
```

```
The name is: {{raw .name}}
```

Output:
```
The name is: fred">x
```

But if I put the variable inside a tag, it gets encoded when I don't want it to:

```
<p class="{{raw .name}}">aaa</p>
```

Output:
```
<p class="fredx%22%3e">aaa</p>
```

I'm building a deliberately vulnerable application and want to allow injection into the class name but can't.

I accept that this might be done to try to protect things, but if someone uses the raw function, it should work in a consistent way and give unencoded strings wherever it is used.

**Comment by lujiacn** [comment]
write a template function,  return "name" as template.HTML or template.JS format.

**Comment by digininja** [comment]
Got a pointer on how to do that?

**Comment by lujiacn** [comment]
`
"asHTML": func(value string) template.HTML {
		return template.HTML(value)
	},
"asJS": func(value string) template.JS {
		return template.JS(value)
`
inject functions to template, refer to: https://github.com/leekchan/gtf

**Comment by digininja** [comment]
Great thanks, I'll have a look at that.

**Comment by digininja** [comment]
Unfortunately that doesn't work. I created this function

```
    revel.TemplateFuncs["htmlSafe"] = func(html string) template.HTML {
        return (template.HTML(fmt.Sprintf("%s---%s", html, html)))
    }   
```

I put the repeated phrase in just to prove to myself that the custom function was being called. As you can see, it is, but something is still getting in the way when it is included inside the paragraph tags.

```
<p>
The name is: fred">x
</p>

<p>
The name in htmlSafe is: fred">x---fred">x
</p>

<p class="fred&#34;&gt;x">aaaa</p>
<p class="fred&#34;&gt;x---fred&#34;&gt;x">aaaa</p>
```

Any other ideas?

**Comment by digininja** [comment]
I've just found the code for `raw` and it is the same as the function your htmlSafe function

```
        // Skips sanitation on the parameter.  Do not use with dynamic data.
        "raw": func(text string) template.HTML {
            return template.HTML(text)
        },  
```

So looks like this approach on its own won't work.

**Comment by notzippy** [comment]
@digininja The http template function in Go is the one that is giving you the grief on this , if you created a function to render the whole attribute it would work, but Go templates will always encode attribute values. Here is an example of doing the entire attribute : https://play.golang.org/p/KcQ1_Cige0Y

**Comment by digininja** [comment]
Thanks, will check it out.
