### ISSUE TITLE
Redis cache not working

### ISSUE THREAD

**Issue by jonathanbrenman** [revel/revel#1455]
Hi all!

I'm trying to get redis with revel working but it is retrieving me error each time and change i do.
Could anyone let me know what I'm doing wrong??

I'm developing in Mac environment.

This what I do:
`err := app.RedisCache.Delete(key)
  if err != nil {
	fmt.Println(err)
  }`

And I'm getting this:

> runtime error: invalid memory address or nil pointer dereference
`In /github.com/garyburd/redigo/redis/pool.go (around line 275)

270:
	Done() <-chan struct{}
271:
	Err() error
272:
}) (*poolConn, error) {
273:
274:
	// Handle limit for p.Wait == true.
275:
	if p.Wait && p.MaxActive > 0 {
276:
		p.lazyInit()
277:
		if ctx == nil {
278:
			<-p.ch
279:
		} else {`

**Comment by notzippy** [comment]
Was there an initialization issue with this ?
