### ISSUE TITLE
HTTP and HTTPS dual mode

### ISSUE THREAD

**Issue by nikilase** [revel/revel#1456]
Is there any way to start the app/website both in HTTP and HTTPS mode so I can have support for devices which can't use the SSL certificate? 
Sorry if this is a dumb question but I am still new to revel and making websites

**Comment by notzippy** [comment]
The best way to do this is using something like a proxy pass (http://nginx.org/en/docs/http/ngx_http_proxy_module.html) for your web server. Having your Revel sit behind a webserver is the idealistic way of running it.

**Comment by nikilase** [comment]
Ok thanks for the tip :)
