### ISSUE TITLE
How to turn-off-logging

### ISSUE THREAD

**Issue by dtmkeng** [revel/revel#1464]
How to turn-off-logging 
```go
router := revel.NewRouter("")

	route := revel.NewRoute(appModule, method, path, action, "", "", 0)
	if err := router.Tree.Add(route.TreePath, route); err != nil {
		panic(err)
	}

	rc := new(RevelController)
```

**Comment by notzippy** [comment]
Logging can be turned off using the app.conf file, see documents for more information

**Comment by dtmkeng** [comment]
> Logging can be turned off using the app.conf file, see documents for more information

I don't use code from `revel cli` , app.conf can support ?

**Comment by notzippy** [comment]
You would need to modify the revel logger manually, you should check out the test module for how to do this using code
