### ISSUE TITLE
How to handle "Request Entity Too Large" ?

### ISSUE THREAD

**Issue by yuki2006** [revel/revel#1465]
After setting "http.maxrequestsize", what is the way to detect that the limit is exceeded in the application in order to display the custom error page of 413 (StatusRequestEntityTooLarge)?

**Comment by notzippy** [comment]
The default server adapter uses the http.MaxBytesReader to limit the amount https://github.com/revel/revel/blob/master/server_adapter_go.go#L135 , you can supply your own server adapter implementation to perform custom solutions
