### ISSUE TITLE
websocket hijack

### ISSUE THREAD

**Issue by ptman** [revel/revel#1468]
According to this article: https://hunter2.com/use-golang-these-mistakes-could-compromise-your-apps-security

**Comment by brendensoares** [comment]
@ptman have you looked at Revel's use of Go's websockets or do you have any idea of the level of effort to address this?

**Comment by ptman** [comment]
I have no idea. I just came across the article. There is even a fix suggested there.

**Comment by notzippy** [comment]
Websockets are ran through Revel filters, which is the CSRF module filter is included will implement the origin check
