### ISSUE TITLE
Compile options get treated as package name

### ISSUE THREAD

**Issue by Laur1nMartins** [revel/revel#1478]
The command `revel  -X qissm/app.Version=17 package -a qissm` results in an error that says that the command tried to import a package called `qissm/app.Version=17` ? Do i have to format my command differently ? To my knowledge i did what is referenced in your manual at https://revel.github.io/manual/tool.html. Can someone help me out ?

**Comment by Laur1nMartins** [comment]
The args value of cmd/harness/build.go:
`[/usr/local/go/bin/go build  app.Version=17 -ldflags -X qissm/app.AppVersion=git-376d175-dirty -X qissm/app.BuildTime=2019-11-28T14:20:45Z -tags  -o /Users/laurinmartins/go/bin/revel.d/qissm/qissm  app.Version=17 qissm/app/tmp]` This doesnt seem right at all.

**Comment by brendensoares** [comment]
@Laur1nMartins did you find a solution when digging through the code? Can you reproduce the issue with a new revel app (`revel new testapp`)?

Looks like this is likely an issue with  how the `cmd` repo is paring the args/flags. Any insight is appreciated since you've already done some digging.

**Comment by Laur1nMartins** [comment]
```
$ revel new testapp
$ revel run testapp -X someFlag=value

Revel executing: run a Revel application
WARN  12:13:10    run.go:151: No http.addr specified in the app.conf listening on localhost interface only. This will not allow external access to your application 
WARN  12:13:10 harness.go:218: Detected missing packages, importing them packages=5 
Error stack [utils.go:109 command_config.go:231 build.go:216 harness.go:218 watcher.go:271 watcher.go:215 harness.go:273 run.go:151 revelFork.go:110 proc.go:203 asm_amd64.s:1357]

ERROR 12:13:10  build.go:216: Failed to import package                 output="package someFlag=value: someFlag=value: invalid import path: malformed import path \"someFlag=value\": invalid char '='\n"  error="exit status 1" gopath=/home/laur1n/go GO-ROOT=/usr/local/go
ERROR 12:13:10 harness.go:218: Unable to resolve package                package="someFlag=value" error="exit status 1" 
ERROR 12:13:10  build.go:218: Failed to parse build errors             error="exit status 1" 
ERROR 12:13:10 watcher.go:271: Build detected an error                   error="Go Compilation Error: See console for build error."
```

Happens with a clean testapp as well. I will have a look if i can spot where the error comes from.

**Comment by Laur1nMartins** [comment]
I read through cmd/revel and it seems like no command has -X as available option in there usage description. On the page i mentioned in the first comment is says that -v and -X are available for all commands.

cmd/revel/build.go:39 ->
Is this where i would expect some kind of parsing to be done ? It seems like it is just missing.

**Comment by Laur1nMartins** [comment]
I was using the run command for revel so the corresponding parsing of arguments is in `cmd/revel/run.go:51`. There is also no mentioning of the -X or -v flags.

**Comment by Laur1nMartins** [comment]
If thats ok with you i would do some more digging this weekend and will state what i found tomorrow evening :)

**Comment by Laur1nMartins** [comment]
After more digging i am pretty sure that `cmd/harness/build.go:150 ` handles the c.BuildFlags wrong. But at the moment i seem to not get them inserted correctly.

**Comment by Laur1nMartins** [comment]
cmd/harness/build.go:141
```
		if appVersion == "" {
			appVersion = "noVersionProvided"
		}

		buildTime := time.Now().UTC().Format(time.RFC3339)
		versionLinkerFlags := fmt.Sprintf("-X '%s/app.AppVersion=%s' -X '%s/app.BuildTime=%s'",
			paths.ImportPath, appVersion, paths.ImportPath, buildTime)

		// Append any build flags specified, they will override existing flags
		flags := []string{}
		if len(c.BuildFlags) == 0 {
			flags = []string{
				"build",
				"-i",
				"-ldflags", versionLinkerFlags,
				"-tags", buildTags,
				"-o", binName}
		} else {
			if !contains(c.BuildFlags, "build") {
				flags = []string{"build"}
			}
			if !contains(flags, "-ldflags") {
				ldflags := "-ldflags= " + versionLinkerFlags
				// Add in build flags
				for i := range c.BuildFlags {
					ldflags += "-X '" + c.BuildFlags[i] + "'"
				}
				flags = append(flags, ldflags)
			}
			if !contains(flags, "-tags") {
				flags = append(flags, "-tags", buildTags)
			}
			if !contains(flags, "-o") {
				flags = append(flags, "-o", binName)
			}
		}
```
The above code fixed the issue. 
I will try and create a pull request tomorrow. Kinda failed to do that the last hour.

**Comment by Laur1nMartins** [comment]
https://github.com/revel/cmd/pull/179

**Comment by Laur1nMartins** [comment]
Closing this issue because it got merged into develop
