### ISSUE TITLE
Callback in RegisterModuleInit isn't called

### ISSUE THREAD

**Issue by goevexx** [revel/revel#1482]
I have 
```go
revel.RegisterModuleInit(func(m *revel.Module) {
    ...
})
```
in my modules. But `...` is never called.
I found out, that in `revel/revel/module.go` function `RegisterModuleInit` doesn't get the package path key in line 40.
```go
key := fmt.Sprintf("%+k", stack.Caller(1))
```
So all modules are mapped to "" in `appModule.initializedModules`. Following the docs "%+k " should get the package path. But it doesn't seem to work.

```shell
go version go1.13.6 windows/amd64
```

**Comment by goevexx** [comment]
Replacing imports does the trick

**Comment by notzippy** [comment]
Merged to develop branch
