### ISSUE TITLE
Error in Startup Log Upon deleting the views folder.

### ISSUE THREAD

**Issue by SidAceJog** [revel/revel#1486]
I am new to revel and go. So apologies if this is not quite correct.
I've got a revel REST API. Working fine. To shore it up I've deleted the public & views folders (since these aren't required).
While the app works fine. I get the following log in the console on startup:

`ERROR 12:05:36  revel  server.go:57: Watcher: Failed to stat watched path, code will continue but auto updates will not work error="stat /Users/xyz.yxz/work/go/src/test-api/app/views: no such file or directory"   section=util path=/Users/xyz.yxz/work/go/src/test-api/app/views
`
I've added 
`watch.templates = false` in the app.conf file.

The whole thing works just fine. But it is a bad log in the startup process.

**Comment by notzippy** [comment]
Have you removed the static module from your app.conf? that should fully resolve this issue (please reopen if it doesnt fix it). 

Remove this line:
```
module.static=github.com/revel/modules/static
```
