### ISSUE TITLE
revel/harness: app timed  out

### ISSUE THREAD

**Issue by alexyalinc** [revel/revel#1493]
```Revel executing: run a Revel application
←[32mINFO ←[0m 22:07:21    app     run.go:26: Running revel server
Revel proxy is listening, point your browser to : 9000
ERROR 22:08:20 harness.go:232: Killing revel server process did not respond after wait timeout. processid=15704 
ERROR 22:08:21 watcher.go:270: Could not start application              error="revel/harness: app timed 
out" 
```

This error appears when I run through revel run. At the same time, I am working on laptop battery.
If I run a project with power from 220w, then the project starts.
If I turn off watch mode. That project is launched from both the battery and 200w.

Platform: Windows 10 v2004
go version go1.14.1 windows/amd64
[[override]]
  name = "github.com/revel/modules"
  version = "0.21.0"

[[constraint]]
  name = "github.com/revel/revel"
  version = "0.21.0"

Where to find the reason for this behavior?

**Comment by ptman** [comment]
did it manage to bind to that port?

**Comment by chengkun-kang** [comment]
same issue, any advice? @alexyalinc
