### ISSUE TITLE
Support for 'sameSite' attribute for the revel_flash and revel_session cookies

### ISSUE THREAD

**Issue by chrishulbert** [revel/revel#1494]
Hi, it would be great to have support for 'sameSite' attribute for the revel_flash and revel_session cookies.

If i were to create a pull request where an app.conf setting allowed the sameSite to be specified, in a similar manner to 'cookie.secure', would that be something the project owners would consider merging?

Thanks

**Comment by chrishulbert** [comment]
Added support myself, please consider reviewing?
https://github.com/revel/revel/issues/1499

**Comment by ptman** [comment]
#1359
