### ISSUE TITLE
Post params is not bound 

### ISSUE THREAD

**Issue by lucasalcantara** [revel/revel#1495]
Hi guys, I have a form in my view and when I submit the request the model object is not bound along with the extra field which I am also sending it

Controller:
```
func (c Itinerary) Save(i *models.Itinerary, picture []byte) revel.Result {
	c.Validation.Clear()

	c.srv.Save(i, picture, c.Validation)
	if c.Validation.HasErrors() {
		c.Validation.Keep()
		c.FlashParams()

		return c.Redirect(routes.Itinerary.Index())
	}

	return c.Redirect(routes.Itinerary.Dashboard())
}
```

View:
 ```
<form action="{{url "Itinerary.Save"}}" method="POST" enctype="multipart/form-data">
    <p class="field">
        {{with $field := field "itinerary.Title" .}}
            <strong>Titulo:</strong>
            <input type="text" name="{{$field.Name}}" size="100" value="{{$field.Flash}}" maxlength="100"> *
        {{end}}
    </p>
    <p class="field">
        <strong>Imagem de apresentaçāo:</strong>
        <input type="file"  name="picture" accept="image/x-png,image/jpeg"> *
    </p>
    <input type="submit" value="Criar" onclick="document.getElementById('content').value = document.getElementsByClassName('ql-editor').item(0).innerHTML" />
</form>
 ```

Routes: (if helps)
 ```
GET    /itineraries/dashboard                   Itinerary.Dashboard
GET    /itineraries                             Itinerary.Index
POST   /itineraries                             Itinerary.Save
 ```

So basically when I submit this form the itinerary struct is totally empty
I hope I was clear enough and someone can help me with this problem. Thanks.

**Comment by notzippy** [comment]
Can you show what the browser is posting back to the web application (the posted data). Also the structure of the `model.Itinerary` would be helpful too. You can also share information here https://gitter.im/revel/community for a more interactive experience.

**Comment by lucasalcantara** [comment]
this is the view source of the form data
`itinerary.Title=title&picture=Screenshot+2020-05-29+at+10.27.37.png`

here is the model 
```
type Itinerary struct {
	ID            uint64     `db:"id"`
	Title         string     `db:"title"`
}
```

**Comment by Laur1nMartins** [comment]
Maybe adding 
`log.all.filter.module.revel = stdout`
to your `[dev]` section in your app.conf may reveal any errors that appeard during parsing?

**Comment by notzippy** [comment]
Were you able to resolve this @lucasalcantara ?

**Comment by lucasalcantara** [comment]
@notzippy Probably I was doing some silly thing. I just deleted what I did and rewrite it and, like magic, got resolved
