### ISSUE TITLE
Support for SameSite cookies

### ISSUE THREAD

**Issue by chrishulbert** [revel/revel#1499]
Hi all, thanks for Revel, it's great! :)

Browsers now give warnings for cookies that don't have SameSite or Secure set, that these cookies will be disabled soon. Now in production that's fine, we should have Secure set which is enough. However in local development (where you probably aren't using HTTPS thus cannot use Secure) this may become a problem soon.

So i've made a couple PRs for SameSite cookie support, would you please consider them?

https://github.com/revel/revel/pull/1498
https://github.com/revel/revel.github.io/pull/196

Thanks

**Comment by ptman** [comment]
#1359

**Comment by chrishulbert** [comment]
All merged, thanks very much!
