### ISSUE TITLE
debugging on vscode

### ISSUE THREAD

**Issue by iwasug** [revel/revel#1507]
![image](https://user-images.githubusercontent.com/41350556/91289577-baad2a00-e7bc-11ea-8f37-1f542dbaf80d.png)
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "env": {},
            "showLog": true,
            "program": "${workspaceRoot}/app/tmp/",
            "args": ["-importPath", "basic-crud", "-srcPath", "c:\\Users\\IWA SUGRIWA\\go\\src",  "-runMode", "dev"]
        }
    ]
}

**Comment by ptman** [comment]
Please don't post code as pictures. I have no idea what this issue is about. Please close.

**Comment by iwasug** [comment]
closed
