### ISSUE TITLE
Running a built binary fails with inexplicable "No such file or directory"

### ISSUE THREAD

**Issue by r32rf** [revel/revel#1517]
I built my application in a docker container, and after attempting to either run from run.sh or the binary the only output is:
```
bash: ./server: No such file or directory
```
the ./server file exists and is a proper ELF binary, so that can't be it.
Running from the provided run.sh offers no further clues as to what this could be:
```
./run.sh: 4: /home/r32/.../target/server: not found
```

**Comment by r32rf** [comment]
Building outside of a docker container results in an equally inexplicable 
```
Parsing packages, (may require download if not cached)...ERROR 16:21:42  revel.go:107: Unable to execute                        error="lstat : no such file or directory" 

```

**Comment by notzippy** [comment]
Is the path to the `server` wrong in the bash script?

outside of the container build can you post the verbose results ? (with the `-v` flag)

**Comment by r32rf** [comment]
I figured it out.  A OnAppStart interceptor was looking for a file that doesn't exist.
