### ISSUE TITLE
Revel fails hot reload on Windows 10

### ISSUE THREAD

**Issue by alexander-dc81** [revel/revel#1521]
Revel succeded to hot reload templates on changes, but fails to stop and restart after a change in the code (controllers, etc). Below -v output:

`INFO  11:00:29 watcher.go:208: Watcher:Notify refresh state             Current Index=0  last error index=-1 force=false refresh=true lastError=false
INFO  11:00:29 watcher.go:257: Waiting for refresh timer to expire
Changed detected, recompiling
INFO  11:00:30    app.go:136: Killing revel server pid                 pid=16168 
INFO  11:00:30    app.go:153: Waiting to exit
ERROR 11:01:30    app.go:159: Revel app failed to exit in 60 seconds - killing. processid=16168 killerror=nil 
INFO  11:01:30    app.go:129: Revel App exited                         state="exit status 1" 
INFO  11:01:30    app.go:165: Done Waiting to exit
INFO  11:01:30 harness.go:235: Rebuild Called
INFO  11:01:30  build.go:285: Cleaning dir                             dir=tmp
INFO  11:01:30  build.go:285: Cleaning dir                             dir=routes 
INFO  11:01:30 source_processor.go:31: ProcessSource
Parsing packages, (may require download if not cached)...INFO  11:01:30 source_processor.go:87: Reading packages                         parser=SourceProcessor packageList="[github.com/revel/revel/... github.com/revel/modules/static/... github.com/revel/modules/testrunner/...]" `

**Comment by notzippy** [comment]
Merged requested changes, marking as resolved - Thanks
