### ISSUE TITLE
Handle SIGTERM with ENGINE_SHUTDOWN_REQUEST

### ISSUE THREAD

**Issue by kunihiko-t** [revel/revel#1522]
I'd like to use revel.OnAppStop for graceful shutdown on ECS.
StopTask action on ECS will send SIGTERM to stop the application but revel.OnAppStop doesn't handle SIGTERM.
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_StopTask.html

Are you planning to add syscall.SIGTERM on this line?
https://github.com/revel/revel/blob/ee237a4ce4b7660dcbafda789dd6f524a4a4b47d/server_adapter_go.go#L219

Can I send a Pull Request?

**Comment by notzippy** [comment]
Yes we accept PRs - we had SIGTERM iitially but windows didnt accept it

**Comment by notzippy** [comment]
We already had one https://github.com/revel/revel/pull/1523 Merged to develop
