### ISSUE TITLE
Dependency injection with Revel, is it possible?

### ISSUE THREAD

**Issue by invasionofsmallcubes** [revel/revel#1527]
Hi, I was reading the [testing docs](https://revel.github.io/modules/testing.html) and it's not clear to me how I can inject the collaborators on a Revel controller.

Usually you create a struct like
```
type MyController struct { 
c Collaborator
}
MyController{c: Fake{}}
```

but honestly it's not clear to me how to do this with Revel.
Can you point me to the right documentation or explain how to do it? If this is not idiomatic, another way to inject a fake would be fine.

Thanks

PS: I found a suggestion on [stackoverflow](https://stackoverflow.com/questions/48984348/how-to-mock-service-from-controller-using-revel-framework-in-golang/60185759#60185759) but is less than ideal

```
type MyController struct {
    *revel.Controller
    Initialized   bool
    HealthService func() ([]byte, int)
}

func (t *MyController) init() {
    if !t.Initialized {
        t.Initialized = true
        t.HealthService = func() ([]byte, int) {
            return service.HealthService()
        }
    }
}

func (c MyController) HealthCheckHandler() revel.Result {
    c.init()

    responseBody, status := c.HealthService()
    c.Response.Status = status
    return c.RenderJSON(responseBody)
}

func TestHealth(t *testing.T) {
    mockFunction := func() ([]byte, int) {
        return []byte(`"message":"you custom body here"`), http.StatusOK
    }

    myController := &MyController{
        &revel.Controller{
            Response: &revel.Response{
                Status: 200,
            },
        },
        HealthService: mockFunction,
        Initialized:   true,
    }

    res := myController.HealthCheckHandler()
}
```

**Comment by notzippy** [comment]
Revel creates its own controller instances on the fly so you don't have to initialize them. Injecting / monkey patching the controller is not a real part of the process. That all said there is a method from within the testsuite you can override to invoke a kind of patching. The [Send](https://github.com/revel/revel/blob/master/testing/testsuite.go#L245) function is the one that instaniates an instance of the controller. You could implement this method yourself and create a Controller with a patched value for the test case.

**Comment by brendensoares** [comment]
I've done dependency injection as part of the app init and controller instance hydration. It's definitely possible, but, like ORM, there is no prescribed approach in Revel.
