### ISSUE TITLE
New Revel project doesn't run or build

### ISSUE THREAD

**Issue by caeril** [revel/revel#1533]
Revel modules depends on github.com/myesui/uuid, which doesn't exist. Any attempts to run or build a newly-created revel project fails:

```
[caeril@localhost src]$ revel new foobar
Revel executing: create a skeleton Revel application
Your application has been created in:
   /home/caeril/work/go/src/foobar

You can run it with:
   revel run -a  foobar
[caeril@localhost src]$ revel run -a foobar
Revel executing: run a Revel application
Downloading related packages ...ERROR 10:30:07 command_config.go:250: Failed to import package                 error="exit status 1" gopath=/home/caeril/work/go GO-ROOT=/usr/lib/golang output="go: finding module for package github.com/revel/modules\ngo: finding module for package github.com/stretchr/testify/assert\ngo: finding module for package gopkg.in/yaml.v2\ngo: finding module for package github.com/BurntSushi/toml\ngo: finding module for package github.com/myesui/uuid\ngo: finding module for package gopkg.in/stretchr/testify.v1/assert\ngo: finding module for package github.com/myesui/uuid/savers\ngo: found github.com/revel/modules in github.com/revel/modules v1.0.0\ngo: found github.com/stretchr/testify/assert in github.com/stretchr/testify v1.7.0\ngo: found github.com/BurntSushi/toml in github.com/BurntSushi/toml v0.3.1\ngo: found gopkg.in/yaml.v2 in gopkg.in/yaml.v2 v2.4.0\ngo: github.com/revel/modules@v1.0.0 requires\n\tgithub.com/myesui/uuid@v1.0.0: reading github.com/myesui/uuid/go.mod at revision v1.0.0: unknown revision v1.0.0\n" 
 completed.
Downloading related packages ...ERROR 10:30:09 command_config.go:250: Failed to import package                  error="exit status 1" gopath=/home/caeril/work/go GO-ROOT=/usr/lib/golang output="go: finding module for package github.com/revel/modules\ngo: finding module for package github.com/stretchr/testify/assert\ngo: finding module for package github.com/myesui/uuid/savers\ngo: finding module for package gopkg.in/stretchr/testify.v1/assert\ngo: finding module for package github.com/myesui/uuid\ngo: finding module for package github.com/BurntSushi/toml\ngo: finding module for package gopkg.in/yaml.v2\ngo: found github.com/revel/modules in github.com/revel/modules v1.0.0\ngo: found github.com/stretchr/testify/assert in github.com/stretchr/testify v1.7.0\ngo: found github.com/BurntSushi/toml in github.com/BurntSushi/toml v0.3.1\ngo: found gopkg.in/yaml.v2 in gopkg.in/yaml.v2 v2.4.0\ngo: github.com/revel/modules@v1.0.0 requires\n\tgithub.com/myesui/uuid@v1.0.0: reading github.com/myesui/uuid/go.mod at revision v1.0.0: unknown revision v1.0.0\n"
 completed.
ERROR 10:30:10   file.go:341: Unable to import this package            package=foobar/app 
ERROR 10:30:10   file.go:341: Unable to import this package            package=github.com/revel/revel 
ERROR 10:30:10  revel.go:107: Unable to execute                        error="Revel paths[error No revel found]" 
```

Right now I'm getting around this by copying and modifying my existing revel projects, but new ones neither run nor build.

**Comment by pdause** [comment]
I'm seeing the same behavior while trying to make an build machine.  I am almost certain it has to do with the twinj depending on myesui/uuid.  Looking around myesui has completely disappeared and twinj is archived and read only.  I'm going to copy the entire contents for the directories and hope it will build when it gets to the other machine.

**Comment by caeril** [comment]
Has anyone found a solution to this yet? Are there any plans to migrate to something other than twinj?

**Comment by caeril** [comment]
Ok, I got around this issue by just forking, renaming, and replacing twinj/myesui with google's uuid package.

The fork/rename was required only because I couldn't get the ridiculous go 11 modules system to stop re-downloading during a go clean -modcache after replacing the uuid dependency - it continued to demand the existence of the broken dependency unless the module name was changed.

**Comment by pdause** [comment]
@caeril Did you push a branch with this change?  I'm trying to setup docker for my project at the moment.  I forgot about this issue until I tried to pull everything from scratch.

**Comment by caeril** [comment]
> @caeril Did you push a branch with this change? I'm trying to setup docker for my project at the moment. I forgot about this issue until I tried to pull everything from scratch.

No, but I have my own fork with the workaround here: https://github.com/caeril/frevel

But please don't rely on it. For all I know I might just disappear like the dependency we're talking about, haha.

**Comment by brendensoares** [comment]
Well, it's been quite a couple years. Sad to see Revel is having issues like this. I'll do my best to get back into maintaining this project to at least merge key PRs like this. If anyone else has time to volunteer to assist, that'd be welcome!
