### ISSUE TITLE
jobs module not working with revel build

### ISSUE THREAD

**Issue by bwdxbfzco** [revel/revel#1537]
revel build do not run or include jobs module. it works with revel run (manually) but after build it doesn't work. Even the /@jobs stops to work.

**Comment by khanzadimahdi** [comment]
please add more information about the Revel and Goalng version you use.
do you see any errors? put your error logs here if you see any.

**Comment by bwdxbfzco** [comment]
Revel executing: displays the Revel Framework and Go version
Revel Framework :       Unknown (1.0.0 remote master branch)
Revel Cmd       :       1.0.0   (1.0.0 remote master branch)
Revel Modules   :       Unknown (1.0.0 remote master branch)


Go Location:/usr/bin/go

go version go1.13.8 linux/amd64

**Comment by notzippy** [comment]
resolved in commaind module https://github.com/revel/cmd/pull/210
