### ISSUE TITLE
no required module provides package github.com/bradfitz/gomemcache/memcache; to add it:

### ISSUE THREAD

**Issue by shashibyjus** [revel/revel#1539]
WARN  13:04:17  build.go:420: Could not find in GO path                file=../../go/pkg/mod/github.com/revel/revel@v1.0.0/cache/memcached.go 
ERROR 13:04:17 harness.go:239: Build detected an error                  error="Go Compilation Error (in ../../go/pkg/mod/github.com/revel/revel@v1.0.0/cache/memcached.go:11): no required module provides package github.com/bradfitz/gomemcache/memcache; to add it:" 

Error compiling code, to view error details see proxy running on http://:9000

**Comment by Laur1nMartins** [comment]
Using 
`go mod tidy`
fixes this error for me.

**Comment by brendensoares** [comment]
@Laur1nMartins so I need to run `go mod tidy` on revel to address this? I'll have to add this to the backlog.

**Comment by notzippy** [comment]
This is fixed with the PR https://github.com/revel/cmd/pull/210
