### ISSUE TITLE
could not clone the Skeleton source code

### ISSUE THREAD

**Issue by Menahem-Mendel** [revel/revel#1541]
Revel can't clone the skeleton

```
>> revel new -a app
Revel executing: create a skeleton Revel application
CRIT  13:23:19 revel_logger.go:59: Abort: could not clone the  Skeleton  source code:  path=https://github.com/revel/skeletons:basic/bootstrap4  output=
```

specs:
```
>> go version
go version go1.17.1 windows/amd64
```

**Comment by GlodevP** [comment]
Hi, it helped me to install git and mercurial [https://revel.github.io/tutorial/gettingstarted.html#install_git_and_hg](install guide)

**Comment by notzippy** [comment]
Yes git is part of the requirements see here http://revel.github.io/tutorial/gettingstarted.html#install_git_and_hg
