### ISSUE TITLE
Failed to import package=github.com/garyburd/redigo/redis 

### ISSUE THREAD

**Issue by gourlaa** [revel/revel#1545]
Hello Revel,

I can't build anymore because the package github.com/garyburd/redigo doesn't exist anymore.
What can I do?

Best regards,
Pierre

**Comment by gourlaa** [comment]
I just did a PR : https://github.com/revel/revel/pull/1546

**Comment by stanislav-bozhanov** [comment]
Same problem in our project

**Comment by gourlaa** [comment]
I sent an email to the author, the package has been temporarily restore
