### ISSUE TITLE
Revel on App Engine

### ISSUE THREAD

**Issue by arnaudbriche** [revel/revel#189]
Is it possible to run Revel on top of app engine ?? Would be really awesome !

**Comment by fnkr** [comment]
:+1: 

Any progress here?

**Comment by brendensoares** [comment]
@wlaurance bringing this thread back from the dead, is there anything you have learned regarding Go/Revel and GAE? I'm sure others would appreciate sharing your experience.

**Comment by JustinBeckwith** [comment]
Greetings folks!  I know this is a bit of an old thread, but I wanted to let you know I wrote a post on how to run revel on AppEngine.  It takes advantage of the new Managed VM feature:

http://jbeckwith.com/2015/05/08/docker-revel-appengine/

**Comment by brendensoares** [comment]
@JustinBeckwith great contribution! @anonx added it to our [Articles wiki page](https://github.com/revel/revel/wiki/Articles). Thanks!

PS - I'd love your feedback on Revel once you try some of the other frameworks and anti-frameworks :)
