### ISSUE TITLE
The <select name="{{$field.Name}}"> was not set "selected"?

### ISSUE THREAD

**Issue by Michael2008S** [revel/revel#212]
When I use the code in the issue https://github.com/robfig/revel/issues/203 :
    {{range $.answerType}}
        {{option $field (printf "%s" .Name) (printf "%s - %s" .Name .Describe) }}
    {{end}}

__________tpl Code___________
{{with $field := field "customerServiceQa.AnswerType" .}}
{{$field.Value}}
<  select name="{{$field.Name}}">
    {{range $.answerType}}
        {{option $field (printf "%s" .Name) (printf "%s - %s" .Name .Describe) }}
    {{end}}
</select>
{{end}}

_________Html__________

I can get the right {{$field.Value}}. But the option was not set "selected"

```
        option
        <select name="customerServiceQa.AnswerType">

                <option value="branch">branch - 分支</option>

                <option value="option">option - 选择</option>

                <option value="finish">finish - 完成</option>

                <option value="input">input - 输入</option>

        </select>
```

**Comment by jameslai** [comment]
`radio` and `checkbox` exhibit the old problem. Is the intention to never allow the native helpers to solve this issue and to utilize workarounds? I notice `option` evaluates both the `Flash` and `Value` methods, but `radio` and `checkbox` were never updated.

**Comment by olarriga** [comment]
I have the same problem. Option is not set selected. If I convert all to string (f.Value(), f.Flash and val) and do the comparaison with string it works.

**Comment by eparziale** [comment]
Actually, I was able to answer my own question by modifying the existing radio function from here: https://godoc.org/github.com/revel/revel#pkg-variables

This function works, and handles value as well as flash, just as in the current version of **option**

 ```
revel.TemplateFuncs["custom_radio"] = func(f *revel.Field, val string) template.HTML {
		checked := ""
		flash := f.Flash()
		value := fmt.Sprintf("%v", f.Value())
		if flash == val || flash == "" && value == val {
			checked = " checked"
		}
		return template.HTML(fmt.Sprintf(`<input type="radio" name="%s" value="%s"%s>`,
			html.EscapeString(f.Name), html.EscapeString(val), checked))
	}
```
