### ISSUE TITLE
Add abilty to push params to current template as field.flash

### ISSUE THREAD

**Issue by Jetvp** [revel/revel#221]
Hi,

I just made this patch which will push the current params to the field.flash not storing it in a cookie for the next event (after a redirect).  This allows the form to be returned directly instead of having to have two requests occurring.

https://github.com/Jetvp/revel/commit/b67c19c0aaebfbd818e6ffc0a597ac48bcc30397

**Comment by brendensoares** [comment]
### TODO
- [ ] decide if @Jetvp's commit is the best approach (consider alternatives, if any, and refine the API)

**Comment by notzippy** [comment]
Needs documentation

**Comment by notzippy** [comment]
Flash data is availabe in viewargs as is the controller
