### ISSUE TITLE
additional doc for the magical Render() functions

### ISSUE THREAD

**Issue by rbucker** [revel/revel#235]
when the Render() function needs to be called inside the declared function/route and does the magical template file lookup and function args... the documentation should be more clear.

**Comment by pedromorgan** [comment]
Olde bug so closing

**Comment by brendensoares** [comment]
@pedromorgan though this is old, I think we should leave it open as it's assigned to a future release (v0.13) and we'll need to consider it's suggestions on improving the documentation for `Render()` then. Do you agree? I'll wait for your reply before opening the issue again.

**Comment by pedromorgan** [comment]
apologies.. but yes .. after rereading .. will fix..

**Comment by notzippy** [comment]
The docs look much clearer now
