### ISSUE TITLE
GAE quickstart

### ISSUE THREAD

**Issue by Jetvp** [revel/revel#239]
Hi,

I know there is the GAE branch and had a quick look through it.  I was just wondering besides the obvious controller changes in the sample what else was required.  Did you have to do any special builds/changes to revel itself?

Thanks!

**Comment by fnkr** [comment]
:+1:

**Comment by brendensoares** [comment]
### TODO
- [ ] Define how to deploy a Revel app to GAE

**Comment by notzippy** [comment]
Closing issue until further interest is shown
