### ISSUE TITLE
Hot-reload doesn't work on OSX

### ISSUE THREAD

**Issue by kalnado** [revel/revel#25]
Just playing around with go and installed revel. Followed the tutorial http://robfig.github.com/revel/tutorial/ (only difference is I used another directory instead of `~/gocode`). 

Hot-reload doesn't work - neither for go files, nor for templates. The only situation where it does work is if I start the app with a compilation error – I see the error when first loading the app in the browser, then I can fix the error, reload the browser and see the error is gone. Further changes no longer trigger a re-compile though.

go version go1.0.2 (installed using homebrew) on OS X 10.8.2
go env:
GOROOT="/usr/local/Cellar/go/1.0.2"
GOBIN=""
GOARCH="amd64"
GOCHAR="6"
GOOS="darwin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOTOOLDIR="/usr/local/Cellar/go/1.0.2/pkg/tool/darwin_amd64"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread -fno-common"
CGO_ENABLED="1"

**Comment by davidroman0O** [comment]
Just to notify :) 

The issue still exists on OSX https://imgur.com/a/wv37xxy
Same thing on WSL2 on Windows 10

Just by doing the tutorial, it doesn't works
