### ISSUE TITLE
Interceptors for specific actions

### ISSUE THREAD

**Issue by pix64** [revel/revel#258]
I'm using an interceptor to get user information (from a database). Some actions though I would like to restrict access to logged in users. I wanted to use an interceptor for this because it would be convenient to so do, but interceptors work at the controller level.

I would like to do something like this

```go
revel.InterceptFunc(getUser, revel.BEFORE, &comments{})
revel.InterceptFuncAction(forbidGuests, revel.BEFORE, "comments.new")
```

The comments controller would contain actions should as view and new. In this case I would like for guests to be able to view comments, but not able to create new comments.

Does this sound reasonable? or should I restructure my app so actions which require the user to be logged in be in a separate controller?

**Comment by brendensoares** [comment]
Closing this in favor of #420. It seems composing a controller with a modified embedded controller would be an ideal for require auth per controller. You would then ideally be able to override the `Before()` method to base requirements on action as needed.
