### ISSUE TITLE
support for Server Side Event(SSE)

### ISSUE THREAD

**Issue by notedit** [revel/revel#262]
rails 4 has support SSE,   revel will support this?

**Comment by exherb** [comment]
@robfig

looks 

```go
f, ok := w.(http.Flusher)
w.Write(raw)
f.Flush()
```

is not working ...

**Comment by brendensoares** [comment]
@exherb @robfig doesn't maintain Revel any longer.

What are you expecting to happen and what is actually happening?

More details will help us help you. Also consider asking your question on stackoverflow.com with the `golang` tag.
