### ISSUE TITLE
Character missing under windows  when compiling Booking (Backslash plague ?)

### ISSUE THREAD

**Issue by bussiere** [revel/revel#270]
It seems that when making main.go it has some missing character under windows exemple ::
 It may be some kind of backslash plague ?

here \ontrollers instead of \controllers 

        C:\Documents and Settings\jmartinbertdel-tp\Mes documents\Mercurial\Gopa
        th\src\github.com\robfig\revel\samples\booking\app\ontrollers (from $GOPATH)

the output of my compilation 
https://github.com/bussiere/booking/blob/master/Error_Compiling_windows.txt

**Comment by anonx** [comment]
> how did #719 affect this?

@brendensoares Yeah, It didn't. I successfully reproduced the bug multiple times by reverting #719 and then merging it again.  But apparently it was just a coincidence.

**Comment by jeevatkm** [comment]
In-favour of #1054 and revel/cmd#46, revel will handle file path according to OS and without impacting revel import path handling.

I'm closing this one.
