### ISSUE TITLE
Hot compile is very slow

### ISSUE THREAD

**Issue by cswank** [revel/revel#290]
I've been working on a new revel app and have been switching back and forth between 2 computers.  On one computer the app builds in about 1 second, on the other it takes more than 30 seconds.  By "the app builds" I mean after typing revel run /path/to/my/app and then refreshing the browser and waiting for the page to load.

They are both running ubuntu 13.04, are both new computers with decent processors, both have go 1.1.1 installed.  I can get more info later (one of them is at work), but just wanted to see if anyone else has had problems with a slow build.  It makes development a challenge.

**Comment by poyannabati** [comment]
+1 on "go install github.com/mattn/go-sqlite3". 

Significantly reduced build time.

**Comment by pedromorgan** [comment]
Can someone explain why ?

So I can stick on the FAQ

**Comment by anonx** [comment]
@pedromorgan https://github.com/revel/revel/issues/290#issuecomment-52385218

**Comment by pedromorgan** [comment]
Yes apologies, I noticed that later..

Check the bottom of http://revel-docs.daffodil.uk.com/manual/faq.html

**Comment by roblillack** [comment]
I still think that somehow the ‘dependency detection’ is broken. If you look at my [comment above](#issuecomment-53533710), you'll notice that all the missing packages are dependencies not used by revel, but my custom controllers.
