### ISSUE TITLE
Modular, driver-based logger interface

### ISSUE THREAD

**Issue by goodsign** [revel/revel#316]
Hi Rob!

I'm one of the [seelog](https://github.com/cihub/seelog) package creators and I'd like to somehow integrate seelog to my revel projects without hacks.

What is the currently recommended approach to using custom log systems? 

Do you plan on adding some interface like

``` go
type SomeLogInterface interface {
    Log(level LogLevel, format string, vals ...interface{})
}
```

so that others could just easily plug in any log system they want? Or do you plan to use any other approach?

I've heard about future plans on glog, but I'm currently interested in case where I want to use something custom.

BTW I saw in your 'guidelines for contributing' that you considered integrating seelog. If  this is still what you plan to do, then I could help with that and contribute or consult with any seelog feature or best seelog integration practices.

**Comment by notzippy** [comment]
Logger PR submitted #1213
