### ISSUE TITLE
Using gdb with Revel

### ISSUE THREAD

**Issue by edp** [revel/revel#33]
I started to develop a web app with Go and Revel, and was wondering if there was a way to run my application under [gdb](http://golang.org/doc/gdb). Go itself has support for this but I don't know how to launch Revel with debugging symbols.

**Comment by brendensoares** [comment]
Debugging Revel apps with `gdb` is a common request needing an official answer.

### TODO
- [ ] Official guide on how to debug Revel code
- [ ] Enhancements to facilitate easy debugging (`revel debug`, IDE integration, etc)

**Comment by notzippy** [comment]
Closing - docs have intellij debugging now
