### ISSUE TITLE
run Revel on live site on port 80

### ISSUE THREAD

**Issue by tim-peterson** [revel/revel#331]
Can there be documentation somewhere for how to run Revel from a real live site on port 80? 

I set up Revel on localhost:8888 no problem but then when I went to my-live-site.com and ran:

```
run revel mylivesiteapp
```

I get the following error

```
ERROR 2013/10/01 12:58:15 harness.go:167: Failed to start reverse proxy: listen
tcp xx.xxx.xx.xx:80: cannot assign requested address
```

Adding Nginx as a proxy with [this nginx.conf](https://gist.github.com/tim-peterson/6774608) didn't help either.

The bottom line it'd be nice for newcomers such as myself to be able to see Revel in real live action. This would seem to help adoption.

**Comment by brendensoares** [comment]
@tim-peterson this is a good idea. I've noted it. We definitely want Revel to be easy to use and learn. Thanks!
