### ISSUE TITLE
Create new application in current directory

### ISSUE THREAD

**Issue by tejainece** [revel/revel#348]
When the following command is executed:

```bash
revel new ./NewApplication
```

The new project should be created in current working directory. Instead it is being created in $GOPATH/src/ directory.

**Comment by brendensoares** [comment]
Due to how Go requires packages to be inside of a `$GOPATH` we cannot support this request. Something related has been added to [detect the current `$GOPATH` you are in (if any)](revel/revel#1004).

Thanks for offering this feature idea.

**Comment by alkchr** [comment]
> Due to how Go requires packages to be inside of a `$GOPATH` we cannot support this request.

I think you can: https://github.com/revel/revel/issues/1004#issuecomment-221785882.
https://github.com/revel/cmd/commit/b85dd76b3efb094a382bffac8bae1c1e9d49ec90 added support of multiple `GOPATH`s but not of relative paths.

**Comment by brendensoares** [comment]
@alkchr I see what you're saying. We can add some logic to allow relative paths within a `$GOPATH`. It seems a little bit magical, but it should work as expected.

@jeevatkm shall we reopen this for v0.14?

**Comment by jeevatkm** [comment]
User mentioned:
> Instead it is being created in $GOPATH/src/ directory.

I would like to clarify this, is it relative path request or request for creating a project outside `$GOPATH/src`?

**Comment by pedromorgan** [comment]
What @tejainece mentioned...
`The new project should be created in current working directory. Instead it is being created in $GOPATH/src/ directory.`

Which seems a bit daft to me.

**Comment by alkchr** [comment]
@jeevatkm It doesn't matter. **It is possible** to support both absolute and relative paths with multiple GOPATHs. That's all we need to know. Whether we want to implement it or not and what's the priority of this issue is another question.

**Comment by alkchr** [comment]
Though wait, you about this issue, not #1004.

**Comment by jeevatkm** [comment]
@alkchr yes this issue, not #1004

**Comment by jeevatkm** [comment]
@alkchr - Thanks for clarifying. Please continue to share your thoughts on improving Revel.

@brendensoares - We are not reopening this issue.
