### ISSUE TITLE
Eagerly load templates in dev mode

### ISSUE THREAD

**Issue by tw4452852** [revel/revel#353]
Today, I rewrite my blog code (https://github.com/tw4452852/totorow), but when I run it in product mode, it return 500 status code when i visit the "/", but some other links(e.g. /rss) work well. 
So I change to the dev mode, everything is OK...

Many thanks for help!

**Comment by pedromorgan** [comment]
Is this issue valid or can it be closed ?

**Comment by anonx** [comment]
@pedromorgan Still valid.
