### ISSUE TITLE
Feature: `revel run` default to current detected package

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#389]
If we traverse up the path until we hit a "src" directory we should be able to detect the package path relative to the GOPATH.

This would save me from typing out the full package path (which is not often short).

Thoughts?

**Comment by jeevatkm** [comment]
@brendensoares I implemented here, have a look this [branch](https://github.com/revel/cmd/commit/b4514f2f162519d70306c0c46d16b0dfc84eb32c) :)

**Comment by jeevatkm** [comment]
I'm closing this in-favour of revel/cmd#56
