### ISSUE TITLE
Access Control, Asset Fingerprinting, Responders

### ISSUE THREAD

**Issue by ghost** [revel/revel#393]
First of all, thanks for a great framework! I really like what I have seen so far, and I am  evaluating a migration from Rails to Revel. The problem is that I would need feature parity for some important areas, which are:
- access control management
- responders -> setting response type and template based on accept headers
- asset fingerprinting

Now, I don't think Revel has these features "off-the-shelf" - but there might be some plugins or libraries that I can add?

**Comment by nullne** [comment]
So is there anything useful with access control in revel?

**Comment by notzippy** [comment]
@nullne There isn't a module written which fully implements an ACL library. You can implement a version of your own by using [interceptors](http://revel.github.io/manual/interceptors.html), which is what I have typically done in the past. We are looking at alternatives though which would integrate with the GORM module (revel/modules#32).
