### ISSUE TITLE
Graceful app shutdown hook

### ISSUE THREAD

**Issue by TripleDogDare** [revel/revel#397]
Currently Revel performs a process kill on the app. This doesn't give the app a chance to perform any actions before shutting down.

harness/harness.go:153-159
SHA: abc464838b1e45be6563b72b75f8b85a1bf6f771

``` go
        // Kill the app on signal.
        ch := make(chan os.Signal)
        signal.Notify(ch, os.Interrupt, os.Kill)
        <-ch
        if h.app != nil {
                h.app.Kill()
        }
        os.Exit(1)
```

Which eventually leads to
harness/app.go:83-92

``` go
// Terminate the app server if it's running.
func (cmd AppCmd) Kill() {
        if cmd.Cmd != nil && (cmd.ProcessState == nil || !cmd.ProcessState.Exited()) {
                revel.TRACE.Println("Killing revel server pid", cmd.Process.Pid)
                err := cmd.Process.Kill()
                if err != nil {
                        revel.ERROR.Fatalln("Failed to kill revel server:", err)
                }
        }
}
```

I'm thinking something like the following code used instead of AppCmd.Kill() could solve the problem. I don't know if it would be possible to make the timeout configurable.

``` go
// Terminates a server
func (cmd AppCmd) Terminate() error {
        revel.TRACE.Println("Terminating revel server pid: ", cmd.Process.Pid)
        cmd.Cmd.Signal(os.Interrupt)
        select {
        case <-cmd.waitChan():
                return
        case <-time.After(10 * time.Second):
                revel.TRACE.Println("Timeout; Force kill revel server pid: ", cmd.Process.Pid)
                cmd.Process.Kill()
                return
        }
        panic("Impossible")
}
```

**Comment by markus-wa** [comment]
Considering this still has not been implemented yet, are there any plans to do so?

**Comment by winduptoy** [comment]
Am I correct in stating that there is no way to cleanly shutdown a database connection when the server is shutdown since this hook does not exist? The booking sample application only opens a database connection.

**Comment by notzippy** [comment]
@winduptoy PR #1224 has an implementation of graceful shutdown, but I was hesitant in implementing it because the version requirement was go 1.8

**Comment by intel352** [comment]
@notzippy I assume it's possible to check go version from within the code. Perhaps integrate the graceful shutdown, but gate it behind a minimum version check?  That way the overall package is still usable for older environments, while at least getting the functionality implemented.
