### ISSUE TITLE
Authorization or acl support?

### ISSUE THREAD

**Issue by YueHonghui** [revel/revel#409]
Is there authorization or acl or rbac implementation in revel or golang? Will this be supported by revel in future? I searched such library, but didn't found good implementation by golang.

**Comment by hsluoyz** [comment]
Hi, I'm the author of [casbin](https://github.com/hsluoyz/casbin). It is an authorization library that supports models like MAC, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.

Of course you can also don't use RBAC at all, and only use the basic ACL model. casbin can be highly customized to adapt to multiple scenarios.

Please consider it and let me know if there's any question:)

**Comment by notzippy** [comment]
Duplicated
