### ISSUE TITLE
track current Revel version

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#418]
Along with git tagging, we should add a `VERSION` file in the root of the revel package and expose it to Revel apps.

**Comment by pedromorgan** [comment]
Also #474

**Comment by pedromorgan** [comment]
Having it in a version.txt file file solved a lot of porblem with flightgear... compiling docs, cmake et all...

In the meantime, one possibility for the docs is to use a data file..
like
https://github.com/pedromorgan/revel.github.io/blob/pedro/_data/version.yaml
and appears on the homepage
http://revel-docs.daffodil.uk.com/

**Comment by brendensoares** [comment]
@pedromorgan I really like that YAML file idea. Is that a jekyll feature? Can it read from remote domains?

**Comment by pedromorgan** [comment]
yes the _data directory is a jekyll feature..
http://jekyllrb.com/docs/datafiles/

Dont think it will work on remote domain, but could be scripted I suppose

**Comment by brendensoares** [comment]
The PR#858 may not be perfect, but it's present. Closing.
