### ISSUE TITLE
Controller Before() / After()

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#420]
Would be nice if all controllers had before and after methods that ran automatically if present.

**Comment by brendensoares** [comment]
This needs its own RFC. I'll take ownership of it.

**Comment by pedromorgan** [comment]
Here's a snippet from a pylons/py2 application in production, and port in progress to revel.

One of the pains is adding intercept* 

Note some of these "requests" come from
- LAN  = IP address alows browsing (in building)
- Public = some controller not need authentication in this case
- A POST requires authentication etcc


```
class RpcAccountsController(BaseController):
		
	def __before__(self):
		self.auth, self.staffUser = auth.check_session(request, is_staff=True)
		
		
	##======================================================================
	@jsonify
	def accounts(self):
		
		payload = dict(success=True, auth=self.auth)
		if not self.auth:
			return payload
```

**Comment by notzippy** [comment]
Merged
