### ISSUE TITLE
Disabling jobs module

### ISSUE THREAD

**Issue by ottob** [revel/revel#438]
According to the [docs](http://robfig.github.io/revel/manual/jobs.html) it should be possible to disable the jobs module by removing the `module.jobs = github.com/robfig/revel/modules/jobs` line from app.conf.

I've tried this. But on startup revel still prints `Go to /@jobs to see job status.` and my jobs are being run.

Bug?

**Comment by brendensoares** [comment]
### TODO
- [ ] refactor `ProcessSource()` to selectively process app code as needed
- [ ] verify this fixes the unexpected loading of modules like `jobs`

**Comment by notzippy** [comment]
If your code imports from jobs, then the builder will pull in the jobs module and start them. 
It would be better to have a configuration setting to enable or disable adding the jobs.
