### ISSUE TITLE
Fully qualified controller naming

### ISSUE THREAD

**Issue by plestoon** [revel/revel#445]
suppose i have two controllers both named UserController under controllers/api/v1/ and controllers/api/v2. since controllers is currently only indexed by their names,  please add support for fully qualified package name in the routes file.

**Comment by brendensoares** [comment]
This needs its own RFC in `revel/rfcs`. @plestoon @NitroKKX can you take ownership of this?

**Comment by notzippy** [comment]
#1185 closes this
