### ISSUE TITLE
Evaluate Revel version numbering and package dependencies

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#474]
Python's recent attempt at formal version numbers: http://www.python.org/dev/peps/pep-0440/ This may be a bit overboard for Revel's use, but it's worth discussing.

GoPM seems to be a pragmatic solution to the package management issue Go is facing. https://github.com/gpmgo/gopm It aims to be backwards compatible with `go get`.

**Comment by pedromorgan** [comment]
Is there a way to "embed" the version number in the docs also.. automatically ??

eg latest relase is {{version}} - but that comes automatically from revel source ??

**Comment by brendensoares** [comment]
@pedromorgan not that I can find. Maybe we should manually add "Tested against Revel vMj.Mn.Pt"? We could use automated tests to help verify the docs are all valid, but that may need additional effort in order to accomplish that in an effective way.

**Comment by notzippy** [comment]
the revel/meta package takes care of this
