### ISSUE TITLE
Support for Params object (include request.body)

### ISSUE THREAD

**Issue by TeemoWan** [revel/revel#488]
Now, All request parameters are collected into a single Params object. That includes:

URL Path parameters
URL Query parameters
Form values (Multipart or not)
File uploads

but request body parameters are not collected into a single Params object. examaple: angluar's json request.

my english is poor, hope you understand,sorry

**Comment by rendon** [comment]
@smothers :+1: After a while trying to read some JSON from the request body this line did the trick.

    content, _ := ioutil.ReadAll(c.Request.Body)

**Comment by notzippy** [comment]
JSON is now collected as well
