### ISSUE TITLE
Access to any project files using Static module

### ISSUE THREAD

**Issue by mcheng89** [revel/revel#503]
By passing the prefix param in the url, I am able to access code under the application directory.

Examples: 
/tmp/main.go?prefix=app/
/routes?prefix=conf/

**Comment by pedromorgan** [comment]
ok @alkchr I wanna stick your above post in the manual  http://revel.github.io/manual/parameters.html

is that ok. .snag for me is the pages of app.conf and paramaters need to be on same page .. maybe
