### ISSUE TITLE
Using objects for filesystem paths instead of strings

### ISSUE THREAD

**Issue by ghost** [revel/revel#505]
Can we use something more elaborate for storing filesystem paths, to abstract operating system differences? Here's my try at porting the python's [pathlib](http://docs.python.org/3.4/library/pathlib.html) module (see also [PEP-0428](http://www.python.org/dev/peps/pep-0428/)):
https://github.com/opennota/pathlib

**Comment by brendensoares** [comment]
@anonx @pushrax this is related to #260 right?

**Comment by anonx** [comment]
@brendensoares Right, and it is labeled for consideration in v0.12.
I personally have never felt comfortable concatenating paths and making that kind of stuff. That's too fragile. So, I'm :+1: the idea of using some abstraction layer instead. Haven't investigated whether pathlib fits our needs or something else is required, though.

**Comment by brendensoares** [comment]
#270 looks related
