### ISSUE TITLE
Issue labels

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#545]
We should define what each label means and its usage.

For example, the different between `feature` and `enhancement`. I would say a `feature` is a free standing addition to Revel while an `enhancement` is a modification to an existing `feature`.

Do we need `contributor ready`? What about `templates`?

Do we need to add any new labels?

**Comment by pedromorgan** [comment]
Am adding all sort of labels now, 2015 styleeeeeeeee ;-)) and close this one its 2015 yipeeeeeee!!!!!!!!

**Comment by anonx** [comment]
@pedromorgan Cool. The only thing I'm missing is a clear list of criterias. For example, how long it is ``bug`` till it becomes ``OOps`` :) ?
By the way, wouldn't we offence someone if we add ``mad-ideas`` label to their issue? Or is it like a label just for internal use?

**Comment by brendensoares** [comment]
@anonx rofl yes we should remove `mad-ideas`. @pedromorgan can you add a wiki page with definitions for each of your suggested labels? Also, let's try to keep the labels serious. It's funny, but the focus shouldn't be our silly labels.

Golang has some useful labels to consider as well: https://github.com/golang/go/issues

**Comment by brendensoares** [comment]
FYI, I changed `mad-ideas` to `ambitious-ideas` for now. I think these mean the same thing without any negative feeling.

The labels I'd like to see
- effort level
  - `effort-minutes`
    Will take up to 60 minutes to implement.
  - `effort-hours`
  - `effort-weeks`
    These should be broken up into smaller items, we should never accept issues this large; too much uncertainty/risk
- priority level (http://en.wikipedia.org/wiki/MoSCoW_method)
  - `priority-could`
  - `priority-should`
  - `priority-must`
  - `priority-immediate`
- accepted status
  - `accepted`
  - `accepted for contribution`
    This may be more appropriate for low priority issues that the core team won't accept soon. Same meaning, at least to me, as `contributor ready`.
  - `declined`
- `needs RFC`
  If so, someone must take ownership of drafting the RFC. This should replace the current `feature` and `enhancement` labels. I feel like `bug`s should have their own RFC format to include reproduction steps, expect outcome vs actual, tested versions, etc. `support` labels should not be needed anymore if we force everyone to use stackoverflow.com.
- `discuss` status
  - `waiting for reply`
  - `more details needed`
  Not sure if these are needed or not. It seems any additional detail should be in an RFC. Thoughts?
- topic categories
  - `controller`
  - `log`
  - `template`
  - `modules`
  - `docs`
  - etc, more ideas wanted.

**Comment by anonx** [comment]
Wow, @brendensoares your classification is super awesome. ``more details needed``  is needed, IMO.
+ topic categories: testing (or testsuite), router, samples, harness, revel cmd.

**Comment by pedromorgan** [comment]
I just added these in a night to "get the picture".. so afaik there is no harm in nuking some, adding a few like @brendensoares suggested above, et all...

Also we must bear in mind that a more than one label for a bug, eg controller+template as some of these issues crossover..

**Comment by brendensoares** [comment]
@pedromorgan no worries, all your effort has been valuable. Keep it up!

As far as overlapping labels, that's fine. I expect to see a single issue with multiple tags: `bug` `priority-immediate` `controller` `template` `effort-minutes`. Agreed?

**Comment by brendensoares** [comment]
I've added the labels and decided to not add `accepted for contribution` and instead cover that with both `accepted` and `contributor ready`.

Now we just need to start using the new labels. In order to decide priority, effort and accepted/declined, we need to decide to meet each week to review RFCs and bug reports. How does Sunday sound? We could limit the weekly meeting to 30 minutes or less.

**Comment by brendensoares** [comment]
I prepended all topic category labels with a hash `#` to signify its use as a tag. I don't know if all of our topic tags are needed, but we can prune them as we maintain Revel.

I also color coded and grouped the new labels. It's all looking much more organized now. Hurray!

**Comment by pedromorgan** [comment]
It would be handy if you pinged me when on IRC

**Comment by brendensoares** [comment]
@pedromorgan I normally do, but I'll make sure I do more often.
