### ISSUE TITLE
Named routes

### ISSUE THREAD

**Issue by landaire** [revel/revel#547]
This would be an enhancement to reverse routing, but named routes would be a great addition to current reverse routing. Currently reverse routing works by using the method signature: `routes.Controller.Action(args)`. It'd be nice to have named routes so if the action or controller name ever changed, you would only have to update the routes file. [Here is how Rails implements this in the routing file](http://guides.rubyonrails.org/v2.3.11/routing.html#named-routes). A new method for calling the route by name could be added to the router, for something like `routes.Generate("route_name", args)`.

**Comment by notzippy** [comment]
Closing see namespace . #1185
