### ISSUE TITLE
Remove HTTPS from Revel

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#549]
As mentioned by @pushrax, Revel is currently handling functionality that it doesn't need to, such as HTTPS.

We need to consider what Revel could do without to enhance separation of concerns and increase the focus of Revel.

@revel/core Thoughts?

**Comment by brendensoares** [comment]
https://github.com/revel/revel/issues/918#issuecomment-89431129 @jniltonho wants to keep HTTPS support.

**Comment by notzippy** [comment]
Server engine allows this to be done
