### ISSUE TITLE
Expose http.Handler

### ISSUE THREAD

**Issue by bobobo1618** [revel/revel#553]
Sorry if this has already come up before, I feel like I've wanted it long enough that everyone should have argued to their heart's content.

Anyhow, I'd like for Revel to expose the `http.Handler` and allow another package to set up the `main` method and run the application.

Exposing it in this manner would open up a lot of possibilities, particular with integration with other libraries and the Go ecosystem in general (AppEngine is among the things that could be done with this I believe).

Plus, it lets other people take care of things like HTTPS (#549) by just running Go's built in `ListenAndServeTLS`.

Without this, I feel that Revel's cutting itself out of a large portion of the ecosystem, distancing itself needlessly from the great work being done by other projects.

**Comment by notzippy** [comment]
Issue #1156 allows for a custom server engine which will allow any implementation
