### ISSUE TITLE
Pluggable logger

### ISSUE THREAD

**Issue by pushrax** [revel/revel#554]
For production applications, having structured log output is a must (e.g. JSON). It would be cool if you could set up Revel to send its logs out to a formatter before printing.

Since there is no standard "Logger" interface, implementing this is a bit annoying. A co-worker wrote https://github.com/Sirupsen/logrus which I really like, but it wouldn't be great to introduce a dependency just for this. One option could be to copy out this interface:

``` go
type StandardLogger interface {
    Print(...interface{})
    Printf(string, ...interface{})
    Printfln(...interface{})

    Fatal(...interface{})
    Fatalf(string, ...interface{})
    Fatalln(...interface{})

    Panic(...interface{})
    Panicf(string, ...interface{})
    Panicln(...interface{})
}
```

and set it to a `log.Logger` by default.

Alternatively, we can introduce our own formatter interface, with the default being Revel's current formatting.

Thoughts?

**Comment by janekolszak** [comment]
Maybe this will help anyone: https://github.com/janekolszak/revfluent
It's a small Revel + Fluentd logger.

**Comment by littlexiang** [comment]
seems writing a module to override the revel.LOGGER is a good way
