### ISSUE TITLE
Watch "pkgs" directory for code changes

### ISSUE THREAD

**Issue by landaire** [revel/revel#559]
In a few of my apps I have business logic which doesn't really belong in a controller, so I added an `app/pkgs` directory which looks like this:

```
app
├── pkgs
│   ├── some_namespace
│   │   └── package_api.go
│   └── some_other_namespace
│       └── other_logic.go
```

Then, in my controller I'm able to use `import "app_name/app/pkgs/some_namespace"` or the other to import that code but separate it out from my other controllers.

I was thinking that it'd be really useful to add functionality to Revel which would watch the `pkgs` directory and recompile as needed similar to how we already do for controllers and other files. Right now if I make modifications to these files I have to run `go get ./app/pkgs/some_namespace/...` then restart the application, which is kind of annoying.

My current path probably isn't ideal and the directory to be watched should be in the app root, but would this be a welcome addition?

**Comment by notzippy** [comment]
Closing If people still need revel to watch the entire gopath, please re-open
