### ISSUE TITLE
Remove 30 second sleeps from CI

### ISSUE THREAD

**Issue by pushrax** [revel/revel#613]
There is a series of `sleep 30` commands in the Travis build sequence. They exist to prevent an occasional error of some kind.

It would be awesome to kill them and reduce CI time from several minutes to seconds.

**Comment by mark-adams** [comment]
Also, is there any reason that "revel test" can't just launch the app with a random unused port?

**Comment by oinume** [comment]
I removed `sleep 30` of each `revel test` and got no failure, can't we remove that?
https://github.com/revel/revel/pull/1025
