### ISSUE TITLE
List of Revel apps

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#616]
@landr0id could you do a search on github and find as many Revel apps, modules, etc that you can find and add it to a page on the wiki?

I think it'd be a good idea to begin building the community and exposing how others are using Revel.

Side note, I've already found 2 blogs coded in Revel, simple though they are. I'd still like to move forward with the Gobl repo to build an example blog application to both demo Revel (user auth, DB models, templates, etc) as well as have a more concrete point of reference for testing ideas and features.

[Current Revel App List](https://github.com/revel/revel/wiki/Apps-in-the-Wild)

**Comment by dbriemann** [comment]
I didn't find a way to make a pull request for the wiki page.. seems that is not possible on github? 
However you may add my latest Revel project if you like:
- https://namesmith.io - Business Name Generator and Domain Name Search

It's all done with Revel. Great framework!

**Comment by alkchr** [comment]
@dbriemann :+1: Great project. Exact thing I was looking for.

**Comment by brendensoares** [comment]
@dbriemann added :)

**Comment by goors** [comment]
This is my github clone written in Go and Revel: https://murphy.rs.
 I will make it open source soon. Just to find some free time.

**Comment by brendensoares** [comment]
Added murphy.rs @goors

**Comment by alkchr** [comment]
According to the [blog post](http://axialcorps.com/2013/10/24/axial-lyceum-go-crash-course/) and cookie names, there is also https://www.ties.com.

**Comment by brendensoares** [comment]
nice find @alkchr
