### ISSUE TITLE
Change RenderArgs to ViewArgs

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#622]
I'd like to rename `RenderArgs` to `ViewArgs` and possibly even create a  `View` model object that every controller instance (read: request) has.

This naming convention seems more appropriate for an MVC web app. It almost feels to me that a `Template` should not be a first-class citizen; it should be a parameter on a `View` object. This should allow us to more easily and logically modularize the template engine used to generate a controller result.

**Comment by pedromorgan** [comment]
This is a sill issue, around naming convention..

So renderArgs works, cos u are rendering a html out
it also works with pdf, with rendering a page,
even rendering an svg..

The idea is that stuff is passed onto something to "render" it.. 
now views/ is what seome people call it templates/ another et all..

So on that note, I wanna close it.. cos I dont see any point in this debate..

**Comment by brendensoares** [comment]
@pedromorgan this issue also has the idea of a `View` object instance that is related to template handling. It is better than `Render` because Revel uses MVC and the "V" isn't used in Revel currently.

**Comment by pedromorgan** [comment]
Who's gonna shit and get off the pot ? ;-)

**Comment by shawncatz** [comment]
This was resolved as part of #1138

**Comment by pedromorgan** [comment]
xref in docs https://github.com/revel/revel.github.io/pull/114/commits/422c9278cb26108a053babab60109ddaa0ed99ab
