### ISSUE TITLE
Add extension support to `conf/routes` via `pathtree`

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#659]
I've setup the following routes, attempting to use one handler for all, ie 
/airport.EGLL.html, /airport.EGLL.json and  /airport.EGLL.xml.
made it large for readability
# /airport/:ident.:ext

```
 GET     /airport/:ident.:ext       Airport.AirportHandler
  #GET     /airport/:ident.html         Airport.AirportHtml
  #GET     /airport/:ident.json         Airport.AirportJson
  #GET     /airport/:ident.xml          Airport.AirportXml
```

And my current handler is

```
func (c Airport) AirportHandler(ident, ext string) revel.Result {

    data := navdb.GetAirport(ident) 
    switch ext {
        case "json":
            return c.RenderJson(data)

        case "xml":
            return c.RenderXml(data)
    }
    return c.Render(data)
}
```

However I get a 404 not found..I'm expecting  to assign the part after the dot.

**Comment by notzippy** [comment]
Do this and fix the issue with wildcard mapping being prioritized before other mapping

**Comment by notzippy** [comment]
TODO
 [ ] Fork https://github.com/Jetvp/pathtree/commits/master

**Comment by notzippy** [comment]
This is resolved now . If not please re-open
