### ISSUE TITLE
Symbolic Walker

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#673]
Per @pushrax and @verdverm's comments on #555, we need a general walker function that is able to walk symbolic links. This is used in multiple places noted below (copied from #555):

draft: https://gist.github.com/verdverm/75b036439591ac0ef47e

we should probably call it:   `revelWalk`

There are walk functions, which make use of `filepath.Walk`, in...
 - `watcher.go`
 - `template.go`
 - `i18n.go`
 - `harness/reflect.go`

**Comment by jeevatkm** [comment]
Generic `Walk` is [implemented and improved](https://github.com/revel/revel/commit/ff67cb9752654097fc1af8214eaeb7ba6149ccd0) as part this PR #867.

Also `revel/cmd` related changes ([1](https://github.com/revel/cmd/commit/6005ac35f74eabf3ea77074dee7bd55692478ff4) & [2](https://github.com/revel/cmd/commit/1f8f1065730430f80669d1d62fe9c03b436124a9)) have been done.

I'm closing this one.
