### ISSUE TITLE
Wrapping ResponseWriter to access StatusCode

### ISSUE THREAD

**Issue by cryptix** [revel/revel#704]
Hi,

I'm basically trying to port [go-tigertonic](https://github.com/rcrowley/go-tigertonic)'s metrics features to Revel. 

For `tigertonic.Timed`, this was really simple with a Filter:

``` go
func NewTimerFilter(name string, reg metrics.Registry) revel.Filter {
    if reg == nil {
        reg = metrics.DefaultRegistry
    }

    t := metrics.NewTimer()
    if err := reg.Register(name, t); err != nil {
        panic(err)
    }

    return func(c *revel.Controller, fc []revel.Filter) {
        defer t.UpdateSince(time.Now())
        fc[0](c, fc[1:])
    }
}
```

Now I wanted to copy `tigertonic.CountedByStatusXX` and stumbled over that `c.Response.Status` is just used to overwrite what status code revel sends out but isn't updated by the panic handler or the router and basically stays 0 if you don't touch it. In #278 that @robfig  wrote that

> Actually capturing the status and content length would have to be done by implementing the http.ResponseWriter interface as a wrapper of the "real" ResponseWriter, and applying the result to that one. That could be done in a filter, or by wrapping Server.Handler to pass down your custom implementation.

I tried it like this (`tigertonic` gladly already has such a wrapper called `TeeResponseWriter`) but the StatusCode on that writer is also 0 every time.

``` go
func NewStatusXXCounterFilter(name string, reg metrics.Registry) revel.Filter {
    if reg == nil {
        reg = metrics.DefaultRegistry
    }
    var (
        counter1xx = metrics.NewCounter()
        counter2xx = metrics.NewCounter()
        counter3xx = metrics.NewCounter()
        counter4xx = metrics.NewCounter()
        counter5xx = metrics.NewCounter()
    )
    if err := reg.Register(fmt.Sprintf("%s-1xx", name), counter1xx); err != nil {
        panic(err)
    }
    if err := reg.Register(fmt.Sprintf("%s-2xx", name), counter2xx); err != nil {
        panic(err)
    }
    if err := reg.Register(fmt.Sprintf("%s-3xx", name), counter3xx); err != nil {
        panic(err)
    }
    if err := reg.Register(fmt.Sprintf("%s-4xx", name), counter4xx); err != nil {
        panic(err)
    }
    if err := reg.Register(fmt.Sprintf("%s-5xx", name), counter5xx); err != nil {
        panic(err)
    }

    return func(c *revel.Controller, fc []revel.Filter) {
        teeW := tigertonic.NewTeeResponseWriter(c.Response.Out)
        c.Response.Out = teeW
        fc[0](c, fc[1:])

        log.Println("ResponseStatus:", teeW.StatusCode)
        if teeW.StatusCode < 200 {
            counter1xx.Inc(1)
        } else if teeW.StatusCode < 300 {
            counter2xx.Inc(1)
        } else if teeW.StatusCode < 400 {
            counter3xx.Inc(1)
        } else if teeW.StatusCode < 500 {
            counter4xx.Inc(1)
        } else {
            counter5xx.Inc(1)
        }
    }
}

```

I put the `StatusXXCounterFilter` in the first place of my Filter slice so that it also gets the 500 after the PanicFilter but I guess the way I update the ResponseWriter the controller should use is wrong somehow (`c.Response.Out = teeW`).

Any ideas? Thanks

**Comment by brendensoares** [comment]
@cryptix are you still interested in implementing a PR for this issue?

**Comment by notzippy** [comment]
Closing due to lack of response
