### ISSUE TITLE
ValidationResult.Message and i18n

### ISSUE THREAD

**Issue by ghost** [revel/revel#706]
Hello,

I was wondering why the `function (r *ValidationResult) Message(message string, args ...interface{}) *ValidationResult` doesn't handle different languages. Should the message already be converted to the requested language before passing it to the `ValidationResult`? How would I handle error reporting to the user with different languages?

Thanks in advance.

**Comment by brendensoares** [comment]
@anonx @pushrax looking at this with fresh eyes makes me think that perhaps there isn't a better solution than what I called a work around above. Are there any reasonable alternatives to @anonx's passing for localized message text from controller?

**Comment by brendensoares** [comment]
This is feels like a good candidate for the RFC repo.
