### ISSUE TITLE
CANCELLED: Rename `public` folder

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#710]
http://revel.github.io/manual/organization.html

The `public` folder can be directly served by the web server or the `Static` module as it contains static assets.

Would it be more clear to call it `static` or perhaps `assets`?

**Comment by pedromorgan** [comment]
Is this not in "config" by now ?? 
Eg static in revel, nginx, apache3, et all

**Comment by brendensoares** [comment]
@pedromorgan we provide static file serving as a Revel module in case devers don't setup a front end HTTP server.

**Comment by brendensoares** [comment]
I've cancelled this change. No value added.
