### ISSUE TITLE
Sync up labels/milestones in other repos

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#721]
- [x] cmd
- [x] revel.github.io

We need the labels and milestones to be consistent with this repo. Can we version the cmd the same as the framework?

**Comment by brendensoares** [comment]
@anonx I agree that the separate repos need their own version, but we should think about how we could ensure the samples have the exact version their expect. Short of adopting a package management approach, we could discuss runtime version checks such as a value specified in `config/app.conf`.

**Comment by mnapoli** [comment]
FYI we just released this at Piwik: https://github.com/piwik/github-sync

Still in beta, testers welcome :)

**Comment by brendensoares** [comment]
@mnapoli that would have been useful. I'll keep it mind, thanks!

I've applied labels to all current repos except for category labels, which we can add as we go.
