### ISSUE TITLE
Test Postform with csrf protection

### ISSUE THREAD

**Issue by ghost** [revel/revel#736]
Please for Help.
http://stackoverflow.com/questions/26035816/testing-post-method-with-csrf

Thanks for help

**Comment by ptman** [comment]
Is it really necessary to parse the document body? Isn't the csrf_token supposed to be in the cookies/headers? At least I get some value from t.Session["csrf_token"]. But I do have some problem with that being invalidated:

    TRACE 2016/03/23 14:38:51 csrf.go:38: REVEL-CSRF: Session's token: 'uhVOHiZRhO+FWzE2kobYb9IS0cCZDPGhynxJGZ4Apoo='
    TRACE 2016/03/23 14:38:52 tokengen.go:26: REVEL-CSRF: Generated new Token: 'VPJAjYL5zTqSVN7GrIHcU5Q+NeMScfqzVoGHi6UJD0M='
    TRACE 2016/03/23 14:38:52 csrf.go:55: REVEL-CSRF: Processing unsafe 'POST' method...
    TRACE 2016/03/23 14:38:52 csrf.go:83: REVEL-CSRF: Token received from client: ''

**Comment by ptman** [comment]
Ok, that was my mistake. t.Session["csrf_token"] works really well.
