### ISSUE TITLE
revel package doesn't read from go env

### ISSUE THREAD

**Issue by drewwells** [revel/revel#742]
If GOROOT isn't set as an environment variable, the builder throws errors.  However, go env shows that my goroot is set.  Setting GOROOT to go env GOROOT resolves the issue.

```
go env
GOARCH="amd64"
GOBIN="/Users/go/bin"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.3.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.3.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by brendensoares** [comment]
@drewwells 

1. What do you get with `pwd $GOROOT` and `ls $GOROOT` when it doesn't work and when it does?
2. Can you reproduce this issue on another machine (e.g. physical, VM or remote)?
3. I'm not sure there is an action item so far. What could Revel do to address your issue? It uses the `go/build` package to get `GOROOT` from the default context (http://golang.org/pkg/go/build/#Context).

**Comment by drewwells** [comment]
This is old now, I don't know if it's even a problem anymore. Closing

**Comment by brendensoares** [comment]
@drewwells perfect!
