### ISSUE TITLE
How to integrate gorilla sessions with Revel?

### ISSUE THREAD

**Issue by kostonstyle** [revel/revel#743]
Hi
It is possible to use gorilla session with Revel.
I discover on google groups
https://groups.google.com/forum/#!topic/revel-framework/xLI5dc4OIWc
would this works?

Thanks so much.

**Comment by pedromorgan** [comment]
This issue is not resolved..

We need to determine how to "plugin" third part.. for fun ;-)

Can we get down to the bottom of this ?

**Comment by brendensoares** [comment]
@pedromorgan @shelakel it seems that the gorilla/sessions package has not been designed to be modular as it depends on other gorilla packages. Is this correct? If so, they're isn't anything simple that Revel can do as far as I can think.

**Comment by notzippy** [comment]
Added session engine support #1216
