### ISSUE TITLE
Revel unbuildable on Windows

### ISSUE THREAD

**Issue by klauspost** [revel/revel#747]
The current "develop" branch is unbuildable on Windows, since goagain relies on functions in syscall that aren't available on Windows.

I have opened an issue on goagain, hoping they can create stub functions for unsupported platforms.

https://github.com/rcrowley/goagain/issues/24

In my personal opinion resolving this is a blocker for your next release. I would love to see goagain functionality in Revel, but currently this makes it impossible for us to consider an upgrade.

**Comment by rwese** [comment]
Today I updated go and now receive the same error mentioned here.

* GO Version: `go version go1.11.1 windows/amd64`
* `src\github.com\revel\revel\server_adapter_go.go:135:79: undefined: syscall.SIGUSR2`

If you need further details please let me know how I can be more verbose.

**Comment by rwese** [comment]
Looks like the problem only occurs when the windows-cmd is used. (Windows 10, Version 1803)

When I used the Git-Bash `go get...` it worked as expected.

**Comment by notzippy** [comment]
@rwese Thanks for commenting, this should be fixed soon
