### ISSUE TITLE
#750 = Seven Five Zero = Candidate Project

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#750]
Can I put forward a candidate projects..
ie a #severner-fiver-ziro projects

The projects below, please add and push to the limitz..

- for testing revel and pushing the limitz/crash
- using latest bleeding edge, and a real world application..
- but not so important that it dies completely.. till later

Lets really hack....

The Factory Planner
====================================
https://github.com/daffodil/factory-planner
and live site at
http://factory-planner.daffodil.uk.com
- manage shitts, work out time and stuff
- Needt data on shifts. I have spead sheet u also

FlightGear Navigation Data Project - fg-navdb
====================================
A Complex application that used postgis and spatial queries for mapnick and alike..
- configuration of system and import
https://github.com/FreeFlightSim/fg-navdb
and live site at
http://navdb.freeflightsim.org/

Very interested in a few issues to make the site "work nice"..
- configuration using different formats
- presenting  static directories
- making it restart live

What does it do ?
- reads line data from xplane
- imports into postgis using python atmo
- a revel application to serve the data
- from the backend postgis in spatial queries
- serves  json, and soon xml and kml 
- need so golang experts to implement, websocked, caching + redis + cookie et all
- will be a platform "api service for nav data" 
- also included is a mapserver ie mapnick using db structure..

**Comment by pedromorgan** [comment]
We need to make candidate project live again..
Make it work in real world,, and shit happens alike..

**Comment by brendensoares** [comment]
@pedromorgan Why is this here? If anything, it should be a wiki page.

Are you wanting to have a more comprehensive sample Revel app?

We can chat more on IRC soon.

**Comment by pedromorgan** [comment]
Ok.. maybe I explain why am crazy.....

The skeleton apps look like simple concepts..
and there's loads of blogs and simple stuff.. even slight clever..


But we neeed new users, from java, php, django, et all to actually have a serious intentional 
almost working apps, and we need to promote this..

The idea in my head is a new developer maybe both to go as well as revel..
and 
1) seeing other "projects" and now their wired, and starting at a ifiot level
2) proposing "help wanted".. I'm doing this and am stuck.. need a little step up to get me there..

Thats probably what I meant my candidate projects..


But anyway.. close this issue.. wasa mad idea..
