### ISSUE TITLE
Revel package command not working

### ISSUE THREAD

**Issue by svalleru** [revel/revel#780]
When I run 'revel package myapp' command, it's throwing 'Abort: Failed to parse template' error !

My GOPATH is "/Users/myuser/Desktop/golang"
# Console Log:

bash-3.2# revel package myapp
~
~ revel! http://revel.github.io
~
INFO  2014/10/27 16:49:45 revel.go:320: Loaded module static
TRACE 2014/10/27 16:49:45 build.go:128: Exec: [/usr/bin/git --git-dir=/Users/myuser/Desktop/golang/src/myapp/.git describe --always --dirty]
WARN  2014/10/27 16:49:54 build.go:132: Cannot determine git repository version: exit status 128
TRACE 2014/10/27 16:49:54 build.go:77: Exec: [/usr/local/bin/go build -ldflags -X findsimi/app.APP_VERSION "" -tags  -o /Users/myuser/Desktop/golang/bin/myapp myapp/app/tmp]
Abort: Failed to parse template /Users/myuser/Desktop/golang/src/github.com/revel/cmd/revel/package_run.sh.template: open /Users/myuser/Desktop/golang/src/github.com/revel/cmd/revel/package_run.sh.template: no such file or directory

**Comment by arturcesarmelo** [comment]
what exactly did you do @svalleru ??

**Comment by notzippy** [comment]
This conversation is not relevant to the current version of Revel @arturcesarmelo  - it is 5 years old
