### ISSUE TITLE
could you give a sample for csrf?

### ISSUE THREAD

**Issue by xpbliss** [revel/revel#788]
csrf.go is merged , could you give a sample for csrf?
Thanks.

**Comment by pedromorgan** [comment]
Need to add some stuff to docs about moduiles

**Comment by anonx** [comment]
> Need to add some stuff to docs about modules

@pedromorgan Not now. csrf is not ready and unfortunately cannot be used yet. CSRF is a module but it should be turned into filter, I think.

**Comment by brendensoares** [comment]
@anonx when can we meet up on IRC? Maybe this Sunday?

**Comment by anonx** [comment]
@brendensoares OK. I'm trying to be always online. So, any day is OK. Are you still in GMT-8 timezone? If so, either morning or evening hours would be cool.

**Comment by brendensoares** [comment]
@anonx great! Let's aim for tomorrow evening, say 5pm PST. How's that?

**Comment by anonx** [comment]
Jan 3, 2015, 5pm (PST). Right? :+1:

**Comment by brendensoares** [comment]
@anonx :currency_exchange: :hourglass_flowing_sand:  Yes, sir.

**Comment by anonx** [comment]
#### To do list:
* [ ] Create filter as `csrf` package in `revel/revel`.
  * [ ] Apply [Synchronizer Token Pattern](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#General_Recommendation:_Synchronizer_Token_Pattern) to all requests but `GET`, `HEAD`, `OPTIONS`, `TRACE`, and `WS`; **+/-** check origin if presented.
  * [ ] Check `origin` of Websocket handshake connections.
* [ ] Fix template helper function.
* [ ] Revise `exempt` functionality. Replace `map` by thread safe version.

**Comment by brendensoares** [comment]
This is important, but I think we can push it to v0.13. Agreed?

**Comment by rambocoder** [comment]
Looking at the code, the allowed methods are mostly implemented https://github.com/revel/revel/blob/c5893f222a8983e12aaac6ffaac0362ddcc56087/modules/csrf/app/csrf.go#L16 for GET, HEAD, OPTIONS and TRACE, but not WS.

I think CSRF filter would be widely used if it was added to skeleton by default https://github.com/revel/revel/blob/c5893f222a8983e12aaac6ffaac0362ddcc56087/skeleton/app/init.go#L13

**Comment by brendensoares** [comment]
@rambocoder that's a good idea.

**Comment by Gujie** [comment]
Hello!
Any update on this? 
Should we just use the current CSRF module and just comment out this part for now?
```
if !isSameOrigin {
    c.Result = c.Forbidden("REVEL CSRF: Same origin mismatch.")
    return
}
```
Also, is there any release date already planned for v0.13?
Thanks for the great work!

**Comment by anonx** [comment]
@Gujie I think the only option right now is to use https://github.com/cbonello/revel-csrf.

**Comment by brendensoares** [comment]
Added this to the roadmap. We need to wrap this up. Either remove the csrf code or fix it,

**Comment by notzippy** [comment]
See https://github.com/revel/modules/tree/master/csrf/app

**Comment by tr0mb1r** [comment]
csrf still doesn't work?

**Comment by ptman** [comment]
I have the same origin mismatch problem on localhost as well. I patched https://github.com/revel/modules/blob/master/csrf/app/csrf.go#L114

**Comment by tr0mb1r** [comment]
@ptman I've this problem with the latest version of csrf.go

**Comment by danilopolani** [comment]
+1 for Origin mismatch on localhost @notzippy @brendensoares .

Currently I'm using NGINX reversing to localhost:9000 and `c.Request.URL.Scheme` /  `c.Request.URL.Host` in `csrf.go` (and in controllers) are always empty.

@ptman how did you solve?

**Comment by ptman** [comment]
I think there should be a localhost exception or maybe http exception like in https://github.com/cbonello/revel-csrf/blob/master/csrf.go#L56
