### ISSUE TITLE
Docs are obsolete, inaccessible TestRequest.testSuite

### ISSUE THREAD

**Issue by birkirb** [revel/revel#791]
The testing documentation here is obsolete:

http://revel.github.io/manual/testing.html

MakeRequest is no longer a method on a suite. Since TestRequest struct hides the suite field, I can no longer implement my own methods (like PutFormCustom or whatever).  Is the loss of flexibility here intentional or is this something that might be fixed?

**Comment by goodgravy** [comment]
@brendensoares the referenced documentation at http://revel.github.io/manual/testing.html has yet to be updated—I don't believe this issue should have been closed

**Comment by pedromorgan** [comment]
Am busy atmo, but if someone can gimme a quick rundown of where things are and what to do then it would be helpful..

**Comment by pedromorgan** [comment]
Ok we need to get a grip on this test, and make the booking work...

**Comment by jeevatkm** [comment]
Docs taken care for v0.13 release, so I'm closing this one.
