### ISSUE TITLE
revel session cookie not set on binary http response

### ISSUE THREAD

**Issue by flamingtop** [revel/revel#792]
While using https://github.com/dchest/captcha for captcha generation, the following action renders a binary response. Revel's session cookie isn't set(updated) in this case. Since the cookie is encrypted and there's no API for me to decrypt & re-encrypt the existing cookie, I couldn't set the cookie response header with c.Response.Cookie = . I worked around it by moving c.Session["captcha_id"] = id into another non-binary action. 

```
func (c App) Captcha() revel.Result {
    id := captcha.New()
    c.Session["captcha_id"] = id
    c.Response.ContentType = "image/png"
    captcha.WriteImage(c.Response.Out, id, 240, 80)
    return c.RenderText("")
}
```

I don't know if this is a issue or not. Ideally if revel syncs the session cookie, my captcha implementation will be cleaner.

**Comment by notzippy** [comment]
Server engine resolves this now
