### ISSUE TITLE
Some questions about revel & go docs

### ISSUE THREAD

**Issue by LorenzV** [revel/revel#793]
Hello,

I just started using go(lang) and i must say that, go & revel have really bad documentation compared to other languages/frameworks i've used. 

For example. Today i was trying to pass a variable to my template with revel. The revel docs dont tell me how. But it does say how to pass functions to the template. However they don't tell you how to use them in your template and the golang docs also don't tell you that. Eventually i went to github and looked for it myself and found RenderArgs in the source code. I don't really understand how such important stuff is so hidden for the user.

Yesterday i wanted to use an ORM. Again. Docs don't explain how. I had to read sample source code and google stuff about "revel + gorm" instead of reading a small text in the docs on how it works.
You know why Laravel(PHP) is such popular framework these days? Because their documentation is awesome. Everything you need to know is in their and well explained. Unfortunately it's PHP, and i want to move to a better language.

You know.. 1 great documented framework can change the popularity of an entire language.

It's not like everything i told isn't in the docs though, it's just so hidden. Starting Go devs will have a hard time understanding how everything works. I'd suggest you have a look at the laravel docs. You can see that every single situation is explained and given a code sample. This makes it super easy for developers to understand everything.

**Comment by pedromorgan** [comment]
@LorenzV  thanks for the pointers..

Here's a version for u to review.. am getting familiar with thing and interlinking.. so critisism most welcome

http://revel-docs.daffodil.uk.com/

**Comment by LorenzV** [comment]
@pedromorgan I've compared it, and i really like the improvements.

I like:
- The visual update for the notes
- Everything is more structured
- More info is now bold or in another color
- The list of functions added in the "template" section
- i18n = renamed , i'd still prefer "Translations" though, but that's just my opinion
- Menu looks better/cleaner

I probably didnt see all the changes.

I would add:
- more colors to the code samples
- More topics to the manual (Those from my prev. comment) , but that will prob. take alot of time

**Comment by brendensoares** [comment]
I added this to v0.12 on [the Revel Roadmap](https://github.com/revel/revel/wiki/Roadmap).

**Comment by pedromorgan** [comment]
@LorenzV thanks for the feedback..

Re colors in code samples, were limited really by pygments, and already "borrowed" the github-jekyll theme http://revel-docs.daffodil.uk.com/css/jekyll-github.css

However, as i understand it, github has moved away from pygments to another highlighter...  but I agree that it could be nicer..

**Comment by LorenzV** [comment]
@pedromorgan The only reason i want to add colors to the code samples is to make them more fun to read.

**Comment by pedromorgan** [comment]
playing with pygment styles.. feedback appreciated

http://revel-docs.daffodil.uk.com/manual/validation.html

**Comment by LorenzV** [comment]
hmmmm i would try to look for other colors. Also, i think the old style of the notes was better. Im not such a fan of the gradient background :) and the h2 font looks too big for its container.

**Comment by pedromorgan** [comment]
@LorenzV - you are more than welcome to come up with a style.. I'm not a designer (and am am colour blind lol)

Main "override" style is http://revel-docs.daffodil.uk.com/css/revel.3.css

**Comment by LorenzV** [comment]
@pedromorgan maybe i'll do that. and being color blind might be an advantage because you're less likely to make things unreadable towards other color blind people ^_^

**Comment by LorenzV** [comment]
I tried.. ^_^
Before: http://puu.sh/e1Wa5/32fd8189a3.png
After: http://puu.sh/e1W6v/38a07b0600.png

It's kinda annoying that the colors for the code samples dont see the difference between strings, function names and package names.

I'm not a designer either. Just wanted to show my preferences. Also dont mind the note that i added there, it's just for showing the style.

Anyway. I think the content of the manual is more important than the styling right now, but an update of it is always welcome ^_^

**Comment by pedromorgan** [comment]
Yep, pygments is not that good, but it does kinda support htmldjango for templatea and ini files..

The alternate I looked at is "rougr", http://rouge.jayferd.us/demo but that dont support ini or templates so have not pursued further...

**Comment by brendensoares** [comment]
@LorenzV I like your changes. I also agree we can progressively improve the style after we update the manual.

@pedromorgan rouge does seem to support `ini`, but not sure how it would render Go templates.

**Comment by pedromorgan** [comment]
at present am using "htmldjango" which highlights the html and django
templates, which is thankfully similar

**Comment by brendensoares** [comment]
@LorenzV I'm closing this as there are no action items here. Please feel free to ask more questions on StackOverflow.com or by submitting pull requests to our `revel/revel.github.io` repo to improve documentation. Thanks for your help!
