### ISSUE TITLE
Using Revel on Windows

### ISSUE THREAD

**Issue by benjamin-wss** [revel/revel#794]
Hello,

I tried out Revel in my workstation at work (powered by Linux) and it worked great but when I wanted to use Revel on windows (my home machine), there are no guidelines on how can I run the revel command or how to map the command to my PATH.

Can you please point me to the right direction?

Thanks.

**Comment by dhananjayve** [comment]
i had tried but gain following error

C:\Users\dkvon>go get github.com/revel/cmd/revel

C:\Users\dkvon>revel run github.com/revel/samples/chat
'revel' is not recognized as an internal or external command,
operable program or batch file.

I am new in golang suggest me solution

**Comment by aftemark** [comment]
Windows 10 user here.
Instructions appeared a bit confusing for me or just missed a step.
if you install go from msi installer, you have to add this path to PATH enviroment variable.
![env](https://user-images.githubusercontent.com/10334032/30499559-ac1e5eb8-9a63-11e7-9634-ecc4bfa9334d.JPG)
