### ISSUE TITLE
Redis Cache Optimizations

### ISSUE THREAD

**Issue by ready4god2513** [revel/revel#802]
I am working my way through the cache package and one thing that I am noticing is that some operations fail to make use of available features due to implicit contracts (in documentation).  Can someone give a little insight as to why this is done?  For example, with redis incrementing a key does not require that the key be set in advance.  However, the way the increment is implemented is the following-

``` golang
func (c RedisCache) Increment(key string, delta uint64) (uint64, error) {
    conn := c.pool.Get()
    defer conn.Close()
    // Check for existance *before* increment as per the cache contract.
    // redis will auto create the key, and we don't want that. Since we need to do increment
    // ourselves instead of natively via INCRBY (redis doesn't support wrapping), we get the value
    // and do the exists check this way to minimize calls to Redis
    val, err := conn.Do("GET", key)
    if err != nil {
        return 0, err
    } else if val == nil {
        return 0, ErrCacheMiss
    }
    currentVal, err := redis.Int64(val, nil)
    if err != nil {
        return 0, err
    }
    var sum int64 = currentVal + int64(delta)
    _, err = conn.Do("SET", key, sum)
    if err != nil {
        return 0, err
    }
    return uint64(sum), nil
}
```

It isn't a _huge_ deal, but that means that in order to initially increment a counter we require 3 round trips to redis and all subsequent increments require 2 trips.  Thoughts?

**Comment by notzippy** [comment]
No pull request submitted, closing
