### ISSUE TITLE
template url func gives "index out of range" when param is undefined

### ISSUE THREAD

**Issue by pbnjay** [revel/revel#811]
Just spent over 30 mins debugging a simple omission cause the error message sent me down the wrong path. But I think it should be pretty easy to fix.

In short: in the template I have `{{url "MC.Thing" $id}}` but my func was: `func (c MC) Thing() revel.Result`

But the template panicked with: `results.go:128: runtime error: index out of range`

I'd expect an error more like "invalid arguments for url MC.Thing"

**Comment by brendensoares** [comment]
@pbnjay can you tell us the steps to reproduce this issue and what you expect should happen. I can get this fixed in the code when I know for sure I actually fixed the issue you're seeing. Thanks.

**Comment by anonx** [comment]
@brendensoares, the issue is ``{{url "Controller.Action" .arg1 .arg2 ...}}`` helper panics in case of incorrect input rather than showing a user friendly error message.

**Comment by pbnjay** [comment]
Yeah, sorry on my phone right now but I believe it was my view func didn't
have a named parameter but I thought it did. The "url" helper didn't do a
bounds check.

Something like:
func (a *App) Thing() revel.Result {
...
}

Then:
{{url "App.Thing" 1234}}

**Comment by pbnjay** [comment]
Whoops I think anonx edited after my github email was sent. Knew I should have checked the site first...

**Comment by brendensoares** [comment]
@anonx thanks I get it now.
