### ISSUE TITLE
Master moderator:

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#816]
This is confusing..

We need a clear line to tag bugs..
atmo even though I am adming..

I want to ccreate tags..
So whilst core team can go and have a list..

I wish we tag message+bug and therby bug of bugs..

We are on the rising edge and eveything is running. and lets face it go is young..

new approach and all..

**Comment by pedromorgan** [comment]
Closing as am tagging ;-)

**Comment by brendensoares** [comment]
#827 should help use decide what we'll work on per release. @anonx I agree on deadlines. We had agreed to every 6 weeks before: https://github.com/revel/revel/blob/master/CONTRIBUTING.md#how-revel-is-developed
