### ISSUE TITLE
revel creates or overwrites binaries in $GOPATH/bin

### ISSUE THREAD

**Issue by xiam** [revel/revel#819]
There is a [known but closed](https://github.com/revel/revel/issues/320) issue that I ran into this week. Here's how to reproduce:

Create a new app called `revel` and run it with no additional code.

```
revel new foo/revel
revel run foo/revel
```

Open http://localhost:9000 and then send `^C` to the `revel run` process.

Try tu run `revel run` again:

```
revel run foo/revel
ERROR 2014/12/03 09:29:04 revel.go:273: Failed to import  with error: import "": invalid import path
```

As commented in #320, the `revel` binary is being overwritten. In fact it signature looks different before and after running `foo/revel`.

```
fedora-x64:~/go/bin > sha1sum revel 
39a723dc4c2d9b1adf2e247373bf1243a4585fd2  revel
fedora-x64:~/go/bin > sha1sum revel
50c11fe42af135947fc45e79227be0f3f7b42bda  revel
```

One way to recover is by using:

```
rm ~/go/bin/revel
go get -u github.com/revel/cmd/revel
```

Let's try with another name:

```
revel run foo/otherapp
```

Open localhost:9000, a new binary `otherapp` will be created in `$GOPATH/bin/`

Is it there a limitation that justifies messing with the user's `$GOPATH/bin`? If there is none, I think `revel` should not take the freedom to overwrite user files (or even itself) without a warning, and if a limitation exists it would be nice to know what the limitation is so we could find a workaround.

Thanks,

**Comment by brendensoares** [comment]
@xiam thanks for the detailed steps to reproduce! Every issue should have these details! It makes our efforts so much more enjoyable when the burden of proof isn't only on us (@revel/core).

@anonx did you test your proposed solution?

**Comment by anonx** [comment]
@brendensoares, yes I did.

**Comment by brendensoares** [comment]
@anonx can we get a PR? Also, did you leave the @revel/core? I can't assign this to you.
