### ISSUE TITLE
JavaScript Web Tokens (JWT)  Session Support in Revel: Is it possible? If so, can it be documented? 

### ISSUE THREAD

**Issue by lozandier** [revel/revel#825]
Is there a conventional way of integrating [JavaScript Web Tokens](http://jwt.io/) support within  Revel controllers/actions--particularly to replace cookie sessions? 

If so, it seemingly would be of great value of seeing such things in documentation. JavaScript Web Tokens (JWTs) are an increasingly popular way to do things such as authentication instead of doing such things with cookies. 

With JWTs, there's significantly less need for session stores for all sorts of requests like checking whether the user can access particular representations of data.

**Comment by brendensoares** [comment]
@lozandier I'd be interested in seeing what you come up with. I have no experience with JWT, but I've heard of them and I'm always curious about applying new technology for great good ;)

**Comment by notzippy** [comment]
Closing due to no response in over a year
