### ISSUE TITLE
Persona example session key not matched

### ISSUE THREAD

**Issue by amlwwalker** [revel/revel#830]
Hi When I run the persona example locally, I log in with my Persona account which is successful (as far as Persona is concerned) however on my terminal I get:

~~~
INFO  2014/12/21 15:29:24 session.go:123: Session cookie signature failed
~~~
Is there a read/write permissions issue or something? Where would this be stored, in bin??
Thanks
Alex

**Comment by brendensoares** [comment]
:+1: great thread with good amount of details. I like the screenshots. This is a fine example of community collaboration! Great work @anonx and @amlwwalker !
