### ISSUE TITLE
Production mode panic shows too much detail

### ISSUE THREAD

**Issue by goofcc** [revel/revel#831]
**win7x64+go1.3.3+reve0.11,In production mode, calling panic method throws debugging information, rather than 500 Internal Server Error**

D:/go/src/github.com/revel/revel/panic.go:25 (0x4629e8)
	handleInvocationPanic: c.Response.Out.Write(debug.Stack())
D:/go/src/github.com/revel/revel/panic.go:12 (0x47b50c)
	func.041: handleInvocationPanic(c, err)
c:/go/src/pkg/runtime/panic.c:248 (0x411323)
	panic: runtime·newstackcall(d->fn, (byte*)d->args, d->siz);
D:/go/src/github.com/revel/revel/intercept.go:93 (0x47b493)
	func.040: panic(err)
c:/go/src/pkg/runtime/panic.c:248 (0x411323)
	panic: runtime·newstackcall(d->fn, (byte*)d->args, d->siz);
D:/go/src/myapp/app/controllers/app.go:10 (0x48961a)
	App.Index: panic("123")
<autogenerated>:19 (0x489a67)
c:/go/src/pkg/runtime/asm_amd64.s:361 (0x42d049)
	call32: CALLFN(call32, 32)
c:/go/src/pkg/reflect/value.go:563 (0x43e4c7)
	Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
c:/go/src/pkg/reflect/value.go:411 (0x43d16e)
	Value.Call: return v.call("Call", in)
D:/go/src/github.com/revel/revel/invoker.go:35 (0x4623d3)
	ActionInvoker: resultValue = methodValue.Call(methodArgs)[0]
D:/go/src/github.com/revel/revel/compress.go:56 (0x455e6c)
	CompressFilter: fc[0](c, fc[1:])
D:/go/src/github.com/revel/revel/intercept.go:103 (0x460e60)
	InterceptorFilter: fc[0](c, fc[1:])
D:/go/src/myapp/app/init.go:37 (0x4894f8)
	func.001: fc[0](c, fc[1:]) // Execute the next filter stage.
D:/go/src/github.com/revel/revel/i18n.go:155 (0x46029b)
	I18nFilter: fc[0](c, fc[1:])
D:/go/src/github.com/revel/revel/validation.go:191 (0x47448a)
	ValidationFilter: fc[0](c, fc[1:])
D:/go/src/github.com/revel/revel/flash.go:45 (0x45d481)
	FlashFilter: fc[0](c, fc[1:])
D:/go/src/github.com/revel/revel/session.go:148 (0x4709ca)
	SessionFilter: fc[0](c, fc[1:])
D:/go/src/github.com/revel/revel/params.go:133 (0x4640ba)
	ParamsFilter: fc[0](c, fc[1:])
D:/go/src/github.com/revel/revel/filterconfig.go:208 (0x45d047)
	FilterConfiguringFilter: fc[0](c, fc[1:])
D:/go/src/github.com/revel/revel/router.go:472 (0x46e686)
	RouterFilter: fc[0](c, fc[1:])
D:/go/src/github.com/revel/revel/panic.go:15 (0x4627b7)
	PanicFilter: fc[0](c, fc[1:])
D:/go/src/github.com/revel/revel/server.go:43 (0x46ed32)
	handleInternal: Filters[0](c, Filters[1:])
D:/go/src/github.com/revel/revel/server.go:31 (0x46ea20)
	handle: handleInternal(w, r, nil)
c:/go/src/pkg/net/http/server.go:1235 (0x4fc2a7)
	HandlerFunc.ServeHTTP: f(w, r)
c:/go/src/pkg/net/http/server.go:1673 (0x4fe286)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
c:/go/src/pkg/net/http/server.go:1174 (0x4fbe15)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
c:/go/src/pkg/runtime/proc.c:1445 (0x416020)
	goexit: runtime·goexit(void)

**Comment by brendensoares** [comment]
So it seems to be a Windows specific issue. Someone will need to trace the code on Windows and find out why it's acting differently.

## TODO
- [ ] trace Windows runtime panic code to find out why it's taking a different code path

**Comment by brendensoares** [comment]
I have confirmed that Windows is handling `panic("123")` differently than Linux with a brand new app (`revel new test` and `revel run test`).

Further, I discovered that this issue has been around for over a year. #260 has already documented that Windows file paths are not being evaluated properly and are always (causing the raw stack trace to be displayed)[https://github.com/revel/revel/blob/develop/panic.go#L22]. This means that Revel is unable to display anything other than the raw stack trace as neither the template for a dev mode error page nor the template for the simple production 500 page can be loaded.

## TODO
In order to ensure that this sensitive debug stack trace is NOT shown in production mode, we need to:
- [ ] add an condition check on `revel.DevMode` for `ERROR.Print(err, "\n", string(debug.Stack()))` inside of the above cited line in `panic.go`

@anonx @pushrax please sanity check my findings.

**Comment by anonx** [comment]
@brendensoares Not sure this is Windows specific.

Here is the code, I use for check:
![panic("123") sample](http://i.imgur.com/hl98Al4.png)


If I'm running it under Linux using ``revel run github.com/anonx/sample prod`` I get an error:
![error message](http://i.imgur.com/ZnUKlGd.png)
So, this is the exact behaviour we expect.


However, if I use ``revel build github.com/anonx/sample /tmp/sample`` and ``cd /tmp/sample && ./run.sh`` it shows a stack trace:
![stack trace](http://i.imgur.com/JddbHk0.png)
Thus, the problem @goofcc identified is valid not only on Windows, but at least on Linux, too.
