### ISSUE TITLE
testrunner

### ISSUE THREAD

**Issue by yanlinpu** [revel/revel#832]
how to use the files in the public directory in revel testrunner

**Comment by brendensoares** [comment]
@yanlinpu please explain what you're trying to do so we can help you. I'm closing this until we hear from you. Thanks.

**Comment by yanlinpu** [comment]
I'm very sorry for that in holiday.
when i want to test, i must copy the public folder in the testrunner to the local.
![Uploading W3PCAW[CCX3($HGC{WP[P51.jpg . . .]()

**Comment by anonx** [comment]
So, those asset files are not visible, right? I'm afraid this is a bug. We have a fix in #824, but it is not merged yet.

**Comment by yanlinpu** [comment]
yes. 
thanks.

**Comment by anonx** [comment]
@yanlinpu It should be fixed now. Upgrade to the latest version of revel: `go get -u github.com/revel/cmd/revel`.

**Comment by yanlinpu** [comment]
@anonx  thx
