### ISSUE TITLE
is boolean True ? or false ?

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#835]
Am updating docs..
can we confirm that this is correct..

http://revel.github.io/manual/binding.html#booleans

    The string values "true", "on", and "1" are all treated as **true**,  otherwise it is **false**.

This is strange..
does True, TRUE, or ON or On also..

maybe this is incorrect with true ?
in php a 0 is false, and any value > 0 is a true
also in js a "" value if false, but "foo" is true ?

"off" is false..

To make it easier can we clarify for end users who are migrating..

**Comment by pedromorgan** [comment]
Ok this is bugging me..
Mainly because I am migrating py/php apps to go ;-)

So the check in those domains is
- prove it false = default stuff
- or prove its true...

I prefer the false stuff, as is default, ie 0, none et all

So can I suggest we change to @anox plan and patch..
Ie and also include "yes" and "no" even in international..

Maybe there are two checks..
- definately false
- definate true
- use defaults for type ?

this wuld solve some stuff for legacy apps, but also I thingk imho the way  to go..

**Comment by pedromorgan** [comment]
We Need a function global function, in psuedo code

   func IsTrue(some_val) {
        case "false", "off", "0", "": 0, 0.0 "nowt", "no":
           return false
         default:
               return  LookupInterNatinal(some_val, LANG_CODE)
        return true
}

**Comment by pedromorgan** [comment]
From a practical standpoint..
- a check box send value and http = "on  ?
- a pyqt button is true on false
- an ajax and javascript would be none
- a python None is a false
- a query string in pylons request.params.get("foo") would be none
- whilst request.params['foo"] would cKrashz and app in py
- A $_GET['foo'] in php = false  


Food for thought..

=========================
Legacy Damage
=========================
I think there i no legacy damage in using @anox suggestion above of oppositing

**Comment by anonx** [comment]
@pedromorgan You mean @anonx (just like anonymous x)? @anox is somebody else.

**Comment by brendensoares** [comment]
@pedromorgan do you want to create a PR to address this change? We should also document this (as mentioned above).

**Comment by jeevatkm** [comment]
I'm closing this in-favour of PR #1070
