### ISSUE TITLE
[docs] - database config

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#836]
Has anyone got a good example for a database and orm config..

Nice would be to show where to initialise, read the config etc

Here's the target page
http://revel-docs.daffodil.uk.com/manual/database.html

**Comment by pedromorgan** [comment]
Also am confused what the db module is about ?

are there any examples ?

http://godoc.org/github.com/revel/revel/modules/db/app

**Comment by brendensoares** [comment]
Booking sample app demonstrates how to use gorp.

- http://revel.github.io/samples/booking.html#database--gorp-plugin

**Comment by pedromorgan** [comment]
Yes booking sample shows sqlite, 

What we want is a more proper config, demonstrating mysql, postgres, even mssql ?

I think what needs clearing up is...

1) how to do the config and
2) where should i create connection etc..
3) how to pass connection around, with multiple database best practise..

I got this issue with https://github.com/freeflightsim/fg-navdb
where I kinda want to pass a golang db interface around, but allow third party orm etc to inherit above that..

**Comment by brendensoares** [comment]
This should be in [v0.14](https://github.com/revel/revel/wiki/Roadmap#v014-see-issues). I'll move it.
