### ISSUE TITLE
Nuke routes csv config

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#838]
Ok, so the csv config looks nice, and simple

But is actually serverly limited..for example handling subdomains ot GET/POST in one line etc

So I think it was a good, at the time, but now I dont..

Infact I would say that moving to a yaml/toml/json config is an upmost priority, into the next version, as the current is not "futurable"

I think what made me realise this is that is such is a problem is how subdomains are not supported and I need them urgent

- https://github.com/revel/revel/pull/536
- https://github.com/revel/revel/search?utf8=%E2%9C%93&q=subdomain&type=Issues

It also made me realise that I could write a small script to convert a couple of legacy pylons apps

**Comment by brendensoares** [comment]
@pedromorgan [it's planned in v0.15](https://github.com/revel/revel/wiki/Roadmap#v015-see-issues), but it's not as important as other features. The current custom format(not CSV) is proven and working.

Maybe we can visit #536 and #358 in the next release to support subdomains without rewriting the router for other formats.
