### ISSUE TITLE
Configuration Clashes

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#839]
Am updating the docs and looking at the config page
http://revel-docs.daffodil.uk.com/manual/appconf.html

The issue is the "build in properties"

- the idea I think is that these are "reserved variables"
- Ie u can use your own custom config, but also DONT clash with revel..

If revel detects as clash somehow , eg a new key added to reserved and not recognised..
Then it should crash..

Make sense ?? am thinking out loud

**Comment by pedromorgan** [comment]
Also when does Config and getting variables come into scope ?

And are there triggered to register config changes, eg changing a database config and live switch ??

**Comment by brendensoares** [comment]
Built-in properties may not be the correct name. Perhaps "Supported Config Properties"? There is nothing wrong with them being overridden. No worries there unless you can think of a problem.

`app.conf` is loaded in [`revel.go Init()`](https://github.com/revel/revel/blob/master/revel.go#L151)
