### ISSUE TITLE
consult: how to parse a constant var In revel template ?

### ISSUE THREAD

**Issue by xpbliss** [revel/revel#840]
tmpl, _ := revel.MainTemplateLoader.Template("Admin/staticPrjPub.html")
		c.Render(Lists, subTitle)
		var b bytes.Buffer
		err := tmpl.Render(&b, c.RenderArgs)
the "Admin/staticPrjPub.html" is a file.  It's ok.

but i want to parse a constant var (datatpl,such as the following), and pass the c.RenderArgs into it, how to do?
datatpl := `{{range .Lists}}........{{end}}`

**Comment by notzippy** [comment]
Not proper area for asking questions, please do so on the forum https://groups.google.com/forum/#!forum/revel-framework

**Comment by brendensoares** [comment]
[Revel's README](https://github.com/revel/revel/blob/master/README.md#join-the-community) suggests [StackOverflow](http://stackoverflow.com/questions/tagged/revel) for these sorts of questions.
