### ISSUE TITLE
UTF-8 should be considered for length related validators

### ISSUE THREAD

**Issue by tomodian** [revel/revel#841]
Currently `len(str)` is used in length related validators, but this will cause unintended result when UTF-8 string is given.

Example:
```
name := "世界"    // --> len("世界") will be 6

// All these validations will cause unintended result
c.Validation.MinSize(name, 3).Message("At least 3 characters")   // --> Pass
c.Validation.MaxSize(name, 5).Message("At most 5 characters") // --> Pass
c.Validation.Length(name, 2).Message("Must be 2 characters") // --> Pass
```
Using `utf8.RuneCountInString(str)` will be more developer friendly.
Have a look at my forked repo: https://github.com/tomodian/revel/commit/76e2d7134478a6445d01a6f273af7f4720273ad4

**Comment by brendensoares** [comment]
@tomodian can you submit a PR so we can merge this fix? Thanks!

**Comment by xuanxu** [comment]
[PR fixing this issue here](https://github.com/revel/revel/pull/890)

**Comment by anonx** [comment]
Thank you @tomodian, @xuanxu. The issue has been resolved.
