### ISSUE TITLE
go get 'github.com/revel/revel' failed

### ISSUE THREAD

**Issue by CipherChen** [revel/revel#842]
my go env:

```
GOARCH="amd64"
GOBIN="/home/Binary/go_test_bin/"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/note/Development/Workspaces/Go"
GORACE=""
GOROOT="/home/Binary/go"
GOTOOLDIR="/home/Binary/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

After `go get github.com/revel/revel `:

```
[note@Eleanor go_test_bin]$ tree $GOPATH/src/github.com/revel/revel -d -L 1
/home/note/Development/Workspaces/Go/src/github.com/revel/revel
|-- cache
|-- conf
|-- harness
|-- mail
|-- modules
|-- samples
|-- skeleton
|-- templates
`-- testdata
```

But after that I still don't get `revel` cmd:
```
[note@Eleanor go_test_bin]$ which revel
/usr/bin/which: no revel in (/home/note:..
```

I found an explanation on http://stackoverflow.com/questions/26120448/cant-install-revel-with-go-get but the solution didn't work for me.

**Comment by anonx** [comment]
@CipherChen What's your `$PATH`?
```sh
echo $PATH
```
Did you added your `$GOBIN` folder to `$PATH`?
```sh
export PATH="$PATH:/path/to/my/bin/dir"
```

And yeah, now we encourage Revel community to stackoverflow, IRC, or google groups for any kind of questions. GH Issues are only for bug reports and related stuff now.

**Comment by CipherChen** [comment]
Thanks @anonx 

My $GOBIN

```
[note@Eleanor go_test_bin]$ echo $GOBIN
/home/Binary/go_test_bin/
[note@Eleanor go_test_bin]$ ls $GOBIN
gocode  hello
```

I'm sure I've added $GOBIN in $PATH, since
```
[note@Eleanor revel]$ which hello
/home/Binary/go_test_bin/hello
```

And I cann't find `revel` in the $GOBIN.

**Comment by anonx** [comment]
Sure, you should run `go get github.com/revel/cmd/revel` not just `revel/revel`.

**Comment by brendensoares** [comment]
@CipherChen http://revel.github.io/tutorial/gettingstarted.html#build-the-revel-command-line-tool
