### ISSUE TITLE
Add Dockerfile generation to revel build

### ISSUE THREAD

**Issue by klauspost** [revel/revel#845]
Here is a simple template for a minimal Dockerfile, using a small Debian for a new small container:

```
FROM debian:stable
COPY ./{{.BinName}} /revel/{{.BinName}}
COPY ./run.sh /revel/run.sh
COPY ./src  /revel/src

CMD ["/bin/sh", "/revel/run.sh"]

EXPOSE 9000
```

This could easily be implemented as part of the build/package process. The only caveat is that it will only work when run on Linux, since the binary should be linux/amd64, and of course a Windows EXE will not work.

**Comment by brendensoares** [comment]
@klauspost thanks for this! I have been putting off learning docker. I should try this out soon.

**Comment by pault84** [comment]
With the new docker beta. this could totally work on windows now.
Docker is now "supported" on a windows environment. this would be pretty cool to have.!

**Comment by notzippy** [comment]
Added to cli tool
