### ISSUE TITLE
Make Static Dir Configurable

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#847]
Is it possible to make the "static root dir a setting", eg in app.conf

```
static.root = /home/some_project/public_stash
static.url = /public/ 

[dev]
static.root = ./test_static 

[prod]
static.root = ~/public_stash
```

**Comment by notzippy** [comment]
Ideally in production you would want to have your proxy bypass revel completely to access the public static files and folders directly. But I would not be totally against this, the change would be in the static module, static.go:serveFile:81

    -		basePath = revel.BasePath
    +		basePath = revel.Config.StringDefault("static.root", revel.BasePath)

But since this is a module issue you need to create the issue against the revel/modules project, so I am closing this, feel free to do a pull request with the above code.

**Comment by pedromorgan** [comment]
Err am perplexed..
The static module is "build in revel".. not here
https://github.com/revel/modules

but here
https://github.com/revel/revel/tree/master/modules


So it means here ??
https://github.com/revel/revel/blob/master/modules/static/app/controllers/static.go#L85

Also whats in the back of my head is having the {{static_ver "/js/foo.js"}} tags

**Comment by notzippy** [comment]
Try `https://github.com/revel/modules/tree/develop` You want to target the change against a development branch. 

I am not sure what you mean by the `{{static ...}}` tag we already have `{{url "public/js/foo.js"}}` tags to do reverse routing using the routes file

**Comment by pedromorgan** [comment]
WTF.. Ok so this is version "next realsase right"..

Maybe I better change some of the docs to reflect this now...

and am switching everything here over to develop..

**Comment by notzippy** [comment]
AFAIK next release is v0.12 https://github.com/revel/revel/wiki/Roadmap#v012-see-issues so I would say yes develop will move to master.

**Comment by brendensoares** [comment]
@pedromorgan file a RFC explaining the problem you're trying to solve and why we should care about it. Thanks.

PS - what are you talking about "switching everything here over to develop"?

**Comment by notzippy** [comment]
With the new routing you can now use the `url` to specify static routes as well, so no need for this to be in the conf
