### ISSUE TITLE
Watch other directories

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#849]
As part of a new project bumped into a problem with directories not watches..

https://github.com/daffodil/factory-planner

Notably `mods/`

Is it possible to add a path to the watchers..
eg

     watchers.extra = "/home/path/tocode", "/another/path

or alike

**Comment by brendensoares** [comment]
Checkout #153 and https://github.com/revel/cmd/blob/develop/harness/harness.go#L154-L161

**Comment by anonx** [comment]
@pedromorgan, what's the use-case? What kind of files are in `mods/`? What do you want to do with them?

**Comment by brendensoares** [comment]
@pedromorgan do you have a use case for this? If not, let's close it.
