### ISSUE TITLE
Apply filter to specific revel route like node expressjs middlewares

### ISSUE THREAD

**Issue by nxtuong7488** [revel/revel#850]
I am wondering is there anyway to apply filter to specific routes. Currently, controllers are declared in route config file to specify which controller to handle a specific route.
POST    /api/user/login                                 Auth.Login 

Now, is there anyway I can inject a filter before a controllers or declare multiple controllers/middlewares for this route. For example, suppose I want to protect a list of API (by checking user session), is there anyway to do something like:

POST    /api/user/login                                 [Auth.UserLoggedIn, Auth.Login]

which basically go through two controllers, in which the first one will just reject the request if no user session being found. That way, i can eliminate a quite number of duplicate code and make the app more modular. The concept is similar to nodejs middleware (or equivalent implementation in a number of framework).

Thanks.

**Comment by notzippy** [comment]
Dude, this is not the forum ! Post there and there will be a response.

**Comment by notzippy** [comment]
What you are looking for is FilterConfigurator http://revel.github.io/manual/filters.html

Per-Action configuration

Although all requests are sent down the revel.Filters chain, Revel also provides a FilterConfigurator, which allows the developer to add, insert, or remove filter stages based on the Action or Controller.

This functionality is implemented by the FilterConfiguringFilter, itself a filter stage.

**Comment by brendensoares** [comment]
@nxtuong7488 I hope you found your answer. If not, feel free to join us on IRC or post to StackOverflow.com and tag your questions with `revel`. We try to keep github issue focused on core development topics rather than app development. Thanks!
