### ISSUE TITLE
Should add a function to get all Action?

### ISSUE THREAD

**Issue by xpbliss** [revel/revel#851]
maybe you dear should add a function to get all the Action name.

so that can give the different user the different Action permission.  and easy to use RBAC like this(https://github.com/mikespook/gorbac).

**Comment by brendensoares** [comment]
@xpbliss this would be a good candidate for an RFC (`revel/rfcs` repo) describing what problem needs to be solved and why we should care.

Agreed @anonx @pushrax @pedromorgan ?

**Comment by pedromorgan** [comment]
Is this still valid folks ??

**Comment by hsluoyz** [comment]
Hi, I'm the author of [casbin](https://github.com/hsluoyz/casbin). It is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.

So please consider using casbin when revel implements RBAC security. Also let me know if there's any question:)
