### ISSUE TITLE
massive favour = version.yaml

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#856]
Can we in each repository and branch and modules etc..

Include a version.yaml file with the contents..
eg
revel: 0.11.2

This will make it much easier as am scripting stuff to gen documents..
inc current = soon history docs
and next docs..

as long as its got
Release.Version.Minor then cool
and also -stable -develop tags eg
0.11.2-stable
0.13.13-develop
Or something alike..
This could even get down to module level

I dont care what format it end up as, as long as I can quick parse it into somethings, preferably taml and some "structure"..

This will make it idea easy to compile tags vs branches and a jenkins job I am working on..

Idea is to completelly automate revel releases, down to docs and branches et all..
ie develoeprs heavean

**Comment by pedromorgan** [comment]
actually I explain what the real problem is from flight gear..

Something machine readable that aint in code..
Eg python modules have
__init__.py
and
__VERSION__ = 5.2

But there is one in "documentation" land and having to somehow read that file to make the "version" of the docs..

If it was a simple text file, then one can eat it..

I am very familiar with this problem as a contributor to
- smarty - http://www.smarty.net/
- flightgear - http://api-docs.freeflightsim.org/
- fgms - making webiste ontop of api http://fgms.freeflightsim.org/

and many many others..
sphinx sucks
godoc sucks
markdown sucks
doxygen is better
jekyll is a blog

its all a nightmare to pull these things together..

What we actually want is a set of state/api/code/docs generates automatically that are true and correct at the time..

But we need some trigger to to make the "updates happen", even if its upstream..
eg swapping from go 1.1 to 1.4
and revel 0.09 to 1.13

As long as the versioning runs with the docs, then it whould bestraight forward..

eg a new git tag = 0.23
and jenkins can read that and go off and compile new set of docs and all..

**Comment by pedromorgan** [comment]
This way we can copy Django which is a good case example..

docs.django.com/latest/ << latest stable
docs.django.com/next/ << latest dodgy in develop
docs.django.com/1.4/ << last stable
docs.django.com/1.2/ << before stable

We have to guarantee that user can get access to legacy docs as part of the contract

an working on this concept at
http://revel-docs.daffodil.uk.com/

If anyone understands what I'm on about in automating stuff a bit, then please whisper back..

Maybe we even start to eat dog food.. and make "revel"  compile itself..

**Comment by pedromorgan** [comment]
Infact the best version no is the date..
2015-01-25T23:00: 07
There is no argument then about version.. latest

**Comment by brendensoares** [comment]
@pedromorgan I already agreed on the YAML file idea in #418. We'll want to add a `revel version` command also.
