### ISSUE TITLE
reflect.go:299: Could not find import...

### ISSUE THREAD

**Issue by arvenil** [revel/revel#859]
I recently was updating a lot of packages in project (including revel) and I ended up with:

```
TRACE 2015/01/20 22:23:50 harness.go:126: Rebuild
TRACE 2015/01/20 22:23:50 reflect.go:299: Could not find import: fmt
TRACE 2015/01/20 22:23:50 reflect.go:299: Could not find import: net/http
TRACE 2015/01/20 22:23:50 reflect.go:299: Could not find import: runtime
TRACE 2015/01/20 22:23:50 reflect.go:299: Could not find import: strings
TRACE 2015/01/20 22:23:50 reflect.go:299: Could not find import: fmt
TRACE 2015/01/20 22:23:50 reflect.go:299: Could not find import: net/http
...
```

Only standard libraries are listed.

Everything works though. But still those TRACE errors are making me suspicious :) Any idea?

**Comment by notzippy** [comment]
I see those as well, the reflect package looks at the import and tries to determine a list of packages that a file needs to compile. Packages are determined by  the prefix of the package name (like "github.com/foo/bar") The standard libray errors out since it has no such prefix.

**Comment by brendensoares** [comment]
@arvenil thanks for bringing this up. It seems @robfig [noted some TODOs that touch on this trace](https://github.com/revel/revel/blame/master/harness/reflect.go#L291) you're seeing. The message itself is not very clear and could be improved.

I'll close this for now since it isn't a breaking issue, but we'll have to improve this soon. Thanks!

**Comment by brendensoares** [comment]
Actually, I think we should keep this open and just assign it to the backlog, that way we'll come back to it later (rather than hoping we do sometime in the future).

**Comment by notzippy** [comment]
This is part of the cli project and will be taken care of there
