### ISSUE TITLE
controller.go:96: No RenderArg names found for Render call on line 5 (Action Test.Index )

### ISSUE THREAD

**Issue by jinchizhong** [revel/revel#861]
Hi friends.

I cannot reference variants in templates. The console output line:

```
controller.go:96: No RenderArg names found for Render call on line 5 (Action Test.Index )
```

Here is my `controllers/test.go`

``` go
    package controllers

    import "github.com/revel/revel"

    type Test struct {
            *revel.Controller
    }

    func (c Test) Index(xxx string) revel.Result {
            println(xxx)
            return c.Render(xxx)
    }
```

Then, I read `controller.go`, I found this:

``` go
    func (c *Controller) Render(extraRenderArgs ...interface{}) Result {
        // Get the calling function name.
        _, _, line, ok := runtime.Caller(1)
        if !ok {
            ERROR.Println("Failed to get Caller information")
        }

        // Get the extra RenderArgs passed in.
        if renderArgNames, ok := c.MethodType.RenderArgNames[line]; ok {
            if len(renderArgNames) == len(extraRenderArgs) {
                for i, extraRenderArg := range extraRenderArgs {
                    c.RenderArgs[renderArgNames[i]] = extraRenderArg
                }
            } else {
                ERROR.Println(len(renderArgNames), "RenderArg names found for",
                    len(extraRenderArgs), "extra RenderArgs")
            }
        } else {
            ERROR.Println("No RenderArg names found for Render call on line", line,
                "(Action", c.Action, ")")
        }

        return c.RenderTemplate(c.Name + "/" + c.MethodType.Name + "." + c.Request.Format)
    }
```

I change `_, _, line, ok := runtime.Caller(1)` to `xa, xb, line, ok := runtime.Caller(1)` and dump them, I get follow error:

```
2015/01/23 02:32:54 controller.go:96: No RenderArg names found for Render call on  134586657 /home/jcz/go/src/github.com/revel/revel/samples/chat/app/controllers/test.go  line 5 (Action Test.Index )
```

Then I read other codes in revel, I known revel expect got `11` instead of `5`.
And I think `11` is a right value, not `5`. Maybe there is a bug in gogcc. 
I known I'd better to report this issue to golang project.
But I cannot reproduce this issue without revel, because I am a beginner of golang(I learn golang since today).

My system: `Ubuntu 14.04.1 LTS i386`
go is installed by `sudo apt-get install gccgo`

```
jcz@jcz-nuc:~/go/src/github.com/revel/revel$ dpkg -l | grep gccgo
ii  gccgo                                                 4:4.9-1ubuntu6                                      i386         Go compiler, based on the GCC backend
ii  gccgo-4.9                                             4.9.1-0ubuntu1                                      i386         GNU Go compiler
ii  gccgo-go                                              1.2.1-0ubuntu1                                      i386         Go tool for use with gccgo
```

**Comment by jinchizhong** [comment]
And, can anybody tell me: how to work around this issue. 
Thank you.

**Comment by brendensoares** [comment]
@jinchizhong we'll need to test this issue to see if we can reproduce it. I can't do that now, but I'll try to soon.

In the mean time, can you try something like:
```go
func (c Test) Index() revel.Result {
    xxx := "test string
    return c.Render(xxx)
}
```

**Comment by jinchizhong** [comment]
Hi @brendensoares 

I change `controllers/test.go` to:

    package controllers
    
    import "github.com/revel/revel"
    
    type Test struct {
        *revel.Controller
    }
    
    func (c Test) Index() revel.Result {
        xxx := "Test String"
        return c.Render(xxx)
    }

Nothing is changed.

BTW, the official demo is also cannot works good in my machine.

Here are two warnings:

    2015/01/23 04:11:42 controller.go:96: No RenderArg names found for Render call on  134580909 /home/jcz/go/src/github.com/revel/revel/samples/chat/app/controllers/app.go  line 7 (Action Application.Index )
    2015/01/23 04:12:09 controller.go:96: No RenderArg names found for Render call on  134586543 /home/jcz/go/src/github.com/revel/revel/samples/chat/app/controllers/test.go  line 5 (Action Test.Index )

`revel/revel/samples/chat/app/controllers/app.go` is also work badly.
It must be `12` not `7` in `revel/revel/samples/chat/app/controllers/app.go`

**Comment by jinchizhong** [comment]
Hi @brendensoares 

I'm very happy to tell you a message.

I install another package in ubuntu that also provide go.
And then I rerun the demo, everything is OK.
I hope that can help you.

    sudo apt-get install golang

**Comment by anonx** [comment]
So, the issue has been resolved? I'm closing it then. Feel free to reopen.

**Comment by xaionaro** [comment]
Confirm. I had the same issue. And it disappeared after updating golang in Debian (from 1.3.1 to 1.3.3) and rebuilding the project.

**Comment by xaionaro** [comment]
Sorry. It appared again:

    ERROR 2015/05/07 10:16:16 controller.go:97: No RenderArg names found for Render call on line 281 (Action Units.Index )

**Comment by brendensoares** [comment]
I tried my `xxx` suggestion above in Revel v0.12 and Go 1.4 on Mac OS X and it works fine.

I'm going to close this unless it can be proven. We could schedule a time to talk on IRC if needed to confirm the issue.

Thanks.

**Comment by wildattire** [comment]
Is there any hope of re-opening this? We are experiencing the exact same problem after upgrading from Go 1.7 to Go 1.9.

**Comment by notzippy** [comment]
@wildattire have you tried a `revel clean` and rebuild ?
Worst case you can assign the values into `c.ViewArgs` like
```
a,b,c := 1,2,3
c.Render(a,b,c)
```
is the same as
```
c.ViewArgs["a"]=1
c.ViewArgs["b"]=2
c.ViewArgs["c"]=3
c.Render()
```
I will try to test this later today

**Comment by wildattire** [comment]
Thanks. Yes, we've done a clean rebuild of revel and pretty much all dependencies everywhere.
in this line:

`if renderArgNames, ok := c.MethodType.RenderArgNames[line]; ok { ... }`

The value of line is 478, but c.MethodType.RenderArgNames has a single entry in it, with a key of 479. So perhaps there is an off-by-one error somewhere?

We've kludged up a little patch in the Render() function to reassign line in the event there's only one entry in the map:

```
	if _, ok := c.MethodType.RenderArgNames[line]; !ok && len(c.MethodType.RenderArgNames) == 1 {
		for k := range c.MethodType.RenderArgNames {
			line = k
		}
	}
```
Which resolves the error.

I can also confirm that your suggestion of manually setting ViewArgs prior to zero-param Render() also works. Thanks.

**Comment by notzippy** [comment]
@wildattire 
Hmm, what type of variables are you passing ? I tried a int, string, time.Time - all worked without errors (go 1.9). I tried with one and two variables

**Comment by notzippy** [comment]
I figured it out ! This fails
```
	return c.Render(
		a,
		b)

```
This works 
```
	return c.Render(a,b)
```

**Comment by wildattire** [comment]
We are passing:
 - 2 large structs with strings, ints, bools, []strings, etc
 - 7 struct slices, all of different types, each with nested structs, strings, etc
 - 5 strings

15 parameters total, most of which are slices of structs. It's a fair amount of data. Sorry, not at liberty to explicate the structure of all of them.

**Comment by wildattire** [comment]
Oops, I only saw your question for some reason, not the fix. I can confirm, when we put all our parameters on a single line, it works fine. Thanks!

**Comment by notzippy** [comment]
I can see why you went multiline ! Lol
