### ISSUE TITLE
Add more app skeletons

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#862]
#727 provides a bower based skeleton.

It may be a good idea to introduce a repo for `revel/skeletons` that will contain template for bootstrap, foundation, bower, ember, angular, etc. So we would remove the `skeleton` folder from the Revel library. This should be fine as it's only used [by the `revel new` command](https://github.com/revel/cmd/blob/a11342d6e7b475488f6d71d13542dcad20b76ba3/revel/new.go#L16).

I don't think this needs a RFC since it's more of a organizational issue. @revel/core let me know if you agree.

**Comment by anonx** [comment]
Not @revel/core but anyway... I think this is a reasonable decision. The only concern is to make sure that we wouldn't have to repeat ourselves. Like a few copies of the same `app.conf` or any other file for every of the skeletons: bootstrap, foundation, bower, ember, angular. That would be a lot of files difficult to maintain. So, I think there should be some basic part of skeleton and extension (which overrides basic part) in a form of boostrap, ember, or something else.

**Comment by notzippy** [comment]
The new CLI tool will address having skeletons in the cloud so to speak
