### ISSUE TITLE
Is my templatefuncs issue?

### ISSUE THREAD

**Issue by xpbliss** [revel/revel#863]
in controller,i define a TemplateFuncs in the init() function.
```go
   func init() {
       revel.TemplateFuncs["addOne"] = func(a int) int {
                return a + 1
        }
    }
```
it's ok when using "addOne" function under the view directory other files. but when i read the file and let's a template file. revel always says "template: :165: function "addOne" not defined". the following is the code.

in controller:
```go
wfile, _:= os.OpenFile(os.TempDir()+"/"+time.Now().Format("200601021504")+".xml", os.O_CREATE|os.O_RDWR, 666)
    body, _ := ioutil.ReadFile(revel.BasePath + "/docTemplate/my.xml") //my.xml is the template files,although in the app.conf "template.delimiters = "[[ ]]"",but in the my.xml,it must use the "{{}}"
    str := string(body)
    str = strings.Replace(str, "&quot;", `"`, -1)
    t, er := template.New("").Parse(str)
    if er != nil {
    fmt.Println(er)
    }

con := revel.ExecuteTemplate(template.Must(t, er), c.RenderArgs)
wfile.WriteString(con)
```
in views (my.xml):
```go
{{range $num,$prj:=.prj}}
         This is the order {{addOne $num}}----{{$prj.Name}}
    {{end}}
```
what wrong with my codes?

**Comment by xpbliss** [comment]
how to use
revel.TemplateFuncs["addOne"] = func(a int) int {
return a + 1
}
into
 t, er := template.New("").Funcs("addOne").Parse(str)   ?

**Comment by xpbliss** [comment]
It must be do as the following. it's ok.
	funcMap := template.FuncMap{
		"addOne": revel.TemplateFuncs["addOne"],
	}
	t, er := template.New("").Funcs(funcMap).Parse(str)

why not direct to using the {{addOne $num}}? any other ways?

**Comment by brendensoares** [comment]
@xpbliss I edited your comments to format the code samples. It makes it much easier to read. Please try to use the code formatting in the future :)

As far as your question...
> but when i read the file and let's a template file. revel always says "template: :165: function "addOne" not defined

What do you mean "read the file" and "let's a template file"?

**Comment by xpbliss** [comment]
sorry!
"read the file"---> get the content from the file "my.xml"
"let's a template file" -----parse the content and save to another file.

as my mention the first above,then  revel always says "template: :165: function "addOne" not defined.
if then do the second above ,then it's ok.  if you save the first as a example, you'll find.

**Comment by notzippy** [comment]
In your first example you can simply do a 

     t, er := template.New("").Funcs(revel.TemplateFuncs).Parse(str)

And it will work, this is what occurs when revel retrieves the templates internally and the revel.ExecuteTemplate does not perform that action because it should already have been done at that point.

**Comment by notzippy** [comment]
Closing issue
