### ISSUE TITLE
Deploy to heroku doesn't work

### ISSUE THREAD

**Issue by fellz** [revel/revel#866]
Hi there
I am trying to deploy the app to heroku but 

Starting process with command `mygoapp`
2015-02-04T13:33:27.196406+00:00 app[web.1]: bash: mygoapp: command not found

```
Procfile
web: mygoapp
```

I thought it should be compiled to mygoapp bin and run the app but it appears that it doesn't compile...
I used this to build app
`heroku create -b https://github.com/revel/heroku-buildpack-go-revel.git`

and with godep

godep save ./...

of course i also added .godir

**Comment by brendensoares** [comment]
I wish I could help, but I have not tried running Revel on Heroku. If I have time in the near future, I can try myself, but in the mean time, please investigate further and share any findings here.

Thanks!

**Comment by munrocape** [comment]
@fellz 

If you are using that buildpack, remove the procfile. 

Also, do you deploy from the mygoapp/ dir? If so, I believe your .godir should be `mygoapp` and not `github.com/fellz/mygoapp`

**Comment by fellz** [comment]
```
-----> Running: godep go install -tags heroku ./...
go build github.com/fellz/mygoapp/tests: no buildable Go source files in /tmp/build_2817461966e127c0d32d3351f5ea5892/fellz-mygoapp-59c4fc3/.go/src/github.com/fellz/mygoapp/tests
godep: go exit status 1

 !     Push rejected, failed to compile Revel app
```

Still no luck. Deleted Procfile. 
Well i guess Revel kind of special case Go app that need some configs to be build on Heroku i guess. That sounds pretty sad because i like go for it's simplicity and no magic but in this case ... 
If we look at the log message
```  no buildable Go source files in ... .go/src/github.com/fellz/mygoapp/tests ```
But there is a file app_test.go. and it want to build that dir also beyond my understanding ...

**Comment by anonx** [comment]
@fellz Your revel test file cannot be named as `app_test.go`. Everything with `_test.go` at the end is treated as a golang test file. Revel tests are usual golang files. Thus it should be `apptest.go` or any other name without that suffix.

**Comment by fellz** [comment]
Oh finally it works )) 
Fixed that test file ( btw i changed because go test doesn't see any test files in test dir) 
Removed Procfile
Added  ``` github.com/fellz/mygoapp ``` to .godir
This is valid config if anyone need this 
https://github.com/fellz/mygoapp

**Comment by anonx** [comment]
> i changed because go test doesn't see any test files in test dir

@fellz That's how it should work. `tests` directory is for `revel test` not `go test`. It is possible to write go tests for revel tests though :-)

**Comment by netbun** [comment]
@fellz, please close this issue

**Comment by brendensoares** [comment]
@pushrax @anonx Is there anything we can document from this issue to help others?

cc @pedromorgan

**Comment by anonx** [comment]
@brendensoares I think so. There are a few articles related to the subj BTW:
1. Original http://www.jamesward.com/2012/09/28/run-revel-apps-on-heroku
2. Update http://traviscline.com/blog/2012/11/18/update-running-revel-apps-on-heroku/
And the one you have mentioned in [Articles](https://github.com/revel/revel/wiki/Articles):
1. https://medium.com/@jatescher/building-a-go-web-app-with-revel-on-heroku-37247cc1d9a6

Though, I don't quite understand why anybody would want to install golang and all necessary dependencies on production server if it's possible to test, configure, build, and pack everything locally. And it can be automated, too.

**Comment by brendensoares** [comment]
@anonx added that 2nd link to Articles as the other 2 were already there.

As far as using Heroku and the like, it may be a matter of inexperience and/or ease. Also, if Heroku is the preferred platform for a project, could they deploy binaries? I don't know, but my gut says you can't.

**Comment by franchb** [comment]
I have the same issue. `.godir` and `Procfile` - nothing helps...

Maybe, there is any other issue with Golang app on Heroku?

**Comment by Steve-hyas** [comment]
@franchb I am not a Heroku expert, but I will try to deploy a sample app this weekend..

**Comment by notzippy** [comment]
@franchb I am not a Heroku expert, but I will try to deploy a sample app this weekend..

**Comment by franchb** [comment]
Thank you, @notzippy 

I will post here if I can solve this problem myself.

**Comment by franchb** [comment]
Sorry, the error was due to the presence of an internal error in the code. Everything is working!

My advice for next beginners -- try to log steps in your main code.

**Comment by notzippy** [comment]
thanks for replying
