### ISSUE TITLE
meta.git = Most wanted

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#875]
Can someone in the team create the
/revel-meta

repository
and the basic licenxe and read me..

I have a cunning plan, but this would be where I can place
a lot of where stuff is etc..
Idea is that this will be a jenkinjs job on open shift

and copying a little of how FlightGear build such a huge system

So please @brendensoares , @notzippy , @anonx or whoever..
Create this an then I automate things a bit more..

This will also be good for builders and is intended to be upstread static data of whats downstream..
a bit of a cmake.txt scenario in yamle encoded xhtml data

**Comment by pedromorgan** [comment]
ASAP please

**Comment by pedromorgan** [comment]
The base is this complex build for FG
- https://gitorious.org/fg/fgmeta/

But in our case its much much simpler

**Comment by anonx** [comment]
@pedromorgan What will it automate? Docs compilation?

**Comment by pedromorgan** [comment]
Yes an all else..

Revel needs a space like the FG above.. but less complicates..

However it will be machine readable this stuff and core intention.......

So please create that as I need it for jenkins..

Expect all strange scripts and alike..

**Comment by pedromorgan** [comment]
And yes automate stuff is main objective..

**Comment by pedromorgan** [comment]
BTW @brendensoares 
Can we start using revel-determinator.com.domain
and also very important

if we got a somainn and some githue and revel@openhsift jenkins
then we are laaaughing

Can we start use domaain splease ?

**Comment by brendensoares** [comment]
revel-determinator??

Laughing?

We can start using the domain, but we should release v0.12 first. What do you want to use it for right now?

You are a crazy Welsh. It's hard to understand what you're saying sometimes, but I've created a `meta` repo for you to experiment. Hopefully then I'll see the value of your idea.
