### ISSUE TITLE
switch Revel Docs

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#876]
@brendensoares mainly

Can we merge develop into next..
With all my stuff and links etc

I KNOw there are flaws and will hot patch as we go

Trust me
So this now..
and we work out godocs and stuff as we go..

This is a huge hold up imho..
lets step the docs up first..

merge it..
Please..

You guys do and develop code.. 
if its a complete cock up in manual i generally know..
but lets mode on........
and i deal with docs..

**Comment by brendensoares** [comment]
I don't understand what you're asking. Move `develop` into next?

I'm focused on finishing the new subpackages and then we can release v0.12. I assume this is what you want.

Not sure how you are being held up on docs. You want to release docs now and it can't wait?
