### ISSUE TITLE
Params Time Binding

### ISSUE THREAD

**Issue by ready4god2513** [revel/revel#878]
I may have been doing something wrong, but I believe that there is a mistake in the docs.  The docs state that ```The SQL standard time formats [“2006-01-02”, “2006-01-02 15:04”] are built in.``` but that doesn't appear to be the case.

Right here is where the bindings are set- https://github.com/revel/revel/blob/master/binder.go#L226 which is perfect.  HOWEVER, the default config to ship with revel actually does have the date format set here- https://github.com/revel/revel/blob/master/skeleton/conf/app.conf.template#L69  So by default revel appears to only bind on ```01/02/2006``` and ```01/02/2006 15:04```

So either the docs need to change or the default config needs to change.

Let me know if I am incorrect on this.  Thanks!

**Comment by anonx** [comment]
Hi, @ready4god2513. You are right, looks like the docs are outdated.

> The SQL standard time formats [“2006-01-02”, “2006-01-02 15:04”] are built in.

These formats [were](https://github.com/revel/revel/commit/78f6670017c2f46773252dfb0cc373125935ebb7) built in ages ago:
![SQL time formats](http://i.imgur.com/cdSiDO3.png)
Now they are not.

Fix is more than welcome here: https://github.com/revel/revel.github.io/tree/develop


#### Related docs links
https://revel.github.io/manual/appconf.html#formatting
https://revel.github.io/manual/binding.html#date--time

**Comment by anonx** [comment]
We are probably coming back to the time format mentioned in the docs: https://github.com/revel/revel/pull/872#discussion_r25130060. So, changes to the docs may not be needed.

**Comment by ptman** [comment]
So change config to ISO8601 ? I can do a PR if that moves this forward.

**Comment by jeevatkm** [comment]
As per my understanding, binder code look okay. Just skeleton [app.conf](https://github.com/revel/revel/blob/develop/skeleton/conf/app.conf.template#L69) needs an update from 
```ini
format.date     = 01/02/2006
format.datetime = 01/02/2006 15:04
```
to
```ini
format.date     = 2006-01-02
format.datetime = 2006-01-02 15:04
```
@ptman would you like to do it?

**Comment by jeevatkm** [comment]
Taken care, thanks to @ptman 

I'm closing this one.
