### ISSUE TITLE
Routes not loaded when OnAppStart callback run

### ISSUE THREAD

**Issue by pbnjay** [revel/revel#883]
I will try to track some of this down, but it seems that routes have not yet been loaded when OnAppStart callbacks are processed, causing a panic when a reverse route retrieval is attempted. I haven't been able to find documentation about expected behavior one way or the other.

To get around this, I'm using a sync.Once in an existing BEFORE Interceptor, but obviously this is not ideal.

**Comment by pbnjay** [comment]
Here's a minimal example for the base skeleton app:

    $ revel new noroutes
    $ vim noroutes/app/controllers/app.go

```
package controllers

import (
        "github.com/revel/revel"
        "log"
        "noroutes/app/routes"
)

type App struct {
        *revel.Controller
}

func (c App) Index() revel.Result {
        return c.Render()
}

func init() {
        revel.OnAppStart(func() {
                log.Println(routes.App.Index())
        })
}
```

    $ revel run noroutes

Hit up http://localhost:9000 in your browser and then you'll see:

```
ERROR 2015/02/25 12:11:55 router.go:419: Failed to find reverse route: App.Index map[]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1f8182]

goroutine 16 [running]:
runtime.panic(0x436c80, 0x70c244)
	/usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/panic.c:279 +0xf5
noroutes/app/routes.tApp.Index(0x0, 0x0)
	/Users/jeremy/src/noroutes/app/routes/routes.go:15 +0x92
noroutes/app/controllers.func·001()
	/Users/jeremy/src/noroutes/app/controllers/app.go:19 +0x2a
github.com/revel/revel.runStartupHooks()
	/Users/jeremy/src/github.com/revel/revel/server.go:126 +0x65
github.com/revel/revel.Run(0xeeb7)
	/Users/jeremy/src/github.com/revel/revel/server.go:100 +0x4ce
main.main()
	/Users/jeremy/src/noroutes/app/tmp/main.go:108 +0xe08
```

**Comment by notzippy** [comment]
The router is initialized in the same fashion as your call 

	OnAppStart(func() {
		MainRouter = NewRouter(path.Join(BasePath, "conf", "routes"))
		if MainWatcher != nil && Config.BoolDefault("watch.routes", true) {
			MainWatcher.Listen(MainRouter, MainRouter.path)
		} else {
			MainRouter.Refresh()
		}
	})

So if your OnAppStart happens before the router then you wont see the routes. I always thought OnAppStart should have a weight assigned to it so that important things can happen first

**Comment by anonx** [comment]
Link to the fragment of code @notzippy has mentioned above: https://github.com/revel/revel/blob/master/router.go#L424-L431

**Comment by pbnjay** [comment]
Yeah I figured this was an init() ordering issue, but I can't seem to find a way to address this easily.

I could hack in an optional weight to the OnAppStart() call, or add a new func OnAppStartWeighted().

**Comment by pbnjay** [comment]
Actually... looking at the code @anonx linked to, when watching is enabled, MainRouter.Refresh() isn't called yet after the router is loaded from `router.go:init()` - so when the app init is called the routes are still empty. In fact running in "prod" mode on my example works perfectly without any changes.

So maybe the "fix" is as easy as preemptively calling MainRouter.Refresh() before adding to the watcher?

**Comment by anonx** [comment]
@pbnjay I think you are right and the code below would do the trick:
```diff
OnAppStart(func() {
	MainRouter = NewRouter(path.Join(BasePath, "conf", "routes"))
	if MainWatcher != nil && Config.BoolDefault("watch.routes", true) {
		MainWatcher.Listen(MainRouter, MainRouter.path)	
-	} else {
-		MainRouter.Refresh()
	}
+	MainRouter.Refresh()
})
```
Right now, routes generation is triggered by the first request to the app. And the change forces it to refresh routes on app start no matter what. @brendensoares did the same change to templates generation IIRC.

**Comment by anonx** [comment]
#884 is merged, so I'm closing this.
