### ISSUE TITLE
Howto Template

### ISSUE THREAD

**Issue by jniltinho** [revel/revel#905]
Rules in Template:

Example:

Get {{set number1 = number / 1024}} or
{{set number1 = number * 1024}}

**Comment by anonx** [comment]
Templates should not be used for calculations. That's what controllers are for. But if you really want to, create a template helper function in one of your controllers or in `app/init.go`:
```go
func init() {
	revel.TemplateFuncs["multiply"] = func(a, b int) int {
		return a * b
	}
}
```
Use it in your template as:
```djangotemplate
{{set . "number1" (multiply .number 1024)}}
{{.number1}}
```
-----------------------------------------------------------------------------
**And as I have already said, Stackoverflow is where questions should be asked. This is a bugtracker.**

**Comment by pushrax** [comment]
Sometimes templates are the right place to do certain calculations if the result is only relevant to the view. For example, calculating a percentage from a ratio. However, the cleanest way would be to create a filter ("TemplateFunc") that does the specific calculation, rather than doing arbitrary math in the template.

**Comment by jniltinho** [comment]
:+1: 
Thanks

I'll post my questions on Stackoverflow

I migrated my Beego project to Revel, I am very loving the Revel, congratulations to all of the community are doing a wonderful job.

The revel.github.io was pretty much after the upgrade.

I hope I can help in translating some contents to Portuguese Brazil and create some screencast

**Comment by notzippy** [comment]
@jniltinho Help with documentation and translation would be great. Screencasts would be very appreciated as well. :100:

**Comment by pedromorgan** [comment]
We need to include a quick "template starter" to the docs, its on my TODO list...

**Comment by brendensoares** [comment]
@jniltinho thank your very much for your gratitude! It means a lot to me (and us) to have positive feedback from fellow developers :)
