### ISSUE TITLE
Tag like there is no tomorrow

### ISSUE THREAD

**Issue by notzippy** [revel/revel#907]
I know we are not at version 1 yet, but I would still like to start putting in tags on all repositories after a release. If anyone has an objection to this let me know. 

AFAIK we are at version v0.11 in the following
* revel/cmd
* revel/revel 
* revel/modules 
* revel/cron 
* revel/config
* revel/samples
* revel/heroku-buildpack-go-revel 

And at version v0.12 in the following
* revel/revel.github.io

revel/rfcs has no need for this and revel/meta is empty

Is that right ?

**Comment by pedromorgan** [comment]
revel/meta is WIP and soon ....

But idea of meta is to basically do as above..
and pointers to all the repos, and all the tags..
a bit of a go.deps, but in yaml and used to generate www site etc..

We also need to look at revel/openshift-buildpack......

and make a page on platforms it downt run on.. yet eg appengine

**Comment by pedromorgan** [comment]
ALSO, tags make a github Release.. chich could be automated by jenkins..

Anyone who wants access to my Jenkisn server.. then please email me...

But am working towards automation more.. and even using revel-frameworks.com
and custom plugins and more automation away from github.. (and its limitations)

**Comment by brendensoares** [comment]
@notzippy :100: agreed. I just mentioned this to @anonx in the v0.12 PR regarding the `cmd` repo.

@notzippy Can you set these up? We should setup matching milestones, too. This may not apply to the `samples` repo, though. Thoughts?

**Comment by notzippy** [comment]
@brendensoares I think `samples` should be labeled as well since there will be some changes which are not backwards compatible. I will label once we we are united on what the version name should be :+1:

**Comment by brendensoares** [comment]
@notzippy https://github.com/revel/revel/wiki/Meetings#agenda Added.

**Comment by pedromorgan** [comment]
@brendensoares  Can u tag NOW.. modules needs to be 0.12 as I need for api query.. 
Same with docs also.. 
@notzippy has got it right inmho.. particuar if we have to "emergency fix a release".. so need to tag everything..

Someone mentioned a manifest recently on IRC, can remember who..
Can we add that to revel/meta

**Comment by pedromorgan** [comment]
Taken an initiative and tagged revel.gh.io ;-)

First time I even done that, its easy when u have perms init.. ;-)))

**Comment by brendensoares** [comment]
@pedromorgan cmd, modules, samples all tagged with `v0.12.0.

**Comment by anonx** [comment]
Can we close this?
