### ISSUE TITLE
non-fatal errors when building

### ISSUE THREAD

**Issue by rtm7777** [revel/revel#908]
Hi everyone!

In my project I added `tmp` and `routes` folder to `.gitignore`, as they are generated when the app is building.

And after upgrading to Revel 0.12 I got few errors in console, because the build tool is trying to clear it.

Maybe we should check if this folders are exist before clearing?

Thoughts?

Travis build:
https://travis-ci.org/rtm7777/rozklad_cdtu/builds/55864135

**Comment by brendensoares** [comment]
@rtm7777 I noted the same thing locally, but didn't create an issue for it yet, so we'll use this :)

Thanks!

**Comment by brendensoares** [comment]
This has been merged. Thanks all!
