### ISSUE TITLE
Error v0.12.0 -- Failed to load module.

### ISSUE THREAD

**Issue by jniltinho** [revel/revel#909]
~
~ revel! http://revel.github.io
~
2015/03/26 00:43:12 revel.go:300: Failed to load module.  Import of github.com/revel/revel/modules/static failed: cannot find package "github.com/revel/revel/modules/static" in any of:
	src/github.com/revel/revel/modules/static (from $GOROOT)
	src/github.com/revel/revel/modules/static (from $GOPATH)

**Comment by brendensoares** [comment]
Try running `go get github.com/revel/cmd/revel` and make sure your `$GOPATH` `/src` folder has `github.com/revel/modules` in it.

I looks like you're running an old version of revel. Can you provide reproduction steps?

**Comment by anonx** [comment]
@jniltinho You need to update your `conf/app.conf`. We have move modules to a separate repo in revel v0.12.0. So, replace:
```ini
module.static=github.com/revel/revel/modules/static
```
and
```ini
module.testrunner = github.com/revel/revel/modules/testrunner
```
by their new paths:
```ini
module.static=github.com/revel/modules/static
```
and
```ini
module.testrunner = github.com/revel/modules/testrunner
```
Thank you.

@brendensoares BTW did we include this in the release notes.

**Comment by brendensoares** [comment]
@anonx [Noted in release](https://github.com/revel/revel/releases/tag/v0.12.0) Thanks!

**Comment by xpbliss** [comment]
where is the "github.com/revel/revel/modules/static"  in the revel v0.12.0 ?

http://github.com/revel/revel/modules/static  is the "404"

**Comment by xpbliss** [comment]
f:\go_example\src\myap\app\tmp\main.go:699: undefined: revel.TestSuites
ERROR 2015/03/26 16:34:06 build.go:247: Failed to parse build errors:
 # myap/app/tmp

How to do?

**Comment by anonx** [comment]
@xpbliss Here is a list of breaking changes: https://github.com/revel/revel/releases/tag/v0.12.0
You need to update your files in `tests/` directory. Instead of `revel.TestSuite` you should use `testing.TestSuite` (from `github.com/revel/revel/testing` package).

**Comment by xpbliss** [comment]
After i execute "go get github.com/revel/cmd/revel" again, it's ok.

**Comment by jniltinho** [comment]
:+1: 
Update Revel and CMD

Changes conf/app.conf

Run app, logs

INFO  2015/03/26 09:13:44 revel.go:329: Loaded module static
INFO  2015/03/26 09:13:44 revel.go:329: Loaded module testrunner
INFO  2015/03/26 09:13:44 revel.go:206: Initialized Revel v0.12.0 (2015-03-25) for >= go1.3
INFO  2015/03/26 09:13:44 main.go:30: Running revel server

**Comment by brendensoares** [comment]
Excellent! Thanks for helping u improve Revel! @jniltinho @xpbliss
