### ISSUE TITLE
how can I use packages version manager with revel?

### ISSUE THREAD

**Issue by xuxiangyang** [revel/revel#916]
Hi，I a newcomer to revel. I have a question about  managing extra packages. If I use another package, How can I lock it's version? how to use revel with [gopm](https://github.com/gpmgo/gopm), or something like gopm?
I need some help, Thank you.

**Comment by pedromorgan** [comment]
There are many choices.. check here
https://code.google.com/p/go-wiki/wiki/PackageManagementTools

I've used godeps, but the choice is probably something you have to take

**Comment by pedromorgan** [comment]
Also check gvn, (Go Version Manager). .whilst not a package manager is useful tool 
https://github.com/moovweb/gvm

**Comment by pedromorgan** [comment]
Note to seld.. add pakacge manager to docs

**Comment by xuxiangyang** [comment]
Thank you... I will try to use godeps.

**Comment by anonx** [comment]
Thanks everybody. I'm closing it now. @xuxiangyang feel free to reopen if you need to.
Note to @pedromorgan to add package manager to docs :smile:

**Comment by brendensoares** [comment]
@anonx @pedromorgan should we reopen this to make sure package manager gets added in next release?

**Comment by ptman** [comment]
Maybe Go15VENDOREXPERIMENT is more relevant to this than #923

**Comment by brendensoares** [comment]
Closing this due to age and low priority.
