### ISSUE TITLE
Balancing Support and New Features

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#917]
I am struggling to absorb everyone's feedback, bugs and the roadmap all at once.

I need help. I need to delegate tasks. @notzippy @pedromorgan We've talked about new roles for the core team, let's do it!

@pushrax Are you able to be active on the core team? If not I can take you off.

@anonx Are you going to help shape Revel, if so you need to join the team. Otherwise we're going to move ahead without you. Your feedback as a community member is valuable, but I want to work closer with you if possible.

**Comment by anonx** [comment]
@brendensoares I joined the team ~12 hours ago.

> Otherwise we're going to move ahead without you. 

Go ahead. I'll get over it.

**Comment by brendensoares** [comment]
@anonx no doubt you'd get over it and go write another framework :) Glad you made your membership official. Revel sorely needs active devs like you.

**Comment by jniltinho** [comment]
PS - we broke 5,000 GitHub Stars!!! W00t!

Beego -> 4159

Revel +1000 ++

Revel ***long life***

**Comment by jniltinho** [comment]
Hello everyone !!!
My first project using Revel (SPAMD Antispam, Panel Admin Web Mail, Antispam)
Like PostfixAdmin, Modoboa, IRedMail, but with easy installation
Will soon be on Github

![spamd_antispam_revel](https://cloud.githubusercontent.com/assets/1027494/6951579/b4804714-d892-11e4-9567-d5898939e19f.png)

![spamd_antispam1](https://cloud.githubusercontent.com/assets/1027494/6951590/c12fc00c-d892-11e4-84ae-ceff0be1871f.png)

![spamd_antispam2](https://cloud.githubusercontent.com/assets/1027494/6951593/c72bd770-d892-11e4-9a8a-a1999105b591.png)

![spamd_antispam3](https://cloud.githubusercontent.com/assets/1027494/6951600/d384e5b6-d892-11e4-9edd-a2d1d05f0a18.png)

![spamd_antispam4](https://cloud.githubusercontent.com/assets/1027494/6951603/d9a0b8d0-d892-11e4-865b-63f11fff0898.png)

**Comment by brendensoares** [comment]
@jniltinho excellent! Let me know when it's up and I'll add it to our [Apps in the Wild](https://github.com/revel/revel/wiki/Apps-in-the-Wild) wiki page :)

**Comment by pedromorgan** [comment]
Looks nice...

**Comment by anonx** [comment]
@jniltinho Looks cool.

**Comment by pedromorgan** [comment]
The project is probably not FOSS yet, as there as some dodgy parts..

We need to get better at this.. and rock on revel-www in revel..

**Comment by jniltinho** [comment]
@pedromorgan 
I'm making a transition from a legacy application for an OpenSource application
I am working to improve the App every day, will soon have a demo, is an application with several modules, I'm losing a little time with the core to facilitate the creation of other modules.

Aspx (.NET) to Golang(Revel)

**Comment by pedromorgan** [comment]
Keep us updated re pitfallsn good luck on last 10%

**Comment by brendensoares** [comment]
@revel/core who changed the label colors on `revel/revel`? If we make changes, we should at least be consistent across our repos.

**Comment by brendensoares** [comment]
@revel/core alright, so `declined` label was also removed...what's going on? We [have a workflow](https://github.com/revel/revel/wiki/Revel-Workflow#labels) that we need to stick to. Any changes should be discussed and accepted by the whole team.

@pedromorgan did you make these changes?

**Comment by notzippy** [comment]
@brendensoares - I did not make these changes...

**Comment by brendensoares** [comment]
@pedromorgan ...?

**Comment by brendensoares** [comment]
@notzippy I want to implement your idea of roles for #892. Which role would you be best at? Would we rotate roles?

**Comment by notzippy** [comment]
@brendensoares 

Personally I think I would be pretty good at first responder / public relations, the other roles I can take responsibility for a periods of time as well (but not for a month). I am normally available monday - friday 7pm or later for meetings. 

I think it is a vital to rotate positions, no one person can sail a ship, but we all need to be on the same page as far as where that ship is going to. So weekly or biweekly meetups or mashups or whatever you would like to call them are needed. It would be nice if we could have a shared whiteboard, or the likes for working out ideas (I like seeing a goal visually), that would be good (even a shared google worksheet would be good enough). A shared text hangout while working on the sheet would be nice so we can converse while looking at the whiteboard / Agenda...

Just some random thoughts today...
