### ISSUE TITLE
Templating Dream = we want jinja2 with a django, smarty style, with handlers

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#918]
For all u template designer out there......

What we all want as template designers....
is we gone through all the templaiting "techniques"
- eg 
- smarty devs 
- django devs 
- jinga1devs, and jango2
- pinocide oand this and that

We Need to clean up templates..
BIGTIME..

If we can help by making it simple to read a previous template but no same template is another platform..

Come on all u smarty, jinga2, django, et all template users ..

chime in..

**Comment by pedromorgan** [comment]
{% extend "SomeLAYOUT" %}
{% set page = "hello" %}
<h1>Thankx, here is replay vid below</h1>

</sex>

**Comment by jniltinho** [comment]
:+1: 
Pongo2 -> https://github.com/flosch/pongo2
I'm looking Pongo2, very interesting for those from the Python world

We can add a feature in the **next roadmap to add Pongo2**?

Cool !!!

:100:

**Comment by pedromorgan** [comment]
Yes please..
 Am migrating jinga2 n smarty

**Comment by brendensoares** [comment]
@jniltinho already in the current target version [pluggable template engine](https://github.com/revel/revel/wiki/Roadmap#v013-see-issues)

**Comment by brendensoares** [comment]
Closing this as duplicate of #99 and #123

**Comment by jniltinho** [comment]
@brendensoares  I’m sorry.
Thanks, 
New features in 0.13, please do not remove HTTPS, I'm using in my project

**Comment by pedromorgan** [comment]
Can we keep this open,, for feedback please..

**Comment by pedromorgan** [comment]
Wheres the pongo version ??

Can we have a 
- revel/thirdparty
and a a sub modules ??
eg pongo ? gorm, gorp ?

**Comment by brendensoares** [comment]
@pedromorgan no, they have their own repos. I don't see a need to keep their code in our own mirrored repo, do you?

Also, I put this in the backlog, but it may not get much attention if it's there and not in the roadmap.

**Comment by notzippy** [comment]
@brendensoares , @pedromorgan It is on the road map "Pluggable template engine"

**Comment by brendensoares** [comment]
@notzippy indeed it is :confounded:
