### ISSUE TITLE
Just a thought.. cache could ideally be its own project

### ISSUE THREAD

**Issue by vsiv** [revel/revel#920]
I am interested in just the cache implementation for couple of projects. I encourage you guys to think about making it a separate project in itself, in case you haven't already discussed that... Thoughts? Thanks.

**Comment by notzippy** [comment]
Have you looked at the current cache [implementation](http://revel.github.io/manual/cache.html)

Looking at a filesystem cache is targeted for v.15 in the [Roadmap](https://github.com/revel/revel/wiki/Roadmap#v015-see-issues)
Although we do welcome any insights or discussions on the subject

**Comment by anonx** [comment]
Cache is already its own package. And I think it is a good idea to make it even less dependent from revel. This works for testing package, too. There are tasks with higher priority right now though. So, added to backlog for now.

**Comment by brendensoares** [comment]
:+1: this is ready for contribution if anyone else has time to do this.

**Comment by notzippy** [comment]
Closing, there are other topics in need of focus
