### ISSUE TITLE
How to debug app with GDB?

### ISSUE THREAD

**Issue by kaneshin** [revel/revel#921]
Hi revel team,

I'm making a web application and API with `revel` framework.
It's fantastic for developers to create web applications on Golang!!

However, I'm bothering to debug around my app.

It's just inconvenience because to debug revel app needs to…
- pass arguments to execute revel.
    - `workspace/bin/app -importPath app revel -srcPath "workspace/src" -runMode dev`
    - It means, type `gdb -silent --args workspace/bin/app -importPath app revel -srcPath "workspace/src" -runMode dev` to run gdb with revel.
- run `harness` (I'm not sure what is correct name.) **to get requests**.

The below link was used as a reference.
http://stackoverflow.com/questions/23952886/revel-debugging-how-to

My debugging routine..

```
$ gdb --args some-app -importPath github.com/path/to/app -runMode dev
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin14.1.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pairs-go...done.
warning: Missing auto-load scripts referenced in section .debug_gdb_scripts
of file /Users/kaneshin/gopath/bin/pairs-go
Use `info auto-load python-scripts [REGEXP]' to list them.
```

```
(gdb) start
Temporary breakpoint 1 at 0x2000: file /Users/kaneshin/gopath/src/github.com/path/to/app/app/tmp/main.go, line 36.
Starting program: /Users/kaneshin/gopath/bin/pairs-go -importPath github.com/path/to/app -runMode dev
warning: Could not open OSO archive file "/BinaryCache/corecrypto/corecrypto-233.1.2~26/Symbols/BuiltProducts/libcorecrypto_static.a"
warning: `/BinaryCache/coreTLS/coreTLS-35.1.2~2/Objects/coretls.build/coretls.build/Objects-normal/x86_64/system_coretls_vers.o': can't open to read symbols: No such file or directory.
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.1.2~2/Symbols/BuiltProducts/libcoretls_ciphersuites.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.1.2~2/Symbols/BuiltProducts/libcoretls_handshake.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.1.2~2/Symbols/BuiltProducts/libcoretls_record.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.1.2~2/Symbols/BuiltProducts/libcoretls_stream_parser.a"
[New Thread 0x1017 of process 73882]

Temporary breakpoint 1, main.main () at /Users/kaneshin/gopath/src/github.com/path/to/app/app/tmp/main.go:36
warning: Source file is more recent than executable.
36      func main() {
```

```
(gdb) b app/controllers/api/foo.go:48
Breakpoint 2 at 0x9efe0: file /Users/kaneshin/gopath/src/github.com/path/to/app/app/controllers/api/foo.go, line 48.
```

```
(gdb) c
Continuing.
INFO  2015/03/18 03:05:42 revel.go:320: Loaded module static
INFO  2015/03/18 03:05:42 revel.go:320: Loaded module testrunner
INFO  2015/03/18 03:05:42 revel.go:320: Loaded module jobs
INFO  2015/03/18 03:05:42 main.go:39: Running revel server
Go to /@tests to run the tests.
Go to /@jobs to see job status.
INFO  2015/03/18 03:05:42 dbmanager.go:40: DB is : map[base:0xc2080fa000 login:0xc2080fa090]
Listening on :9000...
```

Further more; One debugging process, one request.
So, I have to run GDB debugger again if debugger got request.

Please tell me other method to debug if revel provided.

Or, teach me what debugging feature will be implemented for future if revel doesn't support typical debugging methods now.

Thank you for your consideration.

**Comment by notzippy** [comment]
Thanks for your write up, currently like most GO apps, gdb support is not overly useful. The only thing you can really do with it is set breakpoints and step through code, but a key component - variable inspection was has been missing from GDB since GO 1.2. 

Revel does have exceptional logging support which is very useful for seeing what is going on. Using `revel.DEBUG.Printf("MyVariable %#v",myVariable)` is a quick way to see the value of a variable (Make sure the logger is turned on in the [app.conf](http://revel.github.io/manual/logging.html)).

There is a command function for revel that was written and just has not been merged to launch revel with the ability to launch revel with the debugger see #294

**Comment by kaneshin** [comment]
@notzippy 
Thanks for your reply!

Actually I just wanna stop running application by breakpoints because to verify code should be passed through.

I also got the situation of GDB so far.
- [gdb: Wrong values for local variables](https://github.com/golang/go/issues/8256)

So, I'm giving up debugging with GDB now. :+1: 

Thanks again for your time!!!

**Comment by notzippy** [comment]
Have a look at this project https://github.com/derekparker/delve, I have not tried this recently but it looked pretty good last year, and they are working on making an interface to an ide (the group that developed the golang plugin for intellij is assisting with this https://github.com/go-lang-plugin-org/go-lang-idea-plugin)

**Comment by brendensoares** [comment]
revel/rfcs#4

**Comment by mrichman** [comment]
@notzippy Is there any further info out there for debugging Revel with the IntelliJ Go plugin?
