### ISSUE TITLE
How could i run revel build or revel package with godeps

### ISSUE THREAD

**Issue by kurtzhong** [revel/revel#923]
I am using godep to manage some package for some revel applications, but revel build seems to use the packages from the $GOPATH, how could i let it use the packages from the godeps's packages.

**Comment by anonx** [comment]
> but revel build seems to use the packages from the $GOPATH

@kurtzhong Right, just as any golang application. That's why `godep` has `restore` command that is:

> the opposite of `godep save`. It will install the package versions specified in Godeps/Godeps.json to your GOPATH

https://github.com/tools/godep#restore

**Comment by anonx** [comment]
By the way, now it is not possible to run `godep go test` after every change to code (as described [here](https://github.com/tools/godep#edit-test-cycle)). But I hope we'll have a [solution](https://github.com/revel/revel/issues/889#issuecomment-89614910) soon.

**Comment by anonx** [comment]
Does that answer you question? I'm closing this issue now, feel free to reopen again.

**Comment by kurtzhong** [comment]
Sorry for the late response, i've been busy making our revel app into production.  Basically it's  `godep save -r ./... ` under the revel app's root path, and it will generate a `Godeps` folder.

```
.
├── app
├── conf
├── Godeps
├── messages
├── public
├── README.md
├── run
└── tests
```

To run the revel app, i use a custom script with the following content: 

```bash
#!/bin/bash
GOPATH=`godep path`:$GOPATH revel run www.example.com/myapp/portal 
```

There is one problem, the `godep save` doesn't pull all the content in `revel/modules/testrunner`, it just pull the  `revel/modules/testrunner/app`, so when the revel runs it won't start saying no route file found, and I have to get around this by git clone manually the `github.com/revel/modules` repo and remove the `.git` info. Other than this, so far so good.

**Comment by anonx** [comment]
Hello, @kurtzhong. Thank you for using revel. Try to use `godep save ./app/tmp` (still under the revel app's root path) instead of the command you use. That should solve the problem.

**Comment by anonx** [comment]
Though, wait. It doesn't solve the issue. Looks like a conceptual problem. I'll mark this as a bug.

**Comment by ptman** [comment]
What about GO15VENDOREXPERIMENT with revel?

**Comment by ptman** [comment]
I had no intention of unassigning this, sorry.

**Comment by notzippy** [comment]
Closing, use vendoring instead

**Comment by zuoRambo** [comment]
I add `github.com/revel/revel` to `vendor` and add `revel` to *$PATH*,but when i run `revel run my_app`, i get the follow error
```bash
~
~ revel! http://revel.github.io
~
ERROR 2017/08/09 15:52:22 revel.go:346: Failed to find Revel with error: cannot find package "github.com/revel/revel" in any of:
	/usr/local/go/src/github.com/revel/revel (from $GOROOT)
	/tmp/src/github.com/revel/revel (from $GOPATH)
```

what's wrong? `vendor` is useless ?

**Comment by ptman** [comment]
I'm using https://github.com/golang/dep , but I can't use it for revel itself, because revel needs the revel binary installed in $GOPATH/bin. So I have this in `Gopkg.toml`:

    ignored = [
      "github.com/revel/cron",
      "github.com/revel/modules",
      "github.com/revel/modules/jobs/app/jobs",
      "github.com/revel/revel",
      "github.com/revel/revel/testing",
    ]

That is, I use dep to vendor everything but revel.

**Comment by zuoRambo** [comment]
@ptman @notzippy ,i can't understand why "build.Import" was not search vendor firstly?

**Comment by ptman** [comment]
@zuoRambo how did you install revel? go get github.com/revel/cmd/revel ? in that case revel is installed in GOPATH, not vendor/. Did you remove revel from GOPATH?

**Comment by notzippy** [comment]
@zuoRambo Have you tried using revel/meta#11 ? You can use that to bring your gopath to the state of revel versions from 0.14-0.17. Alternately this person got vendoring to work after cleaning out of his gopath references to the revel package revel/modules#35
