### ISSUE TITLE
websocket issue

### ISSUE THREAD

**Issue by gaochao1** [revel/revel#926]
"golang.org/x/net/websocket" should be 	"github.com/golang/net/websocket"

**Comment by 1lann** [comment]
Are you sure? For what reason?
```
package github.com/golang/net/websocket
	imports github.com/golang/net/websocket
	imports github.com/golang/net/websocket: code in directory /Users/jason/Workspace/Go/src/github.com/golang/net/websocket expects import "golang.org/x/net/websocket"
```
Also github.com/golang/net is just a mirror of golang.org/x/net.

**Comment by gaochao1** [comment]
package golang.org/x/net/websocket: unrecognized import path "golang.org/x/net/websocket",perhaps was blocked by the firewall.
"github.com/golang/net/websocket" is ok.

**Comment by brendensoares** [comment]
If it's just a mirror then there's no gain. Where are you that would cause golang.org to be blocked by a firewall? Closing for now.

**Comment by anonx** [comment]
@brendensoares Google IPs are [blocked](https://en.wikipedia.org/wiki/2014_China_censorship_of_Google_services) in China.

**Comment by 1lann** [comment]
Seems to be related to golang/go#10484. Try changing your DNS?

**Comment by anonx** [comment]
I think this problem could be solved by use of either `godep` or `vendor` for the Revel Sources.

**Comment by brendensoares** [comment]
@anonx what is `vendor`? Perhaps https://github.com/kardianos/vendor ?

**Comment by anonx** [comment]
@brendensoares Yes, exactly.
