### ISSUE TITLE
Test runner doesn't show which assertion failed

### ISSUE THREAD

**Issue by michaelbironneau** [revel/revel#931]
According to the [current manual](http://revel.github.io/manual/testing.html#interactively), failed tests come with additional information as to what caused the failure, such as the assertion that failed and a stack trace. However, I don't see this information:

![image](https://cloud.githubusercontent.com/assets/7848020/7650485/d8c2f008-faee-11e4-95a3-807df93b3933.png)

Running the test non-interactively using `revel run` doesn't give any more detail. Is there a configuration setting that I should set to get this information?

Thanks

**Comment by anonx** [comment]
Hello, @michaelbironneau. What operating system are you using?
According to #928 there are issues with showing detailed info in tesrunner module on Windows.

Expected result is below:
![Revel Testrunner](http://i.imgur.com/zLjKWsw.png)

Instead windows users see what you have published above.

**Comment by michaelbironneau** [comment]
Yep, that's it, thanks :).
