### ISSUE TITLE
Using revel template module as standalone

### ISSUE THREAD

**Issue by avdept** [revel/revel#932]
Is it possible?

**Comment by anonx** [comment]
Hey, @avdept. Revel uses standard [`html/template`](https://golang.org/pkg/html/template/) package. Or do you mean something else?

**Comment by avdept** [comment]
@anonx As far as i understood from revel doc, there is feature to call functions from html templates(besides those passed into view) ?

**Comment by anonx** [comment]
@avdept Right, Revel has a list of [built in](https://github.com/revel/revel/blob/master/template.go#L46) functions (like `url`, `append`, `msg`, etc.) and additionally user defined ones (that you register with `revel.TemplateFuncs`), if there are any.

But that is achieved by use of standard [Funcs](https://golang.org/pkg/html/template/#Template.Funcs) method

> Funcs adds the elements of the argument map to the template's function map. It panics if a value in the map is not a function with appropriate return type. However, it is legal to overwrite elements of the map. The return value is the template, so calls can be chained.

**Comment by brendensoares** [comment]
No action items here. Closing.
