### ISSUE TITLE
Large uploads fail

### ISSUE THREAD

**Issue by bejayoharen** [revel/revel#936]
When doing a large upload, I get a timeout if the upload takes more than 1 minute -- even if the client is steadily providing data. The server should not timeout if while the client is providing data.

The error I see in my logs comes from here (line 49 in params.go):

		if err := req.ParseMultipartForm(32 << 20 /* 32 MB */); err != nil {
			WARN.Println("Error parsing request body:", err)

In revel/server.go, I noticed the server timeouts are set, so I was able to work around my issue with:

    init() {
    	revel.OnAppStart(fixServerTimeout)
    }

    func fixServerTimeout() {
    	revel.Server.ReadTimeout = 0
    	revel.Server.WriteTimeout = 0
    }

which is neither documented or intuitive, but does work.

I think your intention may have been to timeout if the client does not provide data for a minute, or if the server fails to respond after a minute.

Consider, however, the case where the client is uploading a huge file: the server does not respond for a minute because it is still reading, which is perfectly legitimate. However, since it's not writing for a minute, it times out because of the write timeout (Another workaround might be to use threading and send continues).

I don't think the server read/write timeouts should be set at all, or if they are, they should be larger and configurable in the conf file.

**Comment by anonx** [comment]
> I don't think the server read/write timeouts should be set at all, or if they are, they should be larger and configurable in the conf file.

Agree. Looks like the timeouts became a reason of more bad things than good. Let's use "no timeouts" option by default and make it configurable. The following change is required (https://github.com/revel/revel/blob/develop/server.go#L85-L90):

```diff
Server = &http.Server{
	Addr:         localAddress,
	Handler:      http.HandlerFunc(handle),
-	ReadTimeout:  time.Minute,
-	WriteTimeout: time.Minute,
+	ReadTimeout:  Config.IntDefault("timeout.read", 0) * time.Second,
+	WriteTimeout: Config.IntDefault("timeout.write", 0) * time.Second,
}
```
@bejayoharen Do you want to create a PR?

**Comment by bejayoharen** [comment]
Okay, I just copied your changes -- no testing. I don't really know how the revel config system works internally.

**Comment by anonx** [comment]
@bejayoharen Yeah, I didn't test either and missed the fact `int` has to be type casted to `time.Duration`.

**Comment by bejayoharen** [comment]
Okay: https://github.com/revel/revel/pull/940

**Comment by anonx** [comment]
:+1: Thanks.
