### ISSUE TITLE
undefined: "net/http/pprof".Trace

### ISSUE THREAD

**Issue by kurtzhong** [revel/revel#937]
I met this error after using the pprof module today: 
```
[ERRO] 2015/05/25 13:43:01.998282 build.go:101: # github.com/revel/modules/pprof/app/controllers
Godeps/_workspace/src/github.com/revel/modules/pprof/app/controllers/pprof.go:34: undefined: "net/http/pprof".Trace
```
My go version is `go version go1.3.3 linux/amd64` and I am using revel 0.12.0.

Do i need some newer version of go to get rid of this error? Currently i am just disabling the line: 

```
return PprofHandler(pprof.Trace)
```

**Comment by wangmingjob** [comment]
+1 I also met it

**Comment by anonx** [comment]
I haven't tested it yet, but it [may be related](https://stackoverflow.com/questions/20854237/golang-net-http-pprof-doesnt-work#20875828) to the default timeouts introduced in v0.12 (#843).

@kurtzhong, @wangmingjob, could you please add the following fragment to your `init.go` and share the results with us:
```go
func init() {
	revel.OnAppStart(func() {
		revel.Server.ReadTimeout  = 0
		revel.Server.WriteTimeout = 0
	})
}
```

**Comment by kurtzhong** [comment]
![selection_065](https://cloud.githubusercontent.com/assets/735693/7860260/0d175b60-057a-11e5-9f9f-aed578c485b8.png)

Adding the lines doesn't help, besides it's a compile error.

**Comment by brendensoares** [comment]
@kurtzhong @wangmingjob  Are you in China? See #926.

I'm closing assuming that your access is being blocked. Re-open if this is not the issue.

**Comment by kurtzhong** [comment]
We use VPN, so the network is not an issue. I think it's a go version issue. The pprof.Trace support is added in go commit [690db9](https://github.com/golang/go/commit/690db9c89fef427f44a921250421dd2d5fa1a03f). And it does't appear in any go releases, including the latest  `v1.4`, `v1.4.1`, `v.1.4.2` , but it does exit in `master` branch. Which means i should build go version from the master branch to git rid of this error. For now i will just comment out the line that invokes the pprof.Trace in godeps.

**Comment by brendensoares** [comment]
@kurtzhong Thank you for the additional details and work around. I appreciate it!
