### ISSUE TITLE
Config.String() bombing

### ISSUE THREAD

**Issue by niiamon** [revel/revel#938]
There seems to be something strange going on with revel.Config.String(str).

This is what my code looks like:

```go
var Config *revel.MergedConfig = revel.Config
var Driver, _ = &Config.String("db.driver")
var Spec, _ = &Config.String("db.spec")
```

No matter how I look at it, I al always getting this strange error:

`multiple-value Config.String() in single-value context`

Clearly, this is wrong since MergedConfig.String(str) returns `(result string, found bool)`. Anyone else seeing this? 

For now I am hardcoding config vars while I figure this out.

**Comment by nadeemc** [comment]
You're trying to get the pointer of the result when you do &Config.String(), that's why it's saying you're trying to use a single value when multiple are returned. Instead, change it to:

```go
driver, _ := Config.String("db.driver")
Driver = &driver
```

**Comment by niiamon** [comment]
That also doesn't work. What `Driver := &driver` does it so assign a pointer to driver, to Driver. What I want is the value contained in the variable, not the memory reference.

**Comment by nadeemc** [comment]
The *&* symbol is what is assigning the memory reference, so you can remove that to get the original value:

```go
// Assuming you've defined Driver somewhere in the file already
var Driver string

// Read the config value
var found bool
Driver, found = Config.String("db.driver")
if !found {
    panic("db.driver was not defined in the config file.")
}

fmt.Println("Read db.driver value: %s", Driver)
```

You don't need to do the *found* check if you don't want to, but it will help ensure the app doesn't try to run with an empty Driver value.

**Comment by nadeemc** [comment]
P.S. Don't put this logic inside an init() method directly, as revel may not have parsed the config file yet. Instead, set it up as follows:

```go
import (
	"fmt"
	"github.com/revel/revel"
)
var (
	Driver string
)

func init() {
	revel.OnAppStart(func() {
		var found bool
		Driver, found = revel.Config.String("db.driver")
		if !found {
			panic("db.driver is not defined in the config section.")
		}

		fmt.Println("Using db.driver value from config: %s", Driver)
	})
}
```

**Comment by niiamon** [comment]
Thanks a lot. I've got it going properly right now. I'm still getting comfortable with Go.
