### ISSUE TITLE
Symlinks in views directory are treated as templates

### ISSUE THREAD

**Issue by acorbelli** [revel/revel#941]
In app/views/ create a symlink for [Controller]/  to another location (such as duplicating the templates from another directory, [Controller]/ -> [Controller2]/ )

The template loader will treat [Controller] as a symlinked template, and not a symlinked directory

TRACE 2015/05/27 14:26:54 template.go:234: symlink template: [viewspath]/Controller

EDIT - UPDATE:

The initial report wasn't accurate. If the symlink uses relative paths, it appears those relative paths are removed/resolved, so when rendering a template...

views/[Controller]/subdir = -> ../[Controller2]/subdir

then it gets added to the file list in the template loader as: [Controller2]/subdir

> ll
> drwxr-xr-x  3 user  group    102 May 27 14:29 Angular
> ll Angular/
> lrwxr-xr-x  1 user  group  31 May 27 14:29 Application -> ../../application/app1/
> ll Angular/Application/
> -rw-r--r--  1 user  group   11 May 27 20:05 app.js
> -rw-r--r--  1 user  group   0 May 24 22:35 controllers.js
> -rw-r--r--  1 user  group  122 May 27 14:12 test.html

to render I call: 
`c.RenderTemplate("app1/test.html")`

**Comment by jeevatkm** [comment]
@acorbelli - Sorry for delayed response. v0.13 includes the resolving symlink in `views` path. Will this [commit](https://github.com/revel/revel/commit/ff67cb9752654097fc1af8214eaeb7ba6149ccd0) address your issue?

**Comment by jeevatkm** [comment]
I'm closing this one In-favor of PR #867.
