### ISSUE TITLE
default HttpOnly and Secure to true

### ISSUE THREAD

**Issue by jmhodges** [revel/revel#942]
Leaving cookie.httponly and cookie.secure to false by default on cookies will cause folks without detailed knowledge of how web security works (which is most of folks) wide open to impersonation, replay, and XSS attacks.

To handle developers trying to work locally, a check can be done to see if we are in DevMode and to allow the default to be false then.

**Comment by jmhodges** [comment]
The code in question: https://github.com/revel/revel/blob/0d091bfa31943267e4c3f3ffb3bec6082ec6b49f/revel.go#L186-187

**Comment by anonx** [comment]
Here is another related fragment: https://github.com/revel/revel/blob/master/skeleton/conf/app.conf.template#L35-L54

**Comment by brendensoares** [comment]
PR #943 fixes this.
