### ISSUE TITLE
Maybe not issue but any help is appriciated

### ISSUE THREAD

**Issue by goors** [revel/revel#945]
Maybe this is stupid question but how can use comparison operators in templates? For example:

<pre>
    {{range .categories}}
        {{if .ParentCategory eq .Id}}
          show something
        {{end}}
    {{end}}
</pre>
ParentCategory is int and Id is int.
gives me some error 
<pre>1: executing "Admin/Index.html" at <.ParentCategory>: ParentCategory has arguments but cannot be invoked as function </pre>

**Comment by notzippy** [comment]
See http://golang.org/pkg/text/template/#hdr-Functions you need the function *eq* first then the items you are comparing

**Comment by anonx** [comment]
@goors `eq` is a function that expects multiple arguments, so here is the right version of inner fragment:
```html
{{ if eq .ParentCategory .Id }}
...
{{ end }}
```

**Comment by brendensoares** [comment]
:+1:
