### ISSUE TITLE
How to call template custom function on view?

### ISSUE THREAD

**Issue by goors** [revel/revel#946]
I know this is not and issue, but there are some many things that are missing in your manual and I have to guess how to do things.

I have this function:
<pre>
revel.TemplateFuncs["get_subcategories"] = func(a int) []*models.RouteCategory {
		results, err := GorpController{}.Txn.Select(models.RouteCategory{},
			`select * from RouteCategory where ParentCategory = ?`, a)
		//`select * from RouteCategory`)
		if err != nil {
			panic(err)
		}

		var subcategories []*models.RouteCategory
		for _, r := range results {
			b := r.(*models.RouteCategory)
			subcategories = append(subcategories, b)
		}
		return subcategories
	}
</pre>

How to call this on view?

<pre>{{range get_subcategories .Id}} </pre>

gets me and error "runtime error: invalid memory address or nil pointer dereference". 

Maybe I am doing this wrong way. Please suggest something.

I know problem is with 
<pre>results, err := GorpController{}.Txn.Select(models.RouteCategory{},
			`select * from RouteCategory where ParentCategory = ?`, a)</pre>

but I do not understand why.

**Comment by goors** [comment]
I solved this other way since my guess is that I can not access GorpController like that.
So I did this instead:

<pre>

revel.TemplateFuncs["get_subcategories"] = func(a int) []*models.RouteCategory {

		rows, err := Dbm.Db.Query(`select * from RouteCategory where ParentCategory = ?`, a)
		if err != nil {
			panic(err)
		}

		var (
			Id int
			CategoryName string
			IsActive int
			ParentCategory sql.NullString
			CategoryDescription string

		)

		defer rows.Close()
		var subcategories []*models.RouteCategory
		for rows.Next() {
			err := rows.Scan(&Id, &CategoryName, &IsActive, &ParentCategory, &CategoryDescription)
			if err != nil {
				log.Fatal(err)
			}
			subcategories = append(subcategories, &models.RouteCategory{Id, ParentCategory, CategoryName, CategoryDescription, IsActive,})
			log.Println(Id, ParentCategory, CategoryName, CategoryDescription, IsActive)
		}
		err = rows.Err()
		if err != nil {
			log.Fatal(err)
		}

		return subcategories
	}
</pre>

**Comment by brendensoares** [comment]
:+1:
