### ISSUE TITLE
how to add block "javascript" in templates?

### ISSUE THREAD

**Issue by goors** [revel/revel#947]
I am used to twig where I have 
<pre>
    {% block javascript%}
    {% endblock %}
</pre>

I usually put that in my footer file and then from controller template I can do
<pre>
     {% block javascript%}
    //javscript code here
     {% endblock %}
</pre>

How can I do that in revel? I tried https://godoc.org/github.com/acsellers/multitemplate but that is not working.

**Comment by goors** [comment]
Never mind. I used {{append . "moreScripts" "js/admin/index/index.js"}} and so on. And so on.

**Comment by brendensoares** [comment]
:+1:
