### ISSUE TITLE
Problems with gorm: nullable columns are always null instead of some post value

### ISSUE THREAD

**Issue by goors** [revel/revel#948]
In form I have select with name Parent that is not null and have some number in dropdown (for example 7).
Table that has parent column is always NULL and not that number 7.
Parent is defined as FK in table RouteCategory and default value is null. FK is to table itself.

This is model:
<pre>
type RouteCategory struct {

	Id					int
	ParentCategory  	*sql.NullInt64 		`gorm:"column:ParentCategory sql:"index;null"`
	CategoryName   		string  			`gorm:"column:CategoryName; sql:"type:varchar(64);"`
	CategoryDescription string  			`gorm:"column:CategoryDescription; sql:"type:varchar(255);"`
	IsActive 			int 				`gorm:"column:IsActive; sql:"type:smallint(1);"`
}
</pre>
Can you maybe help me with that?
<pre>
     log.Println(a.Request.Form.Get("ParentCategory"))// --> this is string and not int or int64
     err := a.Txn.Insert(&category) ->this inserts null for parent instead of number 7

</pre>

**Comment by zhuharev** [comment]
You can show more code(html form and controller)?
