### ISSUE TITLE
Booking app - back button after logout

### ISSUE THREAD

**Issue by goors** [revel/revel#949]
Hi,

I am testing this booking sample app and I noticed that when I press back button after logout
I can see page that requires valid session user.

I know this is common problem in many web frameworks and it is usually solved with 
.htaccess file.

How can I solve this revel without using some javascript hack?

**Comment by 1lann** [comment]
You can change the header to force fetch all pages which require authentication if this is really an issue for you, in most cases this is fine as the page doesn't actually have any functionality (no actions can be made) as it's just loaded from cache. These are the HTTP headers you can use to deny caching of the page (you can also use meta http-equiv in your HTML):
```
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
```

**Comment by goors** [comment]
Yes this is working. Thank you.

**Comment by brendensoares** [comment]
You're on a roll @goors! Thanks for sharing! :100:
