### ISSUE TITLE
main.go:14: revel redeclared as imported package name

### ISSUE THREAD

**Issue by baiyuxiong** [revel/revel#950]
__Error log__:
ERROR 2015/06/07 18:16:43 build.go:101: # github.com/xxx/xxxx/app/tmp
go/src/github.com/xxx/xxxx/app/tmp/main.go:13: revel redeclared as imported package name
	previous declaration at go/src/github.com/xxx/xxxx/app/tmp/main.go:7

__main.go content__:
7	"github.com/revel/revel"
8	_ "github.com/xxx/xxxx/app"
9	controllers "github.com/xxx/xxxx/app/controllers"
10	tests "github.com/xxx/xxxx/tests"
11	controllers1 "github.com/revel/modules/static/app/controllers"
12	_ "github.com/revel/modules/testrunner/app"
13	controllers0 "github.com/revel/modules/testrunner/app/controllers"
14	revel "github.com/revel/revel"

__My code__:
__controllers/app.go:__
type App struct {
	BaseController
}

func (c App) Index() revel.Result {
	return c.Render()
}

__controllers/base.go:__
//.....
func init() {
	revel.InterceptMethod((*BaseController).Before, revel.BEFORE)
}

type BaseController struct {
	*revel.Controller
}

func (c *BaseController) __CheckValidate__(__res revel.Result__) revel.Result{
	if res != nil{
		return res;
	}
	return nil
}
//.....

If remove function "__CheckValidate__" or remove param "__res revel.Result__", All works well.

**Comment by zhuharev** [comment]
7 and 14 are identical to the line, remove one of them

**Comment by brendensoares** [comment]
If you have more helpful info, please reopen. Thanks.
