### ISSUE TITLE
Why optional func parameters in controller are not working? CRUD code redundancy.

### ISSUE THREAD

**Issue by goors** [revel/revel#952]
I was reading lot of about go and i see i can not have optional parameters (or default value for some params) in methods. 
Lets take for example simple crud.

I want to use same controller action for create and update and just to do simple:

<pre>
    func (c Account) User(user models.User, verifyPassword string, id ...int64) {

        /*
        validate user etc
       */
        if len(id) > 0 {
            c.Txn.Update(&model)
        } else{
            c.Txn.INsert(&model)
        }
    }
</pre>

This gives me and error when I try to do this in template {{ url "Account.User" }} saying that I am missing parameter. And once i hardcode value for route i have some invalid memory address or nil pointer dereference on god know what part of code.

With this "Go official policy" I will have code redundancy for CRUD and that sucks! I do not want code redundancy!

So instead of one function I will have to use two functions for same thing that are just different 
in one line of code.

Since I started learning go and revel 7 days ago, maybe I missed something.
The only reason I used revel and go is speed. I am using go/revel for some project that has
lot of requests (million per day).

Is there any way to solve this?

**Comment by anonx** [comment]
If you want your **action**:
```go
func (c Account) User(user models.User, verifyPassword string, id ...int64) {
}
```
to have an optional `id` parameter, add to your `conf/routes` something like (in that order):
```go
#Method  #Pattern             #Action
GET      /account/user/:id    Account.User
GET      /account/user        Account.User
```
Now `url` template helper correctly works both as `url "Account.User"` and as `url "Account.User" 12345`. *Instead of `GET` use the method you need and update the pattern to what you need.*

**Comment by pedromorgan** [comment]
Can i close this?
