### ISSUE TITLE
Websocket with SSL can't work at dev mode

### ISSUE THREAD

**Issue by linlexing** [revel/revel#953]
When run at dev mode, the security websocket execution error.
Browser Tip:

> WebSocket connection to 'wss: // ...' failed: Error during WebSocket handshake: net :: ERR_RESPONSE_HEADERS_TRUNCATED

Server Tip:

> server.go: 1775: http: TLS handshake error from 127.0.0.1:288
> 82: tls: first record does not look like a TLS handshake

Run at prod model, not the problem.

**Comment by 1lann** [comment]
Post code to reproduce this to help the developers debug this issue.

**Comment by ptman** [comment]
I have this same problem

**Comment by ptman** [comment]
Looks like harness can only proxy non-SSL websockets. I got it working by replacing https://github.com/revel/cmd/blob/master/harness/harness.go#L207 with:

    d, err := tls.Dial("tcp", host, &tls.Config{InsecureSkipVerify: true})

But someone with a better familiarity to revel should probably integrate this so that it works both with SSL and without.

**Comment by pedromorgan** [comment]
So whats the problem, simply adding the tls.Config will make it work ??

**Comment by brendensoares** [comment]
Thanks for starting work on this @ptman, we'll add this to our todo list.

**Comment by ptman** [comment]
So is this actually already fixed in https://github.com/revel/cmd/commit/f122160a111500bce9e52c9337a9e208c049b7b0 ?

**Comment by notzippy** [comment]
Looks like it, closing
