### ISSUE TITLE
html5 import is not dispatch load event

### ISSUE THREAD

**Issue by chrislearn** [revel/revel#954]
Recent I create a project use revel and [aurelia](http://aurelia.io/). But only in chrome aurelia always loading, no error report.
I found that aurelia add some import tag in the html page, and listener the load event, but it never dispatched in chrome, after I comment some code in resulst.go which set Content-Disposition header, it worked. I don't know why.

https://github.com/revel/revel/compare/master...chrislearn:patch-1

**Comment by bertzzie** [comment]
Hello,

I also have the same problem with Polymer.

**Comment by pedromorgan** [comment]
?? is this a bug ??

**Comment by bertzzie** [comment]
@pedromorgan As per the HTML 5 Import standard [1], particularly the fetching import part:

> 3. Fetch a resource from LOCATION with request's origin set to the origin of the master document, the mode to CORS and the credentials mode to same-origin.
>     1. If fetched response type is error or the response has a header whose name is Content-Disposition:
>         - Add LOCATION and null to the import map and stop.

a HTML Import will failed if there's a `Content-Disposition` header. As far as I understand, revel will always sends down `Content-Disposition` for files served via the static controllers (CMIIW). I think this might become a problem in the future, once more people use HTML Import in the client side. So I kind of agree that this could be categorized as bug.

Maybe we need an option to set the Content-Disposition header by URL Pattern or something as the header is indeed really useful.

[1]: https://w3c.github.io/webcomponents/spec/imports/#fetching-import

**Comment by brendensoares** [comment]
Thanks @bertzzie for the additional info and @chrislearn for the initial issue. We'll add this to the backlog for later consideration.

**Comment by notzippy** [comment]
This can be fixed by using a filter configuration and having the filter adjusted for the static module
