### ISSUE TITLE
RenderTemplate how to pass vars to view?

### ISSUE THREAD

**Issue by goors** [revel/revel#955]
Well how to use:

<pre>return a.RenderTemplate("Admin/Index.html") </pre>

and pass some <br>var user string</b> for example?

**Comment by goors** [comment]
I got it:
<pre>
c.RenderArgs["routes"] = routes
c.RenderArgs["categories"] = categories
return a.RenderTemplate("Admin/Index.html") 
</pre>

**Comment by brendensoares** [comment]
:+1: thanks for sharing your fix!
