### ISSUE TITLE
Routing error while using encoded URL 

### ISSUE THREAD

**Issue by Solido** [revel/revel#956]
Encoded URL parameters behave like unencoded parameters.

Example : 
localhost:8000/v1/qr/http%3A%2F%2Fgoogle.com%0A
will be interpreted like if parameters are not encoded leading to routing
/v1/qr/http://google.com%0A 
and the action never receive the URL parameter

This behavior is maybe correct in Revel ?
It just differe from Play Framework or others tool

BTW, thx for Revel It's a lot of fun to play with :D

**Comment by anonx** [comment]
This is the exact behaviour [standard Mux](https://golang.org/src/net/http/server.go?s=48689:48757#L1646) has (note, they are using `r.URL.Path` [rather than](https://play.golang.org/p/E0JFglBwEM) `r.URL.RawPath`), isn't it?
Though it is possible to change Revel's behaviour. Revel team will have to make changes to the `router.go` and reverse router.

**Comment by pedromorgan** [comment]
Is this a bug ?

**Comment by anonx** [comment]
@pedromorgan Not really. This is the way most go routers work. But this behaviour is different from Play Framework. So, it's up to you @revel/core to decide which one you want.

**Comment by pedromorgan** [comment]
So which one is "standards compliant...." ? 
What are the ramifications of a change ?
sorry for muppet questions...

**Comment by anonx** [comment]
As for standards I don't know to be honest. But I assume both are compliant. That is an internal behaviour of application.

[Related fragment](https://godoc.org/net/url#URL) from Go's `net/url` docs:
> Note that the Path field is stored in decoded form: /%47%6f%2f becomes /Go/. A consequence is that it is impossible to tell which slashes in the Path were slashes in the raw URL and which were %2f. This distinction is rarely important, but when it is, code must not use Path directly.
>
> Go 1.5 introduced the RawPath field to hold the encoded form of Path. The Parse function sets both Path and RawPath in the URL it returns, and URL's String method uses RawPath if it is a valid encoding of Path, by calling the EncodedPath method.

I don't know what will be the consequences of this change, somebody will have to take care of investigating this. Though, at first sight the change looks easy: 1) 1 line in `router.go`, 2) reflect the change in `harness` (probably, use custom reverse proxy handler), aaand the most important 3) make sure nothing is broken, no flaws are introduced by this change.

**Comment by brendensoares** [comment]
Put in the backlog for later consideration. Thanks.

**Comment by notzippy** [comment]
Server engine normalizes the routes now
