### ISSUE TITLE
RenderJson - return base64 code

### ISSUE THREAD

**Issue by goors** [revel/revel#957]
In some acton I have:

    if(a.Params.Get("json") != ""){
        b, _ := json.Marshal(&users)
	    return a.RenderJson(&b)
    } else{
        return a.Render(users)
    }

That return base64 encoded string instead of json.

When I do something like I can se json in browser:

    func ReturnJson(res *revel.Response, in interface{}) revel.Result{
        b, _ := json.Marshal(&in)
	    res.WriteHeader(200, "application/json")
	    res.Out.Write(b)
	    return nil
    }

**Comment by goors** [comment]
I got this. There is no need for  b, _ := json.Marshal(&users) part.
Sorry.

**Comment by brendensoares** [comment]
:+1: thanks for sharing your fix @goors!
