### ISSUE TITLE
Incorrect instructions in Heroku buildpack error message

### ISSUE THREAD

**Issue by gtolle** [revel/revel#958]
(for background, this is my first attempt at deploying a Go webapp to Heroku, and I'm new to Go in general)

After setting up my Heroku app using the Revel buildpack:

```
heroku create -b https://github.com/revel/heroku-buildpack-go-revel
```

I pushed the default `revel new` app source but forgot to add a `.godir` file. The error message pointed to a blog post that doesn't actually mention `.godir` at all. I'd expect the error message to describe how to set up `.godir`.

```
remote: -----> Fetching custom git buildpack... done
remote: -----> Revel app detected
remote:  !     A .godir is required. For instructions:
remote:  !     http://mmcgrana.github.io/2012/09/getting-started-with-go-on-heroku
```

Perhaps it would be better to point to the revel buildpack README?

https://github.com/revel/heroku-buildpack-go-revel/blob/master/README.md

That post did explain how to add my Revel app path to .godir, at least.

**Comment by PradheepShrinivasan** [comment]
@gtolle I am trying to deploy to heroku and i am unable to do so as there is version mismatch in the default build pack.Do you have any success deploying recently to heroku and if so can you share your instructions ?

**Comment by notzippy** [comment]
This error was due to a renaming issue. closing
