### ISSUE TITLE
How to check code coverage?

### ISSUE THREAD

**Issue by Gujie** [revel/revel#960]
Hi everyone!

To test my revel server, I can run it and go to the endpoint `/@tests`. However, this does not provide a code coverage report... Is there anyway I could get one?
Thank you very much for your help!

**Comment by anonx** [comment]
Revel currently does not have its own tool to calculate test coverage and as far as I know its tests are not compatible with the standard `go test -cover` command. So, I don't think there is a way to check coverage apart from creating standard Go tests (like `app_test.go` files in your `app/controllers` directory).

**Comment by ptman** [comment]
Test coverage is a useful and expected tool. It really should be possible to get coverage information out of revel tests. How could this be fixed?

**Comment by alkchr** [comment]
@ptman I agree, test coverage would be good to have. The easiest way I see is to make Revel tests compatible with the standard go tests. That may be achieved by use of code generation. So, instead of test runner (that uses reflection) Revel could have a test generator that would scan your `tests/` directory and generate standard go tests.

**Comment by ptman** [comment]
Maybe `revel test` could do the code generation and run coverage (or `revel cover`) without having to modify how `/@tests` currently works.

**Comment by alkchr** [comment]
@ptman Yes, that's even better.

**Comment by Gr1N** [comment]
+1 It would be very useful to have `cover` integration for revel framework.

**Comment by mindworker** [comment]
I just get started with Revel and it's great so far. But, please integrate coverage reports!

**Comment by ptman** [comment]
https://blog.cloudflare.com/go-coverage-with-external-tests/

**Comment by ptman** [comment]
I tried to make a simple _test.go:

    func TestRevelTests(t *testing.T) {
        revel.cmdTest.Run(packageArgs)
    }

But it naturally didn't work, as I only got it to produce (empty) code coverage for the `revel test` command that compiles a separate binary (without coverage profiling) to run the tests.

**Comment by skategui** [comment]
Do you have an idea if it's going to be possible to test the coverage and have a report of the test ? Of it's not something considered right now ... ? 

Thanks

**Comment by alkchr** [comment]
In case @revel/core decides to use code generation rather than runtime reflection for tests... Go 1.7 introduces an interesting feature that could be useful right for this use-case: https://twitter.com/rakyll/status/736252589742907392

![Go subtests](https://pbs.twimg.com/media/Cjex1C-VEAAaG53.jpg)

**Comment by notzippy** [comment]
Server engine will allow you to write tests that are compatible with code coverage tool from go

**Comment by zuoRambo** [comment]
@notzippy How to refactory my `revel style test` so i could get coverage report ?

**Comment by notzippy** [comment]
Not entirely sure what you mean by `revel style test`. To get code coverage reports you need to run the code as a go test command, which the `revel` command does not do. I am looking into a way to make this possible though and should have a solution soon

**Comment by roger-russel-dafiti** [comment]
Is there a solution to get coverage from revel test?

**Comment by notzippy** [comment]
@roger-russel-dafiti There is - You can see an example in 
https://github.com/revel/examples/blob/master/booking/app/controllers/app_test.go
