### ISSUE TITLE
app.APP_VERSION

### ISSUE THREAD

**Issue by GiorgioG** [revel/revel#964]
how do I access app.APP_VERSION programmatically?  I'm setting an environment variable prior to doing a build, it's getting populated according to the build output: "go build -ldflags -X gs/demo_api_server/app.APP_VERSION "e07116c""

**Comment by zhuharev** [comment]
see [version.go](https://github.com/revel/revel/blob/master/version.go)
answer: `revel.VERSION`

**Comment by ptman** [comment]
I think this was solved on IRC: place `var APP_VERSION string` in `app/init.go`

**Comment by ptman** [comment]
BTW, golint:

    app/init.go:8:5: don't use ALL_CAPS in Go names; use CamelCase

**Comment by pedromorgan** [comment]
Is this a bug now or can I close ??

**Comment by ptman** [comment]
golint is just about style, not a bug IMHO
