### ISSUE TITLE
json data

### ISSUE THREAD

**Issue by tommoholmes** [revel/revel#965]
How to display json data and render to html

**Comment by zhuharev** [comment]
`c.RenderJson(data)`

**Comment by tommoholmes** [comment]
what I mean. I have json data and I want to display json data to my Html

**Comment by goors** [comment]
@tommoholmes, this is not and issue. You should post questions like this on http://stackoverflow.com. @zhuharev answer to this.  When you do c.RenderJson(data) you are actually rendering/serving json to your html (json) output. For example:
<pre>
mp := map[string]interface{}{
    "key1": value1,
    "key2":value2, 
}
c.RenderJson(mp)
</pre>

Of course you can render Gorp database results ans so on.
Fro example:
<pre>
p, err := h.Txn.Get(models.SomeModel{}, id)
if err != nil || p == nil {
    return nil
}
c.RenderJson(p.(*models.SomeModel)) //c is you controller func (c CtrlName) someMethod() revel.Result{}
</pre>

Above code will render results for sql "SELECT * FROM SomeModel WHERE Id=id" and you will see that results on you browser output.

But as I said you should first read docs (http://goo.rs/m9sgt).

**Comment by zhuharev** [comment]
What type of your data? if `byte` convert it to `string`: `somevar :=  string(data)` and render it: `c.Render(somevar)`

**Comment by DavidHunter** [comment]
I am assuming this issue has been solved
