### ISSUE TITLE
Variables in routes file

### ISSUE THREAD

**Issue by PabloK** [revel/revel#967]
Hi, I would like to be able to use variables in the routes file. To invalidate the cache on version changes. Is it possible to implement something like this?

**Comment by zhuharev** [comment]
you can call direct `revel.MainRouter.Refresh()` for refresh all routes

**Comment by brendensoares** [comment]
@PabloK did you [read the manual](https://revel.github.io/manual/appconf.html#dynamic-parameters)?

Closing due to lack of action items.
