### ISSUE TITLE
[Feature request] RAML support 

### ISSUE THREAD

**Issue by janekolszak** [revel/revel#968]
RAML (http://raml.org/) - Restful API Modeling Language.

It would be awesome if Revel could extract the API definition from RAML files. It could use it during the project creation or maybe even somehow instead of routes?

**Comment by pedromorgan** [comment]
I am 20000% henind this...

Lets GO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by pedromorgan** [comment]
To explain more..

Revel is a little baby, and now that the the olde condif format has a few issues..
We want API and configg of configs..

And the nightmare of "configs" for local, dev, p prod.. et all..

So I propose we look at this hard.

Search for issues of Routing and Config..
and what I want is the mother of all configs in revel..
eats anything..
https://github.com/revel/revel/search?utf8=%E2%9C%93&q=+config+yaml&type=Issues

https://github.com/revel/revel/issues/680

SOO.................

Recently I see RAML, and indeed it sings from my song sheet..

With include files , and externals and all..

Love the idea..

I think we should implement this asap..
the yaml eater, and json eater.. and the false teeth..

**Comment by pedromorgan** [comment]
https://github.com/pksunkara/alpaca/blob/master/README.md

**Comment by janekolszak** [comment]
http://raml.org/spec.html

RAML is "RESTful API Modeling", but I guess very small extension to the format could make it useful for routing. I'm no RAML expert though, it may be possible right now.

**Comment by pedromorgan** [comment]
Snag we got is that the "routing in is in .. line format"..

But it worked on some platform which was the start..

Maybe we create a config-crash-mash repos.....
So thro in wll out configs..
and then eat it..
chew it over like..

Its a pinin the ass for me having to kinds manage 3 sets of same
credentials and configs in plases..

I am well into a machine readable format.. that works..
so I can share the db connection on freeflightsim.org..
with
a golang frontend.. in json (coss for internet)
- but back format was yaml (cos I can add comments
- then json config for nginx and db
- and a subdomain in another db..
- and same app capuring routes et all..

Even redirects in Yamls and a loader for redirect would be cooll..
or rewrites for olde.. php/perl and implemeting end pointz..

**Comment by gtrevg** [comment]
Just a quick comment -- I've been working with RAML for quite a while now and it's been pretty awesome.  There's ever growing support for the spec and I see more and more tools using it every day.

There's a number of RAML projects that are doing the same extraction and Server/Client skeleton generation from RAML definitions.

An additional benefit is that, when you are defining your input and output using JSONSchema which RAML fully supports, you could also auto generate the validation code for every endpoint.  Here's an example of that that I hacked together one afternoon for a talk:  https://github.com/gtrevg/golang-rest-raml-validation .  This takes advantage of the fact you can !include json schemas and examples.

Again, so far, using RAML has been pretty awesome.  It would be great to have a skeleton framework generated from a RAML spec.  That will speed up development tremendously.  Additionally, all your documentation will be up to date.

Thanks

**Comment by brendensoares** [comment]
RAML looks interesting. I'm all about industry standards that can be supported by many tools. We'll have to prioritize this for release, but there are many other features in front of this.

**Comment by janekolszak** [comment]
This might be usefull after they move to RAML 1.0
https://github.com/EconomistDigitalSolutions/ramlapi

**Comment by notzippy** [comment]
Closed, targeted cmd branch https://github.com/revel/cmd/issues/73
