### ISSUE TITLE
cross compiling libraries

### ISSUE THREAD

**Issue by amlwwalker** [revel/revel#969]
I am cross compiling my revel application for ARM. It all works fine, however one library is not cross compiled and therefore it fails to build for arm, even though it is fine on OSX.

When I run

`GOOS=linux GOARCH=arm revel package mitm`

I get 

```
ERROR 2015/07/27 09:01:30 build.go:101: # mitm/app/controllers
ArpScan.go:88: undefined: pcap.OpenLive
ArpScan.go:88: undefined: pcap.BlockForever
ArpScan.go:114: undefined: pcap.Handle
ArpScan.go:145: undefined: pcap.Handle
```

How do I cross compile a library that is stored in ~/go/src/github.com/google/gopacket library?

Its this library https://github.com/google/gopacket

**Comment by brendensoares** [comment]
Please go to stackoverflow.com for help on this issue. It doesn't seem related to Revel and I don't have enough time to help you with this problem. Sorry.

Thanks!
