### ISSUE TITLE
Parsing JSON data

### ISSUE THREAD

**Issue by pcrawfor** [revel/revel#97]
Hi,

Was playing around with revel this week, one component I wanted to try was building out JSON API, responding with JSON was no prob but I haven't been able to figure out how to properly parse JSON data posted to an action.

I may be missing something but couldn't find a good way to handle it using the Binder.

**Comment by kumarsiva07** [comment]
@robfig @brendensoares Can you add this to params.go in master?
`func (c Application) Test() rev.Result {
    mentions := []struct {
        Text string `json:text`
    }{}
    err := json.NewDecoder(c.Request.Body).Decode(&mentions)
    if err != nil {
        rev.ERROR.Println(err)
    }
    rev.INFO.Println(mentions)
    return c.RenderText("ok")
}`

**Comment by jeevatkm** [comment]
@kumarsiva07 Can you describe your use case?

**Comment by kumarsiva07** [comment]
Yes.  I am using react instead of revel templates.
So all the request will have request data in the form of json. It's a
application/json type request.

**Comment by jeevatkm** [comment]
@kumarsiva07 - please create an issue with your description and also mention about #97 and #110.
