### ISSUE TITLE
How to flush c.Params.tmpFiles

### ISSUE THREAD

**Issue by otiai10** [revel/revel#972]
Thanks always. I have a question.

- Is there any way to flush tmpFiles of Controller?

----------------

Through using file upload and binding by arg name of Controller

```go
func (c MyApp) MyController(myfile *os.File) revel.Result {
  _, err := os.Rename(myfile.Name(), mydestination)
  if err != nil {
    return c.ReturnError(err)
  }
  return c.RenderJson(map[string]interface{}{})
}
```

because (and of course) I move tmp file, ParamsFilter WARNs error

https://github.com/revel/revel/blob/master/params.go#L125-L130

I guessed solutions for this,

1. DO NOT rename, but copy tmp file to my dest.
2. customize ParamsFilter and replace default.

but it's easier if I can flush tmpFiles in Controller. Please teach me if there is a way to do that.

Thank you

**Comment by otiai10** [comment]
Third solution is here (but it seems a bit irrational)

```go
c.Params = &revel.Params{}
```

**Comment by pedromorgan** [comment]
Whats teh issue here.. are these large files or something ??

Is ita  timeout problem.. 

Or is it parsing didgy URl's etc..?

More explain of problem would be useful ..
ta

**Comment by otiai10** [comment]
Thanks for comment.

My concern is the way to avoid [ParamsFilter WARNs error](https://github.com/revel/revel/blob/master/params.go#L125-L130) occurred by using os.Rename.

**Comment by brendensoares** [comment]
If you don't want to see warnings, then disable the `WARN` level. Overwriting `Params` isn't ideal.
