### ISSUE TITLE
when release  revel v0.13?

### ISSUE THREAD

**Issue by xpbliss** [revel/revel#973]
It seems that the revel has not been  updated for a long time.
when release v0.13?

**Comment by xiongxin** [comment]
when release v1.0?

**Comment by DavidHunter** [comment]
We need more contributors. We just added more people to the project

**Comment by pedromorgan** [comment]
xpbliss.. yo I thought u were a team member.. 

What do u want main.. thats not there at the moment ?

**Comment by anonx** [comment]
@DavidHunter I don't think this is a lack of people but rather a lack of action. If not actively developing new things or refactoring existing code it is at least possible to merge existing PRs. There are some that are simple, not controversial, do not break things, and at the same time important.

**Comment by DavidHunter** [comment]
@anonx I agree with you.

**Comment by brendensoares** [comment]
I'm going through PRs now and have been progressively over the last few days. @alkout @DavidHunter
