### ISSUE TITLE
App failed to start up revel/harness: app died

### ISSUE THREAD

**Issue by kyawmyintthein** [revel/revel#974]
I got following error when I run app.

App failed to start up
revel/harness: app died

func defineBidItemTable(dbm *gorp.DbMap){
    // set "id" as primary key and autoincrement
     t := dbm.AddTable(models.BidItem{}).SetKeys(true, "id") 

    // // e.g. VARCHAR(25)
     t.ColMap("name").SetMaxSize(25)
}

**Comment by pedromorgan** [comment]
Is this still not working or is this a bug ??

**Comment by anonx** [comment]
@kyawmyintthein This is the message you get when your code panics before starting an app. Check your `defineBidItemTable` function.

**Comment by brendensoares** [comment]
No action items. Closing.
