### ISSUE TITLE
amber templating engine with revel

### ISSUE THREAD

**Issue by mrkaspa** [revel/revel#975]

**Comment by anonx** [comment]
@mrkaspa There is no way as far as I know. It is however [planned](https://github.com/revel/revel/wiki/Roadmap#focus-template-engine-asset-pipeline-view-models-cross-platform-support) to implement pluggable in v0.13.

**Comment by mrkaspa** [comment]
Great I would like to contribute, how can I do it ?

**Comment by pedromorgan** [comment]
Ok guys we need to nail templating..

The main thing we need as a ..
1) smarty developer.. yes was an early adocpter..
2) python cos of django jinga2 and inheritance..
3) back to square one with golang templates

So can we push this forward with Pongo.. and for me a smarty3 in templates..

Main thing.. is inheritance which is what we relly relly want..

Is there any consensus about how the interface would work..

**Comment by DavidHunter** [comment]
The contributing guidelines are at https://github.com/revel/revel/blob/master/CONTRIBUTING.md

**Comment by mrkaspa** [comment]
Great thx

**Comment by pedromorgan** [comment]
Sorry guys, changes the title to amber templating..

https://github.com/eknkc/amber

And flagging as templating stuff.. 
Certainly on the todo list is "templateing plugings"..

Looking at 
Pongo2, Amber et all

And we need some more "templating parsers"..
- as a hardocre origningal Smarty2 Developer in php land of younder year
- then django
- then jinja2 = cool

Main thin is inheritance is what all the olde template designers want..

**Comment by anonx** [comment]
I have met a related project https://github.com/golib/hamlengine. Haven't tried it though and have no idea whether it works.

**Comment by pedromorgan** [comment]
https://github.com/revel/revel/pull/506 - Support template engine
https://github.com/revel/revel/pull/602 -

**Comment by notzippy** [comment]
You can now add any template engine you would like with revel, see http://revel.github.io/manual/template-engine.html

closing
