### ISSUE TITLE
Running in prod problem with changes

### ISSUE THREAD

**Issue by goors** [revel/revel#979]
When I run revel in prod any new change that I make to source code (except static files) are not visible.
I have to shutdown process and run it again in order for new changes to be visible. revel clean is not working (i am not sure what is clean for).

Anyway, who can i run it in prod in order to get that changes visible without restarting process?
I know that in dev everything gets recompiled but not in prod.

**Comment by anonx** [comment]
@goors Why do you want your app to be recompiled in `prod` mode? That's actually an expected behaviour to recompile app in `dev` mode only. Though if you want you can modify your `app.conf`:
```diff
[prod]
-mode.dev = false
+mode.dev = true

-watch = false
+watch = true
```
However I don't think this will work without `harness`.

**Comment by goors** [comment]
So you are telling me every time I update app in prod I have to restart revel run app prod process?

**Comment by anonx** [comment]
First of all in production you are not using `revel run` because that starts a reverse proxy (`harness`) in front of your app that was not supposed to be used in the wild, that is just a dev tool.
Instead you are building your app with `revel build /path/to/app /path/to/destination` and then running it as `./run.sh` or `./run.bat`.

**Comment by goors** [comment]
Thanks for that. I will try to do that.

**Comment by goors** [comment]
This build is working, but I do not see difference between that and revel run app prod. Both things are running on same port that i have to proxypass for domain name. It there something like wsgi for go as you have for python and apache?

**Comment by goors** [comment]
Maybe I can do reqrite instead of proxypass  ?
RewriteRule ^(.*)$ http://localhost:appport/$1 [P,L]

What is better?

**Comment by anonx** [comment]
> This build is working, but I do not see difference between that and revel run app prod.

There is a difference. `revel run` starts an app that is called [harness](https://github.com/revel/cmd/tree/master/harness). Harness does a few things:
1. Listens your "127.0.0.1:9000" or whatever address you've configured inside `app.conf`;
2. Starts your app on some random free port;
3. Proxies requests from (1) "127.0.0.1:9000" to (2) that random port;
4. Shows user friendly errors and stuff (which are supposed to be for developer, not for strangers from the internet);
5. Watches changes and recompiles things.

A result of `revel build` is just your app that uses standard Go server.

Actually you can use `revel run` but then that  (1) "127.0.0.1:9000" should be made unavailable for the outer world. And you will have to configure nginx or something to listen :80 / :443 and pass requests to (2) port of your app (not port of harness).

#758 is related to your issue.
