### ISSUE TITLE
JWT Auth Module for Revel

### ISSUE THREAD

**Issue by jeevatkm** [revel/revel#980]
I was developed this [JWT Auth Module](https://github.com/jeevatkm/jwtauth) for my couple of applications. Then I pulled out the auth code as separate revel module (made generic enough for easy integration with revel app) using with those applications. Just now I have pushed my code to github.  [Readme.md](https://github.com/jeevatkm/jwtauth/blob/master/README.md) has additional info.

I would like to contribute JWT Auth Module into [Revel Modules](https://github.com/revel/modules).

@revel/core - Could you guys review and share pointer for improvements? Once every thing is set, you can accept this module into [Revel Modules](https://github.com/revel/modules).

**Comment by xpbliss** [comment]
good work!

**Comment by jeevatkm** [comment]
Improved the documentation in [Readme](https://github.com/jeevatkm/jwtauth) and Added demo Revel Application [here](https://github.com/jeevatkm/jwtauth/tree/master/example/jwtauth-example). Not just contributing once, I would to like improve further and continued contribution. 

BTW are you guys working on any security module for Revel? Since I'm in a need of one. Thought to check with you guys so I can use/develop further/develop new security module. Kindly let me know.

@revel/core - ?

**Comment by jeevatkm** [comment]
Implemented JWT signing methods HS256, HS384, HS512, RS256, RS384, RS512, ES256, ES384 and ES512.

**Comment by pedromorgan** [comment]
Is the idea to move this in revel/modules ??

Or do we create it as `submodule` ??

**Comment by jeevatkm** [comment]
What do you mean by `submodule`?  Can you please describe?

**Comment by pedromorgan** [comment]
I think where revel is headed is towards a more modular approach..
see https://github.com/revel/modules

and the idea soon is to have "auto documentation" and stuff for a website at revelframework.com

So there are tow possible options for the module..

1) stick it in the https://github.com/revel/modules repo
- the assumtion is here that its ther in standard distribution.. and supported..

2) create it as a submodule
This means it would appear as a module.. 
but be an external repo pointing to https://github.com/jeevatkm/jwtauth

3) We just add your module to the list ??

This project is still a baby and teething problems.. .. suck this dummy.. .... ;-)

**Comment by jeevatkm** [comment]
I had point no. 1 in my mind while I developed this module for revel. Please put it under https://github.com/revel/modules. Once its added I will remove my existing repo. Then I will contribute for improvement.

Please let me know, how to add jwtauth module documentation here http://revel.github.io/manual/modules.html? I will add it.

**Comment by pedromorgan** [comment]
Ok re the docs, that is something I;m working on..

The idea is to have a README.md in your repos.. and then the "website" engine will present that as the docs for the manual... 
ie as modules are added etc...

This is down to @brendensoares and I cant actually check it, cos I never ever used JWT..
but it looks goos and assume u put some effort in.. .. any NSA backdoors in there..etc  ?? ;-))

**Comment by pedromorgan** [comment]
Actually what would help is..

1) fork revel/modules and create branch
2) stick your stuff in there...
3) and make it work in revel/modules/ namespace..
4) then request a merge.. so brendan can click and then we all happy ;-))

**Comment by jeevatkm** [comment]
This module is using JWT library https://github.com/dgrijalva/jwt-go as refer by http://jwt.io. From the look of what I searched around. I believe it doesn't have any NSA backdoors. 

As suggested I will prepare a branch from revel/modules. Once done I will submit merge request.

**Comment by pedromorgan** [comment]
https://github.com/jeevatkm/jwtauth/issues/3

**Comment by pedromorgan** [comment]
Ok so I'm not a dev so I must confess that.. 

But what I am after is a REDME.md with the manual ..
the idea here is that docs are gen from your code etc..
for a taste see what I am upto .. https://github.com/pedromorgan/samples/blob/docs_dev/booking/README.md

But your docs are cool anyway.. so dont see any issue really.. ;-)))))

**Comment by jeevatkm** [comment]
Thanks, I just had a look on that Readme.md, I can do few improvements from my existing documentation. Updated doc will be ready when I submit merge request.

**Comment by jeevatkm** [comment]
@pedromorgan - As discussed I have submitted the pull request [here](https://github.com/revel/modules/pull/16).

I know how to write TestSuite for revel application but I don't know how to write one for revel Module. Any help appreciated.

**Comment by jeevatkm** [comment]
Revel module structure of JWTAuth is [here](https://github.com/jeevatkm/modules/tree/jwtauth), cleaned up the previous one.

**Comment by notzippy** [comment]
PR discussion in module, closing
