### ISSUE TITLE
Get server ip:port from controller

### ISSUE THREAD

**Issue by viblo** [revel/revel#981]
I would like to show the server listening ip:port on a page, but Im not sure if its possible at the moment? 

The reason is I have a revel app deployed on multiple servers behind a load balancer, and it would be useful for debugging purposes to quickly know which server that served a certain request. One way to easily handle this would be to print out the ip:port on a page.

**Comment by anonx** [comment]
Have you tried `revel.Config.String("http.addr")` and/or `revel.Config.StringDefault("http.port", "default value")`?

**Comment by pedromorgan** [comment]
Would be handy if it was a "property" of the controller though. imho ??

**Comment by viblo** [comment]
I have the same app.conf everywhere, the two servers where I have deployed my revel app are identical (except that they have their own IPs). The easiest solution would definitely be if it would read the "real" ip and not a configuration/environment value, since otherwise I must configure the two servers differently.

**Comment by anonx** [comment]
@viblo Alternatively, it is possible to use `revel.Server.Addr` to get an address that is listened by your app.

**Comment by viblo** [comment]
That was strange, ```revel.Server.Addr``` returns ```:43812```, same as is printed in revels log. However, in my revel config file I have ```http.port=18227```? I havent event noticed that it actually listens on both ports. (Where does 43812 come from? I thought it would only listen on what is written in config file). Anyway, that value is no help since it doesnt include IP and its not even the port I use to connect to.

**Comment by anonx** [comment]
@viblo Are you starting your app as `run.sh` (after `revel build path/to/myapp path/to/dest`) or as `revel run`?

**Comment by viblo** [comment]
@anonx with ```revel run```. When I now test with run.sh it shows the correct port. I didnt realize that it behaved differently depending on the method used to run. (I do use run.sh in production, so no big concerns about ```revel run```). However, I still dont have the IP.

**Comment by anonx** [comment]
@viblo There is a difference between `revel run` and `run.sh`. `revel run` starts your app and reverse proxy (that one which shows you user friendly errors when there are some), `run.sh` starts your app only.
You don't have IP as by-default your app listens *:port (i.e. all ports). To modify that behaviour you need to set `http.addr` in your `conf/app.conf`. As an example:
```ini
http.addr = ${ADDR}
```
Then run your app as `ADDR=x.x.x.x ./run.sh` when you want specific IP. And just `run.sh` and `revel run` will still work as before listening all ports.

**Comment by viblo** [comment]
Yeah, thats what I would ideally avoid doing, easier if it had the actual listening ip for the request available, but Im not sure if its even possible if the server is setup to listen to *. Anyway for now I have solved my problem by using os.HostName() instead.

**Comment by brendensoares** [comment]
Due to the common use of wildcard IP addresses, the best thing to do is add some app logic to your code that records [`os.Hostname()`](https://golang.org/pkg/os/#Hostname).

There isn't an ideal way to change Revel's `server.go` to  use a specific IP address from a list of available IPs.
