### ISSUE TITLE
Template of all Templates

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#984]
Ok so this is a bit of R&D re where we want to go.. and assumed to be HTML templates..ie views in this templating land..

And there are all sorts of tangents we live, like not having to redo all my templates in porting from XYX lang to go.. eg django, smarty, jinja2 et all..

So for benefit of all, and the ability to do it.. here's a summary.. of what could happen, and am not a go expert..

First off the templating engines in other langs.. mainly..
## Smarty - php

http://www.smarty.net/
V2 is popular http://www.smarty.net/docsv2/en/
V3 introuduced inheritance. http://www.smarty.net/docs/en/
## Django - python

Supports inheritance and popular if using dJango 
https://docs.djangoproject.com/en/1.8/topics/templates/
- alternate  Pongo2 = https://github.com/flosch/pongo2
## jinja2 - python

one of the Defacto python engines -  Supports inheritance
http://jinja.pocoo.org/docs/dev/
 -- attampt with https://github.com/jmoiron/jigo HELP!!
- ? - java, perl ???
# Current Revel
- native golang template/html = http://godoc.org/html/template
- Manual/templates = http://revel.github.io/manual/templates.html

**Pull Requests**
- Support template engine #602
# Future

Roadmap = https://github.com/revel/revel/wiki/Roadmap#v013-see-issues
https://github.com/revel/revel/pull/506 - Pluggable template loader 
# Other Golang Template Engines
## Mustache

https://mustache.github.io/
https://github.com/revel/revel/issues/99
## hamlengine

https://github.com/golib/hamlengine
## Amber

amber templating engine with revel #975
# Context

General idea is that a "dict" or key/value pair 

but also template vars could be "constants", "properties", functions even..

More 2 follow.. am on a mission ..............

**Comment by runner-mei** [comment]
https://github.com/yosssi/ace

**Comment by runner-mei** [comment]
I add pluggable template engine support.  https://github.com/revel/revel/pull/1003
and a pongo2 template engine support.
