### ISSUE TITLE
Using a variable from endpoint as template name

### ISSUE THREAD

**Issue by amlwwalker** [revel/revel#988]
Hi 
I am trying to use a variable set in the revel endpoint that is passed by `c.Render` to the template as a template to load in. For instance:

```
func (c App) MyPage() revel.Result {
    filename := "myfile.html"
    return c.Render(filename)
}
```

then in my mypage.html

```
<section class="content">
   {{template .filename .}}
</section>
```

That fails, so I tried it as a variable:

```
<section class="content">
   {{ template $filename }}
</section>
```

That fails to. I tried the following also, with the following errors:

`{{ template $filename }}` - `unexpected "$filename" in template invocation`
`{{ template }} {{ filename .}}` - `unexpected "}}" in template invocation`
`{{ template "$filename" .}}` - `2: no such template "$filename"`
`{{ template {{$filename}} .}}` - `unexpected "{" in template invocation`

How can I do this?

**Comment by pedromorgan** [comment]
Quick hack is somethings like...
```go
func (c App) MyPage() revel.Result {
    c.RenderArgs["filename"] = "myfile.html"
    return c.Render( c.RenderArgs["filename"] )
}
```

**Comment by anonx** [comment]
Actually, you can't. Go templates require static parameter where you're using `$filename`.

**Comment by amlwwalker** [comment]
@pedromorgan and then what do you do HTML side? I.e `{{ template ??? }}`

@anonx whats the best way to do this - I want a content developer to specify the filename that they have created but I dont want them messing with the template page it will fit into. This works perfectly if I specify the file myself but that slightly defeats the point of having a `<section>` that they can specify content for

**Comment by anonx** [comment]
@amlwwalker How that file is created? Through some web control panel when your app is already running. Or before starting the app using some editor (gedit, nano, vim, notepad, etc.)?

**Comment by amlwwalker** [comment]
It is created before starting the app. It is in a folder next to the Views directory. But I don't want to have to hard code it in myself

**Comment by alkout** [comment]
So that means you trust the content of that file, right? If so, here is a code snippet:
```go
func (c App) MyAction() revel.Result {
	// Make sure the template we need exists.
	tpl, err := revel.MainTemplateLoader.Template("App/Index.html")
	if err != nil {
		return c.NotFound("Page does not exist.")
	}

	// Executing the template (passing c.RenderArgs as context).
	var html bytes.Buffer
	err = tpl.Render(&html, c.RenderArgs)
	if err != nil {
		return c.RenderError(err)
	}

	// Including the HTML rendered above in the context of current template.
	// Thus, it will be possible to include it as {{ .tpl }}.
	// template.HTML() is needed so Go template does not escape things.
	c.RenderArgs["tpl"] = template.HTML(html.String())
	return c.Render()
}
```
Use the parameter you need instead of `"App/Index.html"`. Make sure you receive it from trusted source (like config file).

**Comment by amlwwalker** [comment]
Sweet! Works like a charm! Thank you

**Comment by pedromorgan** [comment]
Should this go into "revel" core ?  would be handy IMHO ..
