### ISSUE TITLE
Support for mustache templates

### ISSUE THREAD

**Issue by kennygrant** [revel/revel#99]
Hi, 

I've had a first look at using mustache templates with Revel, and also rendering layouts as opposed to the current scheme of header/content/footer partials. 

This is a potentially wide-ranging change, so I wanted to get feedback before going too far, and I don't think it's anywhere near a pull request as yet. So I've set up a fork with a branch for this revised templating code (NB changes are on branch):

https://github.com/kennygrant/revel/tree/mustache
and a test app here:
https://github.com/kennygrant/revelry

The first couple of commits were housekeeping and you can ignore - I renamed the packages to ensure I was only using the new code, but in retrospect this probably wasn't necessary. So please ignore that. 

I've also added a templates/layouts folder with the default application layout - this is used if there is no user default layout, and no controller specific layout, so probably not often, but useful as a default. This is the only added folder/file. 

NB Tests are currently broken because I was testing out a simpler variadic Render function - obviously this wouldn't make it in without careful thought on the args change, and would have to be backwards compatible too so that you could continue to pass in just an object, but that could be handled with reflection on the arguments passes in I think. I wanted to see what you think on that stuff first before making changes, and some of this might be broken into smaller chunks.

The real changes are in 3 files:
## template.go

This had the most changes, as it was tied quite tightly to the current go templates. There are now three sections to the file, which I'd be inclined to split into a few files (possibly each parser in its own file), but I've left them all together for ease of reading. The three sections are:

Loader - now holds a map of revel.Template objects by path, loads them as before, but calls the Template to parse, rather than parsing itself with html/template. 
Template objects - Template interface, then a module, then several parser examples (plain text, html/template, moustache template)
TemplateFuncs - as it was but moved to the bottom, these are rather like Rails helpers and likely to keep expanding, and it might be worth splitting them into their own file?

InitGoTemplateSet is a bit ugly and would need to be looked at again - go templates require a global variable to hold this, but it didn't seem to belong on the loader. There must be an easy way to do this but it eluded me today.
Pluggable parsers - I've taken the easy route initially, but if you have a list of Template conforming parsers in an array on loader, that could be added to easily by users. 

I think these internal changes wouldn't affect users of the library, and hope that they could usefully be included without hopefully breaking any current behaviour. They could be done separately from layouts, but I'm very keen to get that in too if possible as it is so handy and generally applicable. 
## controller.go

Add the ability to render in layouts with RenderInLayout. Arguments are (and this is a slight change from the other functions here):

context - as with previous RenderArgs, but passed only by the calling function
options - options for the render, currently only "view", "layout", and "content" are recognised, but this is flexbile

This change was made to allow passing layout and view options directly from the calling controller function, without leaking them in renderargs. Sorry for the gratuitous renaming and moving methods around here! My main reason for wanting to explore this was to make the options more flexible, and to let the controller manage the state presented to the view, rather than making this the model's job (as it would become if you pass in only models or other objects), but this is quite a subjective thing, and would require careful thought. This also clears the way for validation of inputs/outputs in the controller, rather than on models (see recent changes for strong parameters Rails for an example of why you might want to do this).

I've also added a simple variadic example of Render to show how this could deal with calls to:

```
return c.Render()
return c.Render(context)
return c.Render(context,options)
```

as previously, but leaving you with flexible options map which can be expanded later. The difficulty here would be managing calls to previous renders, but it would certainly be possible, esp. with a config flag to manage the transition. This is a big change you might not want right now though. Some changes are necessary for rendering in layouts and specifying layout/view, but the details here could obviously change. I thought I'd give you an example of what we discussed though so that you know what I was talking about on the list. 

I haven't merged the context with RenderArgs on the controller here, but this would obviously be straightforward - I just wanted to see what direct you'd like to go with these changes first before spending too long on it. I do much prefer the name context to the more generic 'args' just because that's what template libraries usually use to refer to the execution context.
## results.go

Very minor changes related to Template objects changing. 

So for now to have a look you should be able to download those two repos, build the revel, and run the app using that revel to see these changes with layout templates (for both sorts of templates), and optional mustache templates as well. You can have a mix of mustache and go templates in the same app, just by naming mustache ones with .mustache on the end.

**Comment by notzippy** [comment]
Closing in favor of https://github.com/revel/revel/pull/1003
