### ISSUE TITLE
suggestions for improvements on docs for watch.*

### ISSUE THREAD

**Issue by insasho** [revel/revel#996]
Regarding https://revel.github.io/manual/appconf.html#watchers:

1. The docs for `watch.mode` refers to `watchers.mode`. This is ambiguous. Which one is it?
2. `watch.mode` and `watch.code` both have a dedicated paragraph for Default setting, but watch.templates and watch.routes specify the default value in parenthesis. 
3. Are the docs correct in stating that watch.templates and watch.routes both default to false? Watch mode w/o watching templates seems a little silly.
4. Watch seems to be implemented with inotify, which is incompatible with VirtualBox shared filesystems (vboxsf) and some other filesystems. Mentioning inotify in this section might save devs some time.

Thanks!

**Comment by alkchr** [comment]
@insasho :+1: for the improvement of docs. As for the 4th point, have you visited `fsnotify`'s home page?
> https://fsnotify.org/
> From the beginning, fsnotify had users, with Rob Figueiredo testing it on OS X and later adopting it for Revel.

**Comment by insasho** [comment]
I was not aware that Revel was using fsnotify. Thanks for the pointer. I'm glad to see https://github.com/go-fsnotify/fsnotify/issues/9 is a feature request for adding polling to fsnotify. I still think it would be useful to mention that watch won't work on many platforms from within a VM as this is a common case.

**Comment by jeevatkm** [comment]
Taken care.
